import type { BlogPost } from "./blog-data";

export const dePostsB4: BlogPost[] = [
  {
    slug: "unix-timestamp-guide-de",
    title: "Unix-Timestamps: Was sie sind und wie man damit arbeitet",
    description:
      "Alles, was Entwickler über Unix-Zeit wissen müssen — was die Epoche ist, das Y2K38-Problem, Timestamp-Konvertierungen in JavaScript, Python und SQL, die Millisekunden-vs.-Sekunden-Falle, Zeitzonenbehandlung sowie Timestamps in JWTs und Datenbanken.",
    date: "2026-03-20",
    author: "BrowseryTools Team",
    category: "Entwickler-Tools",
    tags: ["unix timestamp", "epoche", "datetime", "javascript", "python", "zeitzone"],
    readTime: 9,
    coverEmoji: "⏱️",
    coverGradient: "from-violet-500 to-purple-700",
    locale: "de",
  },
  {
    slug: "url-encoder-guide-de",
    title: "URL-Kodierung erklärt: Prozent-Kodierung in HTTP-Anfragen",
    description:
      "Erfahren Sie, warum Sonderzeichen URLs beschädigen, wie Prozent-Kodierung auf Byte-Ebene funktioniert, der entscheidende Unterschied zwischen encodeURI und encodeURIComponent und häufige Kodierungsfehler in echten Anwendungen.",
    date: "2026-03-19",
    author: "BrowseryTools Team",
    category: "Entwickler-Tools",
    tags: ["URL-Kodierung", "Prozent-Kodierung", "HTTP", "Webentwicklung", "JavaScript"],
    readTime: 7,
    coverEmoji: "🔗",
    coverGradient: "from-cyan-500 to-blue-600",
    locale: "de",
  },
  {
    slug: "uuid-generator-guide-de",
    title: "UUIDs, NanoIDs und CUIDs: Das richtige ID-Format für Ihr Projekt wählen",
    description:
      "Ein tiefer Einblick in UUID v1, v4 und v7, NanoID und CUID2 — was jedes Format ist, wie Kollisionswahrscheinlichkeit funktioniert und wann Sie welches für Datenbankprimärschlüssel, URLs und verteilte Systeme verwenden.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Entwickler-Tools",
    tags: ["UUID", "NanoID", "CUID", "Datenbank", "verteilte Systeme", "Bezeichner"],
    readTime: 8,
    coverEmoji: "🆔",
    coverGradient: "from-violet-500 to-purple-700",
    locale: "de",
  },
  {
    slug: "chmod-guide-de",
    title: "Linux-Dateiberechtigungen erklärt: Ein vollständiger chmod-Leitfaden",
    description:
      "Ein vollständiger Leitfaden zu Unix-Dateiberechtigungen — das Eigentümer/Gruppe/Andere-Modell, Oktalnotation (755, 644, 777), symbolische Notation, Setuid/Setgid/Sticky Bit und Praxisbeispiele für Webserver und SSH-Schlüssel.",
    date: "2026-03-21",
    author: "BrowseryTools Team",
    category: "Entwickler-Tools",
    tags: ["chmod", "Linux", "Dateiberechtigungen", "Unix", "Sicherheit", "Systemadministration"],
    readTime: 8,
    coverEmoji: "🔒",
    coverGradient: "from-green-500 to-teal-600",
    locale: "de",
  },
  {
    slug: "http-status-codes-guide-de",
    title: "HTTP-Statuscodes, die jeder Entwickler kennen sollte",
    description:
      "Eine praktische Referenz für HTTP-Statuscodes — die fünf Kategorien, Tiefblicke auf 200, 201, 204, 301, 302, 304, 400, 401, 403, 404, 409, 422, 429, 500, 502, 503 sowie Leitlinien zum REST-API-Design und Debugging in DevTools.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Entwickler-Tools",
    tags: ["HTTP", "Statuscodes", "REST API", "Webentwicklung", "Debugging"],
    readTime: 7,
    coverEmoji: "📡",
    coverGradient: "from-orange-500 to-red-600",
    locale: "de",
  },
  {
    slug: "video-compression-guide-de",
    title: "So komprimieren Sie Videodateien ohne Qualitätsverlust",
    description:
      "Ein praktischer Leitfaden zur Videokomprimierung: wie Codecs wie H.264, H.265, VP9 und AV1 funktionieren, was die Dateigröße wirklich steuert, verlustfreie vs. verlustbehaftete Komprimierung und die besten Einstellungen für E-Mail, Web, soziale Medien und Archivierung.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Medien-Tools",
    tags: ["Videokomprimierung", "H.264", "Codec", "Dateigröße", "Videobearbeitung"],
    readTime: 7,
    coverEmoji: "🎬",
    coverGradient: "from-red-500 to-pink-600",
    locale: "de",
  },
  {
    slug: "image-formats-guide-de",
    title: "JPEG vs. PNG vs. WebP vs. AVIF: Der vollständige Bildformat-Vergleich",
    description:
      "Verstehen Sie, wie JPEG, PNG, WebP und AVIF Bilder intern komprimieren, wann Sie jedes Format einsetzen, wie sie Core Web Vitals beeinflussen und wie Sie das richtige Format für den richtigen Browser ausliefern.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Bild-Tools",
    tags: ["Bildformate", "JPEG", "PNG", "WebP", "AVIF", "Web-Performance", "Core Web Vitals"],
    readTime: 8,
    coverEmoji: "🖼️",
    coverGradient: "from-blue-500 to-cyan-500",
    locale: "de",
  },
  {
    slug: "exif-data-guide-de",
    title: "EXIF-Metadaten: Was Ihre Fotos über Sie verraten (und wie Sie es entfernen)",
    description:
      "EXIF-Daten betten GPS-Koordinaten, Geräteseriennummern und Zeitstempel in jedes Foto ein, das Sie aufnehmen. Erfahren Sie, was aufgezeichnet wird, die realen Datenschutzrisiken, bekannte Fälle wo Standorte enthüllt wurden und wie man sie anzeigt und entfernt.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Datenschutz & Sicherheit",
    tags: ["EXIF", "Metadaten", "Datenschutz", "GPS", "Fotosicherheit", "Bilddaten"],
    readTime: 8,
    coverEmoji: "📷",
    coverGradient: "from-amber-500 to-orange-600",
    locale: "de",
  },
  {
    slug: "svg-guide-de",
    title: "SVG-Dateien: Ein vollständiger Leitfaden für Entwickler und Designer",
    description:
      "Alles über SVG: das XML-basierte Vektorformat, das unendlich skaliert, wie Kernelemente wie path und viewBox funktionieren, CSS-Gestaltung und Animation, SVGO-Optimierung, XSS-Risiken durch nutzerhochgeladene SVGs und wann SVG in PNG konvertiert werden soll.",
    date: "2026-03-21",
    author: "BrowseryTools Team",
    category: "Entwickler-Tools",
    tags: ["SVG", "Vektorgrafiken", "Webentwicklung", "CSS", "SVGO", "Icons"],
    readTime: 9,
    coverEmoji: "✏️",
    coverGradient: "from-violet-500 to-purple-600",
    locale: "de",
  },
  {
    slug: "lorem-ipsum-guide-de",
    title: "Lorem Ipsum: Ursprung, Verwendung und warum Designer nicht darauf verzichten können",
    description:
      "Die ganze Geschichte hinter Lorem Ipsum — von Ciceros philosophischem Text aus 45 v. Chr. bis zu modernen Design-Workflows. Erfahren Sie, wann Sie es verwenden, wann Sie es vermeiden und wie Sie genau die Menge generieren, die Sie benötigen.",
    date: "2026-03-17",
    author: "BrowseryTools Team",
    category: "Text-Tools",
    tags: ["lorem ipsum", "Platzhaltertext", "Design", "Typografie"],
    readTime: 6,
    coverEmoji: "📝",
    coverGradient: "from-slate-500 to-gray-600",
    locale: "de",
  },
  {
    slug: "markdown-complete-guide-de",
    title: "Markdown: Vollständige Syntaxreferenz für Autoren und Entwickler",
    description:
      "Ein umfassender Leitfaden zu Markdown — wer es erstellt hat und warum, vollständige Syntaxreferenz von Grundlagen bis erweiterten Funktionen, Markdown-Varianten (CommonMark, GFM, MDX) und häufige Fehler zu vermeiden.",
    date: "2026-03-18",
    author: "BrowseryTools Team",
    category: "Text-Tools",
    tags: ["markdown", "Syntax", "Schreiben", "Dokumentation", "Entwickler"],
    readTime: 7,
    coverEmoji: "✍️",
    coverGradient: "from-indigo-500 to-blue-600",
    locale: "de",
  },
  {
    slug: "text-diff-guide-de",
    title: "So vergleichen Sie Textdateien und finden Unterschiede ohne Software",
    description:
      "Erfahren Sie, wie Text-Diff-Algorithmen funktionieren, wie man Unified-Diff-Ausgaben liest, den Unterschied zwischen Zeilen- und Wortebene-Diffs und wie git diff intern funktioniert.",
    date: "2026-03-19",
    author: "BrowseryTools Team",
    category: "Entwickler-Tools",
    tags: ["diff", "Textvergleich", "git", "Code-Review", "Dateivergleich"],
    readTime: 6,
    coverEmoji: "🔍",
    coverGradient: "from-emerald-500 to-teal-600",
    locale: "de",
  },
  {
    slug: "text-encryption-guide-de",
    title: "Clientseitige Textverschlüsselung: Sensible Daten im Browser schützen",
    description:
      "Ein praktischer Leitfaden zur browserbasierten Textverschlüsselung — was clientseitige Verschlüsselung wirklich bedeutet, symmetrische vs. asymmetrische Algorithmen, Schlüsselableitung aus Passwörtern und die realen Grenzen der In-Browser-Kryptografie.",
    date: "2026-03-20",
    author: "BrowseryTools Team",
    category: "Sicherheit",
    tags: ["Verschlüsselung", "AES", "Sicherheit", "Datenschutz", "Kryptografie", "Browser"],
    readTime: 7,
    coverEmoji: "🔐",
    coverGradient: "from-rose-500 to-pink-600",
    locale: "de",
  },
  {
    slug: "word-frequency-guide-de",
    title: "Wortfrequenzanalyse: Ein Werkzeug für Autoren, SEO und Forschung",
    description:
      "Wie Wortfrequenzanalyse Schreibmuster, Schlüsselwortdichte und Dokumentthemen enthüllt. Behandelt Stoppwörter, TF-IDF einfach erklärt, Anwendungsfälle für Autoren und SEO sowie akademische Anwendungen wie Autorschaftsattribution.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Text-Tools",
    tags: ["Wortfrequenz", "Textanalyse", "SEO", "Schreiben", "NLP", "Inhalt"],
    readTime: 6,
    coverEmoji: "📊",
    coverGradient: "from-violet-500 to-purple-600",
    locale: "de",
  },
];
