import type { BlogPost } from "./blog-data";

export const ruPostsB4: BlogPost[] = [
  {
    slug: "unix-timestamp-guide-ru",
    title: "Unix-временны́е метки: полное руководство",
    description:
      "Что такое Unix-временны́е метки, почему они начинаются с 1 января 1970 года, как конвертировать их в читаемые даты и как с ними работать на практике.",
    date: "2026-03-20",
    author: "BrowseryTools Team",
    readTime: 9,
    category: "Инструменты разработчика",
    tags: ["unix timestamp", "время", "дата", "эпоха", "разработка"],
    coverEmoji: "⏱️",
    coverGradient: "from-violet-500 to-purple-700",
    featured: false,
    locale: "ru",
  },
  {
    slug: "url-encoder-guide-ru",
    title: "Кодирование и декодирование URL: полное руководство",
    description:
      "Как работает процентное кодирование URL, какие символы нужно кодировать, в чём разница между encodeURIComponent и encodeURI, и когда кодирование URL важно для безопасности.",
    date: "2026-03-19",
    author: "BrowseryTools Team",
    readTime: 7,
    category: "Инструменты разработчика",
    tags: ["url", "кодирование", "декодирование", "процентное кодирование", "веб"],
    coverEmoji: "🔗",
    coverGradient: "from-cyan-500 to-blue-600",
    featured: false,
    locale: "ru",
  },
  {
    slug: "uuid-generator-guide-ru",
    title: "UUID: что это такое и как их генерировать",
    description:
      "Что такое UUID, чем отличаются версии UUID v1, v4, v5, когда использовать UUID вместо последовательных идентификаторов и как безопасно генерировать их в браузере.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    readTime: 8,
    category: "Инструменты разработчика",
    tags: ["uuid", "идентификаторы", "генератор", "уникальность", "разработка"],
    coverEmoji: "🆔",
    coverGradient: "from-violet-500 to-purple-700",
    featured: false,
    locale: "ru",
  },
  {
    slug: "chmod-guide-ru",
    title: "Права доступа к файлам Unix и команда chmod: полное руководство",
    description:
      "Как работают права доступа к файлам Unix, что означают восьмеричные коды chmod, как читать вывод ls -l и практические примеры команд chmod.",
    date: "2026-03-21",
    author: "BrowseryTools Team",
    readTime: 8,
    category: "Инструменты разработчика",
    tags: ["chmod", "права доступа", "linux", "unix", "файловая система"],
    coverEmoji: "🔒",
    coverGradient: "from-green-500 to-teal-600",
    featured: false,
    locale: "ru",
  },
  {
    slug: "http-status-codes-guide-ru",
    title: "Коды состояния HTTP: полный справочник",
    description:
      "Что означает каждый код состояния HTTP, как интерпретировать ответы 1xx, 2xx, 3xx, 4xx и 5xx и как использовать правильные коды при проектировании API.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    readTime: 7,
    category: "Инструменты разработчика",
    tags: ["http", "коды состояния", "api", "веб", "разработка"],
    coverEmoji: "📡",
    coverGradient: "from-orange-500 to-red-600",
    featured: false,
    locale: "ru",
  },
  {
    slug: "video-compression-guide-ru",
    title: "Сжатие видео: как оно работает и почему это важно",
    description:
      "Как работают кодеки видео, в чём разница между H.264, H.265, VP9 и AV1, что такое битрейт и как балансировать между качеством и размером файла.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    readTime: 7,
    category: "Медиаинструменты",
    tags: ["видео", "сжатие", "кодеки", "h.264", "h.265", "av1"],
    coverEmoji: "🎬",
    coverGradient: "from-red-500 to-pink-600",
    featured: false,
    locale: "ru",
  },
  {
    slug: "image-formats-guide-ru",
    title: "Форматы изображений: JPEG, PNG, WebP, AVIF и другие",
    description:
      "Чем отличаются форматы изображений, когда использовать JPEG, PNG, WebP или AVIF, как работают алгоритмы сжатия и как выбрать правильный формат для вашего проекта.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    readTime: 8,
    category: "Инструменты работы с изображениями",
    tags: ["изображения", "форматы", "jpeg", "png", "webp", "avif", "сжатие"],
    coverEmoji: "🖼️",
    coverGradient: "from-blue-500 to-cyan-500",
    featured: false,
    locale: "ru",
  },
  {
    slug: "exif-data-guide-ru",
    title: "EXIF-данные: метаданные фотографий и конфиденциальность",
    description:
      "Что такое EXIF-данные, какие метаданные хранятся в фотографиях, как они могут раскрыть вашу личную информацию и как безопасно удалить их перед публикацией.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    readTime: 8,
    category: "Конфиденциальность и безопасность",
    tags: ["exif", "метаданные", "конфиденциальность", "фотографии", "геолокация"],
    coverEmoji: "📷",
    coverGradient: "from-amber-500 to-orange-600",
    featured: false,
    locale: "ru",
  },
  {
    slug: "svg-guide-ru",
    title: "SVG: векторная графика для веба",
    description:
      "Что такое SVG, как писать SVG-код вручную, как оптимизировать SVG-файлы и почему SVG лучше растровых изображений для иконок, логотипов и иллюстраций.",
    date: "2026-03-21",
    author: "BrowseryTools Team",
    readTime: 9,
    category: "Инструменты разработчика",
    tags: ["svg", "векторная графика", "веб", "иконки", "анимация"],
    coverEmoji: "✏️",
    coverGradient: "from-violet-500 to-purple-600",
    featured: false,
    locale: "ru",
  },
  {
    slug: "lorem-ipsum-guide-ru",
    title: "Lorem Ipsum: история и правила использования текста-заполнителя",
    description:
      "Откуда взялся Lorem Ipsum, почему он выглядит как латынь, когда стоит и когда не стоит использовать текст-заполнитель в дизайне и прототипировании.",
    date: "2026-03-17",
    author: "BrowseryTools Team",
    readTime: 6,
    category: "Текстовые инструменты",
    tags: ["lorem ipsum", "текст-заполнитель", "дизайн", "типографика", "прототипирование"],
    coverEmoji: "📝",
    coverGradient: "from-slate-500 to-gray-600",
    featured: false,
    locale: "ru",
  },
  {
    slug: "markdown-complete-guide-ru",
    title: "Полное руководство по Markdown",
    description:
      "Полный справочник синтаксиса Markdown: заголовки, списки, ссылки, изображения, таблицы, блоки кода и расширения GitHub Flavored Markdown.",
    date: "2026-03-18",
    author: "BrowseryTools Team",
    readTime: 7,
    category: "Текстовые инструменты",
    tags: ["markdown", "форматирование", "текст", "документация", "github"],
    coverEmoji: "✍️",
    coverGradient: "from-indigo-500 to-blue-600",
    featured: false,
    locale: "ru",
  },
  {
    slug: "text-diff-guide-ru",
    title: "Сравнение текста и алгоритмы diff: полное руководство",
    description:
      "Как работают алгоритмы diff, как читать унифицированный формат diff, когда использовать построчное, пословное и посимвольное сравнение и практические применения.",
    date: "2026-03-19",
    author: "BrowseryTools Team",
    readTime: 6,
    category: "Инструменты разработчика",
    tags: ["diff", "сравнение текста", "git", "версионирование", "разработка"],
    coverEmoji: "🔍",
    coverGradient: "from-emerald-500 to-teal-600",
    featured: false,
    locale: "ru",
  },
  {
    slug: "text-encryption-guide-ru",
    title: "Шифрование текста: клиентское шифрование и AES-256",
    description:
      "Что такое клиентское шифрование, как работает AES-256-GCM, чем симметричное шифрование отличается от асимметричного и как безопасно шифровать текст прямо в браузере.",
    date: "2026-03-20",
    author: "BrowseryTools Team",
    readTime: 7,
    category: "Безопасность",
    tags: ["шифрование", "aes", "конфиденциальность", "безопасность", "криптография"],
    coverEmoji: "🔐",
    coverGradient: "from-rose-500 to-pink-600",
    featured: false,
    locale: "ru",
  },
  {
    slug: "word-frequency-guide-ru",
    title: "Частотный анализ слов: практическое руководство",
    description:
      "Как работает частотный анализ слов, зачем фильтруют стоп-слова, что такое TF-IDF и как использовать частотный анализ для SEO, редактирования и академических исследований.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    readTime: 6,
    category: "Текстовые инструменты",
    tags: ["частота слов", "анализ текста", "tf-idf", "seo", "стоп-слова"],
    coverEmoji: "📊",
    coverGradient: "from-violet-500 to-purple-600",
    featured: false,
    locale: "ru",
  },
];
