import type { BlogPost } from "./blog-data";

export const idPosts: BlogPost[] = [
  {
    slug: "keep-laptop-awake-browser-id",
    title: "Cara Membuat Laptop Tetap Menyala Tanpa Memasang Apa Pun (Mac, Windows, Linux)",
    description: "Cegah laptop atau ponsel Anda masuk mode sleep dengan satu tab browser — tanpa aplikasi, tanpa akun, tanpa iklan. Menggunakan Screen Wake Lock API. Bekerja di Mac, Windows, Linux, iOS, dan Android.",
    date: "2026-04-14",
    author: "BrowseryTools Team",
    category: "Produktivitas",
    tags: ["keep awake", "wake lock", "laptop sleep", "produktivitas", "browser api", "lintas-platform"],
    readTime: 8,
    featured: true,
    coverEmoji: "⚡",
    coverGradient: "from-emerald-500 to-teal-600",
    locale: "id",
  },
  {
    slug: "why-browser-tools-keep-your-data-private-id",
    title: "Mengapa Tool Berbasis Browser Adalah Cara Teraman Menangani Data Anda",
    description: "Pelajari bagaimana tool berbasis browser seperti BrowseryTools memproses semuanya secara lokal di perangkat Anda — file, password, dan data sensitif Anda tidak pernah meninggalkan komputer Anda.",
    date: "2026-02-20",
    author: "BrowseryTools Team",
    category: "Privasi & Keamanan",
    tags: ["privasi", "keamanan", "browser", "pemrosesan lokal", "tanpa unggahan"],
    readTime: 7,
    featured: true,
    coverEmoji: "🔒",
    coverGradient: "from-indigo-500 to-purple-600",
    locale: "id",
  },
  {
    slug: "best-free-developer-tools-browser-id",
    title: "Panduan Lengkap Tool Developer Gratis di Browser Anda",
    description: "JSON formatter, Base64 encoder, JWT decoder, regex tester, UUID generator, dan banyak lagi — semuanya gratis, semuanya di browser Anda. Tanpa instalasi, tanpa iklan, tanpa pendaftaran.",
    date: "2026-02-18",
    author: "BrowseryTools Team",
    category: "Tool Developer",
    tags: ["developer", "JSON", "Base64", "JWT", "regex", "UUID", "tool gratis"],
    readTime: 9,
    featured: true,
    coverEmoji: "⚡",
    coverGradient: "from-amber-500 to-orange-600",
    locale: "id",
  },
  {
    slug: "meme-generator-guide-id",
    title: "Cara Membuat Meme Online Gratis — Tanpa Aplikasi, Tanpa Unggahan, Tanpa Watermark",
    description: "Buat meme online gratis di browser Anda. Unggah gambar, tambahkan teks atas dan bawah dengan font Impact klasik, seret untuk memposisikan, beri gaya tiap baris, dan unduh sebagai PNG. Tidak ada yang diunggah, tanpa watermark.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Tool Gambar",
    tags: ["generator meme", "membuat meme", "pembuat meme", "font Impact", "gratis", "tanpa unggahan"],
    readTime: 7,
    featured: true,
    coverEmoji: "😂",
    coverGradient: "from-yellow-400 to-orange-500",
    locale: "id",
  },
  {
    slug: "favicon-generator-guide-id",
    title: "Cara Membuat Favicon dari Sebuah Gambar (atau Huruf) — Generator Online Gratis",
    description: "Gunakan generator favicon online gratis untuk membuat favicon dari sebuah gambar atau huruf/emoji. Dapatkan semua ukuran (16, 32, 180, 192, 512), favicon.ico multi-ukuran, manifest, dan cuplikan HTML — semuanya di browser Anda.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Tool Developer",
    tags: ["favicon", "generator favicon", "buat favicon dari gambar", "generator favicon online", "pengembangan web", "ikon"],
    readTime: 7,
    featured: true,
    coverEmoji: "🌟",
    coverGradient: "from-violet-500 to-fuchsia-600",
    locale: "id",
  },
  {
    slug: "text-to-speech-guide-id",
    title: "Cara Membacakan Teks dengan Suara Keras Online Gratis — Tanpa Aplikasi, Tanpa Akun",
    description: "Ubah teks apa pun menjadi ucapan langsung di browser Anda. Atur suara, kecepatan, nada, dan volume dengan tool Web Speech API gratis — privat, instan, dan bekerja di Mac, Windows, Linux, iOS, dan Android.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Teks & Bahasa",
    tags: ["text to speech online gratis", "baca teks dengan suara keras", "TTS", "web speech api", "aksesibilitas", "voiceover"],
    readTime: 7,
    featured: true,
    coverEmoji: "🔊",
    coverGradient: "from-sky-500 to-indigo-600",
    locale: "id",
  },
];
