import type { BlogPost } from "./blog-data";

export const frPostsB2: BlogPost[] = [
  {
    slug: "password-security-guide-fr",
    title:
      "Sécurité des mots de passe : pourquoi la plupart sont faibles et comment en créer de solides",
    description:
      "La plupart des gens utilisent des mots de passe faibles sans le savoir. Découvrez ce qui rend un mot de passe solide, comment vérifier le vôtre instantanément et en générer d'inviolables — le tout en toute confidentialité dans votre navigateur.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Sécurité",
    tags: [
      "mot de passe",
      "sécurité",
      "piratage",
      "générateur de mots de passe",
      "robustesse des mots de passe",
    ],
    readTime: 8,
    featured: false,
    coverEmoji: "🛡️",
    coverGradient: "from-green-500 to-emerald-600",
    locale: "fr",
  },
  {
    slug: "remove-image-background-free-fr",
    title:
      "Comment supprimer l'arrière-plan d'une image gratuitement — sans Canva, sans Photoshop",
    description:
      "Supprimez l'arrière-plan de vos photos instantanément grâce à l'IA, directement dans votre navigateur. Sans téléversement, sans abonnement, sans filigrane. Vos images ne quittent jamais votre appareil.",
    date: "2026-02-12",
    author: "BrowseryTools Team",
    category: "Outils d'image",
    tags: [
      "suppression d'arrière-plan",
      "édition d'image",
      "IA",
      "gratuit",
      "sans téléversement",
      "confidentialité",
    ],
    readTime: 6,
    featured: false,
    coverEmoji: "🖼️",
    coverGradient: "from-pink-500 to-rose-600",
    locale: "fr",
  },
  {
    slug: "boost-productivity-pomodoro-todo-fr",
    title:
      "10 façons de booster votre productivité avec des outils de navigateur gratuits",
    description:
      "Du minuteur Pomodoro aux listes de tâches, de l'horloge mondiale au suivi des dépenses — découvrez les outils de productivité qui fonctionnent entièrement dans votre navigateur, sans aucune collecte de données.",
    date: "2026-02-10",
    author: "BrowseryTools Team",
    category: "Productivité",
    tags: [
      "productivité",
      "pomodoro",
      "liste de tâches",
      "concentration",
      "gestion du temps",
    ],
    readTime: 7,
    featured: false,
    coverEmoji: "🎯",
    coverGradient: "from-blue-500 to-cyan-600",
    locale: "fr",
  },
  {
    slug: "free-image-tools-guide-fr",
    title:
      "Le guide complet des outils d'image gratuits — compresser, convertir, redimensionner sans téléverser",
    description:
      "Compression d'images, conversion de formats, redimensionnement, correction des couleurs et suppression d'arrière-plan — le tout traité localement dans votre navigateur, sans téléversement et gratuitement.",
    date: "2026-02-08",
    author: "BrowseryTools Team",
    category: "Outils d'image",
    tags: [
      "compression d'image",
      "convertisseur d'image",
      "redimensionner",
      "gratuit",
      "sans téléversement",
    ],
    readTime: 8,
    featured: false,
    coverEmoji: "🎨",
    coverGradient: "from-violet-500 to-fuchsia-600",
    locale: "fr",
  },
  {
    slug: "qr-code-generator-guide-fr",
    title:
      "Comment générer des QR codes gratuitement — pour des liens, du texte, du Wi-Fi et des cartes de visite",
    description:
      "Générez un nombre illimité de QR codes pour tout contenu — URL, texte brut, identifiants Wi-Fi, vCards — avec une personnalisation complète. 100 % gratuit, sans inscription, fonctionne hors ligne.",
    date: "2026-02-05",
    author: "BrowseryTools Team",
    category: "Outils utilitaires",
    tags: [
      "QR code",
      "générateur de QR code",
      "QR code gratuit",
      "hors ligne",
      "carte de visite",
    ],
    readTime: 5,
    featured: false,
    coverEmoji: "📱",
    coverGradient: "from-teal-500 to-green-600",
    locale: "fr",
  },
  {
    slug: "text-tools-for-writers-developers-fr",
    title:
      "Les meilleurs outils de texte gratuits pour les rédacteurs, développeurs et créateurs de contenu",
    description:
      "Convertisseur de casse, générateur de Lorem ipsum, compteur de caractères, outil de comparaison de texte, éditeur Markdown et bien plus. Tout ce dont un rédacteur ou un développeur a besoin — gratuit et privé.",
    date: "2026-02-03",
    author: "BrowseryTools Team",
    category: "Outils de texte",
    tags: [
      "outils de texte",
      "rédaction",
      "markdown",
      "convertisseur de texte",
      "lorem ipsum",
    ],
    readTime: 6,
    featured: false,
    coverEmoji: "✍️",
    coverGradient: "from-slate-500 to-gray-600",
    locale: "fr",
  },
  {
    slug: "base64-encoding-guide-fr",
    title: "Qu'est-ce que l'encodage Base64 ? Un guide complet avec exemples",
    description:
      "Découvrez ce qu'est l'encodage Base64, pourquoi il existe, où il est utilisé, et comment encoder et décoder des chaînes Base64 instantanément dans votre navigateur — sans aucun outil à installer.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Outils de développement",
    tags: [
      "base64",
      "encodage",
      "développeur",
      "binaire",
      "formats de données",
    ],
    readTime: 7,
    featured: false,
    coverEmoji: "🔡",
    coverGradient: "from-cyan-500 to-blue-600",
    locale: "fr",
  },
  {
    slug: "jwt-decoder-guide-fr",
    title: "Comment décoder et vérifier des jetons JWT dans votre navigateur",
    description:
      "Les jetons JWT sont partout dans l'authentification moderne. Découvrez ce qu'ils contiennent, comment les décoder, repérer les problèmes d'expiration et déboguer les problèmes d'authentification — le tout en toute confidentialité dans votre navigateur.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Outils de développement",
    tags: [
      "JWT",
      "authentification",
      "jeton",
      "OAuth",
      "sécurité",
      "développeur",
    ],
    readTime: 8,
    featured: false,
    coverEmoji: "🔑",
    coverGradient: "from-yellow-500 to-amber-600",
    locale: "fr",
  },
  {
    slug: "css-gradient-generator-guide-fr",
    title:
      "Générateur de dégradés CSS : créez de beaux dégradés sans écrire de code",
    description:
      "Construisez visuellement des dégradés CSS linéaires, radiaux et coniques avec un aperçu en direct. Copiez du CSS prêt pour la production en un clic — sans logiciel de design.",
    date: "2026-02-20",
    author: "BrowseryTools Team",
    category: "Outils de design",
    tags: ["CSS", "dégradé", "design", "frontend", "UI", "couleurs"],
    readTime: 5,
    featured: false,
    coverEmoji: "🌈",
    coverGradient: "from-purple-500 to-pink-600",
    locale: "fr",
  },
  {
    slug: "hash-generator-guide-fr",
    title:
      "MD5, SHA-256, SHA-512 : générateur de hachage gratuit et quand utiliser chacun",
    description:
      "Comprenez la différence entre MD5, SHA-1, SHA-256 et SHA-512. Générez des empreintes de fichiers et de texte instantanément dans votre navigateur. Apprenez quand chaque algorithme est approprié.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Sécurité",
    tags: [
      "hachage",
      "MD5",
      "SHA-256",
      "SHA-512",
      "somme de contrôle",
      "cryptographie",
    ],
    readTime: 7,
    featured: false,
    coverEmoji: "#️⃣",
    coverGradient: "from-gray-500 to-slate-700",
    locale: "fr",
  },
  {
    slug: "screen-recorder-guide-fr",
    title: "Enregistrez votre écran sans installer aucun logiciel",
    description:
      "Votre navigateur peut enregistrer votre écran, une fenêtre ou un onglet grâce à l'API Screen Capture. Découvrez comment capturer une vidéo pour des tutoriels, des rapports de bogues et des démonstrations — sans aucune extension.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Outils utilitaires",
    tags: [
      "enregistreur d'écran",
      "capture d'écran",
      "tutoriel",
      "vidéo",
      "API du navigateur",
    ],
    readTime: 5,
    featured: false,
    coverEmoji: "🎬",
    coverGradient: "from-red-500 to-rose-600",
    locale: "fr",
  },
  {
    slug: "fake-data-generator-guide-fr",
    title:
      "Comment générer de fausses données de test réalistes (JSON et CSV) gratuitement",
    description:
      "Remplissez des bases de données, prototypez des interfaces et écrivez des tests avec de faux noms, e-mails, adresses, numéros de téléphone réalistes et plus encore — exportés en JSON ou CSV, le tout dans votre navigateur.",
    date: "2026-02-16",
    author: "BrowseryTools Team",
    category: "Outils de développement",
    tags: [
      "fausses données",
      "données de test",
      "données fictives",
      "JSON",
      "CSV",
      "outils de développement",
    ],
    readTime: 6,
    featured: false,
    coverEmoji: "🤖",
    coverGradient: "from-green-500 to-teal-600",
    locale: "fr",
  },
  {
    slug: "cron-expression-guide-fr",
    title:
      "Les expressions cron expliquées : comment lire et écrire des planifications cron",
    description:
      "La syntaxe cron reste obscure jusqu'à ce que vous compreniez les cinq champs. Apprenez à lire et écrire des expressions cron, à éviter les erreurs courantes et à analyser n'importe quelle planification instantanément dans votre navigateur.",
    date: "2026-02-14",
    author: "BrowseryTools Team",
    category: "Outils de développement",
    tags: [
      "cron",
      "expression cron",
      "planificateur",
      "DevOps",
      "automatisation",
      "Linux",
    ],
    readTime: 7,
    featured: false,
    coverEmoji: "⏰",
    coverGradient: "from-orange-500 to-red-600",
    locale: "fr",
  },
  {
    slug: "bmi-calculator-guide-fr",
    title:
      "Calculateur d'IMC : ce que c'est, comment le calculer et ce qu'il signifie vraiment",
    description:
      "Calculez votre IMC instantanément en unités métriques ou impériales. Comprenez ce que signifie ce chiffre, ses limites et à quoi correspond un poids santé pour votre taille.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Santé et forme",
    tags: ["IMC", "indice de masse corporelle", "santé", "poids", "calculateur"],
    readTime: 6,
    featured: false,
    coverEmoji: "⚖️",
    coverGradient: "from-teal-500 to-cyan-600",
    locale: "fr",
  },
];
