import type { BlogPost } from "./blog-data";

export const dePostsB5: BlogPost[] = [
  {
    slug: "expense-tracker-guide-de",
    title: "Monatliche Ausgaben verfolgen ohne Apps, Abonnements oder Cloud-Speicher",
    description:
      "Die meisten Menschen haben keine Ahnung, wohin ihr Geld geht. Lernen Sie die 50/30/20-Budgetierungsregel, den Unterschied zwischen fixen und variablen Ausgaben und wie Sie eine monatliche Ausgabenüberprüfung durchführen — ohne sich irgendwo anmelden zu müssen.",
    date: "2026-03-16",
    author: "BrowseryTools Team",
    category: "Produktivität",
    tags: ["ausgaben-tracker", "budgetierung", "persönliche finanzen", "geldverwaltung"],
    readTime: 7,
    coverEmoji: "💸",
    coverGradient: "from-emerald-500 to-green-600",
    locale: "de",
  },
  {
    slug: "invoice-generator-guide-de",
    title: "Professionelle Rechnungen kostenlos erstellen — ohne Abonnement",
    description:
      "Ein vollständiger Leitfaden zur professionellen Rechnungsstellung: Pflichtfelder, Nummerierungskonventionen, Zahlungsziele wie Netto 30, Mahngebührenformulierungen, MwSt.- und GST-Anforderungen nach Land und warum ein kostenloses PDF-Tool besser ist als ein 100-€/Jahr-Abonnement.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Geschäft",
    tags: ["rechnung", "freiberuflich", "abrechnung", "zahlungsziele", "PDF"],
    readTime: 7,
    coverEmoji: "🧾",
    coverGradient: "from-violet-500 to-purple-600",
    locale: "de",
  },
  {
    slug: "loan-calculator-guide-de",
    title: "Kreditrechner: Ihre Hypothek, Ihren Autokredit oder Privatkredit verstehen",
    description:
      "Die Kreditratenformel erklärt, Amortisation entmystifiziert (warum frühe Zahlungen hauptsächlich Zinsen sind), effektiver Jahreszins vs. Nominalzinssatz, wie Sonderzahlungen Tausende sparen und wie man Kreditangebote tatsächlich vergleicht.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Finanzen",
    tags: ["kreditrechner", "hypothek", "amortisation", "effektiver jahreszins", "persönliche finanzen"],
    readTime: 8,
    coverEmoji: "🏦",
    coverGradient: "from-blue-500 to-cyan-600",
    locale: "de",
  },
  {
    slug: "currency-converter-guide-de",
    title: "Wie Wechselkurse funktionieren: Ein praktischer Leitfaden",
    description:
      "Was Wechselkurse beeinflusst, der Geld-Brief-Spread, warum Sie nie den Mittelkurs bekommen, wie Banken und Kreditkarten Gebühren in Spreads verstecken und die Währungsfallen für Reisende und internationale Freiberufler.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Finanzen",
    tags: ["währungsrechner", "wechselkurse", "forex", "reisen", "internationale zahlungen"],
    readTime: 7,
    coverEmoji: "💱",
    coverGradient: "from-amber-500 to-orange-500",
    locale: "de",
  },
  {
    slug: "timezone-guide-de",
    title: "Arbeit über Zeitzonen hinweg: Ein vollständiger Leitfaden für Remote-Teams",
    description:
      "Wie UTC-Offsets funktionieren, warum Sommerzeit die Planung fehleranfällig macht, Best Practices für Meeting-Planung im Remote-Team, das ISO-8601-Datumsformat und die goldene Regel für Entwickler: Zeitstempel immer in UTC speichern.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Produktivität",
    tags: ["zeitzone", "remote-arbeit", "UTC", "planung", "ISO 8601", "entwickler"],
    readTime: 8,
    coverEmoji: "🌐",
    coverGradient: "from-purple-500 to-violet-600",
    locale: "de",
  },
  {
    slug: "compress-video-online-free-de",
    title: "Video online kostenlos komprimieren (kein Upload, kein Wasserzeichen)",
    description:
      "Videodateigröße direkt im Browser reduzieren — kostenlos, kein Konto, kein Wasserzeichen, nichts wird hochgeladen. Lernen Sie die Bitrate-, Auflösungs- und Codec-Einstellungen, die ein Video tatsächlich verkleinern, plus die besten Presets für E-Mail, soziale Medien und das Web.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Medien-Tools",
    tags: ["video online komprimieren kostenlos", "videogröße reduzieren", "videokomprimierung", "video verkleinern", "kein upload", "kostenlos"],
    readTime: 7,
    coverEmoji: "🎬",
    coverGradient: "from-rose-500 to-red-600",
    locale: "de",
  },
  {
    slug: "redact-image-online-de",
    title: "Bilder online schwärzen oder zensieren (Gesichter weichzeichnen & sensible Daten verbergen)",
    description:
      "Gesichter weichzeichnen, Kennzeichen verpixeln und sensible Details in jedem Bild schwärzen — vollständig im Browser, nichts wird hochgeladen. Erfahren Sie, welcher Zensur-Stil wirklich irreversibel ist und welcher Metadatenfehler geschwärzte Daten still preisgibt.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Bild-Tools",
    tags: ["bild schwärzen", "gesichter weichzeichnen", "foto zensieren", "sensible daten verbergen", "verpixeln", "datenschutz"],
    readTime: 7,
    coverEmoji: "🖍️",
    coverGradient: "from-slate-500 to-gray-700",
    locale: "de",
  },
  {
    slug: "roman-numeral-converter-guide-de",
    title: "Römische Zahlen Umrechner: Wie römische Zahlen funktionieren (und wie man MCMXCIV liest)",
    description:
      "Die sieben Symbole, die Additions- und Subtraktionsregeln, die sechs gültigen subtraktiven Paare und häufige Fehler — alles, was Sie brauchen, um römische Zahlen zu lesen und zu schreiben, plus ein kostenloser Umrechner für beide Richtungen.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Rechner",
    tags: ["römische zahlen", "römische zahlen umrechner", "MCMXCIV", "wie römische zahlen funktionieren", "zahlenumrechner"],
    readTime: 7,
    coverEmoji: "🏛️",
    coverGradient: "from-amber-500 to-yellow-600",
    locale: "de",
  },
  {
    slug: "convert-svg-to-png-de",
    title: "SVG in PNG konvertieren (scharf und transparent halten)",
    description:
      "Vektor-SVG-Dateien direkt im Browser in universelle PNG-Bilder umwandeln — kostenlos, kein Upload, kein Wasserzeichen. Erfahren Sie, wie Sie die richtige Exportauflösung wählen, damit es nie unscharf wird, und wie Sie einen transparenten Hintergrund erhalten.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Bild-Tools",
    tags: ["SVG in PNG konvertieren", "svg zu png", "vektor zu raster", "transparentes png", "svg exportieren", "kostenlos"],
    readTime: 7,
    coverEmoji: "🖼️",
    coverGradient: "from-cyan-500 to-blue-600",
    locale: "de",
  },
  {
    slug: "convert-video-to-gif-de",
    title: "Video in GIF konvertieren (und die Datei klein halten)",
    description:
      "Einen MP4- oder MOV-Clip direkt im Browser in ein GIF umwandeln — kein Upload, kein Wasserzeichen. Erfahren Sie, warum GIFs so groß werden, die drei Einstellungen, die sie klein halten, und wann ein kurzes Video besser ist als ein GIF.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Medien-Tools",
    tags: ["video in gif konvertieren", "video zu gif", "mp4 zu gif", "gif erstellen", "kein upload", "kostenlos"],
    readTime: 6,
    coverEmoji: "🎞️",
    coverGradient: "from-fuchsia-500 to-pink-600",
    locale: "de",
  },
  {
    slug: "crop-and-watermark-images-online-de",
    title: "Bilder online zuschneiden und mit Wasserzeichen versehen (kostenlos, kein Upload)",
    description:
      "Auf ein genaues Seitenverhältnis zuschneiden, ohne Verzerrung skalieren und ein Wasserzeichen hinzufügen, das Weiterverwendung tatsächlich abschreckt — alles im Browser, das Original wird nie hochgeladen. Inklusive dem Seitenverhältnis-Fehler, der Ihre Fotos verzerrt.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Bild-Tools",
    tags: ["bild online zuschneiden", "bild wasserzeichen", "bild skalieren", "seitenverhältnis", "kein upload", "kostenlos"],
    readTime: 7,
    coverEmoji: "✂️",
    coverGradient: "from-teal-500 to-emerald-600",
    locale: "de",
  },
  {
    slug: "curl-to-fetch-python-code-de",
    title: "cURL in Code konvertieren (fetch, Python requests, Node.js)",
    description:
      "Einen cURL-Befehl einfügen und funktionierenden JavaScript-fetch-, Python-requests- oder Node.js-Code erhalten — inklusive des DevTools-Tricks 'Als cURL kopieren'. Erfahren Sie, wie jedes Flag auf Code abgebildet wird, damit Sie der Ausgabe vertrauen können — alles lokal im Browser verarbeitet.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Entwickler-Tools",
    tags: ["curl in code konvertieren", "curl zu fetch", "curl zu python", "curl konvertieren", "als curl kopieren", "api"],
    readTime: 7,
    coverEmoji: "🔁",
    coverGradient: "from-indigo-500 to-violet-600",
    locale: "de",
  },
  {
    slug: "scientific-calculator-online-de",
    title: "Wissenschaftlicher Taschenrechner online: Trigonometrie, Logarithmen, Potenzen und die Fehler, die Sie vermeiden sollten",
    description:
      "Ein kostenloser Browser-Taschenrechner mit sin, cos, tan, log, ln, Potenzen, Wurzeln und Konstanten. Lernen Sie die Grad-vs.-Bogenmaß-Falle, die Operatorrangfolge und bearbeitete Beispiele für Zinseszins, Dreiecke und pH-Werte.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Rechner",
    tags: ["wissenschaftlicher taschenrechner online", "grafikrechner", "trig-rechner", "log-rechner", "kostenloser taschenrechner"],
    readTime: 7,
    coverEmoji: "🧮",
    coverGradient: "from-blue-500 to-indigo-600",
    locale: "de",
  },
  {
    slug: "random-picker-guide-de",
    title: "Zufalls-Picker: Zufallszahlen, Würfel, Münzwurf und Namens-Roulette",
    description:
      "Zufallszahlen generieren, Würfel werfen, eine Münze werfen oder einen fairen Gewinner aus einer Liste auswählen — kostenlos und im Browser. Erfahren Sie, wie Sie eine unvoreingenommene Verlosungsziehung durchführen und wann Zufälligkeit wirklich zufällig ist.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Produktivitäts-Tools",
    tags: ["zufallszahlengenerator", "zufälliger namenspicker", "würfelwerfer", "münzwurf", "namensrad", "gewinnspiel"],
    readTime: 6,
    coverEmoji: "🎲",
    coverGradient: "from-violet-500 to-purple-600",
    locale: "de",
  },
];
