import type { BlogPost } from "./blog-data";

export const esPostsB2: BlogPost[] = [
  {
    slug: "password-security-guide-es",
    title: "Seguridad de contraseñas: por qué la mayoría son débiles y cómo crear unas fuertes",
    description:
      "La mayoría de la gente usa contraseñas débiles sin darse cuenta. Aprende qué hace fuerte a una contraseña, cómo comprobar la tuya al instante y generar contraseñas indescifrables, todo de forma privada en tu navegador.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Seguridad",
    tags: ["contraseña", "seguridad", "hackeo", "generador de contraseñas", "fortaleza de contraseña"],
    readTime: 8,
    featured: false,
    coverEmoji: "🛡️",
    coverGradient: "from-green-500 to-emerald-600",
    locale: "es",
  },
  {
    slug: "remove-image-background-free-es",
    title: "Cómo quitar el fondo de las imágenes gratis — sin Canva, sin Photoshop",
    description:
      "Quita el fondo de tus fotos al instante con IA, directamente en tu navegador. Sin subidas, sin suscripciones, sin marcas de agua. Tus imágenes nunca salen de tu dispositivo.",
    date: "2026-02-12",
    author: "BrowseryTools Team",
    category: "Herramientas de Imagen",
    tags: ["quitar fondo", "edición de imágenes", "IA", "gratis", "sin subir", "privacidad"],
    readTime: 6,
    featured: false,
    coverEmoji: "🖼️",
    coverGradient: "from-pink-500 to-rose-600",
    locale: "es",
  },
  {
    slug: "boost-productivity-pomodoro-todo-es",
    title: "10 formas de aumentar tu productividad con herramientas gratuitas del navegador",
    description:
      "Desde el temporizador Pomodoro hasta las listas de tareas, del reloj mundial al control de gastos: descubre las herramientas de productividad que funcionan por completo en tu navegador sin recopilar datos.",
    date: "2026-02-10",
    author: "BrowseryTools Team",
    category: "Productividad",
    tags: ["productividad", "pomodoro", "lista de tareas", "concentración", "gestión del tiempo"],
    readTime: 7,
    featured: false,
    coverEmoji: "🎯",
    coverGradient: "from-blue-500 to-cyan-600",
    locale: "es",
  },
  {
    slug: "free-image-tools-guide-es",
    title: "La guía completa de herramientas de imagen gratuitas — comprimir, convertir y redimensionar sin subir nada",
    description:
      "Compresión de imágenes, conversión de formatos, redimensionado, corrección de color y eliminación de fondos, todo procesado localmente en tu navegador con cero subidas y coste cero.",
    date: "2026-02-08",
    author: "BrowseryTools Team",
    category: "Herramientas de Imagen",
    tags: ["compresión de imágenes", "conversor de imágenes", "redimensionar", "gratis", "sin subir"],
    readTime: 8,
    featured: false,
    coverEmoji: "🎨",
    coverGradient: "from-violet-500 to-fuchsia-600",
    locale: "es",
  },
  {
    slug: "qr-code-generator-guide-es",
    title: "Cómo generar códigos QR gratis — para enlaces, texto, WiFi y tarjetas de visita",
    description:
      "Genera códigos QR ilimitados para cualquier contenido — URLs, texto plano, credenciales WiFi, vCards — con personalización total. 100% gratis, sin registro, funciona sin conexión.",
    date: "2026-02-05",
    author: "BrowseryTools Team",
    category: "Herramientas de Utilidad",
    tags: ["código QR", "generador QR", "código QR gratis", "sin conexión", "tarjeta de visita"],
    readTime: 5,
    featured: false,
    coverEmoji: "📱",
    coverGradient: "from-teal-500 to-green-600",
    locale: "es",
  },
  {
    slug: "text-tools-for-writers-developers-es",
    title: "Las mejores herramientas de texto gratuitas para escritores, desarrolladores y creadores de contenido",
    description:
      "Conversor de mayúsculas y minúsculas, generador de Lorem ipsum, contador de caracteres, comparador de texto, editor de Markdown y mucho más. Todo lo que un escritor o desarrollador necesita, gratis y privado.",
    date: "2026-02-03",
    author: "BrowseryTools Team",
    category: "Herramientas de Texto",
    tags: ["herramientas de texto", "escritura", "markdown", "conversor de texto", "lorem ipsum"],
    readTime: 6,
    featured: false,
    coverEmoji: "✍️",
    coverGradient: "from-slate-500 to-gray-600",
    locale: "es",
  },
  {
    slug: "base64-encoding-guide-es",
    title: "¿Qué es la codificación Base64? Una guía completa con ejemplos",
    description:
      "Aprende qué es la codificación Base64, por qué existe, dónde se usa y cómo codificar y decodificar cadenas Base64 al instante en tu navegador, sin instalar herramientas.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Herramientas para Desarrolladores",
    tags: ["base64", "codificación", "desarrollador", "binario", "formatos de datos"],
    readTime: 7,
    featured: false,
    coverEmoji: "🔡",
    coverGradient: "from-cyan-500 to-blue-600",
    locale: "es",
  },
  {
    slug: "jwt-decoder-guide-es",
    title: "Cómo decodificar y verificar tokens JWT en tu navegador",
    description:
      "Los tokens JWT están por todas partes en la autenticación moderna. Aprende qué contienen, cómo decodificarlos, detectar problemas de expiración y depurar errores de autenticación, todo de forma privada en tu navegador.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Herramientas para Desarrolladores",
    tags: ["JWT", "autenticación", "token", "OAuth", "seguridad", "desarrollador"],
    readTime: 8,
    featured: false,
    coverEmoji: "🔑",
    coverGradient: "from-yellow-500 to-amber-600",
    locale: "es",
  },
  {
    slug: "css-gradient-generator-guide-es",
    title: "Generador de degradados CSS: crea degradados bonitos sin escribir código",
    description:
      "Crea visualmente degradados CSS lineales, radiales y cónicos con una vista previa en vivo. Copia CSS listo para producción con un clic, sin necesidad de software de diseño.",
    date: "2026-02-20",
    author: "BrowseryTools Team",
    category: "Herramientas de Diseño",
    tags: ["CSS", "degradado", "diseño", "frontend", "UI", "colores"],
    readTime: 5,
    featured: false,
    coverEmoji: "🌈",
    coverGradient: "from-purple-500 to-pink-600",
    locale: "es",
  },
  {
    slug: "hash-generator-guide-es",
    title: "MD5, SHA-256, SHA-512: generador de hash gratuito y cuándo usar cada uno",
    description:
      "Entiende la diferencia entre MD5, SHA-1, SHA-256 y SHA-512. Genera hashes de archivos y texto al instante en tu navegador. Aprende cuándo es apropiado cada algoritmo.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Seguridad",
    tags: ["hash", "MD5", "SHA-256", "SHA-512", "checksum", "criptografía"],
    readTime: 7,
    featured: false,
    coverEmoji: "#️⃣",
    coverGradient: "from-gray-500 to-slate-700",
    locale: "es",
  },
  {
    slug: "screen-recorder-guide-es",
    title: "Graba tu pantalla sin instalar ningún software",
    description:
      "Tu navegador puede grabar tu pantalla, ventana o pestaña usando la Screen Capture API. Aprende a capturar vídeo para tutoriales, informes de errores y demos, sin extensiones.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Herramientas de Utilidad",
    tags: ["grabador de pantalla", "captura de pantalla", "tutorial", "vídeo", "API del navegador"],
    readTime: 5,
    featured: false,
    coverEmoji: "🎬",
    coverGradient: "from-red-500 to-rose-600",
    locale: "es",
  },
  {
    slug: "fake-data-generator-guide-es",
    title: "Cómo generar datos de prueba falsos y realistas (JSON y CSV) gratis",
    description:
      "Llena bases de datos, prototipa interfaces y escribe pruebas con nombres, correos, direcciones, números de teléfono y más datos falsos realistas, exportados como JSON o CSV, todo en tu navegador.",
    date: "2026-02-16",
    author: "BrowseryTools Team",
    category: "Herramientas para Desarrolladores",
    tags: ["datos falsos", "datos de prueba", "datos simulados", "JSON", "CSV", "herramientas para desarrolladores"],
    readTime: 6,
    featured: false,
    coverEmoji: "🤖",
    coverGradient: "from-green-500 to-teal-600",
    locale: "es",
  },
  {
    slug: "cron-expression-guide-es",
    title: "Expresiones cron explicadas: cómo leer y escribir programaciones cron",
    description:
      "La sintaxis cron es críptica hasta que entiendes los cinco campos. Aprende a leer y escribir expresiones cron, evitar errores comunes y analizar cualquier programación al instante en tu navegador.",
    date: "2026-02-14",
    author: "BrowseryTools Team",
    category: "Herramientas para Desarrolladores",
    tags: ["cron", "expresión cron", "programador de tareas", "DevOps", "automatización", "Linux"],
    readTime: 7,
    featured: false,
    coverEmoji: "⏰",
    coverGradient: "from-orange-500 to-red-600",
    locale: "es",
  },
  {
    slug: "bmi-calculator-guide-es",
    title: "Calculadora de IMC: qué es, cómo calcularlo y qué significa realmente",
    description:
      "Calcula tu IMC al instante en unidades métricas o imperiales. Entiende qué significa el número, sus limitaciones y cómo es un peso saludable para tu estatura.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Salud y Fitness",
    tags: ["IMC", "índice de masa corporal", "salud", "peso", "calculadora"],
    readTime: 6,
    featured: false,
    coverEmoji: "⚖️",
    coverGradient: "from-teal-500 to-cyan-600",
    locale: "es",
  },
];
