import type { BlogPost } from "./blog-data";

export const ptBRPosts: BlogPost[] = [
  {
    slug: "keep-laptop-awake-browser-pt-BR",
    title: "Como manter seu notebook ativo sem instalar nada (Mac, Windows, Linux)",
    description: "Impeça seu notebook ou celular de entrar em suspensão com uma única aba do navegador — sem apps, sem contas, sem anúncios. Usa a Screen Wake Lock API. Funciona no Mac, Windows, Linux, iOS e Android.",
    date: "2026-04-14",
    author: "BrowseryTools Team",
    category: "Produtividade",
    tags: ["manter ativo", "wake lock", "suspensão do notebook", "produtividade", "api do navegador", "multiplataforma"],
    readTime: 8,
    featured: true,
    coverEmoji: "⚡",
    coverGradient: "from-emerald-500 to-teal-600",
    locale: "pt-BR",
  },
  {
    slug: "why-browser-tools-keep-your-data-private-pt-BR",
    title: "Por que as ferramentas baseadas no navegador são a forma mais segura de lidar com seus dados",
    description: "Descubra como ferramentas baseadas no navegador, como o BrowseryTools, processam tudo localmente no seu dispositivo — seus arquivos, senhas e dados sensíveis nunca saem do seu computador.",
    date: "2026-02-20",
    author: "BrowseryTools Team",
    category: "Privacidade e Segurança",
    tags: ["privacidade", "segurança", "navegador", "processamento local", "sem envios"],
    readTime: 7,
    featured: true,
    coverEmoji: "🔒",
    coverGradient: "from-indigo-500 to-purple-600",
    locale: "pt-BR",
  },
  {
    slug: "best-free-developer-tools-browser-pt-BR",
    title: "O guia definitivo de ferramentas gratuitas para desenvolvedores no seu navegador",
    description: "Formatador de JSON, codificador Base64, decodificador de JWT, testador de regex, gerador de UUID e mais — tudo gratuito, tudo no seu navegador. Sem instalações, sem anúncios, sem cadastro.",
    date: "2026-02-18",
    author: "BrowseryTools Team",
    category: "Ferramentas para Desenvolvedores",
    tags: ["desenvolvedor", "JSON", "Base64", "JWT", "regex", "UUID", "ferramentas gratuitas"],
    readTime: 9,
    featured: true,
    coverEmoji: "⚡",
    coverGradient: "from-amber-500 to-orange-600",
    locale: "pt-BR",
  },
  {
    slug: "meme-generator-guide-pt-BR",
    title: "Como criar um meme online de graça — Sem app, sem envio, sem marca-d'água",
    description: "Crie um meme online de graça no seu navegador. Envie uma imagem, adicione o clássico texto superior e inferior na fonte Impact, arraste para posicionar, dê estilo a cada linha e baixe como PNG. Nada é enviado, sem marca-d'água.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Ferramentas de Imagem",
    tags: ["gerador de memes", "criar um meme", "criador de memes", "fonte Impact", "gratuito", "sem envio"],
    readTime: 7,
    featured: true,
    coverEmoji: "😂",
    coverGradient: "from-yellow-400 to-orange-500",
    locale: "pt-BR",
  },
  {
    slug: "favicon-generator-guide-pt-BR",
    title: "Como criar um favicon a partir de uma imagem (ou de uma letra) — Gerador gratuito online",
    description: "Use um gerador de favicons gratuito online para criar um favicon a partir de uma imagem ou de uma letra/emoji. Obtenha todos os tamanhos (16, 32, 180, 192, 512), um favicon.ico multitamanho, manifesto e trecho de HTML — tudo no seu navegador.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Ferramentas para Desenvolvedores",
    tags: ["favicon", "gerador de favicons", "criar favicon a partir de imagem", "gerador de favicons online", "desenvolvimento web", "ícones"],
    readTime: 7,
    featured: true,
    coverEmoji: "🌟",
    coverGradient: "from-violet-500 to-fuchsia-600",
    locale: "pt-BR",
  },
  {
    slug: "text-to-speech-guide-pt-BR",
    title: "Como ler texto em voz alta online de graça — Sem app, sem conta",
    description: "Transforme qualquer texto em fala diretamente no seu navegador. Ajuste a voz, a velocidade, o tom e o volume com a ferramenta gratuita da Web Speech API — privada, instantânea e funciona no Mac, Windows, Linux, iOS e Android.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Texto e Idioma",
    tags: ["texto para fala online grátis", "ler texto em voz alta", "TTS", "web speech api", "acessibilidade", "narração"],
    readTime: 7,
    featured: true,
    coverEmoji: "🔊",
    coverGradient: "from-sky-500 to-indigo-600",
    locale: "pt-BR",
  },
];
