import type { BlogPost } from "./blog-data";

export const esPosts: BlogPost[] = [
  {
    slug: "keep-laptop-awake-browser-es",
    title: "Cómo mantener tu portátil activo sin instalar nada (Mac, Windows, Linux)",
    description: "Evita que tu portátil o teléfono se suspenda con una sola pestaña del navegador — sin apps, sin cuentas, sin anuncios. Usa la API Screen Wake Lock. Funciona en Mac, Windows, Linux, iOS y Android.",
    date: "2026-04-14",
    author: "BrowseryTools Team",
    category: "Productividad",
    tags: ["mantener activo", "wake lock", "suspensión del portátil", "productividad", "api del navegador", "multiplataforma"],
    readTime: 8,
    featured: true,
    coverEmoji: "⚡",
    coverGradient: "from-emerald-500 to-teal-600",
    locale: "es",
  },
  {
    slug: "why-browser-tools-keep-your-data-private-es",
    title: "Por qué las herramientas basadas en el navegador son la forma más segura de manejar tus datos",
    description: "Descubre cómo las herramientas basadas en el navegador como BrowseryTools procesan todo localmente en tu dispositivo — tus archivos, contraseñas y datos sensibles nunca salen de tu ordenador.",
    date: "2026-02-20",
    author: "BrowseryTools Team",
    category: "Privacidad y Seguridad",
    tags: ["privacidad", "seguridad", "navegador", "procesamiento local", "sin subidas"],
    readTime: 7,
    featured: true,
    coverEmoji: "🔒",
    coverGradient: "from-indigo-500 to-purple-600",
    locale: "es",
  },
  {
    slug: "best-free-developer-tools-browser-es",
    title: "La guía definitiva de herramientas gratuitas para desarrolladores en tu navegador",
    description: "Formateador de JSON, codificador Base64, decodificador de JWT, probador de regex, generador de UUID y más — todo gratis, todo en tu navegador. Sin instalaciones, sin anuncios, sin registro.",
    date: "2026-02-18",
    author: "BrowseryTools Team",
    category: "Herramientas para Desarrolladores",
    tags: ["desarrollador", "JSON", "Base64", "JWT", "regex", "UUID", "herramientas gratuitas"],
    readTime: 9,
    featured: true,
    coverEmoji: "⚡",
    coverGradient: "from-amber-500 to-orange-600",
    locale: "es",
  },
  {
    slug: "meme-generator-guide-es",
    title: "Cómo hacer un meme en línea gratis — Sin app, sin subidas, sin marca de agua",
    description: "Haz un meme en línea gratis en tu navegador. Sube una imagen, añade el clásico texto superior e inferior en fuente Impact, arrastra para colocarlo, da estilo a cada línea y descarga como PNG. Nada se sube, sin marca de agua.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Herramientas de Imagen",
    tags: ["generador de memes", "hacer un meme", "creador de memes", "fuente Impact", "gratis", "sin subidas"],
    readTime: 7,
    featured: true,
    coverEmoji: "😂",
    coverGradient: "from-yellow-400 to-orange-500",
    locale: "es",
  },
  {
    slug: "favicon-generator-guide-es",
    title: "Cómo crear un favicon a partir de una imagen (o una letra) — Generador gratuito en línea",
    description: "Usa un generador de favicons gratuito en línea para crear un favicon a partir de una imagen o una letra/emoji. Obtén todos los tamaños (16, 32, 180, 192, 512), un favicon.ico multitamaño, manifiesto y fragmento HTML — todo en tu navegador.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Herramientas para Desarrolladores",
    tags: ["favicon", "generador de favicons", "crear favicon a partir de imagen", "generador de favicons en línea", "desarrollo web", "iconos"],
    readTime: 7,
    featured: true,
    coverEmoji: "🌟",
    coverGradient: "from-violet-500 to-fuchsia-600",
    locale: "es",
  },
  {
    slug: "text-to-speech-guide-es",
    title: "Cómo leer texto en voz alta en línea gratis — Sin app, sin cuenta",
    description: "Convierte cualquier texto en voz directamente en tu navegador. Ajusta la voz, la velocidad, el tono y el volumen con la herramienta gratuita de la Web Speech API — privada, instantánea y funciona en Mac, Windows, Linux, iOS y Android.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Texto e Idioma",
    tags: ["texto a voz en línea gratis", "leer texto en voz alta", "TTS", "web speech api", "accesibilidad", "locución"],
    readTime: 7,
    featured: true,
    coverEmoji: "🔊",
    coverGradient: "from-sky-500 to-indigo-600",
    locale: "es",
  },
];
