import type { BlogPost } from "./blog-data";

export const ptBRPostsB2: BlogPost[] = [
  {
    slug: "password-security-guide-pt-BR",
    title: "Segurança de senhas: por que a maioria das senhas é fraca e como criar senhas fortes",
    description: "A maioria das pessoas usa senhas fracas sem perceber. Aprenda o que torna uma senha forte, como verificar a sua instantaneamente e gerar senhas impossíveis de quebrar — tudo de forma privada no seu navegador.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Segurança",
    tags: ["senha", "segurança", "hacking", "gerador de senhas", "força da senha"],
    readTime: 8,
    featured: false,
    coverEmoji: "🛡️",
    coverGradient: "from-green-500 to-emerald-600",
    locale: "pt-BR",
  },
  {
    slug: "remove-image-background-free-pt-BR",
    title: "Como remover o fundo de imagens de graça — sem Canva, sem Photoshop",
    description: "Remova fundos de fotos instantaneamente usando IA, direto no seu navegador. Sem uploads, sem assinaturas, sem marcas d'água. Suas imagens nunca saem do seu dispositivo.",
    date: "2026-02-12",
    author: "BrowseryTools Team",
    category: "Ferramentas de Imagem",
    tags: ["remoção de fundo", "edição de imagem", "IA", "grátis", "sem upload", "privacidade"],
    readTime: 6,
    featured: false,
    coverEmoji: "🖼️",
    coverGradient: "from-pink-500 to-rose-600",
    locale: "pt-BR",
  },
  {
    slug: "boost-productivity-pomodoro-todo-pt-BR",
    title: "10 maneiras de aumentar sua produtividade com ferramentas de navegador gratuitas",
    description: "Do timer Pomodoro às listas de tarefas, do relógio mundial ao controle de gastos — descubra as ferramentas de produtividade que funcionam inteiramente no seu navegador, sem coleta de dados.",
    date: "2026-02-10",
    author: "BrowseryTools Team",
    category: "Produtividade",
    tags: ["produtividade", "pomodoro", "lista de tarefas", "foco", "gestão de tempo"],
    readTime: 7,
    featured: false,
    coverEmoji: "🎯",
    coverGradient: "from-blue-500 to-cyan-600",
    locale: "pt-BR",
  },
  {
    slug: "free-image-tools-guide-pt-BR",
    title: "O guia completo de ferramentas de imagem gratuitas — comprima, converta e redimensione sem fazer upload",
    description: "Compressão de imagem, conversão de formato, redimensionamento, correção de cor e remoção de fundo — tudo processado localmente no seu navegador, sem uploads e sem custo.",
    date: "2026-02-08",
    author: "BrowseryTools Team",
    category: "Ferramentas de Imagem",
    tags: ["compressão de imagem", "conversor de imagem", "redimensionar", "grátis", "sem upload"],
    readTime: 8,
    featured: false,
    coverEmoji: "🎨",
    coverGradient: "from-violet-500 to-fuchsia-600",
    locale: "pt-BR",
  },
  {
    slug: "qr-code-generator-guide-pt-BR",
    title: "Como gerar QR codes de graça — para links, texto, Wi-Fi e cartões de visita",
    description: "Gere QR codes ilimitados para qualquer conteúdo — URLs, texto simples, credenciais de Wi-Fi, vCards — com total personalização. 100% grátis, sem cadastro, funciona offline.",
    date: "2026-02-05",
    author: "BrowseryTools Team",
    category: "Ferramentas Utilitárias",
    tags: ["QR code", "gerador de QR", "QR code grátis", "offline", "cartão de visita"],
    readTime: 5,
    featured: false,
    coverEmoji: "📱",
    coverGradient: "from-teal-500 to-green-600",
    locale: "pt-BR",
  },
  {
    slug: "text-tools-for-writers-developers-pt-BR",
    title: "As melhores ferramentas de texto gratuitas para escritores, desenvolvedores e criadores de conteúdo",
    description: "Conversor de caixa de texto, gerador de Lorem ipsum, contador de caracteres, ferramenta de diff de texto, editor Markdown e mais. Tudo o que um escritor ou desenvolvedor precisa — grátis e privado.",
    date: "2026-02-03",
    author: "BrowseryTools Team",
    category: "Ferramentas de Texto",
    tags: ["ferramentas de texto", "escrita", "markdown", "conversor de texto", "lorem ipsum"],
    readTime: 6,
    featured: false,
    coverEmoji: "✍️",
    coverGradient: "from-slate-500 to-gray-600",
    locale: "pt-BR",
  },
  {
    slug: "base64-encoding-guide-pt-BR",
    title: "O que é a codificação Base64? Um guia completo com exemplos",
    description: "Aprenda o que é a codificação Base64, por que ela existe, onde é usada e como codificar e decodificar strings Base64 instantaneamente no seu navegador — sem ferramentas para instalar.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Ferramentas para Desenvolvedores",
    tags: ["base64", "codificação", "desenvolvedor", "binário", "formatos de dados"],
    readTime: 7,
    featured: false,
    coverEmoji: "🔡",
    coverGradient: "from-cyan-500 to-blue-600",
    locale: "pt-BR",
  },
  {
    slug: "jwt-decoder-guide-pt-BR",
    title: "Como decodificar e verificar tokens JWT no seu navegador",
    description: "Os tokens JWT estão por toda parte na autenticação moderna. Aprenda o que eles contêm, como decodificá-los, identificar problemas de expiração e depurar problemas de autenticação — tudo de forma privada no seu navegador.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Ferramentas para Desenvolvedores",
    tags: ["JWT", "autenticação", "token", "OAuth", "segurança", "desenvolvedor"],
    readTime: 8,
    featured: false,
    coverEmoji: "🔑",
    coverGradient: "from-yellow-500 to-amber-600",
    locale: "pt-BR",
  },
  {
    slug: "css-gradient-generator-guide-pt-BR",
    title: "Gerador de gradiente CSS: crie gradientes lindos sem escrever código",
    description: "Crie visualmente gradientes CSS lineares, radiais e cônicos com pré-visualização ao vivo. Copie CSS pronto para produção com um clique — sem necessidade de software de design.",
    date: "2026-02-20",
    author: "BrowseryTools Team",
    category: "Ferramentas de Design",
    tags: ["CSS", "gradiente", "design", "frontend", "UI", "cores"],
    readTime: 5,
    featured: false,
    coverEmoji: "🌈",
    coverGradient: "from-purple-500 to-pink-600",
    locale: "pt-BR",
  },
  {
    slug: "hash-generator-guide-pt-BR",
    title: "MD5, SHA-256, SHA-512: gerador de hash gratuito e quando usar cada um",
    description: "Entenda a diferença entre MD5, SHA-1, SHA-256 e SHA-512. Gere hashes de arquivos e textos instantaneamente no seu navegador. Aprenda quando cada algoritmo é apropriado.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Segurança",
    tags: ["hash", "MD5", "SHA-256", "SHA-512", "checksum", "criptografia"],
    readTime: 7,
    featured: false,
    coverEmoji: "#️⃣",
    coverGradient: "from-gray-500 to-slate-700",
    locale: "pt-BR",
  },
  {
    slug: "screen-recorder-guide-pt-BR",
    title: "Grave sua tela sem instalar nenhum software",
    description: "Seu navegador pode gravar sua tela, janela ou aba usando a Screen Capture API. Aprenda a capturar vídeo para tutoriais, relatórios de bug e demonstrações — sem extensões.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Ferramentas Utilitárias",
    tags: ["gravador de tela", "captura de tela", "tutorial", "vídeo", "API do navegador"],
    readTime: 5,
    featured: false,
    coverEmoji: "🎬",
    coverGradient: "from-red-500 to-rose-600",
    locale: "pt-BR",
  },
  {
    slug: "fake-data-generator-guide-pt-BR",
    title: "Como gerar dados de teste falsos realistas (JSON e CSV) de graça",
    description: "Popule bancos de dados, prototipe interfaces e escreva testes com nomes, e-mails, endereços, números de telefone falsos e realistas e muito mais — exportados como JSON ou CSV, tudo no seu navegador.",
    date: "2026-02-16",
    author: "BrowseryTools Team",
    category: "Ferramentas para Desenvolvedores",
    tags: ["dados falsos", "dados de teste", "dados mock", "JSON", "CSV", "ferramentas para desenvolvedores"],
    readTime: 6,
    featured: false,
    coverEmoji: "🤖",
    coverGradient: "from-green-500 to-teal-600",
    locale: "pt-BR",
  },
  {
    slug: "cron-expression-guide-pt-BR",
    title: "Expressões cron explicadas: como ler e escrever agendamentos cron",
    description: "A sintaxe do cron é enigmática até você entender os cinco campos. Aprenda a ler e escrever expressões cron, a evitar erros comuns e a interpretar qualquer agendamento instantaneamente no seu navegador.",
    date: "2026-02-14",
    author: "BrowseryTools Team",
    category: "Ferramentas para Desenvolvedores",
    tags: ["cron", "expressão cron", "agendador", "DevOps", "automação", "Linux"],
    readTime: 7,
    featured: false,
    coverEmoji: "⏰",
    coverGradient: "from-orange-500 to-red-600",
    locale: "pt-BR",
  },
  {
    slug: "bmi-calculator-guide-pt-BR",
    title: "Calculadora de IMC: o que é, como calcular e o que ele realmente significa",
    description: "Calcule seu IMC instantaneamente em unidades métricas ou imperiais. Entenda o que o número significa, suas limitações e como é um peso saudável para a sua altura.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Saúde e Fitness",
    tags: ["IMC", "índice de massa corporal", "saúde", "peso", "calculadora"],
    readTime: 6,
    featured: false,
    coverEmoji: "⚖️",
    coverGradient: "from-teal-500 to-cyan-600",
    locale: "pt-BR",
  },
];
