import type { BlogPost } from "./blog-data";

export const esPostsB4: BlogPost[] = [
  {
    slug: "unix-timestamp-guide-es",
    title: "Timestamps Unix: Qué Son y Cómo Trabajar con Ellos",
    description:
      "Todo lo que los desarrolladores necesitan saber sobre el tiempo Unix: qué es la época, el problema Y2K38, cómo convertir timestamps en JavaScript, Python y SQL, la trampa de milisegundos vs. segundos, el manejo de zonas horarias y los timestamps en JWTs y bases de datos.",
    date: "2026-03-20",
    author: "BrowseryTools Team",
    category: "Herramientas para Desarrolladores",
    tags: ["unix timestamp", "época", "datetime", "javascript", "python", "zona horaria"],
    readTime: 9,
    coverEmoji: "⏱️",
    coverGradient: "from-violet-500 to-purple-700",
    locale: "es",
  },
  {
    slug: "url-encoder-guide-es",
    title: "Codificación de URL Explicada: La Codificación Porcentual en Solicitudes HTTP",
    description:
      "Aprende por qué los caracteres especiales rompen las URLs, cómo funciona la codificación porcentual a nivel de bytes, la diferencia crítica entre encodeURI y encodeURIComponent, y los errores de codificación más comunes en aplicaciones reales.",
    date: "2026-03-19",
    author: "BrowseryTools Team",
    category: "Herramientas para Desarrolladores",
    tags: ["codificación URL", "codificación porcentual", "HTTP", "desarrollo web", "JavaScript"],
    readTime: 7,
    coverEmoji: "🔗",
    coverGradient: "from-cyan-500 to-blue-600",
    locale: "es",
  },
  {
    slug: "uuid-generator-guide-es",
    title: "UUIDs, NanoIDs y CUIDs: Cómo Elegir el Formato de ID Correcto para tu Proyecto",
    description:
      "Un análisis en profundidad de UUID v1, v4 y v7, NanoID y CUID2 — qué es cada formato, cómo funciona la probabilidad de colisión y cuándo usar cada uno para claves primarias de bases de datos, URLs y sistemas distribuidos.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Herramientas para Desarrolladores",
    tags: ["UUID", "NanoID", "CUID", "base de datos", "sistemas distribuidos", "identificadores"],
    readTime: 8,
    coverEmoji: "🆔",
    coverGradient: "from-violet-500 to-purple-700",
    locale: "es",
  },
  {
    slug: "chmod-guide-es",
    title: "Permisos de Archivos en Linux Explicados: Guía Completa de chmod",
    description:
      "Una guía completa sobre los permisos de archivos Unix: el modelo propietario/grupo/otros, la notación octal (755, 644, 777), la notación simbólica, setuid/setgid/sticky bit y ejemplos del mundo real para servidores web y claves SSH.",
    date: "2026-03-21",
    author: "BrowseryTools Team",
    category: "Herramientas para Desarrolladores",
    tags: ["chmod", "Linux", "permisos de archivos", "Unix", "seguridad", "sysadmin"],
    readTime: 8,
    coverEmoji: "🔒",
    coverGradient: "from-green-500 to-teal-600",
    locale: "es",
  },
  {
    slug: "http-status-codes-guide-es",
    title: "Códigos de Estado HTTP que Todo Desarrollador Debería Conocer",
    description:
      "Una referencia práctica de códigos de estado HTTP: las cinco categorías, análisis en profundidad de 200, 201, 204, 301, 302, 304, 400, 401, 403, 404, 409, 422, 429, 500, 502, 503, más orientación sobre diseño de APIs REST y depuración en DevTools.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Herramientas para Desarrolladores",
    tags: ["HTTP", "códigos de estado", "API REST", "desarrollo web", "depuración"],
    readTime: 7,
    coverEmoji: "📡",
    coverGradient: "from-orange-500 to-red-600",
    locale: "es",
  },
  {
    slug: "video-compression-guide-es",
    title: "Cómo Comprimir Archivos de Video Sin Perder Calidad",
    description:
      "Una guía práctica sobre compresión de video: cómo funcionan los códecs como H.264, H.265, VP9 y AV1, qué controla realmente el tamaño del archivo, compresión con y sin pérdida, y las mejores configuraciones para correo electrónico, web, redes sociales y uso de archivo.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Herramientas Multimedia",
    tags: ["compresión de video", "H.264", "códec", "tamaño de archivo", "edición de video"],
    readTime: 7,
    coverEmoji: "🎬",
    coverGradient: "from-red-500 to-pink-600",
    locale: "es",
  },
  {
    slug: "image-formats-guide-es",
    title: "JPEG vs PNG vs WebP vs AVIF: Comparación Completa de Formatos de Imagen",
    description:
      "Entiende cómo JPEG, PNG, WebP y AVIF comprimen las imágenes bajo el capó, cuándo usar cada formato, cómo afectan a las Core Web Vitals y cómo servir el formato correcto al navegador adecuado.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Herramientas de Imagen",
    tags: ["formatos de imagen", "JPEG", "PNG", "WebP", "AVIF", "rendimiento web", "Core Web Vitals"],
    readTime: 8,
    coverEmoji: "🖼️",
    coverGradient: "from-blue-500 to-cyan-500",
    locale: "es",
  },
  {
    slug: "exif-data-guide-es",
    title: "Metadatos EXIF: Qué Revelan tus Fotos sobre Ti (y Cómo Eliminarlos)",
    description:
      "Los datos EXIF incrustan coordenadas GPS, números de serie del dispositivo y marcas de tiempo en cada foto que tomas. Aprende qué registran, los riesgos reales para la privacidad, casos famosos donde revelaron la ubicación de personas, y cómo verlos y eliminarlos.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Privacidad y Seguridad",
    tags: ["EXIF", "metadatos", "privacidad", "GPS", "seguridad de fotos", "datos de imagen"],
    readTime: 8,
    coverEmoji: "📷",
    coverGradient: "from-amber-500 to-orange-600",
    locale: "es",
  },
  {
    slug: "svg-guide-es",
    title: "Archivos SVG: Guía Completa para Desarrolladores y Diseñadores",
    description:
      "Todo lo que necesitas saber sobre SVG: el formato vectorial basado en XML que escala infinitamente, cómo funcionan los elementos principales como path y viewBox, estilizado y animación con CSS, optimización con SVGO, riesgos XSS de SVG subido por usuarios y cuándo convertir SVG a PNG.",
    date: "2026-03-21",
    author: "BrowseryTools Team",
    category: "Herramientas para Desarrolladores",
    tags: ["SVG", "gráficos vectoriales", "desarrollo web", "CSS", "SVGO", "iconos"],
    readTime: 9,
    coverEmoji: "✏️",
    coverGradient: "from-violet-500 to-purple-600",
    locale: "es",
  },
  {
    slug: "lorem-ipsum-guide-es",
    title: "Lorem Ipsum: Origen, Usos y Por Qué los Diseñadores No Pueden Vivir Sin Él",
    description:
      "La historia completa detrás de Lorem Ipsum: del texto filosófico de Cicerón del 45 a. C. a los flujos de trabajo de diseño modernos. Aprende cuándo usarlo, cuándo evitarlo y cómo generar exactamente la cantidad que necesitas.",
    date: "2026-03-17",
    author: "BrowseryTools Team",
    category: "Herramientas de Texto",
    tags: ["lorem ipsum", "texto de marcador de posición", "diseño", "tipografía"],
    readTime: 6,
    coverEmoji: "📝",
    coverGradient: "from-slate-500 to-gray-600",
    locale: "es",
  },
  {
    slug: "markdown-complete-guide-es",
    title: "Markdown: Referencia Completa de Sintaxis para Escritores y Desarrolladores",
    description:
      "Una guía completa de Markdown: quién lo creó y por qué, referencia completa de sintaxis desde lo básico hasta las características extendidas, variantes de Markdown (CommonMark, GFM, MDX) y errores comunes que evitar.",
    date: "2026-03-18",
    author: "BrowseryTools Team",
    category: "Herramientas de Texto",
    tags: ["markdown", "sintaxis", "escritura", "documentación", "desarrolladores"],
    readTime: 7,
    coverEmoji: "✍️",
    coverGradient: "from-indigo-500 to-blue-600",
    locale: "es",
  },
  {
    slug: "text-diff-guide-es",
    title: "Cómo Comparar Archivos de Texto y Encontrar Diferencias Sin Ningún Software",
    description:
      "Aprende cómo funcionan los algoritmos de diff de texto, cómo leer la salida de diff unificado, la diferencia entre diffs a nivel de línea y de palabra, y cómo funciona git diff bajo el capó.",
    date: "2026-03-19",
    author: "BrowseryTools Team",
    category: "Herramientas para Desarrolladores",
    tags: ["diff", "comparación de texto", "git", "revisión de código", "comparación de archivos"],
    readTime: 6,
    coverEmoji: "🔍",
    coverGradient: "from-emerald-500 to-teal-600",
    locale: "es",
  },
  {
    slug: "text-encryption-guide-es",
    title: "Cifrado de Texto en el Lado del Cliente: Cómo Proteger Datos Sensibles en el Navegador",
    description:
      "Una guía práctica sobre cifrado de texto en el navegador: qué significa realmente el cifrado en el lado del cliente, algoritmos simétricos vs. asimétricos, derivación de claves a partir de contraseñas y las limitaciones reales de la criptografía en el navegador.",
    date: "2026-03-20",
    author: "BrowseryTools Team",
    category: "Seguridad",
    tags: ["cifrado", "AES", "seguridad", "privacidad", "criptografía", "navegador"],
    readTime: 7,
    coverEmoji: "🔐",
    coverGradient: "from-rose-500 to-pink-600",
    locale: "es",
  },
  {
    slug: "word-frequency-guide-es",
    title: "Análisis de Frecuencia de Palabras: Una Herramienta para Escritores, SEO e Investigación",
    description:
      "Cómo el análisis de frecuencia de palabras revela patrones de escritura, densidad de palabras clave y temas de documentos. Cubre palabras vacías, TF-IDF explicado de forma sencilla, casos de uso para escritores y SEO, y aplicaciones académicas como la atribución de autoría.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Herramientas de Texto",
    tags: ["frecuencia de palabras", "análisis de texto", "SEO", "escritura", "NLP", "contenido"],
    readTime: 6,
    coverEmoji: "📊",
    coverGradient: "from-violet-500 to-purple-600",
    locale: "es",
  },
];
