export interface BlogPost {
  slug: string;
  title: string;
  description: string;
  date: string;
  author: string;
  category: string;
  tags: string[];
  readTime: number; // minutes
  featured?: boolean;
  coverEmoji: string;
  coverGradient: string;
}

export const blogPosts: BlogPost[] = [
  {
    slug: "keep-laptop-awake-browser",
    title: "How to Keep Your Laptop Awake Without Installing Anything (Mac, Windows, Linux)",
    description: "Stop your laptop or phone from sleeping with a single browser tab — no apps, no accounts, no ads. Uses the Screen Wake Lock API. Works on Mac, Windows, Linux, iOS, and Android.",
    date: "2026-04-14",
    author: "BrowseryTools Team",
    category: "Productivity",
    tags: ["keep awake", "wake lock", "laptop sleep", "productivity", "browser api", "cross-platform"],
    readTime: 8,
    featured: true,
    coverEmoji: "⚡",
    coverGradient: "from-emerald-500 to-teal-600",
  },
  {
    slug: "ibqa-aljihaz-mustayqizan-ar",
    title: "كيف تبقي جهازك مستيقظاً بدون تثبيت أي شيء (ماك وويندوز ولينكس)",
    description: "امنع لابتوبك أو جوالك من الدخول في وضع السكون بتبويب واحد في المتصفح — بدون تطبيقات، بدون حسابات، بدون إعلانات. تعتمد على واجهة Wake Lock API وتعمل على ماك وويندوز ولينكس وiOS وأندرويد.",
    date: "2026-04-14",
    author: "BrowseryTools Team",
    category: "الإنتاجية",
    tags: ["إبقاء مستيقظ", "wake lock", "نوم اللابتوب", "إنتاجية", "متصفح", "متعدد المنصات"],
    readTime: 8,
    featured: true,
    coverEmoji: "⚡",
    coverGradient: "from-emerald-500 to-teal-600",
  },
  {
    slug: "why-browser-tools-keep-your-data-private",
    title: "Why Browser-Based Tools Are the Safest Way to Handle Your Data",
    description: "Learn how browser-based tools like BrowseryTools process everything locally on your device — your files, passwords, and sensitive data never leave your computer.",
    date: "2026-02-20",
    author: "BrowseryTools Team",
    category: "Privacy & Security",
    tags: ["privacy", "security", "browser", "local processing", "no upload"],
    readTime: 7,
    featured: true,
    coverEmoji: "🔒",
    coverGradient: "from-indigo-500 to-purple-600",
  },
  {
    slug: "best-free-developer-tools-browser",
    title: "The Ultimate Guide to Free Developer Tools in Your Browser",
    description: "JSON formatter, Base64 encoder, JWT decoder, regex tester, UUID generator and more — all free, all in your browser. No installs, no ads, no sign-up.",
    date: "2026-02-18",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["developer", "JSON", "Base64", "JWT", "regex", "UUID", "free tools"],
    readTime: 9,
    featured: true,
    coverEmoji: "⚡",
    coverGradient: "from-amber-500 to-orange-600",
  },
  {
    slug: "password-security-guide",
    title: "Password Security: Why Most Passwords Are Weak and How to Create Strong Ones",
    description: "Most people use weak passwords without realizing it. Learn what makes a strong password, how to check yours instantly, and generate uncrackable ones — all privately in your browser.",
    date: "2026-02-15",
    author: "BrowseryTools Team",
    category: "Security",
    tags: ["password", "security", "hacking", "password generator", "password strength"],
    readTime: 8,
    featured: false,
    coverEmoji: "🛡️",
    coverGradient: "from-green-500 to-emerald-600",
  },
  {
    slug: "remove-image-background-free",
    title: "How to Remove Image Backgrounds for Free — No Canva, No Photoshop",
    description: "Remove backgrounds from photos instantly using AI, right in your browser. No uploads, no subscriptions, no watermarks. Your images never leave your device.",
    date: "2026-02-12",
    author: "BrowseryTools Team",
    category: "Image Tools",
    tags: ["background removal", "image editing", "AI", "free", "no upload", "privacy"],
    readTime: 6,
    featured: false,
    coverEmoji: "🖼️",
    coverGradient: "from-pink-500 to-rose-600",
  },
  {
    slug: "boost-productivity-pomodoro-todo",
    title: "10 Ways to Boost Your Productivity with Free Browser Tools",
    description: "From the Pomodoro timer to todo lists, world clock to expense tracker — discover the productivity tools that work entirely in your browser with zero data collection.",
    date: "2026-02-10",
    author: "BrowseryTools Team",
    category: "Productivity",
    tags: ["productivity", "pomodoro", "todo", "focus", "time management"],
    readTime: 7,
    featured: false,
    coverEmoji: "🎯",
    coverGradient: "from-blue-500 to-cyan-600",
  },
  {
    slug: "free-image-tools-guide",
    title: "The Complete Guide to Free Image Tools — Compress, Convert, Resize Without Uploading",
    description: "Image compression, format conversion, resizing, color correction, and background removal — all processed locally in your browser with zero uploads and zero cost.",
    date: "2026-02-08",
    author: "BrowseryTools Team",
    category: "Image Tools",
    tags: ["image compression", "image converter", "resize", "free", "no upload"],
    readTime: 8,
    featured: false,
    coverEmoji: "🎨",
    coverGradient: "from-violet-500 to-fuchsia-600",
  },
  {
    slug: "qr-code-generator-guide",
    title: "How to Generate QR Codes for Free — For Links, Text, WiFi & Business Cards",
    description: "Generate unlimited QR codes for any content — URLs, plain text, WiFi credentials, vCards — with full customization. 100% free, no sign-up, works offline.",
    date: "2026-02-05",
    author: "BrowseryTools Team",
    category: "Utility Tools",
    tags: ["QR code", "QR generator", "free QR code", "offline", "business card"],
    readTime: 5,
    featured: false,
    coverEmoji: "📱",
    coverGradient: "from-teal-500 to-green-600",
  },
  {
    slug: "text-tools-for-writers-developers",
    title: "The Best Free Text Tools for Writers, Developers and Content Creators",
    description: "Text case converter, Lorem ipsum generator, character counter, text diff tool, Markdown editor and more. Everything a writer or developer needs — free and private.",
    date: "2026-02-03",
    author: "BrowseryTools Team",
    category: "Text Tools",
    tags: ["text tools", "writing", "markdown", "text converter", "lorem ipsum"],
    readTime: 6,
    featured: false,
    coverEmoji: "✍️",
    coverGradient: "from-slate-500 to-gray-600",
  },
  {
    slug: "base64-encoding-guide",
    title: "What is Base64 Encoding? A Complete Guide with Examples",
    description: "Learn what Base64 encoding is, why it exists, where it's used, and how to encode and decode Base64 strings instantly in your browser — no tools to install.",
    date: "2026-02-22",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["base64", "encoding", "developer", "binary", "data formats"],
    readTime: 7,
    featured: false,
    coverEmoji: "🔡",
    coverGradient: "from-cyan-500 to-blue-600",
  },
  {
    slug: "jwt-decoder-guide",
    title: "How to Decode and Verify JWT Tokens in Your Browser",
    description: "JWT tokens are everywhere in modern authentication. Learn what they contain, how to decode them, spot expiry issues, and debug auth problems — all privately in your browser.",
    date: "2026-02-21",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["JWT", "authentication", "token", "OAuth", "security", "developer"],
    readTime: 8,
    featured: false,
    coverEmoji: "🔑",
    coverGradient: "from-yellow-500 to-amber-600",
  },
  {
    slug: "css-gradient-generator-guide",
    title: "CSS Gradient Generator: Create Beautiful Gradients Without Writing Code",
    description: "Visually build linear, radial, and conic CSS gradients with a live preview. Copy production-ready CSS with one click — no design software needed.",
    date: "2026-02-20",
    author: "BrowseryTools Team",
    category: "Design Tools",
    tags: ["CSS", "gradient", "design", "frontend", "UI", "colors"],
    readTime: 5,
    featured: false,
    coverEmoji: "🌈",
    coverGradient: "from-purple-500 to-pink-600",
  },
  {
    slug: "hash-generator-guide",
    title: "MD5, SHA-256, SHA-512: Free Hash Generator and When to Use Each",
    description: "Understand the difference between MD5, SHA-1, SHA-256, and SHA-512. Generate file and text hashes instantly in your browser. Learn when each algorithm is appropriate.",
    date: "2026-02-19",
    author: "BrowseryTools Team",
    category: "Security",
    tags: ["hash", "MD5", "SHA-256", "SHA-512", "checksum", "cryptography"],
    readTime: 7,
    featured: false,
    coverEmoji: "#️⃣",
    coverGradient: "from-gray-500 to-slate-700",
  },
  {
    slug: "screen-recorder-guide",
    title: "Record Your Screen Without Installing Any Software",
    description: "Your browser can record your screen, window, or tab using the Screen Capture API. Learn how to capture video for tutorials, bug reports, and demos — no extensions needed.",
    date: "2026-02-17",
    author: "BrowseryTools Team",
    category: "Utility Tools",
    tags: ["screen recorder", "screen capture", "tutorial", "video", "browser API"],
    readTime: 5,
    featured: false,
    coverEmoji: "🎬",
    coverGradient: "from-red-500 to-rose-600",
  },
  {
    slug: "fake-data-generator-guide",
    title: "How to Generate Realistic Fake Test Data (JSON & CSV) for Free",
    description: "Populate databases, prototype UIs, and write tests with realistic fake names, emails, addresses, phone numbers, and more — exported as JSON or CSV, all in your browser.",
    date: "2026-02-16",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["fake data", "test data", "mock data", "JSON", "CSV", "developer tools"],
    readTime: 6,
    featured: false,
    coverEmoji: "🤖",
    coverGradient: "from-green-500 to-teal-600",
  },
  {
    slug: "cron-expression-guide",
    title: "Cron Expressions Explained: How to Read and Write Cron Schedules",
    description: "Cron syntax is cryptic until you understand the five fields. Learn to read and write cron expressions, avoid common mistakes, and parse any schedule instantly in your browser.",
    date: "2026-02-14",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["cron", "cron expression", "scheduler", "DevOps", "automation", "Linux"],
    readTime: 7,
    featured: false,
    coverEmoji: "⏰",
    coverGradient: "from-orange-500 to-red-600",
  },
  {
    slug: "bmi-calculator-guide",
    title: "BMI Calculator: What It Is, How to Calculate It, and What It Really Means",
    description: "Calculate your BMI instantly in metric or imperial units. Understand what the number means, its limitations, and what healthy weight looks like for your height.",
    date: "2026-02-24",
    author: "BrowseryTools Team",
    category: "Health & Fitness",
    tags: ["BMI", "body mass index", "health", "weight", "calculator"],
    readTime: 6,
    featured: false,
    coverEmoji: "⚖️",
    coverGradient: "from-teal-500 to-cyan-600",
  },
  {
    slug: "color-contrast-accessibility-guide",
    title: "Color Contrast and Web Accessibility: A Complete WCAG Guide",
    description: "Learn why color contrast matters for accessibility, how to calculate contrast ratios, what WCAG AA and AAA mean, and how to check any color combination instantly.",
    date: "2026-02-23",
    author: "BrowseryTools Team",
    category: "Design Tools",
    tags: ["accessibility", "WCAG", "color contrast", "a11y", "design", "UX"],
    readTime: 8,
    featured: false,
    coverEmoji: "♿",
    coverGradient: "from-blue-500 to-indigo-600",
  },
  {
    slug: "sql-formatter-guide",
    title: "How to Format SQL Queries for Readability and Debugging",
    description: "Unformatted SQL is a debugging nightmare. Learn SQL formatting conventions, how to read complex queries with JOINs and subqueries, and format any query instantly in your browser.",
    date: "2026-02-22",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["SQL", "database", "formatting", "MySQL", "PostgreSQL", "developer"],
    readTime: 7,
    featured: false,
    coverEmoji: "🗄️",
    coverGradient: "from-violet-500 to-purple-600",
  },
  {
    slug: "habit-tracker-guide",
    title: "How to Build Good Habits: The Science of Streaks and Daily Tracking",
    description: "Learn the psychology behind habit formation, why streaks work, and how to use a simple browser-based habit tracker to build lasting routines without an app subscription.",
    date: "2026-02-21",
    author: "BrowseryTools Team",
    category: "Productivity",
    tags: ["habits", "habit tracker", "productivity", "streaks", "self-improvement"],
    readTime: 7,
    featured: false,
    coverEmoji: "✅",
    coverGradient: "from-emerald-500 to-green-600",
  },
  {
    slug: "kilmat-murur-guide-ar",
    title: "كيف تنشئ كلمة مرور قوية وكيف تحمي حساباتك من الاختراق",
    description: "تعلّم كيف تنشئ كلمات مرور قوية لا يمكن اختراقها، وكيف تحمي حساباتك باستخدام المصادقة الثنائية ومدير كلمات المرور.",
    date: "2026-03-14",
    author: "BrowseryTools Team",
    category: "الأمن والخصوصية",
    tags: ["كلمة مرور", "أمن", "اختراق", "password", "security", "2FA"],
    readTime: 7,
    featured: false,
    coverEmoji: "🛡️",
    coverGradient: "from-green-500 to-emerald-600",
  },
  {
    slug: "base64-guide-ar",
    title: "ما هو Base64؟ دليل شامل للمطورين العرب",
    description: "فهم Base64 من الداخل: كيف يعمل، أين يُستخدم في JWT والبريد الإلكتروني والصور، والفرق الجوهري بينه وبين التشفير الحقيقي.",
    date: "2026-03-15",
    author: "BrowseryTools Team",
    category: "أدوات المطورين",
    tags: ["base64", "ترميز", "مطورين", "JWT", "encoding", "developer"],
    readTime: 6,
    featured: false,
    coverEmoji: "🔡",
    coverGradient: "from-cyan-500 to-blue-600",
  },
  {
    slug: "qr-code-guide-ar",
    title: "كل ما تحتاج معرفته عن QR Code: الإنشاء والقراءة والاستخدامات",
    description: "دليل شامل عن QR Code: تاريخه، كيف يخزّن البيانات، الفرق بينه وبين الباركود، أنواع المحتوى، ومستويات تصحيح الأخطاء.",
    date: "2026-03-16",
    author: "BrowseryTools Team",
    category: "أدوات عامة",
    tags: ["QR code", "باركود", "qr generator", "qr scanner", "رمز الاستجابة السريعة"],
    readTime: 7,
    featured: false,
    coverEmoji: "📱",
    coverGradient: "from-teal-500 to-green-600",
  },
  {
    slug: "adawat-nass-arabi",
    title: "أدوات معالجة النصوص للكتّاب والمطورين العرب",
    description: "دليل عملي لأدوات معالجة النصوص العربية: عداد الكلمات، تحويل حالة النص، مقارنة النصوص، ومحرر Markdown — وكيف تستخدمها في عملك.",
    date: "2026-03-17",
    author: "BrowseryTools Team",
    category: "أدوات النصوص",
    tags: ["نصوص عربية", "markdown", "text tools", "مقارنة نصوص", "عداد كلمات", "RTL"],
    readTime: 6,
    featured: false,
    coverEmoji: "✍️",
    coverGradient: "from-slate-500 to-gray-600",
  },
  // Agent 1 — AI Tools
  {
    slug: "ai-cost-calculator-guide",
    title: "How to Calculate Your AI API Costs Before You Run Out of Budget",
    description: "Token-based pricing explained: input vs output costs, how GPT-4, Claude, and Gemini charge per 1K tokens, cost scaling with volume, and practical strategies to reduce your monthly AI API bill.",
    date: "2026-03-22",
    author: "BrowseryTools Team",
    category: "AI Tools",
    tags: ["AI", "API costs", "tokens", "GPT-4", "Claude", "budget"],
    readTime: 8,
    coverEmoji: "💰",
    coverGradient: "from-emerald-500 to-teal-600",
  },
  {
    slug: "token-counter-guide",
    title: "Token Counting in LLMs: Why Every Developer Needs to Understand It",
    description: "What tokens actually are, how byte-pair encoding works, why the 750-words-per-1000-tokens rule breaks for Arabic and Chinese, and how token counts affect context windows and API costs.",
    date: "2026-03-22",
    author: "BrowseryTools Team",
    category: "AI Tools",
    tags: ["tokens", "tokenizer", "LLM", "BPE", "context window", "API"],
    readTime: 7,
    coverEmoji: "🔢",
    coverGradient: "from-violet-500 to-purple-600",
  },
  {
    slug: "context-window-guide",
    title: "LLM Context Windows Explained: Limits, Strategies, and How to Work Within Them",
    description: "What a context window is, current limits for GPT-4, Claude, and Gemini, what happens when you exceed them, the lost-in-the-middle problem, and strategies like chunking, summarization, and RAG.",
    date: "2026-03-22",
    author: "BrowseryTools Team",
    category: "AI Tools",
    tags: ["context window", "LLM", "RAG", "GPT-4", "Claude", "Gemini"],
    readTime: 8,
    coverEmoji: "📐",
    coverGradient: "from-purple-500 to-indigo-600",
  },
  {
    slug: "model-comparison-guide",
    title: "GPT-4 vs Claude vs Gemini: How to Compare AI Models for Your Use Case",
    description: "Why benchmark numbers can mislead, key dimensions for comparing AI models (reasoning, coding, cost, context length), and a practical approach to choosing the right model for your specific application.",
    date: "2026-03-22",
    author: "BrowseryTools Team",
    category: "AI Tools",
    tags: ["GPT-4", "Claude", "Gemini", "model comparison", "AI", "benchmarks"],
    readTime: 9,
    coverEmoji: "⚖️",
    coverGradient: "from-amber-500 to-orange-600",
  },
  // Agent 2 — AI/Prompt Tools
  {
    slug: "prompt-formatter-guide",
    title: "How to Format Prompts for Better AI Responses",
    description: "Learn the techniques that separate mediocre AI outputs from precise, actionable ones: role assignment, clear instruction blocks, few-shot examples, chain-of-thought prompting, and structured XML/JSON formats.",
    date: "2026-03-21",
    author: "BrowseryTools Team",
    category: "AI Tools",
    tags: ["AI", "prompts", "ChatGPT", "Claude", "prompt engineering"],
    readTime: 7,
    coverEmoji: "✨",
    coverGradient: "from-violet-500 to-purple-600",
  },
  {
    slug: "system-prompt-builder-guide",
    title: "Writing System Prompts That Actually Work",
    description: "A practical guide to crafting system prompts that produce consistent AI behavior — covering role, context, constraints, output format, and how to test and iterate across customer support, coding, and writing use cases.",
    date: "2026-03-21",
    author: "BrowseryTools Team",
    category: "AI Tools",
    tags: ["AI", "system prompts", "Claude", "ChatGPT", "prompt engineering", "LLM"],
    readTime: 8,
    coverEmoji: "🧠",
    coverGradient: "from-blue-500 to-indigo-600",
  },
  {
    slug: "mcp-config-guide",
    title: "Model Context Protocol (MCP): What It Is and How to Configure It",
    description: "MCP is Anthropic's open standard for connecting AI models to tools, files, and databases. Learn how the client-server architecture works, which servers to use, and how to write a working MCP config for Claude Desktop and Claude Code.",
    date: "2026-03-21",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["MCP", "Claude", "AI tools", "Claude Code", "developer tools", "Anthropic"],
    readTime: 8,
    coverEmoji: "🔌",
    coverGradient: "from-emerald-500 to-teal-600",
  },
  {
    slug: "claude-md-guide",
    title: "CLAUDE.md Files: How to Give AI the Context It Needs About Your Codebase",
    description: "A CLAUDE.md file at your project root gives Claude Code standing context about your stack, conventions, and architecture — eliminating the repeated corrections that come with a context-blind AI assistant.",
    date: "2026-03-21",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["Claude Code", "CLAUDE.md", "AI", "developer tools", "codebase context", "Anthropic"],
    readTime: 7,
    coverEmoji: "📄",
    coverGradient: "from-orange-500 to-amber-500",
  },
  // Agent 3 — Developer Tools batch 1
  {
    slug: "regex-tester-guide",
    title: "Regular Expressions Explained: A Practical Guide for Developers",
    description: "Learn the 20% of regex syntax that covers 80% of real-world use cases — character classes, quantifiers, anchors, groups, and flags — with practical examples for email validation, phone numbers, URL extraction, and more.",
    date: "2026-03-20",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["regex", "regular expressions", "developer", "pattern matching", "validation"],
    readTime: 9,
    coverEmoji: "🔍",
    coverGradient: "from-orange-500 to-red-600",
  },
  {
    slug: "json-formatter-guide",
    title: "JSON Formatting, Validation, and Debugging: A Complete Developer Guide",
    description: "A practical guide to JSON syntax rules, common parse errors, pretty-printing vs minification, deeply nested data, JSON Schema validation, and how JSON differs between APIs and config files.",
    date: "2026-03-20",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["json", "formatting", "validation", "api", "debugging"],
    readTime: 8,
    coverEmoji: "📋",
    coverGradient: "from-yellow-400 to-orange-500",
  },
  {
    slug: "curl-converter-guide",
    title: "cURL to Code: Convert API Requests Between Languages Instantly",
    description: "Understand cURL's flag syntax, common REST API patterns, and how to accurately translate cURL commands into JavaScript fetch, Python requests, and Node.js axios — including the browser DevTools 'Copy as cURL' workflow.",
    date: "2026-03-20",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["curl", "api", "http", "javascript", "python", "rest"],
    readTime: 8,
    coverEmoji: "🔄",
    coverGradient: "from-blue-500 to-cyan-500",
  },
  {
    slug: "unix-timestamp-guide",
    title: "Unix Timestamps: What They Are and How to Work With Them",
    description: "Everything developers need to know about Unix time — what the epoch is, the Y2K38 problem, converting timestamps in JavaScript, Python, and SQL, the milliseconds vs seconds trap, timezone handling, and timestamps in JWTs and databases.",
    date: "2026-03-20",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["unix timestamp", "epoch", "datetime", "javascript", "python", "timezone"],
    readTime: 9,
    coverEmoji: "⏱️",
    coverGradient: "from-violet-500 to-purple-700",
  },
  // Agent 4 — Developer Tools batch 2
  {
    slug: "url-encoder-guide",
    title: "URL Encoding Explained: Percent-Encoding in HTTP Requests",
    description: "Learn why special characters break URLs, how percent-encoding works at the byte level, the critical difference between encodeURI and encodeURIComponent, and common encoding bugs in real applications.",
    date: "2026-03-19",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["URL encoding", "percent encoding", "HTTP", "web development", "JavaScript"],
    readTime: 7,
    coverEmoji: "🔗",
    coverGradient: "from-cyan-500 to-blue-600",
  },
  {
    slug: "uuid-generator-guide",
    title: "UUIDs, NanoIDs, and CUIDs: Choosing the Right ID Format for Your Project",
    description: "A deep dive into UUID v1, v4, and v7, NanoID, and CUID2 — what each format is, how collision probability works, and when to use which for database primary keys, URLs, and distributed systems.",
    date: "2026-03-20",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["UUID", "NanoID", "CUID", "database", "distributed systems", "identifiers"],
    readTime: 8,
    coverEmoji: "🆔",
    coverGradient: "from-violet-500 to-purple-700",
  },
  {
    slug: "chmod-guide",
    title: "Linux File Permissions Explained: A Complete chmod Guide",
    description: "A complete guide to Unix file permissions — the owner/group/other model, octal notation (755, 644, 777), symbolic notation, setuid/setgid/sticky bit, and real-world examples for web servers and SSH keys.",
    date: "2026-03-21",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["chmod", "Linux", "file permissions", "Unix", "security", "sysadmin"],
    readTime: 8,
    coverEmoji: "🔒",
    coverGradient: "from-green-500 to-teal-600",
  },
  {
    slug: "http-status-codes-guide",
    title: "HTTP Status Codes Every Developer Should Know",
    description: "A practical reference for HTTP status codes — the five categories, deep dives on 200, 201, 204, 301, 302, 304, 400, 401, 403, 404, 409, 422, 429, 500, 502, 503, plus guidance on REST API design and debugging in DevTools.",
    date: "2026-03-22",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["HTTP", "status codes", "REST API", "web development", "debugging"],
    readTime: 7,
    coverEmoji: "📡",
    coverGradient: "from-orange-500 to-red-600",
  },
  // Agent 5 — Image/Media Tools
  {
    slug: "video-compression-guide",
    title: "How to Compress Video Files Without Losing Quality",
    description: "A practical guide to video compression: how codecs like H.264, H.265, VP9, and AV1 work, what actually controls file size, lossless vs lossy compression, and the best settings for email, web, social media, and archival use cases.",
    date: "2026-03-18",
    author: "BrowseryTools Team",
    category: "Media Tools",
    tags: ["video compression", "H.264", "codec", "file size", "video editing"],
    readTime: 7,
    coverEmoji: "🎬",
    coverGradient: "from-red-500 to-pink-600",
  },
  {
    slug: "image-formats-guide",
    title: "JPEG vs PNG vs WebP vs AVIF: The Complete Image Format Comparison",
    description: "Understand how JPEG, PNG, WebP, and AVIF each compress images under the hood, when to use each format, how they affect Core Web Vitals, and how to serve the right format to the right browser.",
    date: "2026-03-19",
    author: "BrowseryTools Team",
    category: "Image Tools",
    tags: ["image formats", "JPEG", "PNG", "WebP", "AVIF", "web performance", "Core Web Vitals"],
    readTime: 8,
    coverEmoji: "🖼️",
    coverGradient: "from-blue-500 to-cyan-500",
  },
  {
    slug: "exif-data-guide",
    title: "EXIF Metadata: What Your Photos Reveal About You (And How to Remove It)",
    description: "EXIF data embeds GPS coordinates, device serial numbers, and timestamps into every photo you take. Learn what it records, the real privacy risks, famous cases where it exposed people's locations, and how to view and remove it.",
    date: "2026-03-20",
    author: "BrowseryTools Team",
    category: "Privacy & Security",
    tags: ["EXIF", "metadata", "privacy", "GPS", "photo security", "image data"],
    readTime: 8,
    coverEmoji: "📷",
    coverGradient: "from-amber-500 to-orange-600",
  },
  {
    slug: "svg-guide",
    title: "SVG Files: A Complete Guide for Developers and Designers",
    description: "Everything you need to know about SVG: the XML-based vector format that scales infinitely, how core elements like path and viewBox work, CSS styling and animation, SVGO optimization, XSS risks from user-uploaded SVGs, and when to convert SVG to PNG.",
    date: "2026-03-21",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["SVG", "vector graphics", "web development", "CSS", "SVGO", "icons"],
    readTime: 9,
    coverEmoji: "✏️",
    coverGradient: "from-violet-500 to-purple-600",
  },
  // Agent 6 — Text Tools
  {
    slug: "lorem-ipsum-guide",
    title: "Lorem Ipsum: Origin, Uses, and Why Designers Can't Live Without It",
    description: "The full story behind Lorem Ipsum — from Cicero's 45 BC philosophical text to modern design workflows. Learn when to use it, when to avoid it, and how to generate the exact amount you need.",
    date: "2026-03-17",
    author: "BrowseryTools Team",
    category: "Text Tools",
    tags: ["lorem ipsum", "placeholder text", "design", "typography"],
    readTime: 6,
    coverEmoji: "📝",
    coverGradient: "from-slate-500 to-gray-600",
  },
  {
    slug: "markdown-complete-guide",
    title: "Markdown: Complete Syntax Reference for Writers and Developers",
    description: "A comprehensive guide to Markdown — who created it and why, full syntax reference from basics to extended features, Markdown flavors (CommonMark, GFM, MDX), and common mistakes to avoid.",
    date: "2026-03-18",
    author: "BrowseryTools Team",
    category: "Text Tools",
    tags: ["markdown", "syntax", "writing", "documentation", "developers"],
    readTime: 7,
    coverEmoji: "✍️",
    coverGradient: "from-indigo-500 to-blue-600",
  },
  {
    slug: "text-diff-guide",
    title: "How to Compare Text Files and Find Differences Without Any Software",
    description: "Learn how text diff algorithms work, how to read unified diff output, the difference between line-level and word-level diffs, and how git diff works under the hood.",
    date: "2026-03-19",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["diff", "text comparison", "git", "code review", "file comparison"],
    readTime: 6,
    coverEmoji: "🔍",
    coverGradient: "from-emerald-500 to-teal-600",
  },
  {
    slug: "text-encryption-guide",
    title: "Client-Side Text Encryption: How to Protect Sensitive Data in the Browser",
    description: "A practical guide to browser-based text encryption — what client-side encryption really means, symmetric vs asymmetric algorithms, key derivation from passwords, and the real limitations of in-browser cryptography.",
    date: "2026-03-20",
    author: "BrowseryTools Team",
    category: "Security",
    tags: ["encryption", "AES", "security", "privacy", "cryptography", "browser"],
    readTime: 7,
    coverEmoji: "🔐",
    coverGradient: "from-rose-500 to-pink-600",
  },
  {
    slug: "word-frequency-guide",
    title: "Word Frequency Analysis: A Tool for Writers, SEO, and Research",
    description: "How word frequency analysis reveals writing patterns, keyword density, and document themes. Covers stop words, TF-IDF explained simply, use cases for writers and SEO, and academic applications like authorship attribution.",
    date: "2026-03-21",
    author: "BrowseryTools Team",
    category: "Text Tools",
    tags: ["word frequency", "text analysis", "SEO", "writing", "NLP", "content"],
    readTime: 6,
    coverEmoji: "📊",
    coverGradient: "from-violet-500 to-purple-600",
  },
  // Agent 7 — Productivity & Finance
  {
    slug: "expense-tracker-guide",
    title: "Track Your Monthly Expenses Without Apps, Subscriptions, or Cloud Storage",
    description: "Most people have no idea where their money goes. Learn the 50/30/20 budgeting rule, the difference between fixed and variable expenses, and how to run a monthly expense review — without signing up for anything.",
    date: "2026-03-16",
    author: "BrowseryTools Team",
    category: "Productivity",
    tags: ["expense tracker", "budgeting", "personal finance", "money management"],
    readTime: 7,
    coverEmoji: "💸",
    coverGradient: "from-emerald-500 to-green-600",
  },
  {
    slug: "invoice-generator-guide",
    title: "How to Create Professional Invoices for Free — No Subscriptions Required",
    description: "A complete guide to professional invoicing: required fields, numbering conventions, payment terms like Net 30, late fee language, VAT and GST requirements by country, and why a free PDF tool beats a $100/year subscription.",
    date: "2026-03-17",
    author: "BrowseryTools Team",
    category: "Business",
    tags: ["invoice", "freelancing", "billing", "payment terms", "PDF"],
    readTime: 7,
    coverEmoji: "🧾",
    coverGradient: "from-violet-500 to-purple-600",
  },
  {
    slug: "loan-calculator-guide",
    title: "Loan Payment Calculator: Understand Your Mortgage, Car Loan, or Personal Loan",
    description: "The loan payment formula explained, amortization demystified (why early payments are mostly interest), APR vs interest rate, how extra payments save thousands, and how to actually compare loan offers.",
    date: "2026-03-18",
    author: "BrowseryTools Team",
    category: "Finance",
    tags: ["loan calculator", "mortgage", "amortization", "APR", "personal finance"],
    readTime: 8,
    coverEmoji: "🏦",
    coverGradient: "from-blue-500 to-cyan-600",
  },
  {
    slug: "currency-converter-guide",
    title: "How Currency Exchange Rates Work: A Practical Guide",
    description: "What drives exchange rates, the bid/ask spread, why you never get the mid-market rate, how banks and credit cards hide fees in spreads, and the currency traps that catch travelers and international freelancers.",
    date: "2026-03-19",
    author: "BrowseryTools Team",
    category: "Finance",
    tags: ["currency converter", "exchange rates", "forex", "travel", "international payments"],
    readTime: 7,
    coverEmoji: "💱",
    coverGradient: "from-amber-500 to-orange-500",
  },
  {
    slug: "timezone-guide",
    title: "Working Across Time Zones: A Complete Guide for Remote Teams",
    description: "How UTC offsets work, why DST makes scheduling error-prone, best practices for remote team meeting scheduling, ISO 8601 datetime format, and the golden rule for developers: always store timestamps in UTC.",
    date: "2026-03-20",
    author: "BrowseryTools Team",
    category: "Productivity",
    tags: ["timezone", "remote work", "UTC", "scheduling", "ISO 8601", "developers"],
    readTime: 8,
    coverEmoji: "🌐",
    coverGradient: "from-purple-500 to-violet-600",
  },
  // Agent 8 — Arabic batch 1
  {
    slug: "adawat-almutasaffih-privacy",
    title: "لماذا أدوات المتصفح هي الأكثر أمانًا لبياناتك الشخصية",
    description: "تعرّف على كيفية معالجة أدوات BrowseryTools لبياناتك محليًا في متصفحك دون رفعها لأي سيرفر، وكيف تحمي خصوصيتك بشكل كامل.",
    date: "2026-03-15",
    author: "BrowseryTools Team",
    category: "الخصوصية والأمن",
    tags: ["خصوصية", "أمن", "متصفح", "بيانات", "privacy", "security"],
    readTime: 6,
    coverEmoji: "🔒",
    coverGradient: "from-indigo-500 to-purple-600",
  },
  {
    slug: "adawat-almutawwirin-arabi",
    title: "أفضل أدوات المطورين المجانية في المتصفح لعام 2025",
    description: "دليل شامل لأفضل 10 أدوات مطورين مجانية تعمل في المتصفح، مع مقارنة بين أدوات المتصفح والبدائل الأخرى ولماذا هي الخيار الأمثل.",
    date: "2026-03-16",
    author: "BrowseryTools Team",
    category: "أدوات المطورين",
    tags: ["مطورين", "أدوات", "مجاني", "متصفح", "developer-tools", "free"],
    readTime: 7,
    coverEmoji: "🛠️",
    coverGradient: "from-blue-500 to-cyan-600",
  },
  {
    slug: "json-dalil-arabi",
    title: "دليل JSON الشامل: ما هو وكيف يستخدمه المطورون",
    description: "دليل مفصل باللغة العربية يشرح JSON من الأساسيات: قواعد البناء، الأخطاء الشائعة، الفرق بين JSON وXML، واستخدامه في APIs.",
    date: "2026-03-17",
    author: "BrowseryTools Team",
    category: "أدوات المطورين",
    tags: ["json", "api", "بيانات", "مطورين", "تنسيق", "data-format"],
    readTime: 8,
    coverEmoji: "📋",
    coverGradient: "from-green-500 to-emerald-600",
  },
  {
    slug: "regex-dalil-arabi",
    title: "شرح Regular Expressions بالعربي: دليل المبتدئين",
    description: "دليل شامل للمبتدئين يشرح التعابير النمطية (Regular Expressions) من الصفر مع أمثلة عملية للتحقق من البريد الإلكتروني والهاتف وغيرها.",
    date: "2026-03-18",
    author: "BrowseryTools Team",
    category: "أدوات المطورين",
    tags: ["regex", "regular-expressions", "تعابير-نمطية", "مطورين", "javascript", "python"],
    readTime: 9,
    coverEmoji: "🔍",
    coverGradient: "from-orange-500 to-red-600",
  },
  // Agent 10 — Arabic batch 3
  {
    slug: "adawat-sour-arabi",
    title: "أدوات الصور المجانية: الضغط والتحويل وإزالة الخلفية بدون رفع الملفات",
    description: "اضغط صورك وحوّلها وأزل خلفياتها مجانًا مباشرةً في متصفحك. لا حاجة لرفع ملفاتك أو الاشتراك في أي خدمة.",
    date: "2026-03-13",
    author: "BrowseryTools Team",
    category: "أدوات الصور",
    tags: ["ضغط الصور", "تحويل الصور", "إزالة الخلفية", "image tools", "free"],
    readTime: 7,
    coverEmoji: "🖼️",
    coverGradient: "from-pink-500 to-rose-600",
  },
  {
    slug: "thikaa-isnadi-guide-ar",
    title: "أدوات الذكاء الاصطناعي للمطورين: حساب التكلفة ومقارنة النماذج وعدّ الرموز",
    description: "دليل شامل لفهم تسعير نماذج GPT-4 وClaude وGemini، وكيف تحسب تكاليف API قبل البناء وتُقلّلها في تطبيقاتك.",
    date: "2026-03-14",
    author: "BrowseryTools Team",
    category: "أدوات الذكاء الاصطناعي",
    tags: ["ذكاء اصطناعي", "GPT-4", "Claude", "Tokens", "AI cost", "developers"],
    readTime: 8,
    coverEmoji: "🤖",
    coverGradient: "from-violet-500 to-purple-700",
  },
  {
    slug: "markdown-guide-ar",
    title: "دليل Markdown الشامل للكتّاب والمطورين العرب",
    description: "كل ما تحتاج معرفته عن Markdown — من الصيغ الأساسية إلى استخدامه مع اللغة العربية وتحويله إلى HTML.",
    date: "2026-03-15",
    author: "BrowseryTools Team",
    category: "أدوات الكتابة",
    tags: ["Markdown", "كتابة", "توثيق", "HTML", "Obsidian", "Notion"],
    readTime: 7,
    coverEmoji: "✍️",
    coverGradient: "from-sky-500 to-blue-700",
  },
  {
    slug: "himayat-khusousiyya-arabi",
    title: "دليل حماية الخصوصية على الإنترنت في 2025",
    description: "المخاطر الحقيقية على خصوصيتك الرقمية وخطوات عملية فورية للحد من تتبعك وحماية بياناتك الحساسة.",
    date: "2026-03-16",
    author: "BrowseryTools Team",
    category: "الأمن والخصوصية",
    tags: ["خصوصية", "أمن رقمي", "VPN", "تشفير", "كلمات مرور", "privacy"],
    readTime: 9,
    coverEmoji: "🔒",
    coverGradient: "from-emerald-500 to-teal-700",
  },
];

export function getBlogPost(slug: string): BlogPost | undefined {
  return blogPosts.find((p) => p.slug === slug);
}

export function getFeaturedPosts(): BlogPost[] {
  return blogPosts.filter((p) => p.featured);
}

export function getPostsByCategory(category: string): BlogPost[] {
  return blogPosts.filter((p) => p.category === category);
}

export function getAllCategories(): string[] {
  return [...new Set(blogPosts.map((p) => p.category))];
}
