import type { BlogPost } from "./blog-data";

export const frPostsB3: BlogPost[] = [
  {
    slug: "color-contrast-accessibility-guide-fr",
    title: "Contraste des couleurs et accessibilité web : guide complet WCAG",
    description: "Découvrez pourquoi le contraste des couleurs est essentiel pour l'accessibilité, comment calculer les rapports de contraste, ce que signifient les niveaux WCAG AA et AAA, et comment vérifier instantanément n'importe quelle combinaison de couleurs.",
    date: "2026-02-23",
    author: "BrowseryTools Team",
    category: "Outils de design",
    tags: ["accessibilité", "WCAG", "contraste des couleurs", "a11y", "design", "UX"],
    readTime: 8,
    featured: false,
    coverEmoji: "♿",
    coverGradient: "from-blue-500 to-indigo-600",
    locale: "fr",
  },
  {
    slug: "sql-formatter-guide-fr",
    title: "Comment formater les requêtes SQL pour la lisibilité et le débogage",
    description: "Le SQL non formaté est un cauchemar pour le débogage. Apprenez les conventions de formatage SQL, comment lire des requêtes complexes avec des JOIN et sous-requêtes, et formatez instantanément n'importe quelle requête dans votre navigateur.",
    date: "2026-02-22",
    author: "BrowseryTools Team",
    category: "Outils pour développeurs",
    tags: ["SQL", "base de données", "formatage", "MySQL", "PostgreSQL", "développeur"],
    readTime: 7,
    featured: false,
    coverEmoji: "🗄️",
    coverGradient: "from-violet-500 to-purple-600",
    locale: "fr",
  },
  {
    slug: "habit-tracker-guide-fr",
    title: "Comment construire de bonnes habitudes : la science des séries et du suivi quotidien",
    description: "Apprenez la psychologie derrière la formation des habitudes, pourquoi les séries fonctionnent, et comment utiliser un simple suivi d'habitudes dans le navigateur pour construire des routines durables sans abonnement à une application.",
    date: "2026-02-21",
    author: "BrowseryTools Team",
    category: "Productivité",
    tags: ["habitudes", "suivi d'habitudes", "productivité", "séries", "développement personnel"],
    readTime: 7,
    featured: false,
    coverEmoji: "✅",
    coverGradient: "from-emerald-500 to-green-600",
    locale: "fr",
  },
  {
    slug: "ai-cost-calculator-guide-fr",
    title: "Comment calculer vos coûts d'API IA avant de dépasser votre budget",
    description: "Tarification à base de tokens expliquée : coûts en entrée vs en sortie, comment GPT-4, Claude et Gemini facturent par 1K tokens, la mise à l'échelle des coûts avec le volume, et des stratégies pratiques pour réduire votre facture mensuelle d'API IA.",
    date: "2026-03-22",
    author: "BrowseryTools Team",
    category: "Outils IA",
    tags: ["IA", "coûts API", "tokens", "GPT-4", "Claude", "budget"],
    readTime: 8,
    coverEmoji: "💰",
    coverGradient: "from-emerald-500 to-teal-600",
    locale: "fr",
  },
  {
    slug: "token-counter-guide-fr",
    title: "Comptage de tokens dans les LLM : pourquoi tout développeur doit le comprendre",
    description: "Ce que sont réellement les tokens, comment fonctionne le byte-pair encoding, pourquoi la règle des 750 mots pour 1000 tokens ne s'applique pas à l'arabe et au chinois, et comment les nombres de tokens affectent les fenêtres de contexte et les coûts d'API.",
    date: "2026-03-22",
    author: "BrowseryTools Team",
    category: "Outils IA",
    tags: ["tokens", "tokeniseur", "LLM", "BPE", "fenêtre de contexte", "API"],
    readTime: 7,
    coverEmoji: "🔢",
    coverGradient: "from-violet-500 to-purple-600",
    locale: "fr",
  },
  {
    slug: "context-window-guide-fr",
    title: "Fenêtres de contexte des LLM expliquées : limites, stratégies et comment travailler dans ces contraintes",
    description: "Ce qu'est une fenêtre de contexte, les limites actuelles pour GPT-4, Claude et Gemini, ce qui se passe quand vous les dépassez, le problème du « perdu au milieu », et des stratégies comme le découpage, la résumé et le RAG.",
    date: "2026-03-22",
    author: "BrowseryTools Team",
    category: "Outils IA",
    tags: ["fenêtre de contexte", "LLM", "RAG", "GPT-4", "Claude", "Gemini"],
    readTime: 8,
    coverEmoji: "📐",
    coverGradient: "from-purple-500 to-indigo-600",
    locale: "fr",
  },
  {
    slug: "model-comparison-guide-fr",
    title: "GPT-4 vs Claude vs Gemini : comment comparer les modèles IA pour votre cas d'usage",
    description: "Pourquoi les benchmarks peuvent induire en erreur, les dimensions clés pour comparer les modèles IA (raisonnement, codage, coût, longueur de contexte), et une approche pratique pour choisir le bon modèle pour votre application.",
    date: "2026-03-22",
    author: "BrowseryTools Team",
    category: "Outils IA",
    tags: ["GPT-4", "Claude", "Gemini", "comparaison de modèles", "IA", "benchmarks"],
    readTime: 9,
    coverEmoji: "⚖️",
    coverGradient: "from-amber-500 to-orange-600",
    locale: "fr",
  },
  {
    slug: "prompt-formatter-guide-fr",
    title: "Comment formater les prompts pour de meilleures réponses IA",
    description: "Apprenez les techniques qui séparent les sorties IA médiocres des réponses précises et exploitables : attribution de rôle, blocs d'instructions clairs, exemples few-shot, prompting par chaîne de pensée et formats structurés XML/JSON.",
    date: "2026-03-21",
    author: "BrowseryTools Team",
    category: "Outils IA",
    tags: ["IA", "prompts", "ChatGPT", "Claude", "ingénierie de prompts"],
    readTime: 7,
    coverEmoji: "✨",
    coverGradient: "from-violet-500 to-purple-600",
    locale: "fr",
  },
  {
    slug: "system-prompt-builder-guide-fr",
    title: "Rédiger des prompts système qui fonctionnent vraiment",
    description: "Un guide pratique pour créer des prompts système qui produisent un comportement IA cohérent — couvrant le rôle, le contexte, les contraintes, le format de sortie, et comment tester et itérer pour le support client, le codage et la rédaction.",
    date: "2026-03-21",
    author: "BrowseryTools Team",
    category: "Outils IA",
    tags: ["IA", "prompts système", "Claude", "ChatGPT", "ingénierie de prompts", "LLM"],
    readTime: 8,
    coverEmoji: "🧠",
    coverGradient: "from-blue-500 to-indigo-600",
    locale: "fr",
  },
  {
    slug: "mcp-config-guide-fr",
    title: "Model Context Protocol (MCP) : ce que c'est et comment le configurer",
    description: "MCP est le standard ouvert d'Anthropic pour connecter les modèles IA aux outils, fichiers et bases de données. Apprenez comment fonctionne l'architecture client-serveur, quels serveurs utiliser, et comment rédiger une configuration MCP pour Claude Desktop et Claude Code.",
    date: "2026-03-21",
    author: "BrowseryTools Team",
    category: "Outils pour développeurs",
    tags: ["MCP", "Claude", "outils IA", "Claude Code", "outils développeur", "Anthropic"],
    readTime: 8,
    coverEmoji: "🔌",
    coverGradient: "from-emerald-500 to-teal-600",
    locale: "fr",
  },
  {
    slug: "claude-md-guide-fr",
    title: "Fichiers CLAUDE.md : comment donner à l'IA le contexte dont elle a besoin sur votre base de code",
    description: "Un fichier CLAUDE.md à la racine de votre projet donne à Claude Code un contexte permanent sur votre stack, vos conventions et votre architecture — éliminant les corrections répétées inhérentes à un assistant IA sans contexte.",
    date: "2026-03-21",
    author: "BrowseryTools Team",
    category: "Outils pour développeurs",
    tags: ["Claude Code", "CLAUDE.md", "IA", "outils développeur", "contexte de base de code", "Anthropic"],
    readTime: 7,
    coverEmoji: "📄",
    coverGradient: "from-orange-500 to-amber-500",
    locale: "fr",
  },
  {
    slug: "regex-tester-guide-fr",
    title: "Les expressions régulières expliquées : guide pratique pour les développeurs",
    description: "Apprenez les 20 % de syntaxe regex qui couvrent 80 % des cas d'usage réels — classes de caractères, quantificateurs, ancres, groupes et drapeaux — avec des exemples pratiques pour la validation d'e-mails, numéros de téléphone, extraction d'URL et plus encore.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Outils pour développeurs",
    tags: ["regex", "expressions régulières", "développeur", "correspondance de motifs", "validation"],
    readTime: 9,
    coverEmoji: "🔍",
    coverGradient: "from-orange-500 to-red-600",
    locale: "fr",
  },
  {
    slug: "json-formatter-guide-fr",
    title: "Formatage, validation et débogage JSON : guide complet du développeur",
    description: "Un guide pratique sur les règles de syntaxe JSON, les erreurs d'analyse courantes, la mise en forme vs la minification, les données profondément imbriquées, la validation par schéma JSON, et les différences entre JSON dans les API et les fichiers de configuration.",
    date: "2026-03-20",
    author: "BrowseryTools Team",
    category: "Outils pour développeurs",
    tags: ["json", "formatage", "validation", "api", "débogage"],
    readTime: 8,
    coverEmoji: "📋",
    coverGradient: "from-yellow-400 to-orange-500",
    locale: "fr",
  },
  {
    slug: "curl-converter-guide-fr",
    title: "cURL vers code : convertir les requêtes API entre langages instantanément",
    description: "Comprendre la syntaxe des drapeaux cURL, les modèles d'API REST courants, et comment traduire précisément les commandes cURL en JavaScript fetch, Python requests et Node.js axios — incluant le workflow « Copier en tant que cURL » des DevTools.",
    date: "2026-03-20",
    author: "BrowseryTools Team",
    category: "Outils pour développeurs",
    tags: ["curl", "api", "http", "javascript", "python", "rest"],
    readTime: 8,
    coverEmoji: "🔄",
    coverGradient: "from-blue-500 to-cyan-500",
    locale: "fr",
  },
];
