export interface BlogPost {
  slug: string;
  title: string;
  description: string;
  date: string;
  author: string;
  category: string;
  tags: string[];
  readTime: number; // minutes
  featured?: boolean;
  coverEmoji: string;
  coverGradient: string;
}

export const blogPosts: BlogPost[] = [
  {
    slug: "keep-laptop-awake-browser",
    title: "How to Keep Your Laptop Awake Without Installing Anything (Mac, Windows, Linux)",
    description: "Stop your laptop or phone from sleeping with a single browser tab — no apps, no accounts, no ads. Uses the Screen Wake Lock API. Works on Mac, Windows, Linux, iOS, and Android.",
    date: "2026-04-14",
    author: "BrowseryTools Team",
    category: "Productivity",
    tags: ["keep awake", "wake lock", "laptop sleep", "productivity", "browser api", "cross-platform"],
    readTime: 8,
    featured: true,
    coverEmoji: "⚡",
    coverGradient: "from-emerald-500 to-teal-600",
  },
  {
    slug: "ibqa-aljihaz-mustayqizan-ar",
    title: "كيف تبقي جهازك مستيقظاً بدون تثبيت أي شيء (ماك وويندوز ولينكس)",
    description: "امنع لابتوبك أو جوالك من الدخول في وضع السكون بتبويب واحد في المتصفح — بدون تطبيقات، بدون حسابات، بدون إعلانات. تعتمد على واجهة Wake Lock API وتعمل على ماك وويندوز ولينكس وiOS وأندرويد.",
    date: "2026-04-14",
    author: "BrowseryTools Team",
    category: "الإنتاجية",
    tags: ["إبقاء مستيقظ", "wake lock", "نوم اللابتوب", "إنتاجية", "متصفح", "متعدد المنصات"],
    readTime: 8,
    featured: true,
    coverEmoji: "⚡",
    coverGradient: "from-emerald-500 to-teal-600",
  },
  {
    slug: "why-browser-tools-keep-your-data-private",
    title: "Why Browser-Based Tools Are the Safest Way to Handle Your Data",
    description: "Learn how browser-based tools like BrowseryTools process everything locally on your device — your files, passwords, and sensitive data never leave your computer.",
    date: "2026-02-20",
    author: "BrowseryTools Team",
    category: "Privacy & Security",
    tags: ["privacy", "security", "browser", "local processing", "no upload"],
    readTime: 7,
    featured: true,
    coverEmoji: "🔒",
    coverGradient: "from-indigo-500 to-purple-600",
  },
  {
    slug: "best-free-developer-tools-browser",
    title: "The Ultimate Guide to Free Developer Tools in Your Browser",
    description: "JSON formatter, Base64 encoder, JWT decoder, regex tester, UUID generator and more — all free, all in your browser. No installs, no ads, no sign-up.",
    date: "2026-02-18",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["developer", "JSON", "Base64", "JWT", "regex", "UUID", "free tools"],
    readTime: 9,
    featured: true,
    coverEmoji: "⚡",
    coverGradient: "from-amber-500 to-orange-600",
  },
  {
    slug: "password-security-guide",
    title: "Password Security: Why Most Passwords Are Weak and How to Create Strong Ones",
    description: "Most people use weak passwords without realizing it. Learn what makes a strong password, how to check yours instantly, and generate uncrackable ones — all privately in your browser.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Security",
    tags: ["password", "security", "hacking", "password generator", "password strength"],
    readTime: 8,
    featured: false,
    coverEmoji: "🛡️",
    coverGradient: "from-green-500 to-emerald-600",
  },
  {
    slug: "remove-image-background-free",
    title: "How to Remove Image Backgrounds for Free — No Canva, No Photoshop",
    description: "Remove backgrounds from photos instantly using AI, right in your browser. No uploads, no subscriptions, no watermarks. Your images never leave your device.",
    date: "2026-02-12",
    author: "BrowseryTools Team",
    category: "Image Tools",
    tags: ["background removal", "image editing", "AI", "free", "no upload", "privacy"],
    readTime: 6,
    featured: false,
    coverEmoji: "🖼️",
    coverGradient: "from-pink-500 to-rose-600",
  },
  {
    slug: "boost-productivity-pomodoro-todo",
    title: "10 Ways to Boost Your Productivity with Free Browser Tools",
    description: "From the Pomodoro timer to todo lists, world clock to expense tracker — discover the productivity tools that work entirely in your browser with zero data collection.",
    date: "2026-02-10",
    author: "BrowseryTools Team",
    category: "Productivity",
    tags: ["productivity", "pomodoro", "todo", "focus", "time management"],
    readTime: 7,
    featured: false,
    coverEmoji: "🎯",
    coverGradient: "from-blue-500 to-cyan-600",
  },
  {
    slug: "free-image-tools-guide",
    title: "The Complete Guide to Free Image Tools — Compress, Convert, Resize Without Uploading",
    description: "Image compression, format conversion, resizing, color correction, and background removal — all processed locally in your browser with zero uploads and zero cost.",
    date: "2026-02-08",
    author: "BrowseryTools Team",
    category: "Image Tools",
    tags: ["image compression", "image converter", "resize", "free", "no upload"],
    readTime: 8,
    featured: false,
    coverEmoji: "🎨",
    coverGradient: "from-violet-500 to-fuchsia-600",
  },
  {
    slug: "qr-code-generator-guide",
    title: "How to Generate QR Codes for Free — For Links, Text, WiFi & Business Cards",
    description: "Generate unlimited QR codes for any content — URLs, plain text, WiFi credentials, vCards — with full customization. 100% free, no sign-up, works offline.",
    date: "2026-02-05",
    author: "BrowseryTools Team",
    category: "Utility Tools",
    tags: ["QR code", "QR generator", "free QR code", "offline", "business card"],
    readTime: 5,
    featured: false,
    coverEmoji: "📱",
    coverGradient: "from-teal-500 to-green-600",
  },
  {
    slug: "text-tools-for-writers-developers",
    title: "The Best Free Text Tools for Writers, Developers and Content Creators",
    description: "Text case converter, Lorem ipsum generator, character counter, text diff tool, Markdown editor and more. Everything a writer or developer needs — free and private.",
    date: "2026-02-03",
    author: "BrowseryTools Team",
    category: "Text Tools",
    tags: ["text tools", "writing", "markdown", "text converter", "lorem ipsum"],
    readTime: 6,
    featured: false,
    coverEmoji: "✍️",
    coverGradient: "from-slate-500 to-gray-600",
  },
  {
    slug: "base64-encoding-guide",
    title: "What is Base64 Encoding? A Complete Guide with Examples",
    description: "Learn what Base64 encoding is, why it exists, where it's used, and how to encode and decode Base64 strings instantly in your browser — no tools to install.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["base64", "encoding", "developer", "binary", "data formats"],
    readTime: 7,
    featured: false,
    coverEmoji: "🔡",
    coverGradient: "from-cyan-500 to-blue-600",
  },
  {
    slug: "jwt-decoder-guide",
    title: "How to Decode and Verify JWT Tokens in Your Browser",
    description: "JWT tokens are everywhere in modern authentication. Learn what they contain, how to decode them, spot expiry issues, and debug auth problems — all privately in your browser.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["JWT", "authentication", "token", "OAuth", "security", "developer"],
    readTime: 8,
    featured: false,
    coverEmoji: "🔑",
    coverGradient: "from-yellow-500 to-amber-600",
  },
  {
    slug: "css-gradient-generator-guide",
    title: "CSS Gradient Generator: Create Beautiful Gradients Without Writing Code",
    description: "Visually build linear, radial, and conic CSS gradients with a live preview. Copy production-ready CSS with one click — no design software needed.",
    date: "2026-02-20",
    author: "BrowseryTools Team",
    category: "Design Tools",
    tags: ["CSS", "gradient", "design", "frontend", "UI", "colors"],
    readTime: 5,
    featured: false,
    coverEmoji: "🌈",
    coverGradient: "from-purple-500 to-pink-600",
  },
  {
    slug: "hash-generator-guide",
    title: "MD5, SHA-256, SHA-512: Free Hash Generator and When to Use Each",
    description: "Understand the difference between MD5, SHA-1, SHA-256, and SHA-512. Generate file and text hashes instantly in your browser. Learn when each algorithm is appropriate.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Security",
    tags: ["hash", "MD5", "SHA-256", "SHA-512", "checksum", "cryptography"],
    readTime: 7,
    featured: false,
    coverEmoji: "#️⃣",
    coverGradient: "from-gray-500 to-slate-700",
  },
  {
    slug: "screen-recorder-guide",
    title: "Record Your Screen Without Installing Any Software",
    description: "Your browser can record your screen, window, or tab using the Screen Capture API. Learn how to capture video for tutorials, bug reports, and demos — no extensions needed.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Utility Tools",
    tags: ["screen recorder", "screen capture", "tutorial", "video", "browser API"],
    readTime: 5,
    featured: false,
    coverEmoji: "🎬",
    coverGradient: "from-red-500 to-rose-600",
  },
  {
    slug: "fake-data-generator-guide",
    title: "How to Generate Realistic Fake Test Data (JSON & CSV) for Free",
    description: "Populate databases, prototype UIs, and write tests with realistic fake names, emails, addresses, phone numbers, and more — exported as JSON or CSV, all in your browser.",
    date: "2026-02-16",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["fake data", "test data", "mock data", "JSON", "CSV", "developer tools"],
    readTime: 6,
    featured: false,
    coverEmoji: "🤖",
    coverGradient: "from-green-500 to-teal-600",
  },
  {
    slug: "cron-expression-guide",
    title: "Cron Expressions Explained: How to Read and Write Cron Schedules",
    description: "Cron syntax is cryptic until you understand the five fields. Learn to read and write cron expressions, avoid common mistakes, and parse any schedule instantly in your browser.",
    date: "2026-02-14",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["cron", "cron expression", "scheduler", "DevOps", "automation", "Linux"],
    readTime: 7,
    featured: false,
    coverEmoji: "⏰",
    coverGradient: "from-orange-500 to-red-600",
  },
  {
    slug: "bmi-calculator-guide",
    title: "BMI Calculator: What It Is, How to Calculate It, and What It Really Means",
    description: "Calculate your BMI instantly in metric or imperial units. Understand what the number means, its limitations, and what healthy weight looks like for your height.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Health & Fitness",
    tags: ["BMI", "body mass index", "health", "weight", "calculator"],
    readTime: 6,
    featured: false,
    coverEmoji: "⚖️",
    coverGradient: "from-teal-500 to-cyan-600",
  },
  {
    slug: "color-contrast-accessibility-guide",
    title: "Color Contrast and Web Accessibility: A Complete WCAG Guide",
    description: "Learn why color contrast matters for accessibility, how to calculate contrast ratios, what WCAG AA and AAA mean, and how to check any color combination instantly.",
    date: "2026-02-23",
    author: "BrowseryTools Team",
    category: "Design Tools",
    tags: ["accessibility", "WCAG", "color contrast", "a11y", "design", "UX"],
    readTime: 8,
    featured: false,
    coverEmoji: "♿",
    coverGradient: "from-blue-500 to-indigo-600",
  },
  {
    slug: "sql-formatter-guide",
    title: "How to Format SQL Queries for Readability and Debugging",
    description: "Unformatted SQL is a debugging nightmare. Learn SQL formatting conventions, how to read complex queries with JOINs and subqueries, and format any query instantly in your browser.",
    date: "2026-02-22",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["SQL", "database", "formatting", "MySQL", "PostgreSQL", "developer"],
    readTime: 7,
    featured: false,
    coverEmoji: "🗄️",
    coverGradient: "from-violet-500 to-purple-600",
  },
  {
    slug: "habit-tracker-guide",
    title: "How to Build Good Habits: The Science of Streaks and Daily Tracking",
    description: "Learn the psychology behind habit formation, why streaks work, and how to use a simple browser-based habit tracker to build lasting routines without an app subscription.",
    date: "2026-02-21",
    author: "BrowseryTools Team",
    category: "Productivity",
    tags: ["habits", "habit tracker", "productivity", "streaks", "self-improvement"],
    readTime: 7,
    featured: false,
    coverEmoji: "✅",
    coverGradient: "from-emerald-500 to-green-600",
  },
  {
    slug: "kilmat-murur-guide-ar",
    title: "كيف تنشئ كلمة مرور قوية وكيف تحمي حساباتك من الاختراق",
    description: "تعلّم كيف تنشئ كلمات مرور قوية لا يمكن اختراقها، وكيف تحمي حساباتك باستخدام المصادقة الثنائية ومدير كلمات المرور.",
    date: "2026-03-14",
    author: "BrowseryTools Team",
    category: "الأمن والخصوصية",
    tags: ["كلمة مرور", "أمن", "اختراق", "password", "security", "2FA"],
    readTime: 7,
    featured: false,
    coverEmoji: "🛡️",
    coverGradient: "from-green-500 to-emerald-600",
  },
  {
    slug: "base64-guide-ar",
    title: "ما هو Base64؟ دليل شامل للمطورين العرب",
    description: "فهم Base64 من الداخل: كيف يعمل، أين يُستخدم في JWT والبريد الإلكتروني والصور، والفرق الجوهري بينه وبين التشفير الحقيقي.",
    date: "2026-03-15",
    author: "BrowseryTools Team",
    category: "أدوات المطورين",
    tags: ["base64", "ترميز", "مطورين", "JWT", "encoding", "developer"],
    readTime: 6,
    featured: false,
    coverEmoji: "🔡",
    coverGradient: "from-cyan-500 to-blue-600",
  },
  {
    slug: "qr-code-guide-ar",
    title: "كل ما تحتاج معرفته عن QR Code: الإنشاء والقراءة والاستخدامات",
    description: "دليل شامل عن QR Code: تاريخه، كيف يخزّن البيانات، الفرق بينه وبين الباركود، أنواع المحتوى، ومستويات تصحيح الأخطاء.",
    date: "2026-03-16",
    author: "BrowseryTools Team",
    category: "أدوات عامة",
    tags: ["QR code", "باركود", "qr generator", "qr scanner", "رمز الاستجابة السريعة"],
    readTime: 7,
    featured: false,
    coverEmoji: "📱",
    coverGradient: "from-teal-500 to-green-600",
  },
  {
    slug: "adawat-nass-arabi",
    title: "أدوات معالجة النصوص للكتّاب والمطورين العرب",
    description: "دليل عملي لأدوات معالجة النصوص العربية: عداد الكلمات، تحويل حالة النص، مقارنة النصوص، ومحرر Markdown — وكيف تستخدمها في عملك.",
    date: "2026-03-17",
    author: "BrowseryTools Team",
    category: "أدوات النصوص",
    tags: ["نصوص عربية", "markdown", "text tools", "مقارنة نصوص", "عداد كلمات", "RTL"],
    readTime: 6,
    featured: false,
    coverEmoji: "✍️",
    coverGradient: "from-slate-500 to-gray-600",
  },
  // Agent 1 — AI Tools
  {
    slug: "ai-cost-calculator-guide",
    title: "How to Calculate Your AI API Costs Before You Run Out of Budget",
    description: "Token-based pricing explained: input vs output costs, how GPT-4, Claude, and Gemini charge per 1K tokens, cost scaling with volume, and practical strategies to reduce your monthly AI API bill.",
    date: "2026-03-22",
    author: "BrowseryTools Team",
    category: "AI Tools",
    tags: ["AI", "API costs", "tokens", "GPT-4", "Claude", "budget"],
    readTime: 8,
    coverEmoji: "💰",
    coverGradient: "from-emerald-500 to-teal-600",
  },
  {
    slug: "token-counter-guide",
    title: "Token Counting in LLMs: Why Every Developer Needs to Understand It",
    description: "What tokens actually are, how byte-pair encoding works, why the 750-words-per-1000-tokens rule breaks for Arabic and Chinese, and how token counts affect context windows and API costs.",
    date: "2026-03-22",
    author: "BrowseryTools Team",
    category: "AI Tools",
    tags: ["tokens", "tokenizer", "LLM", "BPE", "context window", "API"],
    readTime: 7,
    coverEmoji: "🔢",
    coverGradient: "from-violet-500 to-purple-600",
  },
  {
    slug: "context-window-guide",
    title: "LLM Context Windows Explained: Limits, Strategies, and How to Work Within Them",
    description: "What a context window is, current limits for GPT-4, Claude, and Gemini, what happens when you exceed them, the lost-in-the-middle problem, and strategies like chunking, summarization, and RAG.",
    date: "2026-03-22",
    author: "BrowseryTools Team",
    category: "AI Tools",
    tags: ["context window", "LLM", "RAG", "GPT-4", "Claude", "Gemini"],
    readTime: 8,
    coverEmoji: "📐",
    coverGradient: "from-purple-500 to-indigo-600",
  },
  {
    slug: "model-comparison-guide",
    title: "GPT-4 vs Claude vs Gemini: How to Compare AI Models for Your Use Case",
    description: "Why benchmark numbers can mislead, key dimensions for comparing AI models (reasoning, coding, cost, context length), and a practical approach to choosing the right model for your specific application.",
    date: "2026-03-22",
    author: "BrowseryTools Team",
    category: "AI Tools",
    tags: ["GPT-4", "Claude", "Gemini", "model comparison", "AI", "benchmarks"],
    readTime: 9,
    coverEmoji: "⚖️",
    coverGradient: "from-amber-500 to-orange-600",
  },
  // Agent 2 — AI/Prompt Tools
  {
    slug: "prompt-formatter-guide",
    title: "How to Format Prompts for Better AI Responses",
    description: "Learn the techniques that separate mediocre AI outputs from precise, actionable ones: role assignment, clear instruction blocks, few-shot examples, chain-of-thought prompting, and structured XML/JSON formats.",
    date: "2026-03-21",
    author: "BrowseryTools Team",
    category: "AI Tools",
    tags: ["AI", "prompts", "ChatGPT", "Claude", "prompt engineering"],
    readTime: 7,
    coverEmoji: "✨",
    coverGradient: "from-violet-500 to-purple-600",
  },
  {
    slug: "system-prompt-builder-guide",
    title: "Writing System Prompts That Actually Work",
    description: "A practical guide to crafting system prompts that produce consistent AI behavior — covering role, context, constraints, output format, and how to test and iterate across customer support, coding, and writing use cases.",
    date: "2026-03-21",
    author: "BrowseryTools Team",
    category: "AI Tools",
    tags: ["AI", "system prompts", "Claude", "ChatGPT", "prompt engineering", "LLM"],
    readTime: 8,
    coverEmoji: "🧠",
    coverGradient: "from-blue-500 to-indigo-600",
  },
  {
    slug: "mcp-config-guide",
    title: "Model Context Protocol (MCP): What It Is and How to Configure It",
    description: "MCP is Anthropic's open standard for connecting AI models to tools, files, and databases. Learn how the client-server architecture works, which servers to use, and how to write a working MCP config for Claude Desktop and Claude Code.",
    date: "2026-03-21",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["MCP", "Claude", "AI tools", "Claude Code", "developer tools", "Anthropic"],
    readTime: 8,
    coverEmoji: "🔌",
    coverGradient: "from-emerald-500 to-teal-600",
  },
  {
    slug: "claude-md-guide",
    title: "CLAUDE.md Files: How to Give AI the Context It Needs About Your Codebase",
    description: "A CLAUDE.md file at your project root gives Claude Code standing context about your stack, conventions, and architecture — eliminating the repeated corrections that come with a context-blind AI assistant.",
    date: "2026-03-21",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["Claude Code", "CLAUDE.md", "AI", "developer tools", "codebase context", "Anthropic"],
    readTime: 7,
    coverEmoji: "📄",
    coverGradient: "from-orange-500 to-amber-500",
  },
  // Agent 3 — Developer Tools batch 1
  {
    slug: "regex-tester-guide",
    title: "Regular Expressions Explained: A Practical Guide for Developers",
    description: "Learn the 20% of regex syntax that covers 80% of real-world use cases — character classes, quantifiers, anchors, groups, and flags — with practical examples for email validation, phone numbers, URL extraction, and more.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["regex", "regular expressions", "developer", "pattern matching", "validation"],
    readTime: 9,
    coverEmoji: "🔍",
    coverGradient: "from-orange-500 to-red-600",
  },
  {
    slug: "json-formatter-guide",
    title: "JSON Formatting, Validation, and Debugging: A Complete Developer Guide",
    description: "A practical guide to JSON syntax rules, common parse errors, pretty-printing vs minification, deeply nested data, JSON Schema validation, and how JSON differs between APIs and config files.",
    date: "2026-03-20",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["json", "formatting", "validation", "api", "debugging"],
    readTime: 8,
    coverEmoji: "📋",
    coverGradient: "from-yellow-400 to-orange-500",
  },
  {
    slug: "curl-converter-guide",
    title: "cURL to Code: Convert API Requests Between Languages Instantly",
    description: "Understand cURL's flag syntax, common REST API patterns, and how to accurately translate cURL commands into JavaScript fetch, Python requests, and Node.js axios — including the browser DevTools 'Copy as cURL' workflow.",
    date: "2026-03-20",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["curl", "api", "http", "javascript", "python", "rest"],
    readTime: 8,
    coverEmoji: "🔄",
    coverGradient: "from-blue-500 to-cyan-500",
  },
  {
    slug: "unix-timestamp-guide",
    title: "Unix Timestamps: What They Are and How to Work With Them",
    description: "Everything developers need to know about Unix time — what the epoch is, the Y2K38 problem, converting timestamps in JavaScript, Python, and SQL, the milliseconds vs seconds trap, timezone handling, and timestamps in JWTs and databases.",
    date: "2026-03-20",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["unix timestamp", "epoch", "datetime", "javascript", "python", "timezone"],
    readTime: 9,
    coverEmoji: "⏱️",
    coverGradient: "from-violet-500 to-purple-700",
  },
  // Agent 4 — Developer Tools batch 2
  {
    slug: "url-encoder-guide",
    title: "URL Encoding Explained: Percent-Encoding in HTTP Requests",
    description: "Learn why special characters break URLs, how percent-encoding works at the byte level, the critical difference between encodeURI and encodeURIComponent, and common encoding bugs in real applications.",
    date: "2026-03-19",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["URL encoding", "percent encoding", "HTTP", "web development", "JavaScript"],
    readTime: 7,
    coverEmoji: "🔗",
    coverGradient: "from-cyan-500 to-blue-600",
  },
  {
    slug: "uuid-generator-guide",
    title: "UUIDs, NanoIDs, and CUIDs: Choosing the Right ID Format for Your Project",
    description: "A deep dive into UUID v1, v4, and v7, NanoID, and CUID2 — what each format is, how collision probability works, and when to use which for database primary keys, URLs, and distributed systems.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["UUID", "NanoID", "CUID", "database", "distributed systems", "identifiers"],
    readTime: 8,
    coverEmoji: "🆔",
    coverGradient: "from-violet-500 to-purple-700",
  },
  {
    slug: "chmod-guide",
    title: "Linux File Permissions Explained: A Complete chmod Guide",
    description: "A complete guide to Unix file permissions — the owner/group/other model, octal notation (755, 644, 777), symbolic notation, setuid/setgid/sticky bit, and real-world examples for web servers and SSH keys.",
    date: "2026-03-21",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["chmod", "Linux", "file permissions", "Unix", "security", "sysadmin"],
    readTime: 8,
    coverEmoji: "🔒",
    coverGradient: "from-green-500 to-teal-600",
  },
  {
    slug: "http-status-codes-guide",
    title: "HTTP Status Codes Every Developer Should Know",
    description: "A practical reference for HTTP status codes — the five categories, deep dives on 200, 201, 204, 301, 302, 304, 400, 401, 403, 404, 409, 422, 429, 500, 502, 503, plus guidance on REST API design and debugging in DevTools.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["HTTP", "status codes", "REST API", "web development", "debugging"],
    readTime: 7,
    coverEmoji: "📡",
    coverGradient: "from-orange-500 to-red-600",
  },
  // Agent 5 — Image/Media Tools
  {
    slug: "video-compression-guide",
    title: "How to Compress Video Files Without Losing Quality",
    description: "A practical guide to video compression: how codecs like H.264, H.265, VP9, and AV1 work, what actually controls file size, lossless vs lossy compression, and the best settings for email, web, social media, and archival use cases.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Media Tools",
    tags: ["video compression", "H.264", "codec", "file size", "video editing"],
    readTime: 7,
    coverEmoji: "🎬",
    coverGradient: "from-red-500 to-pink-600",
  },
  {
    slug: "image-formats-guide",
    title: "JPEG vs PNG vs WebP vs AVIF: The Complete Image Format Comparison",
    description: "Understand how JPEG, PNG, WebP, and AVIF each compress images under the hood, when to use each format, how they affect Core Web Vitals, and how to serve the right format to the right browser.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Image Tools",
    tags: ["image formats", "JPEG", "PNG", "WebP", "AVIF", "web performance", "Core Web Vitals"],
    readTime: 8,
    coverEmoji: "🖼️",
    coverGradient: "from-blue-500 to-cyan-500",
  },
  {
    slug: "exif-data-guide",
    title: "EXIF Metadata: What Your Photos Reveal About You (And How to Remove It)",
    description: "EXIF data embeds GPS coordinates, device serial numbers, and timestamps into every photo you take. Learn what it records, the real privacy risks, famous cases where it exposed people's locations, and how to view and remove it.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Privacy & Security",
    tags: ["EXIF", "metadata", "privacy", "GPS", "photo security", "image data"],
    readTime: 8,
    coverEmoji: "📷",
    coverGradient: "from-amber-500 to-orange-600",
  },
  {
    slug: "svg-guide",
    title: "SVG Files: A Complete Guide for Developers and Designers",
    description: "Everything you need to know about SVG: the XML-based vector format that scales infinitely, how core elements like path and viewBox work, CSS styling and animation, SVGO optimization, XSS risks from user-uploaded SVGs, and when to convert SVG to PNG.",
    date: "2026-03-21",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["SVG", "vector graphics", "web development", "CSS", "SVGO", "icons"],
    readTime: 9,
    coverEmoji: "✏️",
    coverGradient: "from-violet-500 to-purple-600",
  },
  // Agent 6 — Text Tools
  {
    slug: "lorem-ipsum-guide",
    title: "Lorem Ipsum: Origin, Uses, and Why Designers Can't Live Without It",
    description: "The full story behind Lorem Ipsum — from Cicero's 45 BC philosophical text to modern design workflows. Learn when to use it, when to avoid it, and how to generate the exact amount you need.",
    date: "2026-03-17",
    author: "BrowseryTools Team",
    category: "Text Tools",
    tags: ["lorem ipsum", "placeholder text", "design", "typography"],
    readTime: 6,
    coverEmoji: "📝",
    coverGradient: "from-slate-500 to-gray-600",
  },
  {
    slug: "markdown-complete-guide",
    title: "Markdown: Complete Syntax Reference for Writers and Developers",
    description: "A comprehensive guide to Markdown — who created it and why, full syntax reference from basics to extended features, Markdown flavors (CommonMark, GFM, MDX), and common mistakes to avoid.",
    date: "2026-03-18",
    author: "BrowseryTools Team",
    category: "Text Tools",
    tags: ["markdown", "syntax", "writing", "documentation", "developers"],
    readTime: 7,
    coverEmoji: "✍️",
    coverGradient: "from-indigo-500 to-blue-600",
  },
  {
    slug: "text-diff-guide",
    title: "How to Compare Text Files and Find Differences Without Any Software",
    description: "Learn how text diff algorithms work, how to read unified diff output, the difference between line-level and word-level diffs, and how git diff works under the hood.",
    date: "2026-03-19",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["diff", "text comparison", "git", "code review", "file comparison"],
    readTime: 6,
    coverEmoji: "🔍",
    coverGradient: "from-emerald-500 to-teal-600",
  },
  {
    slug: "text-encryption-guide",
    title: "Client-Side Text Encryption: How to Protect Sensitive Data in the Browser",
    description: "A practical guide to browser-based text encryption — what client-side encryption really means, symmetric vs asymmetric algorithms, key derivation from passwords, and the real limitations of in-browser cryptography.",
    date: "2026-03-20",
    author: "BrowseryTools Team",
    category: "Security",
    tags: ["encryption", "AES", "security", "privacy", "cryptography", "browser"],
    readTime: 7,
    coverEmoji: "🔐",
    coverGradient: "from-rose-500 to-pink-600",
  },
  {
    slug: "word-frequency-guide",
    title: "Word Frequency Analysis: A Tool for Writers, SEO, and Research",
    description: "How word frequency analysis reveals writing patterns, keyword density, and document themes. Covers stop words, TF-IDF explained simply, use cases for writers and SEO, and academic applications like authorship attribution.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Text Tools",
    tags: ["word frequency", "text analysis", "SEO", "writing", "NLP", "content"],
    readTime: 6,
    coverEmoji: "📊",
    coverGradient: "from-violet-500 to-purple-600",
  },
  // Agent 7 — Productivity & Finance
  {
    slug: "expense-tracker-guide",
    title: "Track Your Monthly Expenses Without Apps, Subscriptions, or Cloud Storage",
    description: "Most people have no idea where their money goes. Learn the 50/30/20 budgeting rule, the difference between fixed and variable expenses, and how to run a monthly expense review — without signing up for anything.",
    date: "2026-03-16",
    author: "BrowseryTools Team",
    category: "Productivity",
    tags: ["expense tracker", "budgeting", "personal finance", "money management"],
    readTime: 7,
    coverEmoji: "💸",
    coverGradient: "from-emerald-500 to-green-600",
  },
  {
    slug: "invoice-generator-guide",
    title: "How to Create Professional Invoices for Free — No Subscriptions Required",
    description: "A complete guide to professional invoicing: required fields, numbering conventions, payment terms like Net 30, late fee language, VAT and GST requirements by country, and why a free PDF tool beats a $100/year subscription.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Business",
    tags: ["invoice", "freelancing", "billing", "payment terms", "PDF"],
    readTime: 7,
    coverEmoji: "🧾",
    coverGradient: "from-violet-500 to-purple-600",
  },
  {
    slug: "loan-calculator-guide",
    title: "Loan Payment Calculator: Understand Your Mortgage, Car Loan, or Personal Loan",
    description: "The loan payment formula explained, amortization demystified (why early payments are mostly interest), APR vs interest rate, how extra payments save thousands, and how to actually compare loan offers.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Finance",
    tags: ["loan calculator", "mortgage", "amortization", "APR", "personal finance"],
    readTime: 8,
    coverEmoji: "🏦",
    coverGradient: "from-blue-500 to-cyan-600",
  },
  {
    slug: "currency-converter-guide",
    title: "How Currency Exchange Rates Work: A Practical Guide",
    description: "What drives exchange rates, the bid/ask spread, why you never get the mid-market rate, how banks and credit cards hide fees in spreads, and the currency traps that catch travelers and international freelancers.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Finance",
    tags: ["currency converter", "exchange rates", "forex", "travel", "international payments"],
    readTime: 7,
    coverEmoji: "💱",
    coverGradient: "from-amber-500 to-orange-500",
  },
  {
    slug: "timezone-guide",
    title: "Working Across Time Zones: A Complete Guide for Remote Teams",
    description: "How UTC offsets work, why DST makes scheduling error-prone, best practices for remote team meeting scheduling, ISO 8601 datetime format, and the golden rule for developers: always store timestamps in UTC.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Productivity",
    tags: ["timezone", "remote work", "UTC", "scheduling", "ISO 8601", "developers"],
    readTime: 8,
    coverEmoji: "🌐",
    coverGradient: "from-purple-500 to-violet-600",
  },
  // Agent 8 — Arabic batch 1
  {
    slug: "adawat-almutasaffih-privacy",
    title: "لماذا أدوات المتصفح هي الأكثر أمانًا لبياناتك الشخصية",
    description: "تعرّف على كيفية معالجة أدوات BrowseryTools لبياناتك محليًا في متصفحك دون رفعها لأي سيرفر، وكيف تحمي خصوصيتك بشكل كامل.",
    date: "2026-03-15",
    author: "BrowseryTools Team",
    category: "الخصوصية والأمن",
    tags: ["خصوصية", "أمن", "متصفح", "بيانات", "privacy", "security"],
    readTime: 6,
    coverEmoji: "🔒",
    coverGradient: "from-indigo-500 to-purple-600",
  },
  {
    slug: "adawat-almutawwirin-arabi",
    title: "أفضل أدوات المطورين المجانية في المتصفح لعام 2025",
    description: "دليل شامل لأفضل 10 أدوات مطورين مجانية تعمل في المتصفح، مع مقارنة بين أدوات المتصفح والبدائل الأخرى ولماذا هي الخيار الأمثل.",
    date: "2026-03-16",
    author: "BrowseryTools Team",
    category: "أدوات المطورين",
    tags: ["مطورين", "أدوات", "مجاني", "متصفح", "developer-tools", "free"],
    readTime: 7,
    coverEmoji: "🛠️",
    coverGradient: "from-blue-500 to-cyan-600",
  },
  {
    slug: "json-dalil-arabi",
    title: "دليل JSON الشامل: ما هو وكيف يستخدمه المطورون",
    description: "دليل مفصل باللغة العربية يشرح JSON من الأساسيات: قواعد البناء، الأخطاء الشائعة، الفرق بين JSON وXML، واستخدامه في APIs.",
    date: "2026-03-17",
    author: "BrowseryTools Team",
    category: "أدوات المطورين",
    tags: ["json", "api", "بيانات", "مطورين", "تنسيق", "data-format"],
    readTime: 8,
    coverEmoji: "📋",
    coverGradient: "from-green-500 to-emerald-600",
  },
  {
    slug: "regex-dalil-arabi",
    title: "شرح Regular Expressions بالعربي: دليل المبتدئين",
    description: "دليل شامل للمبتدئين يشرح التعابير النمطية (Regular Expressions) من الصفر مع أمثلة عملية للتحقق من البريد الإلكتروني والهاتف وغيرها.",
    date: "2026-03-18",
    author: "BrowseryTools Team",
    category: "أدوات المطورين",
    tags: ["regex", "regular-expressions", "تعابير-نمطية", "مطورين", "javascript", "python"],
    readTime: 9,
    coverEmoji: "🔍",
    coverGradient: "from-orange-500 to-red-600",
  },
  // Agent 10 — Arabic batch 3
  {
    slug: "adawat-sour-arabi",
    title: "أدوات الصور المجانية: الضغط والتحويل وإزالة الخلفية بدون رفع الملفات",
    description: "اضغط صورك وحوّلها وأزل خلفياتها مجانًا مباشرةً في متصفحك. لا حاجة لرفع ملفاتك أو الاشتراك في أي خدمة.",
    date: "2026-03-13",
    author: "BrowseryTools Team",
    category: "أدوات الصور",
    tags: ["ضغط الصور", "تحويل الصور", "إزالة الخلفية", "image tools", "free"],
    readTime: 7,
    coverEmoji: "🖼️",
    coverGradient: "from-pink-500 to-rose-600",
  },
  {
    slug: "thikaa-isnadi-guide-ar",
    title: "أدوات الذكاء الاصطناعي للمطورين: حساب التكلفة ومقارنة النماذج وعدّ الرموز",
    description: "دليل شامل لفهم تسعير نماذج GPT-4 وClaude وGemini، وكيف تحسب تكاليف API قبل البناء وتُقلّلها في تطبيقاتك.",
    date: "2026-03-14",
    author: "BrowseryTools Team",
    category: "أدوات الذكاء الاصطناعي",
    tags: ["ذكاء اصطناعي", "GPT-4", "Claude", "Tokens", "AI cost", "developers"],
    readTime: 8,
    coverEmoji: "🤖",
    coverGradient: "from-violet-500 to-purple-700",
  },
  {
    slug: "markdown-guide-ar",
    title: "دليل Markdown الشامل للكتّاب والمطورين العرب",
    description: "كل ما تحتاج معرفته عن Markdown — من الصيغ الأساسية إلى استخدامه مع اللغة العربية وتحويله إلى HTML.",
    date: "2026-03-15",
    author: "BrowseryTools Team",
    category: "أدوات الكتابة",
    tags: ["Markdown", "كتابة", "توثيق", "HTML", "Obsidian", "Notion"],
    readTime: 7,
    coverEmoji: "✍️",
    coverGradient: "from-sky-500 to-blue-700",
  },
  {
    slug: "himayat-khusousiyya-arabi",
    title: "دليل حماية الخصوصية على الإنترنت في 2025",
    description: "المخاطر الحقيقية على خصوصيتك الرقمية وخطوات عملية فورية للحد من تتبعك وحماية بياناتك الحساسة.",
    date: "2026-03-16",
    author: "BrowseryTools Team",
    category: "الأمن والخصوصية",
    tags: ["خصوصية", "أمن رقمي", "VPN", "تشفير", "كلمات مرور", "privacy"],
    readTime: 9,
    coverEmoji: "🔒",
    coverGradient: "from-emerald-500 to-teal-700",
  },
  {
    slug: "compress-video-online-free",
    title: "How to Compress Video Online for Free (No Upload, No Watermark)",
    description: "Reduce video file size right in your browser — free, no account, no watermark, nothing uploaded. Learn the bitrate, resolution, and codec settings that actually shrink a video, plus the best presets for email, social media, and the web.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Media Tools",
    tags: ["compress video online free", "reduce video size", "video compressor", "shrink video", "no upload", "free"],
    readTime: 7,
    coverEmoji: "🎬",
    coverGradient: "from-rose-500 to-red-600",
  },
  {
    slug: "redact-image-online",
    title: "How to Redact or Censor an Image Online (Blur Faces & Hide Sensitive Info)",
    description: "Blur faces, pixelate license plates, and black out sensitive details in any image — entirely in your browser, with nothing uploaded. Learn which censor style is truly irreversible and the metadata mistake that quietly leaks redacted data.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Image Tools",
    tags: ["redact image", "blur faces", "censor photo", "hide sensitive info", "pixelate", "privacy"],
    readTime: 7,
    coverEmoji: "🖍️",
    coverGradient: "from-slate-500 to-gray-700",
  },
  {
    slug: "roman-numeral-converter-guide",
    title: "Roman Numeral Converter: How Roman Numerals Work (and How to Read MCMXCIV)",
    description: "The seven symbols, the add-and-subtract rules, the six valid subtractive pairs, and the common mistakes — everything you need to read and write Roman numerals, plus a free converter that goes both directions.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Calculators",
    tags: ["roman numerals", "roman numeral converter", "MCMXCIV", "how roman numerals work", "number converter"],
    readTime: 7,
    coverEmoji: "🏛️",
    coverGradient: "from-amber-500 to-yellow-600",
  },
  {
    slug: "convert-svg-to-png",
    title: "How to Convert SVG to PNG (Keep It Sharp and Transparent)",
    description: "Turn vector SVG files into universal PNG images right in your browser — free, no upload, no watermark. Learn how to pick the right export resolution so it never looks blurry, and how to keep a transparent background.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Image Tools",
    tags: ["convert svg to png", "svg to png", "vector to raster", "transparent png", "export svg", "free"],
    readTime: 7,
    coverEmoji: "🖼️",
    coverGradient: "from-cyan-500 to-blue-600",
  },
  {
    slug: "convert-video-to-gif",
    title: "How to Convert Video to GIF (and Keep the File Small)",
    description: "Turn an MP4 or MOV clip into a looping GIF right in your browser — no upload, no watermark. Learn why GIFs balloon in size, the three settings that keep them small, and when a short video beats a GIF.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Media Tools",
    tags: ["convert video to gif", "video to gif", "mp4 to gif", "make a gif", "no upload", "free"],
    readTime: 6,
    coverEmoji: "🎞️",
    coverGradient: "from-fuchsia-500 to-pink-600",
  },
  {
    slug: "crop-and-watermark-images-online",
    title: "How to Crop and Watermark Images Online (Free, No Upload)",
    description: "Crop to a precise aspect ratio, resize without distortion, and add a watermark that actually deters reuse — all in your browser, with the original never uploaded. Includes the aspect-ratio mistake that stretches your photos.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Image Tools",
    tags: ["crop image online", "watermark image", "resize image", "aspect ratio", "no upload", "free"],
    readTime: 7,
    coverEmoji: "✂️",
    coverGradient: "from-teal-500 to-emerald-600",
  },
  {
    slug: "curl-to-fetch-python-code",
    title: "How to Convert cURL to Code (fetch, Python requests, Node.js)",
    description: "Paste a cURL command and get working JavaScript fetch, Python requests, or Node.js code — including the DevTools 'Copy as cURL' trick. Learn how each flag maps to code so you can trust the output, all processed locally in your browser.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["curl to code", "curl to fetch", "curl to python", "convert curl", "copy as curl", "api"],
    readTime: 7,
    coverEmoji: "🔁",
    coverGradient: "from-indigo-500 to-violet-600",
  },
  {
    slug: "scientific-calculator-online",
    title: "Scientific Calculator Online: Trig, Logs, Powers, and the Mistakes to Avoid",
    description: "A free in-browser scientific calculator with sin, cos, tan, log, ln, powers, roots, and constants. Learn the degree-vs-radian trap, order of operations, and worked examples for compound interest, triangles, and pH.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Calculators",
    tags: ["scientific calculator online", "graphing calculator", "trig calculator", "log calculator", "free calculator"],
    readTime: 7,
    coverEmoji: "🧮",
    coverGradient: "from-blue-500 to-indigo-600",
  },
  {
    slug: "dagt-alfidyu-online-ar",
    title: "كيف تضغط الفيديو أونلاين مجاناً (بدون رفع وبدون علامة مائية)",
    description: "قلّص حجم ملف الفيديو داخل متصفحك مباشرةً — مجاناً، بدون حساب، بدون علامة مائية، ولا شيء يُرفع. تعرّف على إعدادات معدل البِت والدقة والترميز التي تصغّر الفيديو فعلاً، وأفضل الإعدادات للبريد ووسائل التواصل والويب.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "أدوات الوسائط",
    tags: ["ضغط الفيديو", "تصغير حجم الفيديو", "ضاغط فيديو", "أونلاين", "بدون رفع", "compress video"],
    readTime: 7,
    coverEmoji: "🎬",
    coverGradient: "from-rose-500 to-red-600",
  },
  {
    slug: "takhfif-alsuwar-online-ar",
    title: "كيف تحجب أو تموّه صورة أونلاين (تشويش الوجوه وإخفاء البيانات الحساسة)",
    description: "موّه الوجوه، وبكسل لوحات السيارات، واطمس التفاصيل الحساسة في أي صورة — كلياً في متصفحك، ولا شيء يُرفع. تعرّف على نمط الحجب الذي لا يمكن عكسه، وخطأ البيانات الوصفية الذي يسرّب ما ظننت أنك أخفيته.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "أدوات الصور",
    tags: ["حجب الصور", "تمويه الوجوه", "إخفاء البيانات", "تبكسل", "خصوصية", "censor"],
    readTime: 7,
    coverEmoji: "🖍️",
    coverGradient: "from-slate-500 to-gray-700",
  },
  {
    slug: "alarqam-alrumaniyya-ar",
    title: "محوّل الأرقام الرومانية: كيف تعمل الأرقام الرومانية (وكيف تقرأ MCMXCIV)",
    description: "الرموز السبعة، وقاعدتا الجمع والطرح، والأزواج الطرحية الستة الصحيحة، والأخطاء الشائعة — كل ما تحتاجه لقراءة الأرقام الرومانية وكتابتها، مع محوّل مجاني يعمل في الاتجاهين.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "الحاسبات",
    tags: ["الأرقام الرومانية", "محوّل أرقام رومانية", "MCMXCIV", "كيف تعمل الأرقام الرومانية", "roman numerals"],
    readTime: 7,
    coverEmoji: "🏛️",
    coverGradient: "from-amber-500 to-yellow-600",
  },
  {
    slug: "tahwil-svg-ila-png-ar",
    title: "كيف تحوّل SVG إلى PNG (أبقها واضحة وشفافة)",
    description: "حوّل ملفات SVG المتجهية إلى صور PNG شاملة داخل متصفحك — مجاناً، بدون رفع، بدون علامة مائية. تعرّف على كيفية اختيار دقة الإخراج الصحيحة كي لا تبدو مشوّشة، وكيف تحافظ على خلفية شفافة.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "أدوات الصور",
    tags: ["تحويل SVG إلى PNG", "svg to png", "متجه إلى نقطي", "png شفاف", "تصدير svg", "مجاني"],
    readTime: 7,
    coverEmoji: "🖼️",
    coverGradient: "from-cyan-500 to-blue-600",
  },
  {
    slug: "tahwil-alfidyu-ila-gif-ar",
    title: "كيف تحوّل الفيديو إلى GIF (وتبقي الملف صغيراً)",
    description: "حوّل مقطع MP4 أو MOV إلى صورة GIF متكرّرة داخل متصفحك — بدون رفع، بدون علامة مائية. تعرّف على سبب تضخّم صور GIF، والإعدادات الثلاثة التي تبقيها صغيرة، ومتى يتفوّق الفيديو القصير على GIF.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "أدوات الوسائط",
    tags: ["تحويل الفيديو إلى GIF", "video to gif", "mp4 إلى gif", "صنع gif", "بدون رفع", "مجاني"],
    readTime: 6,
    coverEmoji: "🎞️",
    coverGradient: "from-fuchsia-500 to-pink-600",
  },
  {
    slug: "qass-walalama-almaiya-lilsuwar-ar",
    title: "كيف تقصّ وتضع علامة مائية على الصور أونلاين (مجاناً، بدون رفع)",
    description: "اقصّ إلى نسبة أبعاد دقيقة، وغيّر الحجم دون تشويه، وأضف علامة مائية تردع إعادة الاستخدام فعلاً — كل ذلك في متصفحك، والأصل لا يُرفع أبداً. يتضمّن خطأ نسبة الأبعاد الذي يمدّد صورك.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "أدوات الصور",
    tags: ["قصّ الصور", "علامة مائية", "تغيير حجم الصور", "نسبة الأبعاد", "بدون رفع", "مجاني"],
    readTime: 7,
    coverEmoji: "✂️",
    coverGradient: "from-teal-500 to-emerald-600",
  },
  {
    slug: "tahwil-curl-ila-code-ar",
    title: "كيف تحوّل cURL إلى كود (fetch وPython requests وNode.js)",
    description: "الصق أمر cURL واحصل على كود JavaScript fetch أو Python requests أو Node.js — بما في ذلك خدعة 'Copy as cURL' في أدوات المطوّر. تعرّف على ربط كل علَم بالكود كي تثق بالمخرجات، وكل ذلك يُعالَج محلياً في متصفحك.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "أدوات المطوّرين",
    tags: ["تحويل cURL", "curl إلى fetch", "curl إلى python", "copy as curl", "api", "كود"],
    readTime: 7,
    coverEmoji: "🔁",
    coverGradient: "from-indigo-500 to-violet-600",
  },
  {
    slug: "alaala-alhasiba-alilmiyya-ar",
    title: "الآلة الحاسبة العلمية أونلاين: المثلثات واللوغاريتمات والقوى والأخطاء الشائعة",
    description: "آلة حاسبة علمية مجانية في المتصفح تضم sin وcos وtan وlog وln والقوى والجذور والثوابت. تعرّف على فخ الدرجات مقابل الراديان، وترتيب العمليات، وأمثلة محلولة للفائدة المركّبة والمثلثات ودرجة الحموضة.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "الحاسبات",
    tags: ["آلة حاسبة علمية", "حاسبة بيانية", "حاسبة مثلثات", "حاسبة لوغاريتم", "حاسبة مجانية"],
    readTime: 7,
    coverEmoji: "🧮",
    coverGradient: "from-blue-500 to-indigo-600",
  },
  {
    slug: "meme-generator-guide",
    title: "How to Make a Meme Online Free — No App, No Upload, No Watermark",
    description: "Make a meme online free in your browser. Upload an image, add classic Impact-font top and bottom text, drag to position, style each line, and download as PNG. Nothing uploads, no watermark.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Image Tools",
    tags: ["meme generator", "make a meme", "meme maker", "Impact font", "free", "no upload"],
    readTime: 7,
    featured: true,
    coverEmoji: "😂",
    coverGradient: "from-yellow-400 to-orange-500",
  },
  {
    slug: "meme-generator-guide-ar",
    title: "كيف تنشئ ميماً عبر الإنترنت مجاناً — بدون تطبيق وبدون رفع وبدون علامة مائية",
    description: "أنشئ ميماً عبر الإنترنت مجاناً داخل متصفحك. ارفع صورة، أضف نصاً علوياً وسفلياً بخط Impact الكلاسيكي، حرّكه بالسحب، نسّق كل سطر، ونزّله بصيغة PNG. لا شيء يُرفع وبدون علامة مائية.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "أدوات الصور",
    tags: ["صانع الميمات", "إنشاء ميم", "ميم", "خط Impact", "مجاني", "بدون رفع"],
    readTime: 7,
    featured: true,
    coverEmoji: "😂",
    coverGradient: "from-yellow-400 to-orange-500",
  },
  {
    slug: "favicon-generator-guide",
    title: "How to Create a Favicon From an Image (or a Letter) — Free Online Generator",
    description: "Use a free favicon generator online to create a favicon from an image or a letter/emoji. Get all sizes (16, 32, 180, 192, 512), a multi-size favicon.ico, manifest, and HTML snippet — all in your browser.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["favicon", "favicon generator", "create favicon from image", "favicon generator online", "web development", "icons"],
    readTime: 7,
    featured: true,
    coverEmoji: "🌟",
    coverGradient: "from-violet-500 to-fuchsia-600",
  },
  {
    slug: "favicon-generator-guide-ar",
    title: "كيف تنشئ فافيكون من صورة (أو حرف) — مولّد مجاني عبر الإنترنت",
    description: "استخدم مولّد فافيكون مجاني عبر الإنترنت لإنشاء فافيكون من صورة أو حرف/إيموجي. احصل على كل الأحجام (16 و32 و180 و192 و512) وملف favicon.ico متعدد الأحجام وملف التعريف ومقطع HTML — كل ذلك داخل متصفحك.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["فافيكون", "مولّد فافيكون", "إنشاء فافيكون من صورة", "مولّد فافيكون عبر الإنترنت", "تطوير الويب", "أيقونات"],
    readTime: 7,
    featured: true,
    coverEmoji: "🌟",
    coverGradient: "from-violet-500 to-fuchsia-600",
  },
  {
    slug: "text-to-speech-guide",
    title: "How to Read Text Aloud Online for Free — No App, No Account",
    description: "Turn any text into speech right in your browser. Adjust voice, rate, pitch, and volume with the free Web Speech API tool — private, instant, and works on Mac, Windows, Linux, iOS, and Android.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Text & Language",
    tags: ["text to speech online free", "read text aloud", "TTS", "web speech api", "accessibility", "voiceover"],
    readTime: 7,
    featured: true,
    coverEmoji: "🔊",
    coverGradient: "from-sky-500 to-indigo-600",
  },
  {
    slug: "text-to-speech-guide-ar",
    title: "كيف تقرأ أي نص بصوت مسموع عبر الإنترنت مجاناً — بدون تطبيق وبدون حساب",
    description: "حوّل أي نص إلى كلام مباشرة في متصفحك. تحكّم في الصوت والسرعة والنبرة ومستوى الصوت عبر أداة Web Speech API المجانية — خاصة وفورية وتعمل على ماك وويندوز ولينكس وiOS وأندرويد.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "النصوص واللغة",
    tags: ["تحويل النص إلى كلام", "قراءة النص بصوت", "TTS", "web speech api", "إمكانية الوصول", "تعليق صوتي"],
    readTime: 7,
    featured: true,
    coverEmoji: "🔊",
    coverGradient: "from-sky-500 to-indigo-600",
  },
  {
    slug: "random-picker-guide",
    title: "Random Picker: Random Numbers, Dice, Coin Flips & Name Wheel",
    description: "Generate random numbers, roll dice, flip a coin, or pick a fair winner from a list — free and in your browser. Learn how to run an unbiased giveaway draw and when randomness really is random.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Productivity Tools",
    tags: ["random number generator", "random name picker", "dice roller", "coin flip", "wheel of names", "giveaway"],
    readTime: 6,
    coverEmoji: "🎲",
    coverGradient: "from-violet-500 to-purple-600",
  },
  {
    slug: "random-picker-guide-ar",
    title: "أداة الاختيار العشوائي: أرقام عشوائية ونرد وقرعة وعجلة أسماء",
    description: "ولّد أرقاماً عشوائية، وارمِ النرد، واقذف عملة، أو اختر فائزاً عادلاً من قائمة — مجاناً وداخل متصفحك. تعرّف على كيفية إجراء سحب عادل للجوائز ومتى تكون العشوائية عشوائية فعلاً.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "أدوات الإنتاجية",
    tags: ["مولّد أرقام عشوائية", "اختيار اسم عشوائي", "رمي النرد", "قذف العملة", "عجلة الأسماء", "سحب الجوائز"],
    readTime: 6,
    coverEmoji: "🎲",
    coverGradient: "from-violet-500 to-purple-600",
  },
  {
    slug: "beautify-screenshots-online",
    title: "How to Make Beautiful Screenshots Online (Backgrounds, Shadows & Frames)",
    description: "Turn plain screenshots into polished, share-ready images — add a gradient or mesh background, padding, rounded corners, a soft shadow, and a window frame, all in your browser with nothing uploaded.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Image Tools",
    tags: ["beautify screenshot", "screenshot background", "add shadow to screenshot", "device frame", "social image", "free"],
    readTime: 6,
    coverEmoji: "🖼️",
    coverGradient: "from-sky-500 to-indigo-600",
  },
  {
    slug: "beautify-screenshots-online-ar",
    title: "كيف تصنع لقطات شاشة جميلة أونلاين (خلفيات وظلال وإطارات)",
    description: "حوّل لقطات الشاشة العادية إلى صور أنيقة جاهزة للمشاركة — أضف خلفية متدرّجة أو شبكية، وحشواً، وزوايا مدوّرة، وظلاً ناعماً، وإطار نافذة، كل ذلك داخل متصفحك دون رفع أي شيء.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "أدوات الصور",
    tags: ["تجميل لقطة الشاشة", "خلفية لقطة الشاشة", "إضافة ظل", "إطار جهاز", "صورة اجتماعية", "مجاني"],
    readTime: 6,
    coverEmoji: "🖼️",
    coverGradient: "from-sky-500 to-indigo-600",
  },
  {
    slug: "image-to-text-ocr-guide",
    title: "How to Extract Text From an Image (Free OCR, No Upload)",
    description: "Pull editable text out of photos, screenshots, and scans with free in-browser OCR — supports English, Spanish, French, German, and Arabic, and your image never leaves your device.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Text & Language Tools",
    tags: ["image to text", "OCR online free", "extract text from image", "photo to text", "scan to text", "no upload"],
    readTime: 7,
    coverEmoji: "🔤",
    coverGradient: "from-emerald-500 to-teal-600",
  },
  {
    slug: "image-to-text-ocr-guide-ar",
    title: "كيف تستخرج النص من صورة (OCR مجاني بدون رفع)",
    description: "استخرج نصاً قابلاً للتحرير من الصور ولقطات الشاشة والمستندات الممسوحة عبر OCR مجاني داخل المتصفح — يدعم الإنجليزية والإسبانية والفرنسية والألمانية والعربية، وصورتك لا تغادر جهازك أبداً.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "أدوات النصوص واللغة",
    tags: ["تحويل الصورة إلى نص", "OCR مجاني", "استخراج النص من الصورة", "صورة إلى نص", "مسح إلى نص", "بدون رفع"],
    readTime: 7,
    coverEmoji: "🔤",
    coverGradient: "from-emerald-500 to-teal-600",
  },
  {
    slug: "photo-collage-maker-guide",
    title: "How to Make a Photo Collage Online for Free (No Watermark, No Upload)",
    description:
      "Combine multiple photos into a collage right in your browser with our free photo collage maker. Grid, strip, and mosaic layouts, adjustable spacing and background, PNG/JPEG export — no account, no watermark, no upload.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Image Tools",
    tags: [
      "photo collage maker online free",
      "photo collage",
      "collage maker",
      "image tools",
      "no watermark",
      "browser",
    ],
    readTime: 7,
    featured: true,
    coverEmoji: "🖼️",
    coverGradient: "from-fuchsia-500 to-pink-600",
  },
  {
    slug: "photo-collage-maker-guide-ar",
    title: "كيف تصنع كولاج صور عبر الإنترنت مجانًا (بدون علامة مائية وبدون رفع)",
    description:
      "ادمج عدة صور في كولاج مباشرة داخل متصفحك باستخدام أداة صنع الكولاج المجانية. تخطيطات شبكية وشريطية وفسيفسائية، تباعد وخلفية قابلان للضبط، وتصدير PNG/JPEG — بدون حساب، وبدون علامة مائية، وبدون رفع.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "أدوات الصور",
    tags: [
      "كولاج صور",
      "صنع كولاج",
      "دمج الصور",
      "أدوات الصور",
      "بدون علامة مائية",
      "متصفح",
    ],
    readTime: 7,
    coverEmoji: "🖼️",
    coverGradient: "from-fuchsia-500 to-pink-600",
  },
  {
    slug: "code-screenshot-guide",
    title: "How to Turn Code Into Beautiful Images (A Free Carbon Alternative)",
    description: "Create beautiful, syntax-highlighted code screenshots for Twitter, docs, and slides — a free, private Carbon alternative that runs entirely in your browser. Themes, gradients, macOS window style, and PNG export.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["code screenshot", "carbon alternative", "syntax highlighting", "developer", "code image", "PNG export"],
    readTime: 7,
    featured: false,
    coverEmoji: "🖼️",
    coverGradient: "from-indigo-500 to-purple-600",
  },
  {
    slug: "code-screenshot-guide-ar",
    title: "كيف تحوّل الكود إلى صور جميلة (بديل مجاني لـ Carbon)",
    description: "أنشئ لقطات شاشة جميلة للكود مع تلوين الصياغة لتويتر والتوثيق والشرائح — بديل مجاني وخاص لـ Carbon يعمل بالكامل داخل متصفحك. سمات وتدرّجات ونمط نافذة macOS وتصدير PNG.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "أدوات المطورين",
    tags: ["لقطة شاشة كود", "بديل Carbon", "تلوين الصياغة", "مطورين", "صورة كود", "PNG"],
    readTime: 7,
    featured: false,
    coverEmoji: "🖼️",
    coverGradient: "from-indigo-500 to-purple-600",
  },
  {
    slug: "og-image-generator-guide",
    title: "How to Make an Open Graph Image (1200x630) for Free in Your Browser",
    description: "A free open graph image generator that builds a perfect 1200x630 social share image right in your browser. Pick a template, add a title and logo, export a PNG, and copy the og:image meta tags.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Design",
    tags: ["open graph image generator", "social share image 1200x630", "og:image", "twitter card", "social media", "seo"],
    readTime: 8,
    featured: true,
    coverEmoji: "🖼️",
    coverGradient: "from-sky-500 to-indigo-600",
  },
  {
    slug: "og-image-generator-guide-ar",
    title: "كيف تصنع صورة Open Graph بمقاس 1200×630 مجاناً في متصفحك",
    description: "مُنشئ صور Open Graph مجاني يبني صورة مشاركة اجتماعية مثالية بمقاس 1200×630 داخل متصفحك مباشرة. اختر قالباً، أضف عنواناً وشعاراً، صدّر ملف PNG، وانسخ وسوم og:image.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "التصميم",
    tags: ["مُنشئ صور Open Graph", "صورة مشاركة 1200x630", "og:image", "بطاقة تويتر", "وسائل التواصل", "SEO"],
    readTime: 8,
    featured: true,
    coverEmoji: "🖼️",
    coverGradient: "from-sky-500 to-indigo-600",
  },
  {
    slug: "image-color-picker-guide",
    title: "How to Pick Any Color from an Image Online (Get HEX, RGB & HSL)",
    description:
      "Use a color picker from image online to get HEX from an image instantly. Hover, click, and copy HEX, RGB, and HSL values — plus extract a dominant-color palette. 100% in-browser, no upload.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Design",
    tags: [
      "color picker from image online",
      "get hex from image",
      "image color picker",
      "hex rgb hsl",
      "color palette",
      "design tools",
    ],
    readTime: 7,
    coverEmoji: "🎨",
    coverGradient: "from-fuchsia-500 to-indigo-600",
  },
  {
    slug: "image-color-picker-guide-ar",
    title: "كيف تنتقي أي لون من صورة عبر الإنترنت (احصل على HEX وRGB وHSL)",
    description:
      "استخدم أداة انتقاء الألوان من الصور عبر الإنترنت للحصول على قيمة HEX من صورة فوراً. مرّر وانقر وانسخ قيم HEX وRGB وHSL، إضافةً إلى استخراج لوحة الألوان السائدة. تعمل بالكامل داخل المتصفح بلا رفع.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "التصميم",
    tags: [
      "انتقاء الألوان من الصور",
      "الحصول على hex من صورة",
      "أداة الألوان",
      "hex rgb hsl",
      "لوحة ألوان",
      "أدوات التصميم",
    ],
    readTime: 7,
    coverEmoji: "🎨",
    coverGradient: "from-fuchsia-500 to-indigo-600",
  },
  {
    slug: "remove-exif-data-guide",
    title: "How to Remove EXIF Data from Photos Online (Strip GPS & Metadata)",
    description: "Your photos hide GPS coordinates, your device model, and timestamps. Learn how to remove EXIF data online and strip metadata from any photo before sharing — free, in your browser, nothing uploaded.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Privacy & Security",
    tags: ["remove exif data", "strip metadata", "GPS location", "photo privacy", "EXIF remover", "image metadata"],
    readTime: 7,
    featured: false,
    coverEmoji: "🧹",
    coverGradient: "from-rose-500 to-orange-600",
  },
  {
    slug: "remove-exif-data-guide-ar",
    title: "كيف تحذف بيانات EXIF من الصور أونلاين (إزالة الموقع GPS والبيانات الوصفية)",
    description: "تخفي صورك إحداثيات GPS وطراز جهازك والطوابع الزمنية. تعلّم كيف تحذف بيانات EXIF أونلاين وتزيل البيانات الوصفية من أي صورة قبل مشاركتها — مجاناً، في متصفحك، دون رفع أي شيء.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "الخصوصية والأمن",
    tags: ["حذف بيانات exif", "إزالة البيانات الوصفية", "موقع GPS", "خصوصية الصور", "مزيل EXIF", "بيانات الصورة"],
    readTime: 7,
    featured: false,
    coverEmoji: "🧹",
    coverGradient: "from-rose-500 to-orange-600",
  },
  {
    slug: "signature-maker-guide",
    title: "How to Make an Online Signature: Draw or Type a Transparent PNG to E-Sign",
    description: "Create an online signature in your browser — draw it freehand or type your name in a handwriting font. Export a transparent PNG (or SVG) to e-sign PDFs and documents. No printing, no scanning, no uploads.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Productivity",
    tags: ["online signature maker", "draw signature", "transparent png", "e-sign", "esignature", "sign pdf"],
    readTime: 8,
    featured: true,
    coverEmoji: "✒️",
    coverGradient: "from-blue-500 to-indigo-600",
  },
  {
    slug: "signature-maker-guide-ar",
    title: "كيف تصنع توقيعاً إلكترونياً: ارسمه أو اكتبه كصورة PNG شفافة للتوقيع الرقمي",
    description: "أنشئ توقيعك عبر الإنترنت داخل المتصفح — ارسمه بخط يدك أو اكتب اسمك بخط يدوي. صدّر صورة PNG شفافة (أو SVG) لتوقّع ملفات PDF والمستندات إلكترونياً. بدون طباعة أو مسح ضوئي أو رفع.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "الإنتاجية",
    tags: ["صانع التوقيع", "توقيع إلكتروني", "PNG شفافة", "توقيع PDF", "e-sign", "signature"],
    readTime: 8,
    featured: true,
    coverEmoji: "✒️",
    coverGradient: "from-blue-500 to-indigo-600",
  },
  {
    slug: "speech-to-text-guide",
    title: "Speech to Text Online Free: How to Type With Your Voice in the Browser",
    description: "Convert speech to text online for free with voice typing and dictation — no apps, no sign-up. Learn how the Web Speech API works, which browsers support it, and how to dictate faster than you type.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Text Tools",
    tags: ["speech to text", "voice typing", "dictation", "Web Speech API", "free", "transcription"],
    readTime: 8,
    featured: true,
    coverEmoji: "🎤",
    coverGradient: "from-sky-500 to-indigo-600",
  },
  {
    slug: "speech-to-text-guide-ar",
    title: "تحويل الكلام إلى نص مجاناً: كيف تكتب بصوتك داخل المتصفح",
    description: "حوّل الكلام إلى نص مجاناً عبر الكتابة الصوتية والإملاء — بدون تطبيقات وبدون تسجيل. تعرّف على كيفية عمل Web Speech API، والمتصفحات الداعمة، وكيف تملي أسرع مما تكتب.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "أدوات النصوص",
    tags: ["تحويل الكلام إلى نص", "كتابة صوتية", "إملاء", "Web Speech API", "مجاني", "تفريغ صوتي"],
    readTime: 8,
    featured: true,
    coverEmoji: "🎤",
    coverGradient: "from-sky-500 to-indigo-600",
  },
  {
    slug: "ascii-art-generator-guide",
    title: "How to Turn Any Image Into ASCII Art (Free Browser Generator)",
    description: "Convert any photo into ASCII art in your browser — adjust width, pick a character ramp, invert, add color, then copy the text or export a PNG. No uploads, fully private.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Image Tools",
    tags: ["image to ascii art", "ascii art generator", "ascii art", "image converter", "browser tool", "free"],
    readTime: 7,
    featured: false,
    coverEmoji: "🖼️",
    coverGradient: "from-slate-600 to-zinc-800",
  },
  {
    slug: "ascii-art-generator-guide-ar",
    title: "كيف تحوّل أي صورة إلى فن أسكي (مولّد مجاني في المتصفّح)",
    description: "حوّل أي صورة إلى فن أسكي داخل متصفّحك — اضبط العرض واختر سُلّم الرموز والعكس والألوان، ثم انسخ النصّ أو صدّر صورة PNG. بلا رفع وبخصوصية كاملة.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "أدوات الصور",
    tags: ["تحويل صورة إلى أسكي", "مولّد فن أسكي", "فن أسكي", "محوّل صور", "أداة متصفّح", "مجاني"],
    readTime: 7,
    featured: false,
    coverEmoji: "🖼️",
    coverGradient: "from-slate-600 to-zinc-800",
  },
  {
    slug: "clip-path-generator-guide",
    title: "CSS clip-path Generator: Crop Elements Into Any Shape Without Images",
    description: "Build triangles, hexagons, stars, and section dividers with the CSS clip-path property. Drag points visually and copy production-ready clip-path CSS — no SVG or images needed.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Design Tools",
    tags: ["CSS", "clip-path", "design", "frontend", "UI", "shapes"],
    readTime: 6,
    featured: false,
    coverEmoji: "✂️",
    coverGradient: "from-indigo-500 to-pink-600",
  },
  {
    slug: "clip-path-generator-guide-ar",
    title: "مُنشئ clip-path في CSS: اقصص العناصر إلى أي شكل دون صور",
    description: "ابنِ مثلّثات وأشكالاً سداسية ونجوماً وفواصل أقسام عبر خاصية clip-path في CSS. اسحب النقاط بصرياً وانسخ كوداً جاهزاً للإنتاج — دون SVG أو صور.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "أدوات التصميم",
    tags: ["CSS", "clip-path", "تصميم", "واجهات", "أشكال", "frontend"],
    readTime: 6,
    coverEmoji: "✂️",
    coverGradient: "from-indigo-500 to-pink-600",
  },
  {
    slug: "cubic-bezier-guide",
    title: "Cubic-Bezier Generator: Master CSS Easing Curves",
    description: "Learn how cubic-bezier() easing works in CSS, what the four values mean, and how to design custom transition-timing-function curves with a free visual easing editor.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Design Tools",
    tags: ["cubic bezier generator", "css easing editor", "transition-timing-function", "css animation", "easing curves", "frontend"],
    readTime: 7,
    coverEmoji: "📈",
    coverGradient: "from-fuchsia-500 to-indigo-600",
  },
  {
    slug: "cubic-bezier-guide-ar",
    title: "مولّد Cubic-Bezier: أتقن منحنيات التوقيت في CSS",
    description: "تعلّم كيف تعمل دالة cubic-bezier() للتوقيت في CSS، ومعنى الأرقام الأربعة، وكيف تصمّم منحنيات transition-timing-function مخصصة بمحرّر بصري مجاني.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "أدوات التصميم",
    tags: ["cubic bezier", "منحنيات التوقيت", "css easing", "حركة CSS", "transition", "واجهات"],
    readTime: 7,
    coverEmoji: "📈",
    coverGradient: "from-fuchsia-500 to-indigo-600",
  },
  {
    slug: "glassmorphism-generator-guide",
    title: "How to Create the Frosted Glass Effect in CSS (Glassmorphism Generator)",
    description: "Build the frosted glass effect (glassmorphism) in CSS with a free visual generator. Tune blur, transparency, tint, saturation, and border — copy CSS with the -webkit- prefix and a fallback.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Design",
    tags: ["glassmorphism", "css", "frosted glass", "backdrop-filter", "ui design", "css generator"],
    readTime: 7,
    coverEmoji: "🧊",
    coverGradient: "from-cyan-500 to-blue-600",
  },
  {
    slug: "glassmorphism-generator-guide-ar",
    title: "كيف تصنع تأثير الزجاج المصنفر في CSS (مولِّد الزجاجية)",
    description: "أنشئ تأثير الزجاج المصنفر (الزجاجية) في CSS بمولِّد بصري مجاني. اضبط التمويه والشفافية والصبغة والتشبّع والحدّ، وانسخ الكود مع بادئة -webkit- ونسخة احتياطية.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "التصميم",
    tags: ["زجاجية", "css", "زجاج مصنفر", "backdrop-filter", "تصميم واجهات", "مولّد css"],
    readTime: 7,
    coverEmoji: "🧊",
    coverGradient: "from-cyan-500 to-blue-600",
  },
  {
    slug: "svg-blob-generator-guide",
    title: "SVG Blob Generator: Make Organic Shapes and Wave Dividers in Your Browser",
    description: "Create smooth, random organic blob shapes and SVG wave dividers with a free browser-based organic shape maker. Adjust complexity, randomness, and gradient fill, then copy or download clean SVG.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Design",
    tags: ["svg blob generator", "organic shape maker", "svg", "wave divider", "css", "web design"],
    readTime: 7,
    featured: true,
    coverEmoji: "🫧",
    coverGradient: "from-indigo-500 to-pink-500",
  },
  {
    slug: "svg-blob-generator-guide-ar",
    title: "مولّد أشكال SVG العضوية: اصنع أشكالاً عضوية وفواصل موجية في متصفحك",
    description: "أنشئ أشكالاً عضوية عشوائية ناعمة وفواصل موجية بصيغة SVG عبر أداة مجانية تعمل في المتصفح. اضبط التعقيد والعشوائية والتعبئة المتدرّجة، ثم انسخ أو نزّل كود SVG نظيفاً.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "التصميم",
    tags: ["مولد أشكال عضوية", "svg blob generator", "svg", "فاصل موجي", "تصميم ويب", "css"],
    readTime: 7,
    featured: true,
    coverEmoji: "🫧",
    coverGradient: "from-indigo-500 to-pink-500",
  },
  {
    slug: "periodic-table-guide",
    title: "The Interactive Periodic Table: A Complete Guide to All 118 Elements",
    description: "How the periodic table is organized, what each element category means, and how to read atomic number, mass, and electron configuration — with a free interactive periodic table you can search and explore in your browser.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Science & Education",
    tags: ["periodic table", "chemistry", "elements", "interactive periodic table", "science", "education"],
    readTime: 7,
    featured: true,
    coverEmoji: "⚛️",
    coverGradient: "from-sky-500 to-indigo-600",
  },
  {
    slug: "periodic-table-guide-ar",
    title: "الجدول الدوري التفاعلي: دليل شامل لجميع العناصر الـ118",
    description: "كيف يُنظَّم الجدول الدوري، وماذا تعني كل فئة من العناصر، وكيف تقرأ العدد الذري والكتلة والتوزيع الإلكتروني — مع جدول دوري تفاعلي مجاني تبحث فيه وتستكشفه داخل متصفحك.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "العلوم والتعليم",
    tags: ["الجدول الدوري", "كيمياء", "عناصر", "جدول دوري تفاعلي", "علوم", "تعليم"],
    readTime: 7,
    featured: true,
    coverEmoji: "⚛️",
    coverGradient: "from-sky-500 to-indigo-600",
  },
  {
    slug: "mind-map-maker-guide",
    title: "How to Make a Mind Map in Your Browser — Free, No Sign-Up",
    description: "Build interactive mind maps with a free online mind map maker that runs entirely in your browser. Add branches, connect ideas, color-code, and export as JSON or PNG. No install, no account.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Productivity",
    tags: ["mind map", "mind map maker", "brainstorming", "diagram", "productivity", "free online tool"],
    readTime: 8,
    featured: true,
    coverEmoji: "🧠",
    coverGradient: "from-violet-500 to-fuchsia-600",
  },
  {
    slug: "mind-map-maker-guide-ar",
    title: "كيف تصنع خريطة ذهنية في متصفحك — مجاناً وبدون تسجيل",
    description: "أنشئ خرائط ذهنية تفاعلية بصانع خرائط ذهنية مجاني يعمل بالكامل في متصفحك. أضف الفروع واربط الأفكار ولوّنها وصدّرها بصيغة JSON أو PNG. بدون تثبيت وبدون حساب.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "الإنتاجية",
    tags: ["خريطة ذهنية", "صانع خرائط ذهنية", "عصف ذهني", "مخطط", "إنتاجية", "أداة مجانية"],
    readTime: 8,
    featured: true,
    coverEmoji: "🧠",
    coverGradient: "from-violet-500 to-fuchsia-600",
  },
  {
    slug: "audio-transcriber-guide",
    title: "Transcribe Audio to Text Free — and Generate SRT Subtitles in Your Browser",
    description: "Transcribe audio and video to text free with on-device Whisper AI. No upload, no account. Generate SRT and VTT subtitles for any video, all in your browser.",
    date: "2026-05-22",
    author: "BrowseryTools Team",
    category: "AI Tools",
    tags: ["transcribe audio to text free", "audio to text", "generate subtitles", "SRT", "VTT", "whisper", "speech to text"],
    readTime: 8,
    featured: true,
    coverEmoji: "🎙️",
    coverGradient: "from-rose-500 to-orange-500",
  },
  {
    slug: "audio-transcriber-guide-ar",
    title: "فرّغ الصوت إلى نص مجاناً — وأنشئ ترجمات SRT في متصفحك",
    description: "فرّغ الصوت والفيديو إلى نص مجاناً عبر نموذج Whisper على جهازك. بدون رفع وبدون حساب. أنشئ ترجمات SRT وVTT لأي فيديو، كلّها داخل متصفحك.",
    date: "2026-05-22",
    author: "BrowseryTools Team",
    category: "أدوات الذكاء الاصطناعي",
    tags: ["تفريغ الصوت إلى نص", "صوت إلى نص", "إنشاء ترجمات", "SRT", "VTT", "ويسبر", "تحويل الكلام إلى نص"],
    readTime: 8,
    featured: true,
    coverEmoji: "🎙️",
    coverGradient: "from-rose-500 to-orange-500",
  },
  {
    slug: "image-upscaler-guide",
    title: "How to Upscale an Image Online for Free — AI Image Upscaler in Your Browser",
    description: "Increase image resolution 2x with a free AI image upscaler that runs entirely in your browser. Enhance photos, sharpen details, and upscale images online with no upload and no sign-up.",
    date: "2026-05-22",
    author: "BrowseryTools Team",
    category: "AI Tools",
    tags: ["upscale image online free", "increase image resolution", "ai image upscaler", "image enhancer", "super resolution", "free online tool"],
    readTime: 8,
    featured: true,
    coverEmoji: "🔍",
    coverGradient: "from-cyan-500 to-blue-600",
  },
  {
    slug: "image-upscaler-guide-ar",
    title: "كيف تكبّر صورة عبر الإنترنت مجاناً — مكبّر صور بالذكاء الاصطناعي في متصفحك",
    description: "ارفع دقة الصورة بمقدار الضعف باستخدام مكبّر صور مجاني بالذكاء الاصطناعي يعمل بالكامل في متصفحك. حسّن الصور وزِد وضوح التفاصيل وكبّر الصور عبر الإنترنت دون رفع ودون تسجيل.",
    date: "2026-05-22",
    author: "BrowseryTools Team",
    category: "أدوات الذكاء الاصطناعي",
    tags: ["تكبير الصور مجاناً", "رفع دقة الصورة", "مكبّر صور بالذكاء الاصطناعي", "تحسين الصور", "الدقة الفائقة", "أداة مجانية"],
    readTime: 8,
    featured: true,
    coverEmoji: "🔍",
    coverGradient: "from-cyan-500 to-blue-600",
  },
  {
    slug: "text-summarizer-guide",
    title: "How to Summarize Text Online for Free — with On-Device AI",
    description: "Paste long text and get a short AI summary in seconds with a free text summarizer that runs entirely in your browser. Choose short, medium, or long. No upload, no sign-up, fully private.",
    date: "2026-05-22",
    author: "BrowseryTools Team",
    category: "AI Tools",
    tags: ["text summarizer", "summarize text online free", "ai summary", "on-device ai", "privacy", "free online tool"],
    readTime: 8,
    featured: true,
    coverEmoji: "✂️",
    coverGradient: "from-sky-500 to-indigo-600",
  },
  {
    slug: "text-summarizer-guide-ar",
    title: "كيف تلخّص النصوص عبر الإنترنت مجاناً — بذكاء اصطناعي على جهازك",
    description: "الصق نصاً طويلاً واحصل على ملخّص ذكاء اصطناعي قصير خلال ثوانٍ بملخّص نصوص مجاني يعمل بالكامل في متصفحك. اختر قصيراً أو متوسطاً أو طويلاً. بدون رفع وبدون تسجيل وبخصوصية كاملة.",
    date: "2026-05-22",
    author: "BrowseryTools Team",
    category: "أدوات الذكاء الاصطناعي",
    tags: ["ملخّص النصوص", "تلخيص النصوص أونلاين مجاناً", "ملخص بالذكاء الاصطناعي", "ذكاء اصطناعي على الجهاز", "خصوصية", "أداة مجانية"],
    readTime: 8,
    featured: true,
    coverEmoji: "✂️",
    coverGradient: "from-sky-500 to-indigo-600",
  },
  {
    slug: "translator-guide",
    title: "Free Offline Translator: Translate Text in Your Browser, Privately",
    description: "Translate text between 15 languages with a free offline translator that runs an AI model in your browser. Private translation, no upload, no Google or DeepL — works even without a connection after the first download.",
    date: "2026-05-22",
    author: "BrowseryTools Team",
    category: "Text & Language",
    tags: ["free offline translator", "translate text in browser", "private translation", "on-device translation", "ai translator", "no upload"],
    readTime: 7,
    featured: true,
    coverEmoji: "🌐",
    coverGradient: "from-sky-500 to-indigo-600",
  },
  {
    slug: "translator-guide-ar",
    title: "مترجم مجاني يعمل دون اتصال: ترجم النصوص في متصفحك بخصوصية تامة",
    description: "ترجم النصوص بين 15 لغة عبر مترجم مجاني يعمل دون اتصال ويشغّل نموذج ذكاء اصطناعي في متصفحك. ترجمة خاصة بلا رفع وبلا غوغل أو DeepL — تعمل حتى دون اتصال بعد التنزيل الأول.",
    date: "2026-05-22",
    author: "BrowseryTools Team",
    category: "النصوص واللغة",
    tags: ["مترجم مجاني دون اتصال", "ترجمة النص في المتصفح", "ترجمة خاصة", "ترجمة على الجهاز", "مترجم ذكاء اصطناعي", "بدون رفع"],
    readTime: 7,
    featured: true,
    coverEmoji: "🌐",
    coverGradient: "from-sky-500 to-indigo-600",
  },
  {
    slug: "image-captioner-guide",
    title: "AI Image Caption Generator: Auto Alt Text for Accessibility & SEO",
    description: "Generate descriptive captions and ready-to-use alt text for any image with a free AI image caption generator that runs entirely in your browser. Improve accessibility and SEO — no upload, no account.",
    date: "2026-05-22",
    author: "BrowseryTools Team",
    category: "AI Tools",
    tags: ["image captioning", "alt text generator", "accessibility", "seo", "ai", "image to text"],
    readTime: 8,
    featured: true,
    coverEmoji: "🖼️",
    coverGradient: "from-cyan-500 to-blue-600",
  },
  {
    slug: "image-captioner-guide-ar",
    title: "مُولّد أوصاف الصور بالذكاء الاصطناعي: نص بديل تلقائي لإمكانية الوصول والسيو",
    description: "أنشئ أوصافاً تلقائية ونصاً بديلاً جاهزاً للاستخدام لأي صورة عبر مُولّد أوصاف صور مجاني يعمل بالكامل في متصفحك. حسّن إمكانية الوصول وتحسين محركات البحث — بدون رفع وبدون حساب.",
    date: "2026-05-22",
    author: "BrowseryTools Team",
    category: "أدوات الذكاء الاصطناعي",
    tags: ["وصف الصور", "مولد نص بديل", "إمكانية الوصول", "سيو", "ذكاء اصطناعي", "صورة إلى نص"],
    readTime: 8,
    featured: true,
    coverEmoji: "🖼️",
    coverGradient: "from-cyan-500 to-blue-600",
  },
  {
    slug: "pii-redactor-guide",
    title: "How to Redact PII and Remove Personal Info From Text — Free, In Your Browser",
    description: "Detect and redact PII — names, emails, phone numbers, locations, credit cards, and IPs — with a free online tool that anonymizes text entirely in your browser. No upload, no account.",
    date: "2026-05-22",
    author: "BrowseryTools Team",
    category: "Privacy",
    tags: ["redact pii", "remove personal info from text", "anonymize text online", "pii detector", "data privacy", "free online tool"],
    readTime: 7,
    featured: true,
    coverEmoji: "🛡️",
    coverGradient: "from-emerald-500 to-teal-600",
  },
  {
    slug: "pii-redactor-guide-ar",
    title: "كيف تحجب المعلومات الشخصية وتزيلها من النص — مجاناً وداخل متصفحك",
    description: "اكشف واحجب المعلومات الشخصية — الأسماء والبُرُد الإلكترونية وأرقام الهواتف والمواقع وبطاقات الائتمان وعناوين IP — بأداة مجانية تُخفي هوية النص بالكامل داخل متصفحك. بدون رفع وبدون حساب.",
    date: "2026-05-22",
    author: "BrowseryTools Team",
    category: "الخصوصية",
    tags: ["حجب المعلومات الشخصية", "إزالة المعلومات الشخصية من النص", "إخفاء هوية النص", "كاشف المعلومات الشخصية", "خصوصية البيانات", "أداة مجانية"],
    readTime: 7,
    featured: true,
    coverEmoji: "🛡️",
    coverGradient: "from-emerald-500 to-teal-600",
  },
  {
    slug: "depth-map-guide",
    title: "How to Generate a Depth Map from Any Image — Free, In Your Browser",
    description: "Turn any photo into a depth map with a free AI depth map generator that runs entirely in your browser. Image to depth map with grayscale or colormap output, downloadable PNG. No upload, no install.",
    date: "2026-05-22",
    author: "BrowseryTools Team",
    category: "AI Tools",
    tags: ["depth map generator", "image to depth map", "ai depth estimation", "depth map", "monocular depth", "free online tool"],
    readTime: 8,
    featured: true,
    coverEmoji: "🏔️",
    coverGradient: "from-cyan-500 to-blue-600",
  },
  {
    slug: "depth-map-guide-ar",
    title: "كيف تُنشئ خريطة عمق من أي صورة — مجاناً وداخل متصفحك",
    description: "حوّل أي صورة إلى خريطة عمق بمولّد خرائط عمق مجاني يعمل بالكامل داخل متصفحك. تحويل الصورة إلى خريطة عمق بمخرجات رمادية أو خريطة ألوان، بصيغة PNG قابلة للتنزيل. بدون رفع وبدون تثبيت.",
    date: "2026-05-22",
    author: "BrowseryTools Team",
    category: "أدوات الذكاء الاصطناعي",
    tags: ["مولّد خرائط العمق", "صورة إلى خريطة عمق", "تقدير العمق بالذكاء الاصطناعي", "خريطة عمق", "عمق أحادي", "أداة مجانية"],
    readTime: 8,
    featured: true,
    coverEmoji: "🏔️",
    coverGradient: "from-cyan-500 to-blue-600",
  },
  {
    slug: "zero-shot-classifier-guide",
    title: "Zero-Shot Text Classification: Classify Text With Custom Labels, No Training",
    description: "Sort any text into your own labels with zero-shot text classification — no training data, no upload. A free AI text categorization tool that runs entirely in your browser.",
    date: "2026-05-22",
    author: "BrowseryTools Team",
    category: "AI Tools",
    tags: ["zero-shot classification", "text classification", "AI text categorization", "custom labels", "on-device AI", "free tool"],
    readTime: 7,
    featured: true,
    coverEmoji: "🏷️",
    coverGradient: "from-sky-500 to-indigo-600",
  },
  {
    slug: "zero-shot-classifier-guide-ar",
    title: "التصنيف دون تدريب: صنّف النص بتصنيفاتٍ مخصصة دون تدريب",
    description: "افرز أي نص ضمن تصنيفاتك الخاصة بالتصنيف دون تدريب — دون بيانات تدريب ودون رفع. أداة تصنيف نصوص بالذكاء الاصطناعي مجانية تعمل بالكامل في متصفحك.",
    date: "2026-05-22",
    author: "BrowseryTools Team",
    category: "أدوات الذكاء الاصطناعي",
    tags: ["تصنيف دون تدريب", "تصنيف النصوص", "تصنيف بالذكاء الاصطناعي", "تصنيفات مخصصة", "ذكاء اصطناعي على الجهاز", "أداة مجانية"],
    readTime: 7,
    featured: true,
    coverEmoji: "🏷️",
    coverGradient: "from-sky-500 to-indigo-600",
  },
  {
    slug: "object-cutout-guide",
    title: "How to Cut Out an Object from an Image in Your Browser — AI, Free, No Upload",
    description: "Cut out an object from a photo with one click using AI image segmentation. Click the object, get a transparent PNG, or remove an object from a photo — all in your browser, nothing uploaded.",
    date: "2026-05-22",
    author: "BrowseryTools Team",
    category: "AI",
    tags: ["cut out object from image", "ai image segmentation", "remove object from photo", "transparent png", "segment anything", "background removal"],
    readTime: 7,
    featured: true,
    coverEmoji: "✂️",
    coverGradient: "from-rose-500 to-orange-500",
  },
  {
    slug: "object-cutout-guide-ar",
    title: "كيف تقتطع كائناً من صورة داخل متصفحك — بالذكاء الاصطناعي ومجاناً وبدون رفع",
    description: "اقتطع كائناً من صورة بنقرة واحدة باستخدام تقطيع الصور بالذكاء الاصطناعي. انقر على الكائن لتحصل على PNG شفافة، أو أزِل كائناً من صورة — كل ذلك داخل متصفحك دون رفع أي شيء.",
    date: "2026-05-22",
    author: "BrowseryTools Team",
    category: "الذكاء الاصطناعي",
    tags: ["اقتطاع كائن من صورة", "تقطيع الصور بالذكاء الاصطناعي", "إزالة كائن من صورة", "صورة شفافة", "segment anything", "إزالة الخلفية"],
    readTime: 7,
    featured: true,
    coverEmoji: "✂️",
    coverGradient: "from-rose-500 to-orange-500",
  }
];

export function getBlogPost(slug: string): BlogPost | undefined {
  return blogPosts.find((p) => p.slug === slug);
}

export function getFeaturedPosts(): BlogPost[] {
  return blogPosts.filter((p) => p.featured);
}

export function getPostsByCategory(category: string): BlogPost[] {
  return blogPosts.filter((p) => p.category === category);
}

export function getAllCategories(): string[] {
  return [...new Set(blogPosts.map((p) => p.category))];
}
