import type { BlogPost } from "./blog-data";

export const frPostsB5: BlogPost[] = [
  {
    slug: "expense-tracker-guide-fr",
    title: "Suivez vos dépenses mensuelles sans applications, abonnements ni stockage cloud",
    description: "La plupart des gens ignorent où va leur argent. Découvrez la règle budgétaire 50/30/20, la différence entre charges fixes et variables, et comment effectuer un bilan mensuel des dépenses — sans inscription nulle part.",
    date: "2026-03-16",
    author: "BrowseryTools Team",
    category: "Productivité",
    tags: ["suivi des dépenses", "budget", "finances personnelles", "gestion de l'argent"],
    readTime: 7,
    coverEmoji: "💸",
    coverGradient: "from-emerald-500 to-green-600",
    locale: "fr",
  },
  {
    slug: "invoice-generator-guide-fr",
    title: "Comment créer des factures professionnelles gratuitement — sans abonnement",
    description: "Guide complet de la facturation professionnelle : champs obligatoires, conventions de numérotation, conditions de paiement Net 30, pénalités de retard, exigences TVA et TPS par pays, et pourquoi un outil PDF gratuit vaut mieux qu'un abonnement à 100 €/an.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Business",
    tags: ["facture", "freelance", "facturation", "conditions de paiement", "PDF"],
    readTime: 7,
    coverEmoji: "🧾",
    coverGradient: "from-violet-500 to-purple-600",
    locale: "fr",
  },
  {
    slug: "loan-calculator-guide-fr",
    title: "Calculateur de prêt : comprendre votre crédit immobilier, auto ou personnel",
    description: "La formule de calcul des mensualités expliquée, l'amortissement démystifié (pourquoi les premières mensualités sont surtout des intérêts), TAEG vs taux d'intérêt, comment les remboursements supplémentaires économisent des milliers, et comment vraiment comparer les offres de prêt.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Finance",
    tags: ["calculateur de prêt", "crédit immobilier", "amortissement", "TAEG", "finances personnelles"],
    readTime: 8,
    coverEmoji: "🏦",
    coverGradient: "from-blue-500 to-cyan-600",
    locale: "fr",
  },
  {
    slug: "currency-converter-guide-fr",
    title: "Comment fonctionnent les taux de change : guide pratique",
    description: "Ce qui détermine les taux de change, le spread bid/ask, pourquoi vous n'obtenez jamais le taux interbancaire, comment les banques et cartes de crédit cachent leurs frais dans les spreads, et les pièges monétaires qui piègent voyageurs et freelances internationaux.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Finance",
    tags: ["convertisseur de devises", "taux de change", "forex", "voyage", "paiements internationaux"],
    readTime: 7,
    coverEmoji: "💱",
    coverGradient: "from-amber-500 to-orange-500",
    locale: "fr",
  },
  {
    slug: "timezone-guide-fr",
    title: "Travailler sur plusieurs fuseaux horaires : guide complet pour les équipes à distance",
    description: "Comment fonctionnent les décalages UTC, pourquoi l'heure d'été rend la planification sujette aux erreurs, bonnes pratiques pour les réunions d'équipes à distance, format de date ISO 8601, et la règle d'or pour les développeurs : toujours stocker les horodatages en UTC.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Productivité",
    tags: ["fuseau horaire", "travail à distance", "UTC", "planification", "ISO 8601", "développeurs"],
    readTime: 8,
    coverEmoji: "🌐",
    coverGradient: "from-purple-500 to-violet-600",
    locale: "fr",
  },
  {
    slug: "compress-video-online-free-fr",
    title: "Comment compresser une vidéo en ligne gratuitement (sans envoi, sans filigrane)",
    description: "Réduisez la taille d'un fichier vidéo directement dans votre navigateur — gratuit, sans compte, sans filigrane, rien n'est uploadé. Découvrez les paramètres de débit, résolution et codec qui réduisent réellement une vidéo, plus les meilleurs préréglages pour l'e-mail, les réseaux sociaux et le web.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Outils multimédia",
    tags: ["compresser vidéo en ligne gratuit", "réduire la taille vidéo", "compresseur vidéo", "sans envoi", "gratuit"],
    readTime: 7,
    coverEmoji: "🎬",
    coverGradient: "from-rose-500 to-red-600",
    locale: "fr",
  },
  {
    slug: "redact-image-online-fr",
    title: "Comment masquer ou censurer une image en ligne (flouter les visages et cacher les infos sensibles)",
    description: "Floutez les visages, pixélisez les plaques d'immatriculation et masquez les détails sensibles dans toute image — entièrement dans votre navigateur, sans rien uploader. Découvrez quel style de censure est vraiment irréversible et l'erreur de métadonnées qui fait fuiter discrètement les données censurées.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Outils image",
    tags: ["masquer image", "flouter visages", "censurer photo", "cacher infos sensibles", "pixéliser", "confidentialité"],
    readTime: 7,
    coverEmoji: "🖍️",
    coverGradient: "from-slate-500 to-gray-700",
    locale: "fr",
  },
  {
    slug: "roman-numeral-converter-guide-fr",
    title: "Convertisseur de chiffres romains : comment fonctionnent les chiffres romains (et comment lire MCMXCIV)",
    description: "Les sept symboles, les règles d'addition et de soustraction, les six paires soustractives valides, et les erreurs courantes — tout ce qu'il faut pour lire et écrire les chiffres romains, plus un convertisseur gratuit dans les deux sens.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Calculatrices",
    tags: ["chiffres romains", "convertisseur chiffres romains", "MCMXCIV", "comment fonctionnent les chiffres romains"],
    readTime: 7,
    coverEmoji: "🏛️",
    coverGradient: "from-amber-500 to-yellow-600",
    locale: "fr",
  },
  {
    slug: "convert-svg-to-png-fr",
    title: "Comment convertir un SVG en PNG (garder la netteté et la transparence)",
    description: "Transformez des fichiers SVG vectoriels en images PNG universelles directement dans votre navigateur — gratuit, sans envoi, sans filigrane. Apprenez à choisir la bonne résolution d'export pour éviter le flou, et comment conserver un fond transparent.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Outils image",
    tags: ["convertir svg en png", "svg vers png", "vecteur vers matriciel", "png transparent", "exporter svg", "gratuit"],
    readTime: 7,
    coverEmoji: "🖼️",
    coverGradient: "from-cyan-500 to-blue-600",
    locale: "fr",
  },
  {
    slug: "convert-video-to-gif-fr",
    title: "Comment convertir une vidéo en GIF (et garder le fichier léger)",
    description: "Transformez un clip MP4 ou MOV en GIF en boucle directement dans votre navigateur — sans envoi, sans filigrane. Découvrez pourquoi les GIFs grossissent vite, les trois paramètres pour les garder légers, et quand une courte vidéo est préférable à un GIF.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Outils multimédia",
    tags: ["convertir vidéo en gif", "vidéo vers gif", "mp4 en gif", "créer un gif", "sans envoi", "gratuit"],
    readTime: 6,
    coverEmoji: "🎞️",
    coverGradient: "from-fuchsia-500 to-pink-600",
    locale: "fr",
  },
  {
    slug: "crop-and-watermark-images-online-fr",
    title: "Comment recadrer et ajouter un filigrane en ligne (gratuit, sans envoi)",
    description: "Recadrez à un rapport d'aspect précis, redimensionnez sans distorsion, et ajoutez un filigrane qui dissuade vraiment la réutilisation — tout dans votre navigateur, sans que l'original ne soit jamais uploadé. Inclut l'erreur de rapport d'aspect qui étire vos photos.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Outils image",
    tags: ["recadrer image en ligne", "filigrane image", "redimensionner image", "rapport d'aspect", "sans envoi", "gratuit"],
    readTime: 7,
    coverEmoji: "✂️",
    coverGradient: "from-teal-500 to-emerald-600",
    locale: "fr",
  },
  {
    slug: "curl-to-fetch-python-code-fr",
    title: "Comment convertir cURL en code (fetch, Python requests, Node.js)",
    description: "Collez une commande cURL et obtenez du code JavaScript fetch, Python requests ou Node.js fonctionnel — y compris l'astuce DevTools 'Copier en tant que cURL'. Apprenez comment chaque option correspond au code pour pouvoir valider le résultat, tout traité localement dans votre navigateur.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Outils pour développeurs",
    tags: ["curl en code", "curl vers fetch", "curl vers python", "convertir curl", "copier en tant que curl", "api"],
    readTime: 7,
    coverEmoji: "🔁",
    coverGradient: "from-indigo-500 to-violet-600",
    locale: "fr",
  },
  {
    slug: "scientific-calculator-online-fr",
    title: "Calculatrice scientifique en ligne : trigonométrie, logarithmes, puissances et erreurs à éviter",
    description: "Une calculatrice scientifique gratuite dans le navigateur avec sin, cos, tan, log, ln, puissances, racines et constantes. Découvrez le piège degrés/radians, l'ordre des opérations, et des exemples résolus pour les intérêts composés, les triangles et le pH.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Calculatrices",
    tags: ["calculatrice scientifique en ligne", "calculatrice graphique", "calculatrice trigonométrique", "calculatrice log", "calculatrice gratuite"],
    readTime: 7,
    coverEmoji: "🧮",
    coverGradient: "from-blue-500 to-indigo-600",
    locale: "fr",
  },
  {
    slug: "random-picker-guide-fr",
    title: "Sélecteur aléatoire : nombres aléatoires, dés, pile ou face et roue de noms",
    description: "Générez des nombres aléatoires, lancez des dés, faites un pile ou face, ou choisissez un gagnant équitable dans une liste — gratuit et dans votre navigateur. Apprenez à organiser un tirage au sort sans biais et quand l'aléatoire est vraiment aléatoire.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Outils de productivité",
    tags: ["générateur de nombres aléatoires", "sélecteur de noms aléatoire", "lanceur de dés", "pile ou face", "roue de noms", "concours"],
    readTime: 6,
    coverEmoji: "🎲",
    coverGradient: "from-violet-500 to-purple-600",
    locale: "fr",
  },
];
