import type { BlogPost } from "./blog-data";

export const esPostsB5: BlogPost[] = [
  {
    slug: "expense-tracker-guide-es",
    title: "Controla Tus Gastos Mensuales Sin Apps, Suscripciones Ni Almacenamiento en la Nube",
    description:
      "La mayoría de las personas no sabe adónde va su dinero. Aprende la regla presupuestaria 50/30/20, la diferencia entre gastos fijos y variables y cómo llevar a cabo una revisión mensual de gastos sin registrarte en nada.",
    date: "2026-03-16",
    author: "BrowseryTools Team",
    category: "Productividad",
    tags: ["rastreador de gastos", "presupuesto", "finanzas personales", "gestión del dinero"],
    readTime: 7,
    coverEmoji: "💸",
    coverGradient: "from-emerald-500 to-green-600",
    locale: "es",
  },
  {
    slug: "invoice-generator-guide-es",
    title: "Cómo Crear Facturas Profesionales de Forma Gratuita — Sin Suscripciones",
    description:
      "Guía completa sobre facturación profesional: campos obligatorios, convenciones de numeración, condiciones de pago como Neto 30, cláusulas de recargo por retraso, requisitos de IVA y GST por país, y por qué una herramienta PDF gratuita supera a una suscripción de 100 €/año.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Negocios",
    tags: ["factura", "trabajo autónomo", "facturación", "condiciones de pago", "PDF"],
    readTime: 7,
    coverEmoji: "🧾",
    coverGradient: "from-violet-500 to-purple-600",
    locale: "es",
  },
  {
    slug: "loan-calculator-guide-es",
    title: "Calculadora de Préstamos: Entiende Tu Hipoteca, Préstamo de Coche o Préstamo Personal",
    description:
      "La fórmula de cuota de préstamo explicada, la amortización desmitificada (por qué los pagos iniciales son mayoritariamente intereses), TAE vs. tipo de interés, cómo los pagos adicionales ahorran miles y cómo comparar realmente las ofertas de préstamos.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Finanzas",
    tags: ["calculadora de préstamos", "hipoteca", "amortización", "TAE", "finanzas personales"],
    readTime: 8,
    coverEmoji: "🏦",
    coverGradient: "from-blue-500 to-cyan-600",
    locale: "es",
  },
  {
    slug: "currency-converter-guide-es",
    title: "Cómo Funcionan los Tipos de Cambio: Una Guía Práctica",
    description:
      "Qué impulsa los tipos de cambio, el diferencial comprador/vendedor, por qué nunca obtienes el tipo interbancario, cómo bancos y tarjetas ocultan comisiones en los diferenciales y las trampas de divisas que afectan a viajeros y autónomos internacionales.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Finanzas",
    tags: ["convertidor de divisas", "tipos de cambio", "forex", "viajes", "pagos internacionales"],
    readTime: 7,
    coverEmoji: "💱",
    coverGradient: "from-amber-500 to-orange-500",
    locale: "es",
  },
  {
    slug: "timezone-guide-es",
    title: "Trabajar Entre Zonas Horarias: Guía Completa para Equipos Remotos",
    description:
      "Cómo funcionan los desplazamientos UTC, por qué el horario de verano hace la programación propensa a errores, mejores prácticas para la planificación de reuniones de equipos remotos, el formato datetime ISO 8601 y la regla de oro para desarrolladores: almacena siempre las marcas de tiempo en UTC.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Productividad",
    tags: ["zona horaria", "trabajo remoto", "UTC", "planificación", "ISO 8601", "desarrolladores"],
    readTime: 8,
    coverEmoji: "🌐",
    coverGradient: "from-purple-500 to-violet-600",
    locale: "es",
  },
  {
    slug: "compress-video-online-free-es",
    title: "Cómo Comprimir Vídeo Online de Forma Gratuita (Sin Subidas, Sin Marca de Agua)",
    description:
      "Reduce el tamaño de los archivos de vídeo directamente en tu navegador — gratis, sin cuenta, sin marca de agua, sin nada subido. Aprende los ajustes de tasa de bits, resolución y códec que realmente reducen un vídeo, más los mejores ajustes preestablecidos para correo electrónico, redes sociales y la web.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Herramientas Multimedia",
    tags: ["comprimir vídeo online gratis", "reducir tamaño vídeo", "compresor de vídeo", "reducir vídeo", "sin subida", "gratis"],
    readTime: 7,
    coverEmoji: "🎬",
    coverGradient: "from-rose-500 to-red-600",
    locale: "es",
  },
  {
    slug: "redact-image-online-es",
    title: "Cómo Redactar o Censurar una Imagen Online (Difuminar Caras y Ocultar Información Sensible)",
    description:
      "Difumina caras, pixela matrículas y tapa detalles sensibles en cualquier imagen — completamente en tu navegador, sin nada subido. Aprende qué estilo de censura es verdaderamente irreversible y el error de metadatos que filtra silenciosamente los datos redactados.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Herramientas de Imagen",
    tags: ["redactar imagen", "difuminar caras", "censurar foto", "ocultar información sensible", "pixelar", "privacidad"],
    readTime: 7,
    coverEmoji: "🖍️",
    coverGradient: "from-slate-500 to-gray-700",
    locale: "es",
  },
  {
    slug: "roman-numeral-converter-guide-es",
    title: "Conversor de Números Romanos: Cómo Funcionan (y Cómo Leer MCMXCIV)",
    description:
      "Los siete símbolos, las reglas de suma y resta, los seis pares sustractivos válidos y los errores comunes — todo lo que necesitas para leer y escribir números romanos, más un conversor gratuito que funciona en ambas direcciones.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Calculadoras",
    tags: ["números romanos", "conversor de números romanos", "MCMXCIV", "cómo funcionan los números romanos", "conversor de números"],
    readTime: 7,
    coverEmoji: "🏛️",
    coverGradient: "from-amber-500 to-yellow-600",
    locale: "es",
  },
  {
    slug: "convert-svg-to-png-es",
    title: "Cómo Convertir SVG a PNG (Mantenerlo Nítido y Transparente)",
    description:
      "Convierte archivos SVG vectoriales a imágenes PNG universales directamente en tu navegador — gratis, sin subida, sin marca de agua. Aprende cómo elegir la resolución de exportación correcta para que nunca quede borroso y cómo conservar el fondo transparente.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Herramientas de Imagen",
    tags: ["convertir svg a png", "svg a png", "vector a rasterizado", "png transparente", "exportar svg", "gratis"],
    readTime: 7,
    coverEmoji: "🖼️",
    coverGradient: "from-cyan-500 to-blue-600",
    locale: "es",
  },
  {
    slug: "convert-video-to-gif-es",
    title: "Cómo Convertir Vídeo a GIF (y Mantener el Archivo Pequeño)",
    description:
      "Convierte un clip MP4 o MOV en un GIF en bucle directamente en tu navegador — sin subida, sin marca de agua. Aprende por qué los GIFs crecen en tamaño, los tres ajustes que los mantienen pequeños y cuándo un vídeo corto supera a un GIF.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Herramientas Multimedia",
    tags: ["convertir vídeo a gif", "vídeo a gif", "mp4 a gif", "crear gif", "sin subida", "gratis"],
    readTime: 6,
    coverEmoji: "🎞️",
    coverGradient: "from-fuchsia-500 to-pink-600",
    locale: "es",
  },
  {
    slug: "crop-and-watermark-images-online-es",
    title: "Cómo Recortar y Añadir Marcas de Agua a Imágenes Online (Gratis, Sin Subidas)",
    description:
      "Recorta a una proporción de aspecto precisa, redimensiona sin distorsión y añade una marca de agua que realmente disuade la reutilización — todo en tu navegador, sin que el original se suba nunca. Incluye el error de proporción de aspecto que estira tus fotos.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Herramientas de Imagen",
    tags: ["recortar imagen online", "marca de agua en imagen", "redimensionar imagen", "proporción de aspecto", "sin subida", "gratis"],
    readTime: 7,
    coverEmoji: "✂️",
    coverGradient: "from-teal-500 to-emerald-600",
    locale: "es",
  },
  {
    slug: "curl-to-fetch-python-code-es",
    title: "Cómo Convertir cURL a Código (fetch, Python requests, Node.js)",
    description:
      "Pega un comando cURL y obtén código JavaScript fetch, Python requests o Node.js funcional — incluido el truco de 'Copiar como cURL' de las DevTools. Aprende cómo se mapea cada opción al código para confiar en la salida, todo procesado localmente en tu navegador.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Herramientas para Desarrolladores",
    tags: ["curl a código", "curl a fetch", "curl a python", "convertir curl", "copiar como curl", "api"],
    readTime: 7,
    coverEmoji: "🔁",
    coverGradient: "from-indigo-500 to-violet-600",
    locale: "es",
  },
  {
    slug: "scientific-calculator-online-es",
    title: "Calculadora Científica Online: Trigonometría, Logaritmos, Potencias y los Errores a Evitar",
    description:
      "Una calculadora científica gratuita en el navegador con sin, cos, tan, log, ln, potencias, raíces y constantes. Aprende la trampa de grados vs. radianes, el orden de operaciones y ejemplos prácticos para interés compuesto, triángulos y pH.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Calculadoras",
    tags: ["calculadora científica online", "calculadora gráfica", "calculadora trigonométrica", "calculadora de logaritmos", "calculadora gratuita"],
    readTime: 7,
    coverEmoji: "🧮",
    coverGradient: "from-blue-500 to-indigo-600",
    locale: "es",
  },
  {
    slug: "random-picker-guide-es",
    title: "Selector Aleatorio: Números Aleatorios, Dados, Lanzamiento de Moneda y Ruleta de Nombres",
    description:
      "Genera números aleatorios, lanza dados, tira una moneda o elige un ganador justo de una lista — gratis y en tu navegador. Aprende cómo realizar un sorteo imparcial y cuándo la aleatoriedad es realmente aleatoria.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Herramientas de Productividad",
    tags: ["generador de números aleatorios", "selector de nombres aleatorio", "lanzador de dados", "lanzamiento de moneda", "ruleta de nombres", "sorteo"],
    readTime: 6,
    coverEmoji: "🎲",
    coverGradient: "from-violet-500 to-purple-600",
    locale: "es",
  },
];
