import type { BlogPost } from "./blog-data";

export const ruPostsB2: BlogPost[] = [
  {
    slug: "password-security-guide-ru",
    title: "Безопасность паролей: почему большинство паролей слабые и как создавать надёжные",
    description:
      "Многие используют слабые пароли, сами того не замечая. Узнайте, что делает пароль надёжным, как мгновенно проверить свой и сгенерировать невзламываемые — всё приватно в браузере.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Безопасность",
    tags: ["пароль", "безопасность", "взлом", "генератор паролей", "надёжность пароля"],
    readTime: 8,
    featured: false,
    coverEmoji: "🛡️",
    coverGradient: "from-green-500 to-emerald-600",
    locale: "ru",
  },
  {
    slug: "remove-image-background-free-ru",
    title: "Как бесплатно удалить фон с изображения — без Canva и Photoshop",
    description:
      "Удаляйте фон с фотографий мгновенно с помощью ИИ прямо в браузере. Без загрузок, подписок и водяных знаков. Ваши изображения никогда не покидают устройство.",
    date: "2026-02-12",
    author: "BrowseryTools Team",
    category: "Инструменты для изображений",
    tags: ["удаление фона", "редактирование изображений", "ИИ", "бесплатно", "без загрузки", "приватность"],
    readTime: 6,
    featured: false,
    coverEmoji: "🖼️",
    coverGradient: "from-pink-500 to-rose-600",
    locale: "ru",
  },
  {
    slug: "boost-productivity-pomodoro-todo-ru",
    title: "10 способов повысить продуктивность с помощью бесплатных браузерных инструментов",
    description:
      "От таймера Pomodoro до списков задач, от мирового времени до учёта расходов — откройте для себя инструменты продуктивности, работающие полностью в браузере без сбора данных.",
    date: "2026-02-10",
    author: "BrowseryTools Team",
    category: "Продуктивность",
    tags: ["продуктивность", "pomodoro", "список задач", "фокус", "управление временем"],
    readTime: 7,
    featured: false,
    coverEmoji: "🎯",
    coverGradient: "from-blue-500 to-cyan-600",
    locale: "ru",
  },
  {
    slug: "free-image-tools-guide-ru",
    title: "Полное руководство по бесплатным инструментам для изображений — сжатие, конвертация, изменение размера без загрузки",
    description:
      "Сжатие изображений, конвертация форматов, изменение размера, цветокоррекция и удаление фона — всё обрабатывается локально в браузере, без загрузок и бесплатно.",
    date: "2026-02-08",
    author: "BrowseryTools Team",
    category: "Инструменты для изображений",
    tags: ["сжатие изображений", "конвертер изображений", "изменение размера", "бесплатно", "без загрузки"],
    readTime: 8,
    featured: false,
    coverEmoji: "🎨",
    coverGradient: "from-violet-500 to-fuchsia-600",
    locale: "ru",
  },
  {
    slug: "qr-code-generator-guide-ru",
    title: "Как бесплатно создавать QR-коды — для ссылок, текста, Wi-Fi и визиток",
    description:
      "Создавайте неограниченное количество QR-кодов для любого содержимого — URL, обычный текст, данные Wi-Fi, vCard — с полной настройкой. 100% бесплатно, без регистрации, работает офлайн.",
    date: "2026-02-05",
    author: "BrowseryTools Team",
    category: "Полезные инструменты",
    tags: ["QR-код", "генератор QR", "бесплатный QR-код", "офлайн", "визитка"],
    readTime: 5,
    featured: false,
    coverEmoji: "📱",
    coverGradient: "from-teal-500 to-green-600",
    locale: "ru",
  },
  {
    slug: "text-tools-for-writers-developers-ru",
    title: "Лучшие бесплатные текстовые инструменты для авторов, разработчиков и создателей контента",
    description:
      "Конвертер регистра текста, генератор Lorem ipsum, счётчик символов, инструмент сравнения текста, редактор Markdown и многое другое. Всё, что нужно автору или разработчику — бесплатно и приватно.",
    date: "2026-02-03",
    author: "BrowseryTools Team",
    category: "Текстовые инструменты",
    tags: ["текстовые инструменты", "письмо", "markdown", "конвертер текста", "lorem ipsum"],
    readTime: 6,
    featured: false,
    coverEmoji: "✍️",
    coverGradient: "from-slate-500 to-gray-600",
    locale: "ru",
  },
  {
    slug: "base64-encoding-guide-ru",
    title: "Что такое кодирование Base64? Полное руководство с примерами",
    description:
      "Узнайте, что такое кодирование Base64, зачем оно нужно, где используется и как мгновенно кодировать и декодировать строки Base64 в браузере — без установки программ.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Инструменты разработчика",
    tags: ["base64", "кодирование", "разработчик", "двоичные данные", "форматы данных"],
    readTime: 7,
    featured: false,
    coverEmoji: "🔡",
    coverGradient: "from-cyan-500 to-blue-600",
    locale: "ru",
  },
  {
    slug: "jwt-decoder-guide-ru",
    title: "Как декодировать и проверять JWT-токены в браузере",
    description:
      "JWT-токены повсюду в современной аутентификации. Узнайте, что они содержат, как их декодировать, выявлять проблемы с истечением срока и отлаживать ошибки авторизации — всё приватно в браузере.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Инструменты разработчика",
    tags: ["JWT", "аутентификация", "токен", "OAuth", "безопасность", "разработчик"],
    readTime: 8,
    featured: false,
    coverEmoji: "🔑",
    coverGradient: "from-yellow-500 to-amber-600",
    locale: "ru",
  },
  {
    slug: "css-gradient-generator-guide-ru",
    title: "Генератор CSS-градиентов: создавайте красивые градиенты без написания кода",
    description:
      "Визуально создавайте линейные, радиальные и конические CSS-градиенты с предпросмотром в реальном времени. Копируйте готовый к работе CSS одним кликом — без дизайнерских программ.",
    date: "2026-02-20",
    author: "BrowseryTools Team",
    category: "Инструменты дизайна",
    tags: ["CSS", "градиент", "дизайн", "фронтенд", "UI", "цвета"],
    readTime: 5,
    featured: false,
    coverEmoji: "🌈",
    coverGradient: "from-purple-500 to-pink-600",
    locale: "ru",
  },
  {
    slug: "hash-generator-guide-ru",
    title: "MD5, SHA-256, SHA-512: бесплатный генератор хешей и когда использовать каждый",
    description:
      "Поймите разницу между MD5, SHA-1, SHA-256 и SHA-512. Мгновенно генерируйте хеши файлов и текста в браузере. Узнайте, когда уместен каждый алгоритм.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Безопасность",
    tags: ["хеш", "MD5", "SHA-256", "SHA-512", "контрольная сумма", "криптография"],
    readTime: 7,
    featured: false,
    coverEmoji: "#️⃣",
    coverGradient: "from-gray-500 to-slate-700",
    locale: "ru",
  },
  {
    slug: "screen-recorder-guide-ru",
    title: "Запись экрана без установки программ",
    description:
      "Ваш браузер может записывать экран, окно или вкладку с помощью Screen Capture API. Узнайте, как снимать видео для туториалов, отчётов об ошибках и демонстраций — без расширений.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Полезные инструменты",
    tags: ["запись экрана", "захват экрана", "туториал", "видео", "браузерный API"],
    readTime: 5,
    featured: false,
    coverEmoji: "🎬",
    coverGradient: "from-red-500 to-rose-600",
    locale: "ru",
  },
  {
    slug: "fake-data-generator-guide-ru",
    title: "Как бесплатно генерировать реалистичные тестовые данные (JSON и CSV)",
    description:
      "Наполняйте базы данных, прототипируйте интерфейсы и пишите тесты с реалистичными вымышленными именами, e-mail, адресами, телефонами и не только — экспорт в JSON или CSV, всё в браузере.",
    date: "2026-02-16",
    author: "BrowseryTools Team",
    category: "Инструменты разработчика",
    tags: ["вымышленные данные", "тестовые данные", "mock-данные", "JSON", "CSV", "инструменты разработчика"],
    readTime: 6,
    featured: false,
    coverEmoji: "🤖",
    coverGradient: "from-green-500 to-teal-600",
    locale: "ru",
  },
  {
    slug: "cron-expression-guide-ru",
    title: "Cron-выражения простым языком: как читать и писать расписания cron",
    description:
      "Синтаксис cron кажется загадочным, пока не разберёшься в пяти полях. Научитесь читать и писать cron-выражения, избегать частых ошибок и мгновенно разбирать любое расписание в браузере.",
    date: "2026-02-14",
    author: "BrowseryTools Team",
    category: "Инструменты разработчика",
    tags: ["cron", "cron-выражение", "планировщик", "DevOps", "автоматизация", "Linux"],
    readTime: 7,
    featured: false,
    coverEmoji: "⏰",
    coverGradient: "from-orange-500 to-red-600",
    locale: "ru",
  },
  {
    slug: "bmi-calculator-guide-ru",
    title: "Калькулятор ИМТ: что это, как его рассчитать и что он действительно означает",
    description:
      "Мгновенно рассчитайте свой ИМТ в метрических или имперских единицах. Поймите, что означает это число, его ограничения и каким бывает здоровый вес для вашего роста.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Здоровье и фитнес",
    tags: ["ИМТ", "индекс массы тела", "здоровье", "вес", "калькулятор"],
    readTime: 6,
    featured: false,
    coverEmoji: "⚖️",
    coverGradient: "from-teal-500 to-cyan-600",
    locale: "ru",
  },
];
