import type { BlogPost } from "./blog-data";

export const ruPostsB3: BlogPost[] = [
  {
    slug: "color-contrast-accessibility-guide-ru",
    title: "Контрастность цветов и доступность: руководство по WCAG",
    description:
      "Полное руководство по требованиям WCAG к контрастности цветов, соотношениям для обычного и крупного текста, а также инструментам проверки доступности.",
    date: "2026-02-23",
    author: "BrowseryTools",
    category: "Инструменты дизайна",
    tags: ["доступность", "WCAG", "контрастность цветов", "веб-дизайн", "a11y"],
    readTime: 8,
    featured: false,
    coverEmoji: "♿",
    coverGradient: "from-blue-500 to-indigo-600",
    locale: "ru",
  },
  {
    slug: "sql-formatter-guide-ru",
    title: "Форматирование SQL: соглашения, диалекты и отладка запросов",
    description:
      "Практическое руководство по форматированию SQL-запросов: отступы, заглавные буквы ключевых слов, различия диалектов и приёмы читаемости сложных запросов.",
    date: "2026-02-22",
    author: "BrowseryTools",
    category: "Инструменты разработчика",
    tags: ["SQL", "форматирование", "базы данных", "PostgreSQL", "MySQL"],
    readTime: 7,
    featured: false,
    coverEmoji: "🗄️",
    coverGradient: "from-violet-500 to-purple-600",
    locale: "ru",
  },
  {
    slug: "habit-tracker-guide-ru",
    title: "Как использовать трекер привычек для формирования устойчивых привычек",
    description:
      "Доказательные стратегии отслеживания привычек: как начать, поддерживать последовательность и использовать данные для формирования долгосрочного поведения.",
    date: "2026-02-21",
    author: "BrowseryTools",
    category: "Продуктивность",
    tags: ["привычки", "продуктивность", "трекинг", "личное развитие"],
    readTime: 7,
    featured: false,
    coverEmoji: "✅",
    coverGradient: "from-emerald-500 to-green-600",
    locale: "ru",
  },
  {
    slug: "ai-cost-calculator-guide-ru",
    title: "Как рассчитать и оптимизировать расходы на AI API",
    description:
      "Полное руководство по ценообразованию токенов для OpenAI, Anthropic и других провайдеров: как оценивать расходы, контролировать использование и оптимизировать бюджет на AI.",
    date: "2026-03-22",
    author: "BrowseryTools",
    category: "AI-инструменты",
    tags: ["AI", "расходы", "токены", "OpenAI", "Anthropic", "оптимизация бюджета"],
    readTime: 8,
    coverEmoji: "💰",
    coverGradient: "from-emerald-500 to-teal-600",
    locale: "ru",
  },
  {
    slug: "token-counter-guide-ru",
    title: "Токены в языковых моделях: что это и как их считать",
    description:
      "Разбираем, что такое токены, как разные модели токенизируют текст, почему количество токенов важно для производительности и стоимости, и как эффективно управлять контекстным окном.",
    date: "2026-03-22",
    author: "BrowseryTools",
    category: "AI-инструменты",
    tags: ["токены", "LLM", "контекстное окно", "токенизация", "AI"],
    readTime: 7,
    coverEmoji: "🔢",
    coverGradient: "from-violet-500 to-purple-600",
    locale: "ru",
  },
  {
    slug: "context-window-guide-ru",
    title: "Контекстные окна языковых моделей: полное руководство",
    description:
      "Что такое контекстное окно, как оно влияет на производительность модели, стратегии работы с большими документами и как выбрать модель с нужным размером контекста.",
    date: "2026-03-22",
    author: "BrowseryTools",
    category: "AI-инструменты",
    tags: ["контекстное окно", "LLM", "AI", "токены", "языковые модели"],
    readTime: 8,
    coverEmoji: "📐",
    coverGradient: "from-purple-500 to-indigo-600",
    locale: "ru",
  },
  {
    slug: "model-comparison-guide-ru",
    title: "Сравнение AI-моделей: GPT, Claude, Gemini и другие",
    description:
      "Практическое сравнение ведущих языковых моделей: производительность, контекстные окна, ценообразование и выбор подходящей модели для конкретных задач.",
    date: "2026-03-22",
    author: "BrowseryTools",
    category: "AI-инструменты",
    tags: ["AI-модели", "GPT", "Claude", "Gemini", "сравнение LLM"],
    readTime: 9,
    coverEmoji: "⚖️",
    coverGradient: "from-amber-500 to-orange-600",
    locale: "ru",
  },
  {
    slug: "prompt-formatter-guide-ru",
    title: "Форматирование промптов: техники для лучших результатов от AI",
    description:
      "Практические техники форматирования промптов — назначение ролей, блоки инструкций, few-shot примеры, цепочка мыслей и структурированные выходные данные — для получения стабильных качественных ответов от AI.",
    date: "2026-03-21",
    author: "BrowseryTools",
    category: "AI-инструменты",
    tags: ["промпт-инжиниринг", "AI", "LLM", "форматирование промптов", "ChatGPT"],
    readTime: 7,
    coverEmoji: "✨",
    coverGradient: "from-violet-500 to-purple-600",
    locale: "ru",
  },
  {
    slug: "system-prompt-builder-guide-ru",
    title: "Системные промпты: как писать инструкции, которые работают",
    description:
      "Полное руководство по созданию системных промптов для AI: структура роль-контекст-ограничения-формат, паттерны для типичных сценариев и стратегии тестирования.",
    date: "2026-03-21",
    author: "BrowseryTools",
    category: "AI-инструменты",
    tags: ["системный промпт", "промпт-инжиниринг", "AI", "ChatGPT", "Claude"],
    readTime: 8,
    coverEmoji: "🧠",
    coverGradient: "from-blue-500 to-indigo-600",
    locale: "ru",
  },
  {
    slug: "mcp-config-guide-ru",
    title: "Model Context Protocol (MCP): настройка и конфигурация",
    description:
      "Что такое MCP, как работает архитектура клиент-хост-сервер, популярные MCP-серверы и как написать рабочий конфигурационный файл для Claude Desktop и Claude Code.",
    date: "2026-03-21",
    author: "BrowseryTools",
    category: "Инструменты разработчика",
    tags: ["MCP", "Model Context Protocol", "Claude", "AI-инструменты", "конфигурация"],
    readTime: 8,
    coverEmoji: "🔌",
    coverGradient: "from-emerald-500 to-teal-600",
    locale: "ru",
  },
  {
    slug: "claude-md-guide-ru",
    title: "CLAUDE.md: как настроить контекст проекта для Claude Code",
    description:
      "Что такое CLAUDE.md, что в него включать (стек, команды, архитектура, соглашения), а что нет, и как файл улучшает качество AI-предложений в вашем проекте.",
    date: "2026-03-21",
    author: "BrowseryTools",
    category: "Инструменты разработчика",
    tags: ["CLAUDE.md", "Claude Code", "AI-разработка", "документация", "контекст проекта"],
    readTime: 7,
    coverEmoji: "📄",
    coverGradient: "from-orange-500 to-amber-500",
    locale: "ru",
  },
  {
    slug: "regex-tester-guide-ru",
    title: "Регулярные выражения: полное руководство для разработчиков",
    description:
      "Практическое руководство по регулярным выражениям: базовый синтаксис, группы захвата, lookahead/lookbehind, типичные паттерны и отладка в разных языках программирования.",
    date: "2026-05-21",
    author: "BrowseryTools",
    category: "Инструменты разработчика",
    tags: ["регулярные выражения", "regex", "разработка", "JavaScript", "Python"],
    readTime: 9,
    coverEmoji: "🔍",
    coverGradient: "from-orange-500 to-red-600",
    locale: "ru",
  },
  {
    slug: "json-formatter-guide-ru",
    title: "JSON: синтаксис, ошибки парсинга и форматирование",
    description:
      "Полное руководство по JSON: почему он победил XML, правила синтаксиса, типичные ошибки парсинга, форматирование vs. минификация, навигация по вложенным структурам и валидация по схеме.",
    date: "2026-03-20",
    author: "BrowseryTools",
    category: "Инструменты разработчика",
    tags: ["JSON", "форматирование", "разработка", "API", "отладка"],
    readTime: 8,
    coverEmoji: "📋",
    coverGradient: "from-yellow-400 to-orange-500",
    locale: "ru",
  },
  {
    slug: "curl-converter-guide-ru",
    title: "cURL: анатомия команд и конвертация в код",
    description:
      "Всё о cURL: разбор флагов, типичные REST-паттерны, конвертация в JavaScript fetch, Python requests и Node.js axios, а также работа с функцией «Copy as cURL» в DevTools.",
    date: "2026-03-20",
    author: "BrowseryTools",
    category: "Инструменты разработчика",
    tags: ["cURL", "HTTP", "API", "JavaScript", "Python", "разработка"],
    readTime: 8,
    coverEmoji: "🔄",
    coverGradient: "from-blue-500 to-cyan-500",
    locale: "ru",
  },
];
