import type { BlogPost } from "./blog-data";

export const esPostsB3: BlogPost[] = [
  {
    slug: "color-contrast-accessibility-guide-es",
    title: "Contraste de Color y Accesibilidad: Guía Completa de WCAG",
    description:
      "Aprende los requisitos de contraste de color WCAG 2.1, cómo medir las proporciones de contraste y por qué la accesibilidad del color importa para todos los usuarios.",
    date: "2026-02-23",
    author: "BrowseryTools",
    category: "Herramientas de Diseño",
    tags: ["accesibilidad", "WCAG", "contraste de color", "a11y", "diseño", "UX"],
    readTime: 8,
    coverEmoji: "♿",
    coverGradient: "from-blue-500 to-indigo-600",
    featured: false,
    locale: "es",
  },
  {
    slug: "sql-formatter-guide-es",
    title: "Guía del Formateador SQL: Escribe Consultas Más Limpias y Mantenibles",
    description:
      "Por qué importa el formato SQL, convenciones de estilo para diferentes dialectos, y cómo las herramientas de formato automático hacen que tu código de base de datos sea más legible.",
    date: "2026-02-22",
    author: "BrowseryTools",
    category: "Herramientas para Desarrolladores",
    tags: ["SQL", "base de datos", "formato", "MySQL", "PostgreSQL", "desarrollador"],
    readTime: 7,
    coverEmoji: "🗄️",
    coverGradient: "from-violet-500 to-purple-600",
    featured: false,
    locale: "es",
  },
  {
    slug: "habit-tracker-guide-es",
    title: "Seguimiento de Hábitos: La Ciencia Detrás de los Sistemas de Cambio de Comportamiento",
    description:
      "Por qué funciona el seguimiento de hábitos, la psicología de las rachas y cómo construir sistemas de seguimiento que te mantengan encaminado a largo plazo.",
    date: "2026-02-21",
    author: "BrowseryTools",
    category: "Productividad",
    tags: ["hábitos", "seguimiento de hábitos", "productividad", "rachas", "superación personal"],
    readTime: 7,
    coverEmoji: "✅",
    coverGradient: "from-emerald-500 to-green-600",
    featured: false,
    locale: "es",
  },
  {
    slug: "ai-cost-calculator-guide-es",
    title: "Cómo Controlar los Costos de la API de IA: Guía Práctica de Presupuesto",
    description:
      "Comprende los precios por token de la IA, estima los costos del proyecto antes de construir y optimiza el uso de la API para evitar facturas sorpresa.",
    date: "2026-03-22",
    author: "BrowseryTools",
    category: "Herramientas de IA",
    tags: ["IA", "costos de API", "tokens", "GPT-4", "Claude", "presupuesto"],
    readTime: 8,
    coverEmoji: "💰",
    coverGradient: "from-emerald-500 to-teal-600",
    locale: "es",
  },
  {
    slug: "token-counter-guide-es",
    title: "Cómo Cuentan Tokens los LLM: Guía para Desarrolladores",
    description:
      "Qué son los tokens, cómo los diferentes modelos los cuentan de forma distinta, por qué importa el recuento de tokens para el rendimiento y los costos de la API.",
    date: "2026-03-22",
    author: "BrowseryTools",
    category: "Herramientas de IA",
    tags: ["tokens", "tokenizador", "LLM", "BPE", "ventana de contexto", "API"],
    readTime: 7,
    coverEmoji: "🔢",
    coverGradient: "from-violet-500 to-purple-600",
    locale: "es",
  },
  {
    slug: "context-window-guide-es",
    title: "Ventanas de Contexto LLM Explicadas: Límites, Estrategias y Mejores Prácticas",
    description:
      "Qué es una ventana de contexto, cómo varía entre modelos, qué ocurre cuando se supera el límite y estrategias para gestionar el contexto eficazmente.",
    date: "2026-03-22",
    author: "BrowseryTools",
    category: "Herramientas de IA",
    tags: ["ventana de contexto", "LLM", "RAG", "GPT-4", "Claude", "Gemini"],
    readTime: 8,
    coverEmoji: "📐",
    coverGradient: "from-purple-500 to-indigo-600",
    locale: "es",
  },
  {
    slug: "model-comparison-guide-es",
    title: "GPT-4 vs Claude vs Gemini: Comparación Práctica de Modelos de IA",
    description:
      "Una comparación directa de los principales modelos de IA de 2024 —capacidades, precios, límites de contexto y cuándo usar cada uno para tu caso de uso específico.",
    date: "2026-03-22",
    author: "BrowseryTools",
    category: "Herramientas de IA",
    tags: ["GPT-4", "Claude", "Gemini", "comparación de modelos", "IA", "benchmarks"],
    readTime: 9,
    coverEmoji: "⚖️",
    coverGradient: "from-amber-500 to-orange-600",
    locale: "es",
  },
  {
    slug: "prompt-formatter-guide-es",
    title: "Ingeniería de Prompts: Cómo Estructurar Prompts de IA que Funcionen",
    description:
      "Técnicas prácticas para escribir prompts más claros y efectivos para ChatGPT, Claude y otros LLM —asignación de roles, few-shot, cadena de pensamiento y más.",
    date: "2026-03-21",
    author: "BrowseryTools",
    category: "Herramientas de IA",
    tags: ["IA", "prompts", "ChatGPT", "Claude", "ingeniería de prompts"],
    readTime: 7,
    coverEmoji: "✨",
    coverGradient: "from-violet-500 to-purple-600",
    locale: "es",
  },
  {
    slug: "system-prompt-builder-guide-es",
    title: "Cómo Escribir Prompts de Sistema Efectivos para LLM",
    description:
      "Patrones y técnicas para crear prompts de sistema que den forma consistentemente al comportamiento del modelo —persona, reglas, formato y restricciones explicadas con ejemplos.",
    date: "2026-03-21",
    author: "BrowseryTools",
    category: "Herramientas de IA",
    tags: ["IA", "prompts de sistema", "Claude", "ChatGPT", "ingeniería de prompts", "LLM"],
    readTime: 8,
    coverEmoji: "🧠",
    coverGradient: "from-blue-500 to-indigo-600",
    locale: "es",
  },
  {
    slug: "mcp-config-guide-es",
    title: "Model Context Protocol (MCP): Guía de Configuración para Claude",
    description:
      "Qué es MCP, cómo conecta a Claude con herramientas y datos externos, y cómo escribir archivos de configuración JSON para Claude Desktop y Claude Code.",
    date: "2026-03-21",
    author: "BrowseryTools",
    category: "Herramientas para Desarrolladores",
    tags: ["MCP", "Claude", "herramientas de IA", "Claude Code", "herramientas para desarrolladores", "Anthropic"],
    readTime: 8,
    coverEmoji: "🔌",
    coverGradient: "from-emerald-500 to-teal-600",
    locale: "es",
  },
  {
    slug: "claude-md-guide-es",
    title: "CLAUDE.md: Cómo Darle a Claude Code el Contexto de tu Proyecto",
    description:
      "Qué poner en tu archivo CLAUDE.md, por qué mejora drásticamente las sugerencias de IA y cómo estructurarlo para que Claude entienda tu base de código.",
    date: "2026-03-21",
    author: "BrowseryTools",
    category: "Herramientas para Desarrolladores",
    tags: ["Claude Code", "CLAUDE.md", "IA", "herramientas para desarrolladores", "contexto de base de código", "Anthropic"],
    readTime: 7,
    coverEmoji: "📄",
    coverGradient: "from-orange-500 to-amber-500",
    locale: "es",
  },
  {
    slug: "regex-tester-guide-es",
    title: "Expresiones Regulares Explicadas: Guía Práctica para Desarrolladores",
    description:
      "Una guía completa de expresiones regulares —sintaxis, grupos de captura, lookaheads, banderas y patrones del mundo real para validación, análisis y transformaciones de texto.",
    date: "2026-05-21",
    author: "BrowseryTools",
    category: "Herramientas para Desarrolladores",
    tags: ["regex", "expresiones regulares", "desarrollador", "coincidencia de patrones", "validación"],
    readTime: 9,
    coverEmoji: "🔍",
    coverGradient: "from-orange-500 to-red-600",
    locale: "es",
  },
  {
    slug: "json-formatter-guide-es",
    title: "JSON Explicado: Sintaxis, Errores Comunes y Mejores Prácticas",
    description:
      "Una guía completa de JSON —reglas de sintaxis, errores de análisis que todo desarrollador encuentra, cuándo dar formato o minificar, y cómo validar con JSON Schema.",
    date: "2026-03-20",
    author: "BrowseryTools",
    category: "Herramientas para Desarrolladores",
    tags: ["json", "formato", "validación", "api", "depuración"],
    readTime: 8,
    coverEmoji: "📋",
    coverGradient: "from-yellow-400 to-orange-500",
    locale: "es",
  },
  {
    slug: "curl-converter-guide-es",
    title: "cURL Explicado: Comandos, Banderas y Cómo Convertirlos a Código",
    description:
      "Aprende la anatomía de los comandos cURL, los patrones REST más comunes y cómo traducir cURL a JavaScript fetch, Python requests y Node.js axios.",
    date: "2026-03-20",
    author: "BrowseryTools",
    category: "Herramientas para Desarrolladores",
    tags: ["curl", "api", "http", "javascript", "python", "rest"],
    readTime: 8,
    coverEmoji: "🔄",
    coverGradient: "from-blue-500 to-cyan-500",
    locale: "es",
  },
];
