import type { BlogPost } from "./blog-data";

export const dePosts: BlogPost[] = [
  {
    slug: "keep-laptop-awake-browser-de",
    title: "So halten Sie Ihr Notebook wach, ohne etwas zu installieren (Mac, Windows, Linux)",
    description:
      "Verhindern Sie mit einem einzigen Browser-Tab, dass Ihr Notebook oder Smartphone in den Ruhezustand wechselt – keine Apps, keine Konten, keine Werbung. Nutzt die Screen Wake Lock API. Funktioniert auf Mac, Windows, Linux, iOS und Android.",
    date: "2026-04-14",
    author: "BrowseryTools Team",
    category: "Produktivität",
    tags: ["wach halten", "wake lock", "notebook ruhezustand", "produktivität", "browser api", "plattformübergreifend"],
    readTime: 8,
    featured: true,
    coverEmoji: "⚡",
    coverGradient: "from-emerald-500 to-teal-600",
    locale: "de",
  },
  {
    slug: "why-browser-tools-keep-your-data-private-de",
    title: "Warum browserbasierte Tools der sicherste Weg sind, mit Ihren Daten umzugehen",
    description:
      "Erfahren Sie, wie browserbasierte Tools wie BrowseryTools alles lokal auf Ihrem Gerät verarbeiten – Ihre Dateien, Passwörter und sensiblen Daten verlassen niemals Ihren Computer.",
    date: "2026-02-20",
    author: "BrowseryTools Team",
    category: "Datenschutz & Sicherheit",
    tags: ["datenschutz", "sicherheit", "browser", "lokale verarbeitung", "kein upload"],
    readTime: 7,
    featured: true,
    coverEmoji: "🔒",
    coverGradient: "from-indigo-500 to-purple-600",
    locale: "de",
  },
  {
    slug: "best-free-developer-tools-browser-de",
    title: "Der ultimative Leitfaden zu kostenlosen Entwickler-Tools in Ihrem Browser",
    description:
      "JSON-Formatierer, Base64-Encoder, JWT-Decoder, Regex-Tester, UUID-Generator und mehr – alles kostenlos, alles in Ihrem Browser. Keine Installationen, keine Werbung, keine Anmeldung.",
    date: "2026-02-18",
    author: "BrowseryTools Team",
    category: "Entwickler-Tools",
    tags: ["entwickler", "JSON", "Base64", "JWT", "regex", "UUID", "kostenlose tools"],
    readTime: 9,
    featured: true,
    coverEmoji: "⚡",
    coverGradient: "from-amber-500 to-orange-600",
    locale: "de",
  },
  {
    slug: "meme-generator-guide-de",
    title: "So erstellen Sie ein Meme online kostenlos – keine App, kein Upload, kein Wasserzeichen",
    description:
      "Erstellen Sie ein Meme online kostenlos in Ihrem Browser. Laden Sie ein Bild hoch, fügen Sie klassischen Impact-Text oben und unten hinzu, ziehen Sie ihn an die richtige Stelle, gestalten Sie jede Zeile und laden Sie es als PNG herunter. Nichts wird hochgeladen, kein Wasserzeichen.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Bild-Tools",
    tags: ["meme-generator", "meme erstellen", "meme maker", "Impact-Schrift", "kostenlos", "kein upload"],
    readTime: 7,
    featured: true,
    coverEmoji: "😂",
    coverGradient: "from-yellow-400 to-orange-500",
    locale: "de",
  },
  {
    slug: "favicon-generator-guide-de",
    title: "So erstellen Sie ein Favicon aus einem Bild (oder einem Buchstaben) – kostenloser Online-Generator",
    description:
      "Verwenden Sie einen kostenlosen Favicon-Generator online, um ein Favicon aus einem Bild oder einem Buchstaben/Emoji zu erstellen. Erhalten Sie alle Größen (16, 32, 180, 192, 512), eine Multi-Size-favicon.ico, ein Manifest und ein HTML-Snippet – alles in Ihrem Browser.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Entwickler-Tools",
    tags: ["favicon", "favicon-generator", "favicon aus bild erstellen", "favicon-generator online", "webentwicklung", "symbole"],
    readTime: 7,
    featured: true,
    coverEmoji: "🌟",
    coverGradient: "from-violet-500 to-fuchsia-600",
    locale: "de",
  },
  {
    slug: "text-to-speech-guide-de",
    title: "So lassen Sie Text online kostenlos vorlesen – keine App, kein Konto",
    description:
      "Verwandeln Sie beliebigen Text direkt in Ihrem Browser in Sprache. Stellen Sie Stimme, Tempo, Tonhöhe und Lautstärke mit dem kostenlosen Web-Speech-API-Tool ein – privat, sofort und funktionsfähig auf Mac, Windows, Linux, iOS und Android.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Text & Sprache",
    tags: ["text zu sprache online kostenlos", "text vorlesen", "TTS", "web speech api", "barrierefreiheit", "sprachausgabe"],
    readTime: 7,
    featured: true,
    coverEmoji: "🔊",
    coverGradient: "from-sky-500 to-indigo-600",
    locale: "de",
  },
];
