import type { BlogPost } from "./blog-data";

export const idPostsB2: BlogPost[] = [
  {
    slug: "password-security-guide-id",
    title: "Keamanan Kata Sandi: Mengapa Kebanyakan Kata Sandi Lemah dan Cara Membuat yang Kuat",
    description:
      "Banyak orang menggunakan kata sandi lemah tanpa menyadarinya. Pelajari apa yang membuat kata sandi kuat, cara memeriksanya secara instan, dan membuat yang tak bisa ditembus — semuanya secara privat di browser Anda.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Keamanan",
    tags: ["kata sandi", "keamanan", "peretasan", "generator kata sandi", "kekuatan kata sandi"],
    readTime: 8,
    featured: false,
    coverEmoji: "🛡️",
    coverGradient: "from-green-500 to-emerald-600",
    locale: "id",
  },
  {
    slug: "remove-image-background-free-id",
    title: "Cara Menghapus Latar Belakang Gambar Secara Gratis — Tanpa Canva, Tanpa Photoshop",
    description:
      "Hapus latar belakang dari foto secara instan menggunakan AI, langsung di browser Anda. Tanpa unggah, tanpa langganan, tanpa watermark. Gambar Anda tidak pernah meninggalkan perangkat.",
    date: "2026-02-12",
    author: "BrowseryTools Team",
    category: "Alat Gambar",
    tags: ["penghapusan latar belakang", "pengeditan gambar", "AI", "gratis", "tanpa unggah", "privasi"],
    readTime: 6,
    featured: false,
    coverEmoji: "🖼️",
    coverGradient: "from-pink-500 to-rose-600",
    locale: "id",
  },
  {
    slug: "boost-productivity-pomodoro-todo-id",
    title: "10 Cara Meningkatkan Produktivitas dengan Alat Browser Gratis",
    description:
      "Dari timer Pomodoro hingga daftar tugas, jam dunia hingga pelacak pengeluaran — temukan alat produktivitas yang bekerja sepenuhnya di browser Anda tanpa pengumpulan data.",
    date: "2026-02-10",
    author: "BrowseryTools Team",
    category: "Produktivitas",
    tags: ["produktivitas", "pomodoro", "daftar tugas", "fokus", "manajemen waktu"],
    readTime: 7,
    featured: false,
    coverEmoji: "🎯",
    coverGradient: "from-blue-500 to-cyan-600",
    locale: "id",
  },
  {
    slug: "free-image-tools-guide-id",
    title: "Panduan Lengkap Alat Gambar Gratis — Kompres, Konversi, Ubah Ukuran Tanpa Mengunggah",
    description:
      "Kompresi gambar, konversi format, pengubahan ukuran, koreksi warna, dan penghapusan latar belakang — semuanya diproses secara lokal di browser Anda tanpa unggah dan tanpa biaya.",
    date: "2026-02-08",
    author: "BrowseryTools Team",
    category: "Alat Gambar",
    tags: ["kompresi gambar", "konverter gambar", "ubah ukuran", "gratis", "tanpa unggah"],
    readTime: 8,
    featured: false,
    coverEmoji: "🎨",
    coverGradient: "from-violet-500 to-fuchsia-600",
    locale: "id",
  },
  {
    slug: "qr-code-generator-guide-id",
    title: "Cara Membuat Kode QR Secara Gratis — Untuk Tautan, Teks, WiFi & Kartu Nama",
    description:
      "Buat kode QR tanpa batas untuk konten apa pun — URL, teks biasa, kredensial WiFi, vCard — dengan kustomisasi penuh. 100% gratis, tanpa pendaftaran, bisa offline.",
    date: "2026-02-05",
    author: "BrowseryTools Team",
    category: "Alat Utilitas",
    tags: ["kode QR", "generator QR", "kode QR gratis", "offline", "kartu nama"],
    readTime: 5,
    featured: false,
    coverEmoji: "📱",
    coverGradient: "from-teal-500 to-green-600",
    locale: "id",
  },
  {
    slug: "text-tools-for-writers-developers-id",
    title: "Alat Teks Gratis Terbaik untuk Penulis, Developer, dan Pembuat Konten",
    description:
      "Konverter huruf besar/kecil, generator Lorem ipsum, penghitung karakter, alat perbandingan teks, editor Markdown, dan lainnya. Semua yang dibutuhkan penulis atau developer — gratis dan privat.",
    date: "2026-02-03",
    author: "BrowseryTools Team",
    category: "Alat Teks",
    tags: ["alat teks", "menulis", "markdown", "konverter teks", "lorem ipsum"],
    readTime: 6,
    featured: false,
    coverEmoji: "✍️",
    coverGradient: "from-slate-500 to-gray-600",
    locale: "id",
  },
  {
    slug: "base64-encoding-guide-id",
    title: "Apa Itu Encoding Base64? Panduan Lengkap dengan Contoh",
    description:
      "Pelajari apa itu encoding Base64, mengapa ada, di mana digunakan, dan cara meng-encode serta men-decode string Base64 secara instan di browser Anda — tanpa alat yang perlu diinstal.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Alat Developer",
    tags: ["base64", "encoding", "developer", "biner", "format data"],
    readTime: 7,
    featured: false,
    coverEmoji: "🔡",
    coverGradient: "from-cyan-500 to-blue-600",
    locale: "id",
  },
  {
    slug: "jwt-decoder-guide-id",
    title: "Cara Men-decode dan Memverifikasi Token JWT di Browser Anda",
    description:
      "Token JWT ada di mana-mana dalam autentikasi modern. Pelajari apa isinya, cara men-decode-nya, mendeteksi masalah kedaluwarsa, dan men-debug masalah autentikasi — semuanya secara privat di browser Anda.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Alat Developer",
    tags: ["JWT", "autentikasi", "token", "OAuth", "keamanan", "developer"],
    readTime: 8,
    featured: false,
    coverEmoji: "🔑",
    coverGradient: "from-yellow-500 to-amber-600",
    locale: "id",
  },
  {
    slug: "css-gradient-generator-guide-id",
    title: "Generator Gradien CSS: Buat Gradien Indah Tanpa Menulis Kode",
    description:
      "Bangun gradien CSS linear, radial, dan conic secara visual dengan pratinjau langsung. Salin CSS siap produksi dengan satu klik — tanpa perlu software desain.",
    date: "2026-02-20",
    author: "BrowseryTools Team",
    category: "Alat Desain",
    tags: ["CSS", "gradien", "desain", "frontend", "UI", "warna"],
    readTime: 5,
    featured: false,
    coverEmoji: "🌈",
    coverGradient: "from-purple-500 to-pink-600",
    locale: "id",
  },
  {
    slug: "hash-generator-guide-id",
    title: "MD5, SHA-256, SHA-512: Generator Hash Gratis dan Kapan Menggunakan Masing-masing",
    description:
      "Pahami perbedaan antara MD5, SHA-1, SHA-256, dan SHA-512. Buat hash file dan teks secara instan di browser Anda. Pelajari kapan setiap algoritma tepat digunakan.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Keamanan",
    tags: ["hash", "MD5", "SHA-256", "SHA-512", "checksum", "kriptografi"],
    readTime: 7,
    featured: false,
    coverEmoji: "#️⃣",
    coverGradient: "from-gray-500 to-slate-700",
    locale: "id",
  },
  {
    slug: "screen-recorder-guide-id",
    title: "Rekam Layar Anda Tanpa Menginstal Software Apa Pun",
    description:
      "Browser Anda dapat merekam layar, jendela, atau tab menggunakan Screen Capture API. Pelajari cara menangkap video untuk tutorial, laporan bug, dan demo — tanpa perlu ekstensi.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Alat Utilitas",
    tags: ["perekam layar", "tangkapan layar", "tutorial", "video", "browser API"],
    readTime: 5,
    featured: false,
    coverEmoji: "🎬",
    coverGradient: "from-red-500 to-rose-600",
    locale: "id",
  },
  {
    slug: "fake-data-generator-guide-id",
    title: "Cara Membuat Data Uji Palsu yang Realistis (JSON & CSV) Secara Gratis",
    description:
      "Isi basis data, prototipe UI, dan tulis pengujian dengan nama, email, alamat, nomor telepon palsu yang realistis, dan lainnya — diekspor sebagai JSON atau CSV, semuanya di browser Anda.",
    date: "2026-02-16",
    author: "BrowseryTools Team",
    category: "Alat Developer",
    tags: ["data palsu", "data uji", "data tiruan", "JSON", "CSV", "alat developer"],
    readTime: 6,
    featured: false,
    coverEmoji: "🤖",
    coverGradient: "from-green-500 to-teal-600",
    locale: "id",
  },
  {
    slug: "cron-expression-guide-id",
    title: "Ekspresi Cron Dijelaskan: Cara Membaca dan Menulis Jadwal Cron",
    description:
      "Sintaks cron membingungkan sampai Anda memahami kelima fieldnya. Pelajari cara membaca dan menulis ekspresi cron, menghindari kesalahan umum, dan mengurai jadwal apa pun secara instan di browser Anda.",
    date: "2026-02-14",
    author: "BrowseryTools Team",
    category: "Alat Developer",
    tags: ["cron", "ekspresi cron", "penjadwal", "DevOps", "otomatisasi", "Linux"],
    readTime: 7,
    featured: false,
    coverEmoji: "⏰",
    coverGradient: "from-orange-500 to-red-600",
    locale: "id",
  },
  {
    slug: "bmi-calculator-guide-id",
    title: "Kalkulator BMI: Apa Itu, Cara Menghitungnya, dan Apa Artinya Sebenarnya",
    description:
      "Hitung BMI Anda secara instan dalam satuan metrik atau imperial. Pahami arti angkanya, keterbatasannya, dan seperti apa berat badan sehat untuk tinggi badan Anda.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Kesehatan & Kebugaran",
    tags: ["BMI", "indeks massa tubuh", "kesehatan", "berat badan", "kalkulator"],
    readTime: 6,
    featured: false,
    coverEmoji: "⚖️",
    coverGradient: "from-teal-500 to-cyan-600",
    locale: "id",
  },
];
