import type { BlogPost } from "./blog-data";

export const ptBRPostsB5: BlogPost[] = [
  {
    slug: "expense-tracker-guide-pt-BR",
    title: "Controle Seus Gastos Mensais Sem Apps, Assinaturas ou Armazenamento em Nuvem",
    description: "A maioria das pessoas não sabe para onde vai o dinheiro. Aprenda a regra de orçamento 50/30/20, a diferença entre despesas fixas e variáveis e como fazer uma revisão mensal de gastos — sem se cadastrar em nada.",
    date: "2026-03-16",
    author: "BrowseryTools Team",
    category: "Produtividade",
    tags: ["controle de gastos", "orçamento", "finanças pessoais", "gestão de dinheiro"],
    readTime: 7,
    coverEmoji: "💸",
    coverGradient: "from-emerald-500 to-green-600",
    locale: "pt-BR",
  },
  {
    slug: "invoice-generator-guide-pt-BR",
    title: "Como Criar Faturas Profissionais de Graça — Sem Assinaturas Necessárias",
    description: "Um guia completo de faturamento profissional: campos obrigatórios, convenções de numeração, prazos de pagamento como Net 30, linguagem de multa por atraso, requisitos de IVA e GST por país e por que uma ferramenta PDF gratuita supera uma assinatura cara.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Negócios",
    tags: ["fatura", "freelancing", "cobrança", "prazos de pagamento", "PDF"],
    readTime: 7,
    coverEmoji: "🧾",
    coverGradient: "from-violet-500 to-purple-600",
    locale: "pt-BR",
  },
  {
    slug: "loan-calculator-guide-pt-BR",
    title: "Calculadora de Empréstimos: Entenda seu Financiamento Imobiliário, Veicular ou Pessoal",
    description: "A fórmula de pagamento de empréstimos explicada, amortização desmistificada (por que os pagamentos iniciais são quase todos juros), CET vs. taxa de juros, como pagamentos extras economizam muito dinheiro e como realmente comparar propostas de crédito.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Finanças",
    tags: ["calculadora de empréstimos", "financiamento imobiliário", "amortização", "CET", "finanças pessoais"],
    readTime: 8,
    coverEmoji: "🏦",
    coverGradient: "from-blue-500 to-cyan-600",
    locale: "pt-BR",
  },
  {
    slug: "currency-converter-guide-pt-BR",
    title: "Como Funcionam as Taxas de Câmbio: Um Guia Prático",
    description: "O que impulsiona as taxas de câmbio, o spread bid/ask, por que você nunca obtém a taxa de mercado, como bancos e cartões de crédito escondem taxas nos spreads e as armadilhas de câmbio que pegam viajantes e freelancers internacionais.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Finanças",
    tags: ["conversor de moedas", "taxas de câmbio", "forex", "viagem", "pagamentos internacionais"],
    readTime: 7,
    coverEmoji: "💱",
    coverGradient: "from-amber-500 to-orange-500",
    locale: "pt-BR",
  },
  {
    slug: "timezone-guide-pt-BR",
    title: "Trabalhando em Diferentes Fusos Horários: Um Guia Completo para Equipes Remotas",
    description: "Como os offsets UTC funcionam, por que o horário de verão torna o agendamento propenso a erros, boas práticas para reuniões de equipes remotas, o formato de data ISO 8601 e a regra de ouro para desenvolvedores: sempre armazene timestamps em UTC.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Produtividade",
    tags: ["fuso horário", "trabalho remoto", "UTC", "agendamento", "ISO 8601", "desenvolvedores"],
    readTime: 8,
    coverEmoji: "🌐",
    coverGradient: "from-purple-500 to-violet-600",
    locale: "pt-BR",
  },
  {
    slug: "compress-video-online-free-pt-BR",
    title: "Como Comprimir Vídeo Online de Graça (Sem Upload, Sem Marca D'água)",
    description: "Reduza o tamanho de arquivos de vídeo direto no seu navegador — gratuito, sem conta, sem marca d'água, nada enviado. Aprenda as configurações de bitrate, resolução e codec que realmente diminuem um vídeo, além dos melhores ajustes para e-mail, redes sociais e a web.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Ferramentas de Mídia",
    tags: ["comprimir vídeo online grátis", "reduzir tamanho do vídeo", "compressor de vídeo", "diminuir vídeo", "sem upload", "grátis"],
    readTime: 7,
    coverEmoji: "🎬",
    coverGradient: "from-rose-500 to-red-600",
    locale: "pt-BR",
  },
  {
    slug: "redact-image-online-pt-BR",
    title: "Como Redigir ou Censurar uma Imagem Online (Desfocar Rostos e Ocultar Informações Sensíveis)",
    description: "Desfoque rostos, pixelize placas de carro e apague detalhes sensíveis em qualquer imagem — inteiramente no seu navegador, sem nada ser enviado. Aprenda qual estilo de censura é verdadeiramente irreversível e o erro de metadados que vaza silenciosamente os dados que você pensou ter ocultado.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Ferramentas de Imagem",
    tags: ["redigir imagem", "desfocar rostos", "censurar foto", "ocultar informações sensíveis", "pixelizar", "privacidade"],
    readTime: 7,
    coverEmoji: "🖍️",
    coverGradient: "from-slate-500 to-gray-700",
    locale: "pt-BR",
  },
  {
    slug: "roman-numeral-converter-guide-pt-BR",
    title: "Conversor de Algarismos Romanos: Como Funcionam (e Como Ler MCMXCIV)",
    description: "Os sete símbolos, as regras de adição e subtração, os seis pares subtrativos válidos e os erros comuns — tudo que você precisa para ler e escrever algarismos romanos, mais um conversor gratuito que funciona nas duas direções.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Calculadoras",
    tags: ["algarismos romanos", "conversor de algarismos romanos", "MCMXCIV", "como funcionam algarismos romanos", "conversor de números"],
    readTime: 7,
    coverEmoji: "🏛️",
    coverGradient: "from-amber-500 to-yellow-600",
    locale: "pt-BR",
  },
  {
    slug: "convert-svg-to-png-pt-BR",
    title: "Como Converter SVG para PNG (Mantendo Nitidez e Transparência)",
    description: "Transforme arquivos SVG vetoriais em imagens PNG universais diretamente no seu navegador — gratuito, sem upload, sem marca d'água. Aprenda a escolher a resolução de exportação certa para nunca ficar borrado e como manter o fundo transparente.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Ferramentas de Imagem",
    tags: ["converter SVG para PNG", "SVG para PNG", "vetor para raster", "PNG transparente", "exportar SVG", "grátis"],
    readTime: 7,
    coverEmoji: "🖼️",
    coverGradient: "from-cyan-500 to-blue-600",
    locale: "pt-BR",
  },
  {
    slug: "convert-video-to-gif-pt-BR",
    title: "Como Converter Vídeo para GIF (e Manter o Arquivo Pequeno)",
    description: "Transforme um clipe MP4 ou MOV em GIF em loop diretamente no seu navegador — sem upload, sem marca d'água. Aprenda por que GIFs aumentam de tamanho, as três configurações que os mantêm pequenos e quando um vídeo curto supera um GIF.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Ferramentas de Mídia",
    tags: ["converter vídeo para GIF", "vídeo para GIF", "MP4 para GIF", "criar GIF", "sem upload", "grátis"],
    readTime: 6,
    coverEmoji: "🎞️",
    coverGradient: "from-fuchsia-500 to-pink-600",
    locale: "pt-BR",
  },
  {
    slug: "crop-and-watermark-images-online-pt-BR",
    title: "Como Recortar e Adicionar Marca D'água em Imagens Online (Grátis, Sem Upload)",
    description: "Recorte em uma proporção precisa, redimensione sem distorção e adicione uma marca d'água que realmente inibe o reuso — tudo no seu navegador, com o original nunca enviado. Inclui o erro de proporção que estica suas fotos.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Ferramentas de Imagem",
    tags: ["recortar imagem online", "marca d'água em imagem", "redimensionar imagem", "proporção", "sem upload", "grátis"],
    readTime: 7,
    coverEmoji: "✂️",
    coverGradient: "from-teal-500 to-emerald-600",
    locale: "pt-BR",
  },
  {
    slug: "curl-to-fetch-python-code-pt-BR",
    title: "Como Converter cURL em Código (fetch, Python requests, Node.js)",
    description: "Cole um comando cURL e obtenha código JavaScript fetch, Python requests ou Node.js funcionando — incluindo o truque 'Copiar como cURL' do DevTools. Aprenda como cada flag mapeia para código para que você possa confiar na saída, tudo processado localmente no seu navegador.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Ferramentas para Desenvolvedores",
    tags: ["cURL para código", "cURL para fetch", "cURL para Python", "converter cURL", "copiar como cURL", "api"],
    readTime: 7,
    coverEmoji: "🔁",
    coverGradient: "from-indigo-500 to-violet-600",
    locale: "pt-BR",
  },
  {
    slug: "scientific-calculator-online-pt-BR",
    title: "Calculadora Científica Online: Trigonometria, Logaritmos, Potências e os Erros a Evitar",
    description: "Uma calculadora científica gratuita no navegador com sen, cos, tan, log, ln, potências, raízes e constantes. Aprenda a armadilha graus vs. radianos, ordem de operações e exemplos práticos para juros compostos, triângulos e pH.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Calculadoras",
    tags: ["calculadora científica online", "calculadora gráfica", "calculadora de trigonometria", "calculadora de logaritmo", "calculadora grátis"],
    readTime: 7,
    coverEmoji: "🧮",
    coverGradient: "from-blue-500 to-indigo-600",
    locale: "pt-BR",
  },
  {
    slug: "random-picker-guide-pt-BR",
    title: "Sorteador Aleatório: Números Aleatórios, Dados, Cara ou Coroa e Roleta de Nomes",
    description: "Gere números aleatórios, lance dados, tire cara ou coroa ou escolha um vencedor justo de uma lista — grátis e no seu navegador. Aprenda como fazer um sorteio de giveaway imparcial e quando a aleatoriedade é de fato aleatória.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Ferramentas de Produtividade",
    tags: ["gerador de números aleatórios", "sorteador de nomes", "lançador de dados", "cara ou coroa", "roleta de nomes", "sorteio"],
    readTime: 6,
    coverEmoji: "🎲",
    coverGradient: "from-violet-500 to-purple-600",
    locale: "pt-BR",
  },
];
