import type { BlogPost } from "./blog-data";

export const frPostsB4: BlogPost[] = [
  {
    slug: "unix-timestamp-guide-fr",
    title: "Timestamps Unix : comprendre l'heure Unix et comment l'utiliser",
    description: "Tout ce que les développeurs doivent savoir sur l'heure Unix — l'époque, le problème Y2K38, la conversion de timestamps en JavaScript, Python et SQL, le piège millisecondes/secondes, la gestion des fuseaux horaires et les timestamps dans les JWT et bases de données.",
    date: "2026-03-20",
    author: "BrowseryTools Team",
    category: "Outils pour développeurs",
    tags: ["timestamp unix", "epoch", "datetime", "javascript", "python", "fuseau horaire"],
    readTime: 9,
    coverEmoji: "⏱️",
    coverGradient: "from-violet-500 to-purple-700",
    locale: "fr",
  },
  {
    slug: "url-encoder-guide-fr",
    title: "Encodage URL expliqué : l'encodage pourcent dans les requêtes HTTP",
    description: "Découvrez pourquoi les caractères spéciaux cassent les URL, comment fonctionne l'encodage pourcent au niveau des octets, la différence critique entre encodeURI et encodeURIComponent, et les bugs d'encodage courants dans les applications réelles.",
    date: "2026-03-19",
    author: "BrowseryTools Team",
    category: "Outils pour développeurs",
    tags: ["encodage URL", "encodage pourcent", "HTTP", "développement web", "JavaScript"],
    readTime: 7,
    coverEmoji: "🔗",
    coverGradient: "from-cyan-500 to-blue-600",
    locale: "fr",
  },
  {
    slug: "uuid-generator-guide-fr",
    title: "UUID, NanoID et CUID : choisir le bon format d'identifiant pour votre projet",
    description: "Plongée en profondeur dans les UUID v1, v4 et v7, NanoID et CUID2 — ce qu'est chaque format, comment fonctionne la probabilité de collision, et quand utiliser lequel pour les clés primaires, les URL et les systèmes distribués.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Outils pour développeurs",
    tags: ["UUID", "NanoID", "CUID", "base de données", "systèmes distribués", "identifiants"],
    readTime: 8,
    coverEmoji: "🆔",
    coverGradient: "from-violet-500 to-purple-700",
    locale: "fr",
  },
  {
    slug: "chmod-guide-fr",
    title: "Permissions de fichiers Linux expliquées : guide complet chmod",
    description: "Guide complet des permissions de fichiers Unix — le modèle propriétaire/groupe/autres, la notation octale (755, 644, 777), la notation symbolique, setuid/setgid/sticky bit et exemples concrets pour les serveurs web et les clés SSH.",
    date: "2026-03-21",
    author: "BrowseryTools Team",
    category: "Outils pour développeurs",
    tags: ["chmod", "Linux", "permissions de fichiers", "Unix", "sécurité", "administration système"],
    readTime: 8,
    coverEmoji: "🔒",
    coverGradient: "from-green-500 to-teal-600",
    locale: "fr",
  },
  {
    slug: "http-status-codes-guide-fr",
    title: "Codes de statut HTTP que tout développeur devrait connaître",
    description: "Référence pratique des codes de statut HTTP — les cinq catégories, analyses détaillées de 200, 201, 204, 301, 302, 304, 400, 401, 403, 404, 409, 422, 429, 500, 502, 503, plus des conseils sur la conception d'API REST et le débogage dans les DevTools.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Outils pour développeurs",
    tags: ["HTTP", "codes de statut", "API REST", "développement web", "débogage"],
    readTime: 7,
    coverEmoji: "📡",
    coverGradient: "from-orange-500 to-red-600",
    locale: "fr",
  },
  {
    slug: "video-compression-guide-fr",
    title: "Comment compresser des fichiers vidéo sans perte de qualité",
    description: "Guide pratique de la compression vidéo : comment fonctionnent les codecs H.264, H.265, VP9 et AV1, ce qui contrôle réellement la taille des fichiers, la compression sans perte vs avec perte, et les meilleurs paramètres pour l'e-mail, le web, les réseaux sociaux et l'archivage.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Outils multimédias",
    tags: ["compression vidéo", "H.264", "codec", "taille de fichier", "montage vidéo"],
    readTime: 7,
    coverEmoji: "🎬",
    coverGradient: "from-red-500 to-pink-600",
    locale: "fr",
  },
  {
    slug: "image-formats-guide-fr",
    title: "JPEG vs PNG vs WebP vs AVIF : comparaison complète des formats d'image",
    description: "Comprendre comment JPEG, PNG, WebP et AVIF compressent les images sous le capot, quand utiliser chaque format, comment ils affectent les Core Web Vitals et comment servir le bon format au bon navigateur.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Outils image",
    tags: ["formats d'image", "JPEG", "PNG", "WebP", "AVIF", "performances web", "Core Web Vitals"],
    readTime: 8,
    coverEmoji: "🖼️",
    coverGradient: "from-blue-500 to-cyan-500",
    locale: "fr",
  },
  {
    slug: "exif-data-guide-fr",
    title: "Métadonnées EXIF : ce que vos photos révèlent sur vous (et comment les supprimer)",
    description: "Les données EXIF intègrent des coordonnées GPS, des numéros de série d'appareils et des horodatages dans chaque photo que vous prenez. Découvrez ce qu'elles enregistrent, les risques réels pour la vie privée, les cas célèbres d'exposition de localisation, et comment les consulter et les supprimer.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Confidentialité et sécurité",
    tags: ["EXIF", "métadonnées", "vie privée", "GPS", "sécurité photo", "données image"],
    readTime: 8,
    coverEmoji: "📷",
    coverGradient: "from-amber-500 to-orange-600",
    locale: "fr",
  },
  {
    slug: "svg-guide-fr",
    title: "Fichiers SVG : guide complet pour développeurs et designers",
    description: "Tout ce que vous devez savoir sur SVG : le format vectoriel basé sur XML qui s'adapte infiniment, comment fonctionnent les éléments clés comme path et viewBox, le style CSS et l'animation, l'optimisation SVGO, les risques XSS des SVG téléversés, et quand convertir SVG en PNG.",
    date: "2026-03-21",
    author: "BrowseryTools Team",
    category: "Outils pour développeurs",
    tags: ["SVG", "graphiques vectoriels", "développement web", "CSS", "SVGO", "icônes"],
    readTime: 9,
    coverEmoji: "✏️",
    coverGradient: "from-violet-500 to-purple-600",
    locale: "fr",
  },
  {
    slug: "lorem-ipsum-guide-fr",
    title: "Lorem Ipsum : origine, usages et pourquoi les designers ne peuvent pas s'en passer",
    description: "L'histoire complète de Lorem Ipsum — du texte philosophique de Cicéron en 45 av. J.-C. aux workflows de design modernes. Apprenez quand l'utiliser, quand l'éviter, et comment générer exactement la quantité dont vous avez besoin.",
    date: "2026-03-17",
    author: "BrowseryTools Team",
    category: "Outils texte",
    tags: ["lorem ipsum", "texte de substitution", "design", "typographie"],
    readTime: 6,
    coverEmoji: "📝",
    coverGradient: "from-slate-500 to-gray-600",
    locale: "fr",
  },
  {
    slug: "markdown-complete-guide-fr",
    title: "Markdown : référence complète de syntaxe pour écrivains et développeurs",
    description: "Guide complet du Markdown — qui l'a créé et pourquoi, référence complète de syntaxe des bases aux fonctionnalités étendues, les variantes Markdown (CommonMark, GFM, MDX) et les erreurs courantes à éviter.",
    date: "2026-03-18",
    author: "BrowseryTools Team",
    category: "Outils texte",
    tags: ["markdown", "syntaxe", "écriture", "documentation", "développeurs"],
    readTime: 7,
    coverEmoji: "✍️",
    coverGradient: "from-indigo-500 to-blue-600",
    locale: "fr",
  },
  {
    slug: "text-diff-guide-fr",
    title: "Comment comparer des fichiers texte et trouver les différences sans logiciel",
    description: "Apprenez comment fonctionnent les algorithmes de diff, comment lire la sortie de diff unifié, la différence entre les diffs au niveau de la ligne et du mot, et comment git diff fonctionne sous le capot.",
    date: "2026-03-19",
    author: "BrowseryTools Team",
    category: "Outils pour développeurs",
    tags: ["diff", "comparaison de texte", "git", "revue de code", "comparaison de fichiers"],
    readTime: 6,
    coverEmoji: "🔍",
    coverGradient: "from-emerald-500 to-teal-600",
    locale: "fr",
  },
  {
    slug: "text-encryption-guide-fr",
    title: "Chiffrement de texte côté client : protéger les données sensibles dans le navigateur",
    description: "Guide pratique du chiffrement de texte dans le navigateur — ce que signifie réellement le chiffrement côté client, les algorithmes symétriques vs asymétriques, la dérivation de clé à partir de mots de passe, et les vraies limites de la cryptographie dans le navigateur.",
    date: "2026-03-20",
    author: "BrowseryTools Team",
    category: "Sécurité",
    tags: ["chiffrement", "AES", "sécurité", "vie privée", "cryptographie", "navigateur"],
    readTime: 7,
    coverEmoji: "🔐",
    coverGradient: "from-rose-500 to-pink-600",
    locale: "fr",
  },
  {
    slug: "word-frequency-guide-fr",
    title: "Analyse de fréquence des mots : un outil pour les écrivains, le SEO et la recherche",
    description: "Comment l'analyse de fréquence des mots révèle les patterns d'écriture, la densité des mots-clés et les thèmes des documents. Couvre les mots vides, TF-IDF expliqué simplement, les cas d'usage pour les écrivains et le SEO, et les applications académiques comme l'attribution d'auteur.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Outils texte",
    tags: ["fréquence des mots", "analyse de texte", "SEO", "écriture", "NLP", "contenu"],
    readTime: 6,
    coverEmoji: "📊",
    coverGradient: "from-violet-500 to-purple-600",
    locale: "fr",
  },
];
