import type { BlogPost } from "./blog-data";

export const frPosts: BlogPost[] = [
  {
    slug: "keep-laptop-awake-browser-fr",
    title: "Comment garder votre ordinateur portable éveillé sans rien installer (Mac, Windows, Linux)",
    description: "Empêchez votre ordinateur portable ou votre téléphone de se mettre en veille avec un seul onglet de navigateur — sans application, sans compte, sans publicité. Utilise l'API Screen Wake Lock. Fonctionne sur Mac, Windows, Linux, iOS et Android.",
    date: "2026-04-14",
    author: "BrowseryTools Team",
    category: "Productivité",
    tags: ["rester éveillé", "wake lock", "veille de l'ordinateur portable", "productivité", "api du navigateur", "multiplateforme"],
    readTime: 8,
    featured: true,
    coverEmoji: "⚡",
    coverGradient: "from-emerald-500 to-teal-600",
    locale: "fr",
  },
  {
    slug: "why-browser-tools-keep-your-data-private-fr",
    title: "Pourquoi les outils basés sur le navigateur sont le moyen le plus sûr de gérer vos données",
    description: "Découvrez comment les outils basés sur le navigateur comme BrowseryTools traitent tout localement sur votre appareil — vos fichiers, mots de passe et données sensibles ne quittent jamais votre ordinateur.",
    date: "2026-02-20",
    author: "BrowseryTools Team",
    category: "Confidentialité et sécurité",
    tags: ["confidentialité", "sécurité", "navigateur", "traitement local", "sans téléversement"],
    readTime: 7,
    featured: true,
    coverEmoji: "🔒",
    coverGradient: "from-indigo-500 to-purple-600",
    locale: "fr",
  },
  {
    slug: "best-free-developer-tools-browser-fr",
    title: "Le guide ultime des outils gratuits pour développeurs dans votre navigateur",
    description: "Formateur JSON, encodeur Base64, décodeur JWT, testeur de regex, générateur d'UUID et plus encore — tous gratuits, tous dans votre navigateur. Aucune installation, aucune publicité, aucune inscription.",
    date: "2026-02-18",
    author: "BrowseryTools Team",
    category: "Outils pour développeurs",
    tags: ["développeur", "JSON", "Base64", "JWT", "regex", "UUID", "outils gratuits"],
    readTime: 9,
    featured: true,
    coverEmoji: "⚡",
    coverGradient: "from-amber-500 to-orange-600",
    locale: "fr",
  },
  {
    slug: "meme-generator-guide-fr",
    title: "Comment créer un mème en ligne gratuitement — sans application, sans téléversement, sans filigrane",
    description: "Créez un mème en ligne gratuitement dans votre navigateur. Téléversez une image, ajoutez un texte en haut et en bas dans la police Impact classique, glissez pour positionner, stylisez chaque ligne, et téléchargez en PNG. Rien n'est téléversé, aucun filigrane.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Outils d'images",
    tags: ["générateur de mèmes", "créer un mème", "fabricant de mèmes", "police Impact", "gratuit", "sans téléversement"],
    readTime: 7,
    featured: true,
    coverEmoji: "😂",
    coverGradient: "from-yellow-400 to-orange-500",
    locale: "fr",
  },
  {
    slug: "favicon-generator-guide-fr",
    title: "Comment créer un favicon à partir d'une image (ou d'une lettre) — générateur gratuit en ligne",
    description: "Utilisez un générateur de favicon gratuit en ligne pour créer un favicon à partir d'une image ou d'une lettre/emoji. Obtenez toutes les tailles (16, 32, 180, 192, 512), un favicon.ico multi-tailles, un manifeste et un extrait HTML — le tout dans votre navigateur.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Outils pour développeurs",
    tags: ["favicon", "générateur de favicon", "créer un favicon à partir d'une image", "générateur de favicon en ligne", "développement web", "icônes"],
    readTime: 7,
    featured: true,
    coverEmoji: "🌟",
    coverGradient: "from-violet-500 to-fuchsia-600",
    locale: "fr",
  },
  {
    slug: "text-to-speech-guide-fr",
    title: "Comment lire un texte à voix haute en ligne gratuitement — sans application, sans compte",
    description: "Transformez n'importe quel texte en parole directement dans votre navigateur. Ajustez la voix, la vitesse, la hauteur et le volume avec l'outil gratuit Web Speech API — privé, instantané, et fonctionne sur Mac, Windows, Linux, iOS et Android.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Texte et langue",
    tags: ["synthèse vocale en ligne gratuite", "lire un texte à voix haute", "TTS", "web speech api", "accessibilité", "voix off"],
    readTime: 7,
    featured: true,
    coverEmoji: "🔊",
    coverGradient: "from-sky-500 to-indigo-600",
    locale: "fr",
  },
];
