import type { BlogPost } from "./blog-data";

export const idPostsB5: BlogPost[] = [
  {
    slug: "expense-tracker-guide-id",
    title: "Lacak Pengeluaran Bulanan Tanpa Aplikasi, Langganan, atau Penyimpanan Cloud",
    description: "Kebanyakan orang tidak tahu ke mana uang mereka pergi. Pelajari aturan anggaran 50/30/20, perbedaan antara pengeluaran tetap dan variabel, dan cara menjalankan tinjauan pengeluaran bulanan — tanpa mendaftar ke apa pun.",
    date: "2026-03-16",
    author: "BrowseryTools Team",
    category: "Produktivitas",
    tags: ["pelacak pengeluaran", "anggaran", "keuangan pribadi", "manajemen uang"],
    readTime: 7,
    coverEmoji: "💸",
    coverGradient: "from-emerald-500 to-green-600",
    locale: "id",
  },
  {
    slug: "invoice-generator-guide-id",
    title: "Cara Membuat Invoice Profesional Secara Gratis — Tanpa Langganan",
    description: "Panduan lengkap invoicing profesional: kolom yang wajib ada, konvensi penomoran, syarat pembayaran seperti Net 30, bahasa biaya keterlambatan, persyaratan VAT dan GST per negara, dan mengapa alat PDF gratis mengalahkan langganan $100/tahun.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Bisnis",
    tags: ["invoice", "freelancing", "penagihan", "syarat pembayaran", "PDF"],
    readTime: 7,
    coverEmoji: "🧾",
    coverGradient: "from-violet-500 to-purple-600",
    locale: "id",
  },
  {
    slug: "loan-calculator-guide-id",
    title: "Kalkulator Pinjaman: Pahami KPR, Kredit Kendaraan, atau Pinjaman Pribadi",
    description: "Rumus cicilan pinjaman dijelaskan, amortisasi diungkap (mengapa pembayaran awal sebagian besar adalah bunga), APR vs suku bunga, cara pembayaran ekstra menghemat ribuan, dan cara membandingkan penawaran pinjaman dengan benar.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Keuangan",
    tags: ["kalkulator pinjaman", "KPR", "amortisasi", "APR", "keuangan pribadi"],
    readTime: 8,
    coverEmoji: "🏦",
    coverGradient: "from-blue-500 to-cyan-600",
    locale: "id",
  },
  {
    slug: "currency-converter-guide-id",
    title: "Cara Kerja Nilai Tukar Mata Uang: Panduan Praktis",
    description: "Apa yang mendorong nilai tukar, spread bid/ask, mengapa kamu tidak pernah mendapatkan kurs mid-market, cara bank dan kartu kredit menyembunyikan biaya dalam spread, dan jebakan mata uang yang sering menimpa wisatawan dan freelancer internasional.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Keuangan",
    tags: ["konverter mata uang", "nilai tukar", "forex", "perjalanan", "pembayaran internasional"],
    readTime: 7,
    coverEmoji: "💱",
    coverGradient: "from-amber-500 to-orange-500",
    locale: "id",
  },
  {
    slug: "timezone-guide-id",
    title: "Bekerja Lintas Zona Waktu: Panduan Lengkap untuk Tim Jarak Jauh",
    description: "Cara kerja offset UTC, mengapa DST membuat penjadwalan rawan kesalahan, praktik terbaik penjadwalan rapat tim jarak jauh, format datetime ISO 8601, dan aturan emas untuk developer: selalu simpan timestamp dalam UTC.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Produktivitas",
    tags: ["zona waktu", "kerja jarak jauh", "UTC", "penjadwalan", "ISO 8601", "developer"],
    readTime: 8,
    coverEmoji: "🌐",
    coverGradient: "from-purple-500 to-violet-600",
    locale: "id",
  },
  {
    slug: "compress-video-online-free-id",
    title: "Cara Mengompresi Video Online Secara Gratis (Tanpa Unggah, Tanpa Watermark)",
    description: "Kurangi ukuran file video langsung di browsermu — gratis, tanpa akun, tanpa watermark, tidak ada yang diunggah. Pelajari pengaturan bitrate, resolusi, dan codec yang benar-benar mengompresi video, beserta preset terbaik untuk email, media sosial, dan web.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Alat Media",
    tags: ["kompres video online gratis", "kurangi ukuran video", "pengompresi video", "perkecil video", "tanpa unggah", "gratis"],
    readTime: 7,
    coverEmoji: "🎬",
    coverGradient: "from-rose-500 to-red-600",
    locale: "id",
  },
  {
    slug: "redact-image-online-id",
    title: "Cara Meredaksi atau Menyensor Gambar Online (Blur Wajah & Sembunyikan Info Sensitif)",
    description: "Blur wajah, pikselasi plat nomor, dan samarkan detail sensitif di gambar apa pun — sepenuhnya di browsermu, tanpa ada yang diunggah. Pelajari gaya sensor mana yang benar-benar tidak dapat dibalik dan kesalahan metadata yang diam-diam membocorkan data yang telah diredaksi.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Alat Gambar",
    tags: ["redaksi gambar", "blur wajah", "sensor foto", "sembunyikan info sensitif", "pikselasi", "privasi"],
    readTime: 7,
    coverEmoji: "🖍️",
    coverGradient: "from-slate-500 to-gray-700",
    locale: "id",
  },
  {
    slug: "roman-numeral-converter-guide-id",
    title: "Konverter Angka Romawi: Cara Kerja Angka Romawi (dan Cara Membaca MCMXCIV)",
    description: "Tujuh simbol, aturan penjumlahan dan pengurangan, enam pasang subtraktif yang valid, dan kesalahan umum — semua yang perlu kamu ketahui untuk membaca dan menulis angka Romawi, ditambah konverter gratis yang berjalan dua arah.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Kalkulator",
    tags: ["angka romawi", "konverter angka romawi", "MCMXCIV", "cara kerja angka romawi", "konverter angka"],
    readTime: 7,
    coverEmoji: "🏛️",
    coverGradient: "from-amber-500 to-yellow-600",
    locale: "id",
  },
  {
    slug: "convert-svg-to-png-id",
    title: "Cara Mengkonversi SVG ke PNG (Jaga Ketajaman dan Transparansi)",
    description: "Ubah file SVG vektor menjadi gambar PNG universal langsung di browsermu — gratis, tanpa unggah, tanpa watermark. Pelajari cara memilih resolusi ekspor yang tepat agar tidak buram, dan cara mempertahankan latar belakang transparan.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Alat Gambar",
    tags: ["konversi svg ke png", "svg ke png", "vektor ke raster", "png transparan", "ekspor svg", "gratis"],
    readTime: 7,
    coverEmoji: "🖼️",
    coverGradient: "from-cyan-500 to-blue-600",
    locale: "id",
  },
  {
    slug: "convert-video-to-gif-id",
    title: "Cara Mengkonversi Video ke GIF (dan Menjaga Ukuran File Tetap Kecil)",
    description: "Ubah klip MP4 atau MOV menjadi GIF yang berulang langsung di browsermu — tanpa unggah, tanpa watermark. Pelajari mengapa GIF cepat membesar, tiga pengaturan yang menjaganya tetap kecil, dan kapan video pendek mengalahkan GIF.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Alat Media",
    tags: ["konversi video ke gif", "video ke gif", "mp4 ke gif", "buat gif", "tanpa unggah", "gratis"],
    readTime: 6,
    coverEmoji: "🎞️",
    coverGradient: "from-fuchsia-500 to-pink-600",
    locale: "id",
  },
  {
    slug: "crop-and-watermark-images-online-id",
    title: "Cara Memotong dan Memberi Watermark pada Gambar Online (Gratis, Tanpa Unggah)",
    description: "Potong ke rasio aspek yang tepat, ubah ukuran tanpa distorsi, dan tambahkan watermark yang benar-benar mencegah penggunaan ulang — semuanya di browsermu, dengan aslinya tidak pernah diunggah. Termasuk kesalahan rasio aspek yang meregangkan fotomu.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Alat Gambar",
    tags: ["potong gambar online", "watermark gambar", "ubah ukuran gambar", "rasio aspek", "tanpa unggah", "gratis"],
    readTime: 7,
    coverEmoji: "✂️",
    coverGradient: "from-teal-500 to-emerald-600",
    locale: "id",
  },
  {
    slug: "curl-to-fetch-python-code-id",
    title: "Cara Mengkonversi cURL ke Kode (fetch, Python requests, Node.js)",
    description: "Tempel perintah cURL dan dapatkan kode JavaScript fetch, Python requests, atau Node.js yang berfungsi — termasuk trik 'Copy as cURL' di DevTools. Pelajari cara setiap flag dipetakan ke kode agar kamu bisa mempercayai outputnya, semuanya diproses secara lokal di browsermu.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Alat Developer",
    tags: ["curl ke kode", "curl ke fetch", "curl ke python", "konversi curl", "copy as curl", "api"],
    readTime: 7,
    coverEmoji: "🔁",
    coverGradient: "from-indigo-500 to-violet-600",
    locale: "id",
  },
  {
    slug: "scientific-calculator-online-id",
    title: "Kalkulator Ilmiah Online: Trigonometri, Log, Pangkat, dan Kesalahan yang Harus Dihindari",
    description: "Kalkulator ilmiah gratis dalam browser dengan sin, cos, tan, log, ln, pangkat, akar, dan konstanta. Pelajari jebakan derajat vs radian, urutan operasi, dan contoh yang dikerjakan untuk bunga majemuk, segitiga, dan pH.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Kalkulator",
    tags: ["kalkulator ilmiah online", "kalkulator grafis", "kalkulator trigonometri", "kalkulator log", "kalkulator gratis"],
    readTime: 7,
    coverEmoji: "🧮",
    coverGradient: "from-blue-500 to-indigo-600",
    locale: "id",
  },
  {
    slug: "random-picker-guide-id",
    title: "Random Picker: Angka Acak, Dadu, Lemparan Koin & Roda Nama",
    description: "Buat angka acak, lempar dadu, lempar koin, atau pilih pemenang yang adil dari daftar — gratis dan di browsermu. Pelajari cara menjalankan undian giveaway yang tidak bias dan kapan keacakan benar-benar acak.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Alat Produktivitas",
    tags: ["generator angka acak", "pemilih nama acak", "pelemparan dadu", "lemparan koin", "roda nama", "giveaway"],
    readTime: 6,
    coverEmoji: "🎲",
    coverGradient: "from-violet-500 to-purple-600",
    locale: "id",
  },
];
