import type { BlogPost } from "./blog-data";

export const ptBRPostsB3: BlogPost[] = [
  {
    slug: "color-contrast-accessibility-guide-pt-BR",
    title: "Contraste de Cores e Acessibilidade Web: Um Guia Completo sobre WCAG",
    description: "Aprenda por que o contraste de cores é essencial para a acessibilidade, como calcular razões de contraste, o que significam os níveis WCAG AA e AAA, e como verificar qualquer combinação de cores instantaneamente.",
    date: "2026-02-23",
    author: "BrowseryTools Team",
    category: "Ferramentas de Design",
    tags: ["acessibilidade", "WCAG", "contraste de cores", "a11y", "design", "UX"],
    readTime: 8,
    featured: false,
    coverEmoji: "♿",
    coverGradient: "from-blue-500 to-indigo-600",
    locale: "pt-BR",
  },
  {
    slug: "sql-formatter-guide-pt-BR",
    title: "Como Formatar Queries SQL para Legibilidade e Depuração",
    description: "SQL não formatado é um pesadelo de depuração. Aprenda as convenções de formatação SQL, como ler queries complexas com JOINs e subqueries, e formate qualquer query instantaneamente no seu navegador.",
    date: "2026-02-22",
    author: "BrowseryTools Team",
    category: "Ferramentas para Desenvolvedores",
    tags: ["SQL", "banco de dados", "formatação", "MySQL", "PostgreSQL", "desenvolvedor"],
    readTime: 7,
    featured: false,
    coverEmoji: "🗄️",
    coverGradient: "from-violet-500 to-purple-600",
    locale: "pt-BR",
  },
  {
    slug: "habit-tracker-guide-pt-BR",
    title: "Como Construir Bons Hábitos: A Ciência das Sequências e do Rastreamento Diário",
    description: "Aprenda a psicologia por trás da formação de hábitos, por que as sequências funcionam, e como usar um rastreador de hábitos simples baseado em navegador para construir rotinas duradouras sem assinar um aplicativo.",
    date: "2026-02-21",
    author: "BrowseryTools Team",
    category: "Produtividade",
    tags: ["hábitos", "rastreador de hábitos", "produtividade", "sequências", "autodesenvolvimento"],
    readTime: 7,
    featured: false,
    coverEmoji: "✅",
    coverGradient: "from-emerald-500 to-green-600",
    locale: "pt-BR",
  },
  {
    slug: "ai-cost-calculator-guide-pt-BR",
    title: "Como Calcular os Custos da Sua API de IA Antes de Esgotar o Orçamento",
    description: "Preços baseados em tokens explicados: custos de entrada vs saída, como GPT-4, Claude e Gemini cobram por 1K tokens, escalonamento de custos com volume e estratégias práticas para reduzir sua fatura mensal de API de IA.",
    date: "2026-03-22",
    author: "BrowseryTools Team",
    category: "Ferramentas de IA",
    tags: ["IA", "custos de API", "tokens", "GPT-4", "Claude", "orçamento"],
    readTime: 8,
    coverEmoji: "💰",
    coverGradient: "from-emerald-500 to-teal-600",
    locale: "pt-BR",
  },
  {
    slug: "token-counter-guide-pt-BR",
    title: "Contagem de Tokens em LLMs: Por que Todo Desenvolvedor Precisa Entender Isso",
    description: "O que são tokens, como funciona a codificação por par de bytes, por que a regra de 750 palavras por 1000 tokens falha para árabe e chinês, e como as contagens de tokens afetam janelas de contexto e custos de API.",
    date: "2026-03-22",
    author: "BrowseryTools Team",
    category: "Ferramentas de IA",
    tags: ["tokens", "tokenizador", "LLM", "BPE", "janela de contexto", "API"],
    readTime: 7,
    coverEmoji: "🔢",
    coverGradient: "from-violet-500 to-purple-600",
    locale: "pt-BR",
  },
  {
    slug: "context-window-guide-pt-BR",
    title: "Janelas de Contexto de LLMs Explicadas: Limites, Estratégias e Como Trabalhar Dentro Delas",
    description: "O que é uma janela de contexto, limites atuais para GPT-4, Claude e Gemini, o que acontece quando você os excede, o problema 'perdido no meio' e estratégias como fragmentação, sumarização e RAG.",
    date: "2026-03-22",
    author: "BrowseryTools Team",
    category: "Ferramentas de IA",
    tags: ["janela de contexto", "LLM", "RAG", "GPT-4", "Claude", "Gemini"],
    readTime: 8,
    coverEmoji: "📐",
    coverGradient: "from-purple-500 to-indigo-600",
    locale: "pt-BR",
  },
  {
    slug: "model-comparison-guide-pt-BR",
    title: "GPT-4 vs Claude vs Gemini: Como Comparar Modelos de IA para o Seu Caso de Uso",
    description: "Por que os números de benchmarks podem enganar, dimensões principais para comparar modelos de IA (raciocínio, codificação, custo, comprimento de contexto) e uma abordagem prática para escolher o modelo certo para a sua aplicação.",
    date: "2026-03-22",
    author: "BrowseryTools Team",
    category: "Ferramentas de IA",
    tags: ["GPT-4", "Claude", "Gemini", "comparação de modelos", "IA", "benchmarks"],
    readTime: 9,
    coverEmoji: "⚖️",
    coverGradient: "from-amber-500 to-orange-600",
    locale: "pt-BR",
  },
  {
    slug: "prompt-formatter-guide-pt-BR",
    title: "Como Formatar Prompts para Melhores Respostas de IA",
    description: "Aprenda as técnicas que separam saídas de IA medíocres de respostas precisas e acionáveis: atribuição de papel, blocos de instrução claros, exemplos few-shot, prompting em cadeia de pensamento e formatos estruturados XML/JSON.",
    date: "2026-03-21",
    author: "BrowseryTools Team",
    category: "Ferramentas de IA",
    tags: ["IA", "prompts", "ChatGPT", "Claude", "engenharia de prompts"],
    readTime: 7,
    coverEmoji: "✨",
    coverGradient: "from-violet-500 to-purple-600",
    locale: "pt-BR",
  },
  {
    slug: "system-prompt-builder-guide-pt-BR",
    title: "Escrevendo Prompts de Sistema que Realmente Funcionam",
    description: "Um guia prático para criar prompts de sistema que produzem comportamento consistente de IA — cobrindo papel, contexto, restrições, formato de saída e como testar e iterar em casos de uso de suporte ao cliente, codificação e escrita.",
    date: "2026-03-21",
    author: "BrowseryTools Team",
    category: "Ferramentas de IA",
    tags: ["IA", "prompts de sistema", "Claude", "ChatGPT", "engenharia de prompts", "LLM"],
    readTime: 8,
    coverEmoji: "🧠",
    coverGradient: "from-blue-500 to-indigo-600",
    locale: "pt-BR",
  },
  {
    slug: "mcp-config-guide-pt-BR",
    title: "Model Context Protocol (MCP): O que É e Como Configurar",
    description: "O MCP é o padrão aberto da Anthropic para conectar modelos de IA a ferramentas, arquivos e bancos de dados. Aprenda como a arquitetura cliente-servidor funciona, quais servidores usar e como escrever uma configuração MCP funcional para Claude Desktop e Claude Code.",
    date: "2026-03-21",
    author: "BrowseryTools Team",
    category: "Ferramentas para Desenvolvedores",
    tags: ["MCP", "Claude", "ferramentas de IA", "Claude Code", "ferramentas de desenvolvedor", "Anthropic"],
    readTime: 8,
    coverEmoji: "🔌",
    coverGradient: "from-emerald-500 to-teal-600",
    locale: "pt-BR",
  },
  {
    slug: "claude-md-guide-pt-BR",
    title: "Arquivos CLAUDE.md: Como Dar à IA o Contexto que Ela Precisa sobre a Sua Base de Código",
    description: "Um arquivo CLAUDE.md na raiz do seu projeto fornece ao Claude Code contexto permanente sobre sua stack, convenções e arquitetura — eliminando as correções repetidas que acompanham um assistente de IA sem contexto.",
    date: "2026-03-21",
    author: "BrowseryTools Team",
    category: "Ferramentas para Desenvolvedores",
    tags: ["Claude Code", "CLAUDE.md", "IA", "ferramentas de desenvolvedor", "contexto de base de código", "Anthropic"],
    readTime: 7,
    coverEmoji: "📄",
    coverGradient: "from-orange-500 to-amber-500",
    locale: "pt-BR",
  },
  {
    slug: "regex-tester-guide-pt-BR",
    title: "Expressões Regulares Explicadas: Um Guia Prático para Desenvolvedores",
    description: "Aprenda os 20% da sintaxe regex que cobrem 80% dos casos de uso do mundo real — classes de caracteres, quantificadores, âncoras, grupos e flags — com exemplos práticos de validação de e-mail, números de telefone, extração de URLs e mais.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Ferramentas para Desenvolvedores",
    tags: ["regex", "expressões regulares", "desenvolvedor", "correspondência de padrões", "validação"],
    readTime: 9,
    coverEmoji: "🔍",
    coverGradient: "from-orange-500 to-red-600",
    locale: "pt-BR",
  },
  {
    slug: "json-formatter-guide-pt-BR",
    title: "Formatação, Validação e Depuração de JSON: Um Guia Completo para Desenvolvedores",
    description: "Um guia prático sobre regras de sintaxe JSON, erros comuns de análise, pretty-print vs minificação, dados profundamente aninhados, validação com JSON Schema e como o JSON difere entre APIs e arquivos de configuração.",
    date: "2026-03-20",
    author: "BrowseryTools Team",
    category: "Ferramentas para Desenvolvedores",
    tags: ["json", "formatação", "validação", "api", "depuração"],
    readTime: 8,
    coverEmoji: "📋",
    coverGradient: "from-yellow-400 to-orange-500",
    locale: "pt-BR",
  },
  {
    slug: "curl-converter-guide-pt-BR",
    title: "cURL para Código: Converta Requisições de API Entre Linguagens Instantaneamente",
    description: "Entenda a sintaxe de flags do cURL, padrões comuns de API REST e como traduzir com precisão comandos cURL para JavaScript fetch, Python requests e Node.js axios — incluindo o fluxo 'Copiar como cURL' das DevTools do navegador.",
    date: "2026-03-20",
    author: "BrowseryTools Team",
    category: "Ferramentas para Desenvolvedores",
    tags: ["curl", "api", "http", "javascript", "python", "rest"],
    readTime: 8,
    coverEmoji: "🔄",
    coverGradient: "from-blue-500 to-cyan-500",
    locale: "pt-BR",
  },
];
