import type { BlogPost } from "./blog-data";

export const idPostsB4: BlogPost[] = [
  {
    slug: "unix-timestamp-guide-id",
    title: "Unix Timestamp: Apa Itu dan Cara Menggunakannya",
    description: "Semua yang perlu diketahui developer tentang Unix time — apa itu epoch, masalah Y2K38, mengkonversi timestamp di JavaScript, Python, dan SQL, jebakan milidetik vs detik, penanganan timezone, dan timestamp di JWT serta database.",
    date: "2026-03-20",
    author: "BrowseryTools Team",
    category: "Alat Developer",
    tags: ["unix timestamp", "epoch", "datetime", "javascript", "python", "timezone"],
    readTime: 9,
    coverEmoji: "⏱️",
    coverGradient: "from-violet-500 to-purple-700",
    locale: "id",
  },
  {
    slug: "url-encoder-guide-id",
    title: "URL Encoding Dijelaskan: Percent-Encoding dalam HTTP Request",
    description: "Pelajari mengapa karakter khusus merusak URL, cara kerja percent-encoding di level byte, perbedaan penting antara encodeURI dan encodeURIComponent, dan bug encoding umum di aplikasi nyata.",
    date: "2026-03-19",
    author: "BrowseryTools Team",
    category: "Alat Developer",
    tags: ["URL encoding", "percent encoding", "HTTP", "pengembangan web", "JavaScript"],
    readTime: 7,
    coverEmoji: "🔗",
    coverGradient: "from-cyan-500 to-blue-600",
    locale: "id",
  },
  {
    slug: "uuid-generator-guide-id",
    title: "UUID, NanoID, dan CUID: Memilih Format ID yang Tepat untuk Proyekmu",
    description: "Pembahasan mendalam tentang UUID v1, v4, dan v7, NanoID, dan CUID2 — apa itu masing-masing format, cara kerja probabilitas tabrakan, dan kapan menggunakan mana untuk primary key database, URL, dan sistem terdistribusi.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Alat Developer",
    tags: ["UUID", "NanoID", "CUID", "database", "sistem terdistribusi", "identifier"],
    readTime: 8,
    coverEmoji: "🆔",
    coverGradient: "from-violet-500 to-purple-700",
    locale: "id",
  },
  {
    slug: "chmod-guide-id",
    title: "Izin File Linux Dijelaskan: Panduan chmod Lengkap",
    description: "Panduan lengkap tentang izin file Unix — model owner/group/other, notasi oktal (755, 644, 777), notasi simbolik, setuid/setgid/sticky bit, dan contoh dunia nyata untuk web server dan kunci SSH.",
    date: "2026-03-21",
    author: "BrowseryTools Team",
    category: "Alat Developer",
    tags: ["chmod", "Linux", "izin file", "Unix", "keamanan", "sysadmin"],
    readTime: 8,
    coverEmoji: "🔒",
    coverGradient: "from-green-500 to-teal-600",
    locale: "id",
  },
  {
    slug: "http-status-codes-guide-id",
    title: "Kode Status HTTP yang Harus Diketahui Setiap Developer",
    description: "Referensi praktis untuk kode status HTTP — lima kategori, pembahasan mendalam tentang 200, 201, 204, 301, 302, 304, 400, 401, 403, 404, 409, 422, 429, 500, 502, 503, beserta panduan desain REST API dan debugging di DevTools.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Alat Developer",
    tags: ["HTTP", "kode status", "REST API", "pengembangan web", "debugging"],
    readTime: 7,
    coverEmoji: "📡",
    coverGradient: "from-orange-500 to-red-600",
    locale: "id",
  },
  {
    slug: "video-compression-guide-id",
    title: "Cara Mengompresi File Video Tanpa Kehilangan Kualitas",
    description: "Panduan praktis kompresi video: cara kerja codec seperti H.264, H.265, VP9, dan AV1, apa yang sebenarnya mengontrol ukuran file, kompresi lossless vs lossy, dan pengaturan terbaik untuk email, web, media sosial, dan penggunaan arsip.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Alat Media",
    tags: ["kompresi video", "H.264", "codec", "ukuran file", "pengeditan video"],
    readTime: 7,
    coverEmoji: "🎬",
    coverGradient: "from-red-500 to-pink-600",
    locale: "id",
  },
  {
    slug: "image-formats-guide-id",
    title: "JPEG vs PNG vs WebP vs AVIF: Perbandingan Format Gambar Lengkap",
    description: "Pahami cara kerja JPEG, PNG, WebP, dan AVIF dalam mengompresi gambar, kapan menggunakan setiap format, bagaimana pengaruhnya terhadap Core Web Vitals, dan cara menyajikan format yang tepat ke browser yang tepat.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Alat Gambar",
    tags: ["format gambar", "JPEG", "PNG", "WebP", "AVIF", "performa web", "Core Web Vitals"],
    readTime: 8,
    coverEmoji: "🖼️",
    coverGradient: "from-blue-500 to-cyan-500",
    locale: "id",
  },
  {
    slug: "exif-data-guide-id",
    title: "Metadata EXIF: Apa yang Fotomu Ungkapkan tentang Dirimu (dan Cara Menghapusnya)",
    description: "Data EXIF menyematkan koordinat GPS, nomor seri perangkat, dan timestamp ke setiap foto yang kamu ambil. Pelajari apa yang direkamnya, risiko privasi nyata, kasus terkenal di mana data tersebut mengungkapkan lokasi orang, serta cara melihat dan menghapusnya.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Privasi & Keamanan",
    tags: ["EXIF", "metadata", "privasi", "GPS", "keamanan foto", "data gambar"],
    readTime: 8,
    coverEmoji: "📷",
    coverGradient: "from-amber-500 to-orange-600",
    locale: "id",
  },
  {
    slug: "svg-guide-id",
    title: "File SVG: Panduan Lengkap untuk Developer dan Desainer",
    description: "Semua yang perlu kamu ketahui tentang SVG: format vektor berbasis XML yang dapat diskalakan tanpa batas, cara kerja elemen inti seperti path dan viewBox, styling dan animasi CSS, optimasi SVGO, risiko XSS dari SVG yang diunggah pengguna, dan kapan mengkonversi SVG ke PNG.",
    date: "2026-03-21",
    author: "BrowseryTools Team",
    category: "Alat Developer",
    tags: ["SVG", "grafis vektor", "pengembangan web", "CSS", "SVGO", "ikon"],
    readTime: 9,
    coverEmoji: "✏️",
    coverGradient: "from-violet-500 to-purple-600",
    locale: "id",
  },
  {
    slug: "lorem-ipsum-guide-id",
    title: "Lorem Ipsum: Asal Usul, Kegunaan, dan Mengapa Desainer Tidak Bisa Hidup Tanpanya",
    description: "Kisah lengkap di balik Lorem Ipsum — dari teks filosofis Cicero 45 SM hingga alur kerja desain modern. Pelajari kapan menggunakannya, kapan harus dihindari, dan cara menghasilkan jumlah yang tepat sesuai kebutuhan.",
    date: "2026-03-17",
    author: "BrowseryTools Team",
    category: "Alat Teks",
    tags: ["lorem ipsum", "teks placeholder", "desain", "tipografi"],
    readTime: 6,
    coverEmoji: "📝",
    coverGradient: "from-slate-500 to-gray-600",
    locale: "id",
  },
  {
    slug: "markdown-complete-guide-id",
    title: "Markdown: Referensi Sintaksis Lengkap untuk Penulis dan Developer",
    description: "Panduan komprehensif tentang Markdown — siapa yang membuatnya dan mengapa, referensi sintaksis lengkap dari dasar hingga fitur yang diperluas, varian Markdown (CommonMark, GFM, MDX), dan kesalahan umum yang harus dihindari.",
    date: "2026-03-18",
    author: "BrowseryTools Team",
    category: "Alat Teks",
    tags: ["markdown", "sintaksis", "penulisan", "dokumentasi", "developer"],
    readTime: 7,
    coverEmoji: "✍️",
    coverGradient: "from-indigo-500 to-blue-600",
    locale: "id",
  },
  {
    slug: "text-diff-guide-id",
    title: "Cara Membandingkan File Teks dan Menemukan Perbedaan Tanpa Software Apa Pun",
    description: "Pelajari cara kerja algoritma diff teks, cara membaca output unified diff, perbedaan antara diff level baris dan level kata, serta cara kerja git diff di baliknya.",
    date: "2026-03-19",
    author: "BrowseryTools Team",
    category: "Alat Developer",
    tags: ["diff", "perbandingan teks", "git", "code review", "perbandingan file"],
    readTime: 6,
    coverEmoji: "🔍",
    coverGradient: "from-emerald-500 to-teal-600",
    locale: "id",
  },
  {
    slug: "text-encryption-guide-id",
    title: "Enkripsi Teks Sisi Klien: Cara Melindungi Data Sensitif di Browser",
    description: "Panduan praktis enkripsi teks berbasis browser — apa arti enkripsi sisi klien sebenarnya, algoritma simetris vs asimetris, derivasi kunci dari password, dan keterbatasan nyata kriptografi dalam browser.",
    date: "2026-03-20",
    author: "BrowseryTools Team",
    category: "Keamanan",
    tags: ["enkripsi", "AES", "keamanan", "privasi", "kriptografi", "browser"],
    readTime: 7,
    coverEmoji: "🔐",
    coverGradient: "from-rose-500 to-pink-600",
    locale: "id",
  },
  {
    slug: "word-frequency-guide-id",
    title: "Analisis Frekuensi Kata: Alat untuk Penulis, SEO, dan Penelitian",
    description: "Cara analisis frekuensi kata mengungkapkan pola penulisan, kepadatan kata kunci, dan tema dokumen. Mencakup stop word, penjelasan TF-IDF yang mudah, kasus penggunaan untuk penulis dan SEO, serta aplikasi akademis seperti atribusi kepengarangan.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Alat Teks",
    tags: ["frekuensi kata", "analisis teks", "SEO", "penulisan", "NLP", "konten"],
    readTime: 6,
    coverEmoji: "📊",
    coverGradient: "from-violet-500 to-purple-600",
    locale: "id",
  },
];
