import type { BlogPost } from "./blog-data";

export const dePostsB3: BlogPost[] = [
  {
    slug: "color-contrast-accessibility-guide-de",
    title: "Farbkontrast und Web-Zugänglichkeit: Ein vollständiger WCAG-Leitfaden",
    description: "Erfahren Sie, warum Farbkontrast für Barrierefreiheit wichtig ist, wie Kontrastverhältnisse berechnet werden, was WCAG AA und AAA bedeuten und wie man jede Farbkombination sofort überprüft.",
    date: "2026-02-23",
    author: "BrowseryTools Team",
    category: "Design-Tools",
    tags: ["barrierefreiheit", "WCAG", "farbkontrast", "a11y", "design", "UX"],
    readTime: 8,
    featured: false,
    coverEmoji: "♿",
    coverGradient: "from-blue-500 to-indigo-600",
    locale: "de",
  },
  {
    slug: "sql-formatter-guide-de",
    title: "SQL-Abfragen für Lesbarkeit und Debugging formatieren",
    description: "Unformatiertes SQL ist ein Debugging-Albtraum. Lernen Sie SQL-Formatierungskonventionen, wie man komplexe Abfragen mit JOINs und Unterabfragen liest und jede Abfrage sofort im Browser formatiert.",
    date: "2026-02-22",
    author: "BrowseryTools Team",
    category: "Entwickler-Tools",
    tags: ["SQL", "Datenbank", "formatierung", "MySQL", "PostgreSQL", "entwickler"],
    readTime: 7,
    featured: false,
    coverEmoji: "🗄️",
    coverGradient: "from-violet-500 to-purple-600",
    locale: "de",
  },
  {
    slug: "habit-tracker-guide-de",
    title: "Gute Gewohnheiten aufbauen: Die Wissenschaft von Serien und täglichem Tracking",
    description: "Erfahren Sie die Psychologie hinter der Gewohnheitsbildung, warum Serien wirken und wie man einen einfachen browserbasierten Gewohnheits-Tracker nutzt, um dauerhafte Routinen ohne App-Abonnement aufzubauen.",
    date: "2026-02-21",
    author: "BrowseryTools Team",
    category: "Produktivität",
    tags: ["gewohnheiten", "gewohnheits-tracker", "produktivität", "serien", "selbstverbesserung"],
    readTime: 7,
    featured: false,
    coverEmoji: "✅",
    coverGradient: "from-emerald-500 to-green-600",
    locale: "de",
  },
  {
    slug: "ai-cost-calculator-guide-de",
    title: "KI-API-Kosten berechnen, bevor das Budget überschritten wird",
    description: "Tokenbasierte Preisgestaltung erklärt: Eingabe- vs. Ausgabekosten, wie GPT-4, Claude und Gemini pro 1K Token berechnen, Kostenskalierung mit Volumen und praktische Strategien zur Senkung der monatlichen KI-API-Rechnung.",
    date: "2026-03-22",
    author: "BrowseryTools Team",
    category: "KI-Tools",
    tags: ["KI", "API-Kosten", "Token", "GPT-4", "Claude", "Budget"],
    readTime: 8,
    coverEmoji: "💰",
    coverGradient: "from-emerald-500 to-teal-600",
    locale: "de",
  },
  {
    slug: "token-counter-guide-de",
    title: "Token-Zählung in LLMs: Warum jeder Entwickler das verstehen muss",
    description: "Was Token wirklich sind, wie Byte-Pair Encoding funktioniert, warum die 750-Wörter-pro-1000-Token-Regel für Arabisch und Chinesisch nicht gilt und wie Token-Anzahlen Kontextfenster und API-Kosten beeinflussen.",
    date: "2026-03-22",
    author: "BrowseryTools Team",
    category: "KI-Tools",
    tags: ["token", "tokenizer", "LLM", "BPE", "kontextfenster", "API"],
    readTime: 7,
    coverEmoji: "🔢",
    coverGradient: "from-violet-500 to-purple-600",
    locale: "de",
  },
  {
    slug: "context-window-guide-de",
    title: "LLM-Kontextfenster erklärt: Limits, Strategien und der richtige Umgang",
    description: "Was ein Kontextfenster ist, aktuelle Limits für GPT-4, Claude und Gemini, was passiert, wenn man sie überschreitet, das Lost-in-the-Middle-Problem und Strategien wie Chunking, Zusammenfassung und RAG.",
    date: "2026-03-22",
    author: "BrowseryTools Team",
    category: "KI-Tools",
    tags: ["kontextfenster", "LLM", "RAG", "GPT-4", "Claude", "Gemini"],
    readTime: 8,
    coverEmoji: "📐",
    coverGradient: "from-purple-500 to-indigo-600",
    locale: "de",
  },
  {
    slug: "model-comparison-guide-de",
    title: "GPT-4 vs. Claude vs. Gemini: KI-Modelle für den eigenen Anwendungsfall vergleichen",
    description: "Warum Benchmark-Zahlen in die Irre führen können, wichtige Dimensionen für den Vergleich von KI-Modellen (Denkvermögen, Coding, Kosten, Kontextlänge) und ein praktischer Ansatz für die richtige Modellwahl.",
    date: "2026-03-22",
    author: "BrowseryTools Team",
    category: "KI-Tools",
    tags: ["GPT-4", "Claude", "Gemini", "modellvergleich", "KI", "benchmarks"],
    readTime: 9,
    coverEmoji: "⚖️",
    coverGradient: "from-amber-500 to-orange-600",
    locale: "de",
  },
  {
    slug: "prompt-formatter-guide-de",
    title: "Prompts für bessere KI-Antworten formatieren",
    description: "Lernen Sie die Techniken, die mittelmäßige KI-Ausgaben von präzisen, handlungsorientierten unterscheiden: Rollenzuweisung, klare Anweisungsblöcke, Few-Shot-Beispiele, Chain-of-Thought-Prompting und strukturierte XML/JSON-Formate.",
    date: "2026-03-21",
    author: "BrowseryTools Team",
    category: "KI-Tools",
    tags: ["KI", "prompts", "ChatGPT", "Claude", "prompt-engineering"],
    readTime: 7,
    coverEmoji: "✨",
    coverGradient: "from-violet-500 to-purple-600",
    locale: "de",
  },
  {
    slug: "system-prompt-builder-guide-de",
    title: "System-Prompts schreiben, die wirklich funktionieren",
    description: "Ein praktischer Leitfaden zum Verfassen von System-Prompts, die konsistentes KI-Verhalten erzeugen – mit Rolle, Kontext, Einschränkungen, Ausgabeformat und Testmethodik für Kundensupport-, Coding- und Schreib-Anwendungsfälle.",
    date: "2026-03-21",
    author: "BrowseryTools Team",
    category: "KI-Tools",
    tags: ["KI", "system-prompts", "Claude", "ChatGPT", "prompt-engineering", "LLM"],
    readTime: 8,
    coverEmoji: "🧠",
    coverGradient: "from-blue-500 to-indigo-600",
    locale: "de",
  },
  {
    slug: "mcp-config-guide-de",
    title: "Model Context Protocol (MCP): Was es ist und wie man es konfiguriert",
    description: "MCP ist Anthropics offener Standard für die Verbindung von KI-Modellen mit Tools, Dateien und Datenbanken. Erfahren Sie, wie die Client-Server-Architektur funktioniert, welche Server man verwenden sollte und wie man eine funktionierende MCP-Konfiguration erstellt.",
    date: "2026-03-21",
    author: "BrowseryTools Team",
    category: "Entwickler-Tools",
    tags: ["MCP", "Claude", "KI-Tools", "Claude Code", "entwickler-tools", "Anthropic"],
    readTime: 8,
    coverEmoji: "🔌",
    coverGradient: "from-emerald-500 to-teal-600",
    locale: "de",
  },
  {
    slug: "claude-md-guide-de",
    title: "CLAUDE.md-Dateien: Wie man der KI den nötigen Kontext zur Codebasis gibt",
    description: "Eine CLAUDE.md-Datei im Projektstamm gibt Claude Code dauerhaften Kontext über den eigenen Stack, Konventionen und die Architektur – und eliminiert die ständigen Korrekturen, die mit einem kontextblinden KI-Assistenten einhergehen.",
    date: "2026-03-21",
    author: "BrowseryTools Team",
    category: "Entwickler-Tools",
    tags: ["Claude Code", "CLAUDE.md", "KI", "entwickler-tools", "codebasis-kontext", "Anthropic"],
    readTime: 7,
    coverEmoji: "📄",
    coverGradient: "from-orange-500 to-amber-500",
    locale: "de",
  },
  {
    slug: "regex-tester-guide-de",
    title: "Reguläre Ausdrücke erklärt: Ein praktischer Leitfaden für Entwickler",
    description: "Lernen Sie die 20 % der Regex-Syntax kennen, die 80 % der realen Anwendungsfälle abdecken – Zeichenklassen, Quantoren, Anker, Gruppen und Flags – mit praktischen Beispielen für E-Mail-Validierung, Telefonnummern, URL-Extraktion und mehr.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Entwickler-Tools",
    tags: ["regex", "reguläre ausdrücke", "entwickler", "musterabgleich", "validierung"],
    readTime: 9,
    coverEmoji: "🔍",
    coverGradient: "from-orange-500 to-red-600",
    locale: "de",
  },
  {
    slug: "json-formatter-guide-de",
    title: "JSON formatieren, validieren und debuggen: Ein vollständiger Entwicklerleitfaden",
    description: "Ein praktischer Leitfaden zu JSON-Syntaxregeln, häufigen Parse-Fehlern, hübschem Drucken vs. Minifizieren, tief verschachtelten Daten, JSON-Schema-Validierung und wie sich JSON zwischen APIs und Konfigurationsdateien unterscheidet.",
    date: "2026-03-20",
    author: "BrowseryTools Team",
    category: "Entwickler-Tools",
    tags: ["json", "formatierung", "validierung", "api", "debugging"],
    readTime: 8,
    coverEmoji: "📋",
    coverGradient: "from-yellow-400 to-orange-500",
    locale: "de",
  },
  {
    slug: "curl-converter-guide-de",
    title: "cURL zu Code: API-Anfragen zwischen Sprachen sofort konvertieren",
    description: "cURL-Flag-Syntax verstehen, häufige REST-API-Muster und cURL-Befehle präzise in JavaScript fetch, Python requests und Node.js axios übersetzen – einschließlich des Browser-DevTools-Workflows \"Als cURL kopieren\".",
    date: "2026-03-20",
    author: "BrowseryTools Team",
    category: "Entwickler-Tools",
    tags: ["curl", "api", "http", "javascript", "python", "rest"],
    readTime: 8,
    coverEmoji: "🔄",
    coverGradient: "from-blue-500 to-cyan-500",
    locale: "de",
  },
];
