import type { BlogPost } from "./blog-data";

export const ruPosts: BlogPost[] = [
  {
    slug: "keep-laptop-awake-browser-ru",
    title: "Как не дать ноутбуку уснуть, ничего не устанавливая (Mac, Windows, Linux)",
    description: "Не позволяйте ноутбуку или телефону уходить в спящий режим с помощью одной вкладки браузера — без приложений, без аккаунтов, без рекламы. Использует Screen Wake Lock API. Работает на Mac, Windows, Linux, iOS и Android.",
    date: "2026-04-14",
    author: "BrowseryTools Team",
    category: "Продуктивность",
    tags: ["не давать уснуть", "wake lock", "спящий режим ноутбука", "продуктивность", "браузерный api", "кроссплатформенность"],
    readTime: 8,
    featured: true,
    coverEmoji: "⚡",
    coverGradient: "from-emerald-500 to-teal-600",
    locale: "ru",
  },
  {
    slug: "why-browser-tools-keep-your-data-private-ru",
    title: "Почему браузерные инструменты — самый безопасный способ работать с вашими данными",
    description: "Узнайте, как браузерные инструменты вроде BrowseryTools обрабатывают всё локально на вашем устройстве — ваши файлы, пароли и конфиденциальные данные никогда не покидают компьютер.",
    date: "2026-02-20",
    author: "BrowseryTools Team",
    category: "Конфиденциальность и безопасность",
    tags: ["конфиденциальность", "безопасность", "браузер", "локальная обработка", "без загрузки"],
    readTime: 7,
    featured: true,
    coverEmoji: "🔒",
    coverGradient: "from-indigo-500 to-purple-600",
    locale: "ru",
  },
  {
    slug: "best-free-developer-tools-browser-ru",
    title: "Полное руководство по бесплатным инструментам для разработчиков в браузере",
    description: "Форматировщик JSON, кодировщик Base64, декодер JWT, тестер регулярных выражений, генератор UUID и многое другое — всё бесплатно, всё в вашем браузере. Без установки, без рекламы, без регистрации.",
    date: "2026-02-18",
    author: "BrowseryTools Team",
    category: "Инструменты для разработчиков",
    tags: ["разработчик", "JSON", "Base64", "JWT", "регулярные выражения", "UUID", "бесплатные инструменты"],
    readTime: 9,
    featured: true,
    coverEmoji: "⚡",
    coverGradient: "from-amber-500 to-orange-600",
    locale: "ru",
  },
  {
    slug: "meme-generator-guide-ru",
    title: "Как сделать мем онлайн бесплатно — без приложения, без загрузки, без водяного знака",
    description: "Создайте мем онлайн бесплатно прямо в браузере. Загрузите изображение, добавьте классический верхний и нижний текст шрифтом Impact, перетащите для позиционирования, оформите каждую строку и скачайте в PNG. Ничего не загружается, без водяного знака.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Инструменты для изображений",
    tags: ["генератор мемов", "сделать мем", "создание мемов", "шрифт Impact", "бесплатно", "без загрузки"],
    readTime: 7,
    featured: true,
    coverEmoji: "😂",
    coverGradient: "from-yellow-400 to-orange-500",
    locale: "ru",
  },
  {
    slug: "favicon-generator-guide-ru",
    title: "Как создать фавикон из изображения (или буквы) — бесплатный онлайн-генератор",
    description: "Используйте бесплатный онлайн-генератор фавиконов, чтобы создать фавикон из изображения или буквы/эмодзи. Получите все размеры (16, 32, 180, 192, 512), многоразмерный favicon.ico, манифест и HTML-фрагмент — всё в браузере.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Инструменты для разработчиков",
    tags: ["фавикон", "генератор фавиконов", "создать фавикон из изображения", "генератор фавиконов онлайн", "веб-разработка", "иконки"],
    readTime: 7,
    featured: true,
    coverEmoji: "🌟",
    coverGradient: "from-violet-500 to-fuchsia-600",
    locale: "ru",
  },
  {
    slug: "text-to-speech-guide-ru",
    title: "Как озвучить текст онлайн бесплатно — без приложения, без аккаунта",
    description: "Превратите любой текст в речь прямо в браузере. Настройте голос, скорость, высоту тона и громкость с помощью бесплатного инструмента на основе Web Speech API — приватно, мгновенно и работает на Mac, Windows, Linux, iOS и Android.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Текст и язык",
    tags: ["синтез речи онлайн бесплатно", "озвучить текст", "TTS", "web speech api", "доступность", "озвучка"],
    readTime: 7,
    featured: true,
    coverEmoji: "🔊",
    coverGradient: "from-sky-500 to-indigo-600",
    locale: "ru",
  },
];
