import type { BlogPost } from "./blog-data";

export const idPostsB3: BlogPost[] = [
  {
    slug: "color-contrast-accessibility-guide-id",
    title: "Kontras Warna dan Aksesibilitas Web: Panduan WCAG Lengkap",
    description: "Pelajari mengapa kontras warna penting untuk aksesibilitas, cara menghitung rasio kontras, apa arti WCAG AA dan AAA, dan cara memeriksa kombinasi warna apa pun secara instan.",
    date: "2026-02-23",
    author: "BrowseryTools Team",
    category: "Alat Desain",
    tags: ["aksesibilitas", "WCAG", "kontras warna", "a11y", "desain", "UX"],
    readTime: 8,
    featured: false,
    coverEmoji: "♿",
    coverGradient: "from-blue-500 to-indigo-600",
    locale: "id",
  },
  {
    slug: "sql-formatter-guide-id",
    title: "Cara Memformat Query SQL untuk Keterbacaan dan Debugging",
    description: "SQL yang tidak diformat adalah mimpi buruk debugging. Pelajari konvensi pemformatan SQL, cara membaca query kompleks dengan JOIN dan subquery, serta format query apa pun secara instan di browser.",
    date: "2026-02-22",
    author: "BrowseryTools Team",
    category: "Alat Developer",
    tags: ["SQL", "database", "pemformatan", "MySQL", "PostgreSQL", "developer"],
    readTime: 7,
    featured: false,
    coverEmoji: "🗄️",
    coverGradient: "from-violet-500 to-purple-600",
    locale: "id",
  },
  {
    slug: "habit-tracker-guide-id",
    title: "Cara Membangun Kebiasaan Baik: Ilmu Streak dan Pelacakan Harian",
    description: "Pelajari psikologi di balik pembentukan kebiasaan, mengapa streak berhasil, dan cara menggunakan pelacak kebiasaan berbasis browser yang sederhana untuk membangun rutinitas yang bertahan tanpa berlangganan aplikasi.",
    date: "2026-02-21",
    author: "BrowseryTools Team",
    category: "Produktivitas",
    tags: ["kebiasaan", "pelacak kebiasaan", "produktivitas", "streak", "pengembangan diri"],
    readTime: 7,
    featured: false,
    coverEmoji: "✅",
    coverGradient: "from-emerald-500 to-green-600",
    locale: "id",
  },
  {
    slug: "ai-cost-calculator-guide-id",
    title: "Cara Menghitung Biaya API AI Sebelum Kehabisan Anggaran",
    description: "Penjelasan harga berbasis token: biaya input vs output, cara GPT-4, Claude, dan Gemini mengenakan biaya per 1K token, skalabilitas biaya sesuai volume, dan strategi praktis untuk mengurangi tagihan API AI bulanan.",
    date: "2026-03-22",
    author: "BrowseryTools Team",
    category: "Alat AI",
    tags: ["AI", "biaya API", "token", "GPT-4", "Claude", "anggaran"],
    readTime: 8,
    coverEmoji: "💰",
    coverGradient: "from-emerald-500 to-teal-600",
    locale: "id",
  },
  {
    slug: "token-counter-guide-id",
    title: "Penghitungan Token dalam LLM: Mengapa Setiap Developer Perlu Memahaminya",
    description: "Apa itu token sebenarnya, cara kerja byte-pair encoding, mengapa aturan 750-kata-per-1000-token tidak berlaku untuk bahasa Arab dan Cina, dan cara jumlah token mempengaruhi jendela konteks serta biaya API.",
    date: "2026-03-22",
    author: "BrowseryTools Team",
    category: "Alat AI",
    tags: ["token", "tokenizer", "LLM", "BPE", "jendela konteks", "API"],
    readTime: 7,
    coverEmoji: "🔢",
    coverGradient: "from-violet-500 to-purple-600",
    locale: "id",
  },
  {
    slug: "context-window-guide-id",
    title: "Jendela Konteks LLM Dijelaskan: Batas, Strategi, dan Cara Bekerja Di Dalamnya",
    description: "Apa itu jendela konteks, batas saat ini untuk GPT-4, Claude, dan Gemini, apa yang terjadi saat melampaui batas, masalah lost-in-the-middle, dan strategi seperti chunking, peringkasan, dan RAG.",
    date: "2026-03-22",
    author: "BrowseryTools Team",
    category: "Alat AI",
    tags: ["jendela konteks", "LLM", "RAG", "GPT-4", "Claude", "Gemini"],
    readTime: 8,
    coverEmoji: "📐",
    coverGradient: "from-purple-500 to-indigo-600",
    locale: "id",
  },
  {
    slug: "model-comparison-guide-id",
    title: "GPT-4 vs Claude vs Gemini: Cara Membandingkan Model AI untuk Kasus Penggunaan Anda",
    description: "Mengapa angka benchmark bisa menyesatkan, dimensi utama untuk membandingkan model AI (penalaran, coding, biaya, panjang konteks), dan pendekatan praktis untuk memilih model yang tepat bagi aplikasi Anda.",
    date: "2026-03-22",
    author: "BrowseryTools Team",
    category: "Alat AI",
    tags: ["GPT-4", "Claude", "Gemini", "perbandingan model", "AI", "benchmark"],
    readTime: 9,
    coverEmoji: "⚖️",
    coverGradient: "from-amber-500 to-orange-600",
    locale: "id",
  },
  {
    slug: "prompt-formatter-guide-id",
    title: "Cara Memformat Prompt untuk Respons AI yang Lebih Baik",
    description: "Pelajari teknik yang membedakan output AI yang biasa dari yang tepat dan dapat ditindaklanjuti: penugasan peran, blok instruksi yang jelas, contoh few-shot, chain-of-thought prompting, dan format XML/JSON terstruktur.",
    date: "2026-03-21",
    author: "BrowseryTools Team",
    category: "Alat AI",
    tags: ["AI", "prompt", "ChatGPT", "Claude", "rekayasa prompt"],
    readTime: 7,
    coverEmoji: "✨",
    coverGradient: "from-violet-500 to-purple-600",
    locale: "id",
  },
  {
    slug: "system-prompt-builder-guide-id",
    title: "Menulis System Prompt yang Benar-Benar Berhasil",
    description: "Panduan praktis untuk membuat system prompt yang menghasilkan perilaku AI yang konsisten — mencakup peran, konteks, batasan, format output, dan cara menguji serta mengiterasi untuk kasus penggunaan dukungan pelanggan, coding, dan penulisan.",
    date: "2026-03-21",
    author: "BrowseryTools Team",
    category: "Alat AI",
    tags: ["AI", "system prompt", "Claude", "ChatGPT", "rekayasa prompt", "LLM"],
    readTime: 8,
    coverEmoji: "🧠",
    coverGradient: "from-blue-500 to-indigo-600",
    locale: "id",
  },
  {
    slug: "mcp-config-guide-id",
    title: "Model Context Protocol (MCP): Apa Itu dan Cara Mengonfigurasinya",
    description: "MCP adalah standar terbuka Anthropic untuk menghubungkan model AI ke alat, file, dan database. Pelajari cara kerja arsitektur klien-server, server mana yang digunakan, dan cara menulis konfigurasi MCP yang berfungsi untuk Claude Desktop dan Claude Code.",
    date: "2026-03-21",
    author: "BrowseryTools Team",
    category: "Alat Developer",
    tags: ["MCP", "Claude", "alat AI", "Claude Code", "alat developer", "Anthropic"],
    readTime: 8,
    coverEmoji: "🔌",
    coverGradient: "from-emerald-500 to-teal-600",
    locale: "id",
  },
  {
    slug: "claude-md-guide-id",
    title: "File CLAUDE.md: Cara Memberi AI Konteks yang Dibutuhkan tentang Codebase Anda",
    description: "File CLAUDE.md di root proyek Anda memberi Claude Code konteks tetap tentang stack, konvensi, dan arsitektur Anda — menghilangkan koreksi berulang yang datang dengan asisten AI yang buta konteks.",
    date: "2026-03-21",
    author: "BrowseryTools Team",
    category: "Alat Developer",
    tags: ["Claude Code", "CLAUDE.md", "AI", "alat developer", "konteks codebase", "Anthropic"],
    readTime: 7,
    coverEmoji: "📄",
    coverGradient: "from-orange-500 to-amber-500",
    locale: "id",
  },
  {
    slug: "regex-tester-guide-id",
    title: "Regular Expression Dijelaskan: Panduan Praktis untuk Developer",
    description: "Pelajari 20% sintaks regex yang mencakup 80% kasus penggunaan dunia nyata — karakter class, quantifier, anchor, grup, dan flag — dengan contoh praktis untuk validasi email, nomor telepon, ekstraksi URL, dan lainnya.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Alat Developer",
    tags: ["regex", "regular expression", "developer", "pencocokan pola", "validasi"],
    readTime: 9,
    coverEmoji: "🔍",
    coverGradient: "from-orange-500 to-red-600",
    locale: "id",
  },
  {
    slug: "json-formatter-guide-id",
    title: "Pemformatan, Validasi, dan Debugging JSON: Panduan Lengkap Developer",
    description: "Panduan praktis untuk aturan sintaks JSON, error parse umum, pretty-printing vs minifikasi, data sangat bersarang, validasi JSON Schema, dan perbedaan JSON antara API dan file konfigurasi.",
    date: "2026-03-20",
    author: "BrowseryTools Team",
    category: "Alat Developer",
    tags: ["json", "pemformatan", "validasi", "api", "debugging"],
    readTime: 8,
    coverEmoji: "📋",
    coverGradient: "from-yellow-400 to-orange-500",
    locale: "id",
  },
  {
    slug: "curl-converter-guide-id",
    title: "cURL ke Kode: Konversi Permintaan API Antar Bahasa Secara Instan",
    description: "Pahami sintaks flag cURL, pola REST API umum, dan cara menerjemahkan perintah cURL secara akurat ke JavaScript fetch, Python requests, dan Node.js axios — termasuk alur kerja 'Copy as cURL' DevTools browser.",
    date: "2026-03-20",
    author: "BrowseryTools Team",
    category: "Alat Developer",
    tags: ["curl", "api", "http", "javascript", "python", "rest"],
    readTime: 8,
    coverEmoji: "🔄",
    coverGradient: "from-blue-500 to-cyan-500",
    locale: "id",
  },
];
