import type { BlogPost } from "./blog-data";

export const ptBRPostsB4: BlogPost[] = [
  {
    slug: "unix-timestamp-guide-pt-BR",
    title: "Unix Timestamps: O que São e Como Trabalhar com Eles",
    description: "Tudo que desenvolvedores precisam saber sobre o tempo Unix — o que é a época, o problema Y2K38, conversão de timestamps em JavaScript, Python e SQL, a armadilha de milissegundos vs segundos, fusos horários e timestamps em JWTs.",
    date: "2026-03-20",
    author: "BrowseryTools Team",
    category: "Ferramentas para Desenvolvedores",
    tags: ["unix timestamp", "época", "data e hora", "javascript", "python", "fuso horário"],
    readTime: 9,
    featured: false,
    coverEmoji: "⏱️",
    coverGradient: "from-violet-500 to-purple-700",
    locale: "pt-BR",
  },
  {
    slug: "url-encoder-guide-pt-BR",
    title: "Codificação de URL Explicada: Codificação por Porcentagem em Requisições HTTP",
    description: "Aprenda por que caracteres especiais quebram URLs, como a codificação por porcentagem funciona no nível de byte, a diferença crítica entre encodeURI e encodeURIComponent, e bugs comuns de codificação em aplicações reais.",
    date: "2026-03-19",
    author: "BrowseryTools Team",
    category: "Ferramentas para Desenvolvedores",
    tags: ["codificação de URL", "codificação por porcentagem", "HTTP", "desenvolvimento web", "JavaScript"],
    readTime: 7,
    featured: false,
    coverEmoji: "🔗",
    coverGradient: "from-cyan-500 to-blue-600",
    locale: "pt-BR",
  },
  {
    slug: "uuid-generator-guide-pt-BR",
    title: "UUIDs, NanoIDs e CUIDs: Escolhendo o Formato de ID Certo para o Seu Projeto",
    description: "Um mergulho profundo em UUID v1, v4 e v7, NanoID e CUID2 — o que é cada formato, como funciona a probabilidade de colisão e quando usar qual para chaves primárias de banco de dados, URLs e sistemas distribuídos.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Ferramentas para Desenvolvedores",
    tags: ["UUID", "NanoID", "CUID", "banco de dados", "sistemas distribuídos", "identificadores"],
    readTime: 8,
    featured: false,
    coverEmoji: "🆔",
    coverGradient: "from-violet-500 to-purple-700",
    locale: "pt-BR",
  },
  {
    slug: "chmod-guide-pt-BR",
    title: "Permissões de Arquivo Linux Explicadas: Um Guia Completo de chmod",
    description: "Um guia completo sobre permissões de arquivo Unix — o modelo proprietário/grupo/outros, notação octal (755, 644, 777), notação simbólica, setuid/setgid/sticky bit e exemplos práticos para servidores web e chaves SSH.",
    date: "2026-03-21",
    author: "BrowseryTools Team",
    category: "Ferramentas para Desenvolvedores",
    tags: ["chmod", "Linux", "permissões de arquivo", "Unix", "segurança", "sysadmin"],
    readTime: 8,
    featured: false,
    coverEmoji: "🔒",
    coverGradient: "from-green-500 to-teal-600",
    locale: "pt-BR",
  },
  {
    slug: "http-status-codes-guide-pt-BR",
    title: "Códigos de Status HTTP que Todo Desenvolvedor Deve Conhecer",
    description: "Uma referência prática dos códigos de status HTTP — as cinco categorias, análises detalhadas de 200, 201, 204, 301, 302, 304, 400, 401, 403, 404, 409, 422, 429, 500, 502, 503, além de orientações sobre design de APIs REST e depuração no DevTools.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Ferramentas para Desenvolvedores",
    tags: ["HTTP", "códigos de status", "API REST", "desenvolvimento web", "depuração"],
    readTime: 7,
    featured: false,
    coverEmoji: "📡",
    coverGradient: "from-orange-500 to-red-600",
    locale: "pt-BR",
  },
  {
    slug: "video-compression-guide-pt-BR",
    title: "Como Comprimir Arquivos de Vídeo sem Perder Qualidade",
    description: "Um guia prático de compressão de vídeo: como codecs como H.264, H.265, VP9 e AV1 funcionam, o que realmente controla o tamanho do arquivo, compressão com e sem perdas, e as melhores configurações para e-mail, web, redes sociais e arquivamento.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Ferramentas de Mídia",
    tags: ["compressão de vídeo", "H.264", "codec", "tamanho de arquivo", "edição de vídeo"],
    readTime: 7,
    featured: false,
    coverEmoji: "🎬",
    coverGradient: "from-red-500 to-pink-600",
    locale: "pt-BR",
  },
  {
    slug: "image-formats-guide-pt-BR",
    title: "JPEG vs PNG vs WebP vs AVIF: A Comparação Completa de Formatos de Imagem",
    description: "Entenda como JPEG, PNG, WebP e AVIF comprimem imagens internamente, quando usar cada formato, como eles afetam os Core Web Vitals e como servir o formato certo para o navegador certo.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Ferramentas de Imagem",
    tags: ["formatos de imagem", "JPEG", "PNG", "WebP", "AVIF", "desempenho web", "Core Web Vitals"],
    readTime: 8,
    featured: false,
    coverEmoji: "🖼️",
    coverGradient: "from-blue-500 to-cyan-500",
    locale: "pt-BR",
  },
  {
    slug: "exif-data-guide-pt-BR",
    title: "Metadados EXIF: O que Suas Fotos Revelam sobre Você (e Como Removê-los)",
    description: "Dados EXIF incorporam coordenadas GPS, números de série do dispositivo e timestamps em cada foto que você tira. Aprenda o que registra, os riscos reais à privacidade, casos famosos onde expôs localizações e como visualizar e remover esses dados.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Privacidade e Segurança",
    tags: ["EXIF", "metadados", "privacidade", "GPS", "segurança de fotos", "dados de imagem"],
    readTime: 8,
    featured: false,
    coverEmoji: "📷",
    coverGradient: "from-amber-500 to-orange-600",
    locale: "pt-BR",
  },
  {
    slug: "svg-guide-pt-BR",
    title: "Arquivos SVG: Um Guia Completo para Desenvolvedores e Designers",
    description: "Tudo que você precisa saber sobre SVG: o formato vetorial baseado em XML que escala infinitamente, como os elementos principais como path e viewBox funcionam, estilização e animação CSS, otimização SVGO, riscos de XSS de SVGs enviados por usuários e quando converter SVG para PNG.",
    date: "2026-03-21",
    author: "BrowseryTools Team",
    category: "Ferramentas para Desenvolvedores",
    tags: ["SVG", "gráficos vetoriais", "desenvolvimento web", "CSS", "SVGO", "ícones"],
    readTime: 9,
    featured: false,
    coverEmoji: "✏️",
    coverGradient: "from-violet-500 to-purple-600",
    locale: "pt-BR",
  },
  {
    slug: "lorem-ipsum-guide-pt-BR",
    title: "Lorem Ipsum: Origem, Usos e Por que Designers Não Podem Viver sem Ele",
    description: "A história completa por trás do Lorem Ipsum — do texto filosófico de Cícero de 45 a.C. aos fluxos de trabalho de design modernos. Aprenda quando usá-lo, quando evitá-lo e como gerar a quantidade exata que você precisa.",
    date: "2026-03-17",
    author: "BrowseryTools Team",
    category: "Ferramentas de Texto",
    tags: ["lorem ipsum", "texto de espaço reservado", "design", "tipografia"],
    readTime: 6,
    featured: false,
    coverEmoji: "📝",
    coverGradient: "from-slate-500 to-gray-600",
    locale: "pt-BR",
  },
  {
    slug: "markdown-complete-guide-pt-BR",
    title: "Markdown: Referência Completa de Sintaxe para Escritores e Desenvolvedores",
    description: "Um guia abrangente sobre Markdown — quem o criou e por quê, referência completa de sintaxe do básico a recursos estendidos, variantes de Markdown (CommonMark, GFM, MDX) e erros comuns a evitar.",
    date: "2026-03-18",
    author: "BrowseryTools Team",
    category: "Ferramentas de Texto",
    tags: ["markdown", "sintaxe", "escrita", "documentação", "desenvolvedores"],
    readTime: 7,
    featured: false,
    coverEmoji: "✍️",
    coverGradient: "from-indigo-500 to-blue-600",
    locale: "pt-BR",
  },
  {
    slug: "text-diff-guide-pt-BR",
    title: "Como Comparar Arquivos de Texto e Encontrar Diferenças sem Nenhum Software",
    description: "Aprenda como os algoritmos de diff de texto funcionam, como ler a saída de diff unificado, a diferença entre diffs em nível de linha e palavra, e como o git diff funciona por baixo dos panos.",
    date: "2026-03-19",
    author: "BrowseryTools Team",
    category: "Ferramentas para Desenvolvedores",
    tags: ["diff", "comparação de texto", "git", "revisão de código", "comparação de arquivos"],
    readTime: 6,
    featured: false,
    coverEmoji: "🔍",
    coverGradient: "from-emerald-500 to-teal-600",
    locale: "pt-BR",
  },
  {
    slug: "text-encryption-guide-pt-BR",
    title: "Criptografia de Texto no Lado do Cliente: Como Proteger Dados Sensíveis no Navegador",
    description: "Um guia prático sobre criptografia de texto baseada no navegador — o que a criptografia no lado do cliente realmente significa, algoritmos simétricos vs assimétricos, derivação de chave a partir de senhas e as limitações reais da criptografia no navegador.",
    date: "2026-03-20",
    author: "BrowseryTools Team",
    category: "Segurança",
    tags: ["criptografia", "AES", "segurança", "privacidade", "criptografia", "navegador"],
    readTime: 7,
    featured: false,
    coverEmoji: "🔐",
    coverGradient: "from-rose-500 to-pink-600",
    locale: "pt-BR",
  },
  {
    slug: "word-frequency-guide-pt-BR",
    title: "Análise de Frequência de Palavras: Uma Ferramenta para Escritores, SEO e Pesquisa",
    description: "Como a análise de frequência de palavras revela padrões de escrita, densidade de palavras-chave e temas do documento. Aborda stop words, TF-IDF explicado de forma simples, casos de uso para escritores e SEO, e aplicações acadêmicas como atribuição de autoria.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Ferramentas de Texto",
    tags: ["frequência de palavras", "análise de texto", "SEO", "escrita", "PLN", "conteúdo"],
    readTime: 6,
    featured: false,
    coverEmoji: "📊",
    coverGradient: "from-violet-500 to-purple-600",
    locale: "pt-BR",
  },
];
