import type { BlogPost } from "./blog-data";

export const dePostsB2: BlogPost[] = [
  {
    slug: "password-security-guide-de",
    title: "Passwortsicherheit: Warum die meisten Passwörter schwach sind und wie Sie starke erstellen",
    description:
      "Die meisten Menschen verwenden schwache Passwörter, ohne es zu merken. Erfahren Sie, was ein starkes Passwort ausmacht, wie Sie Ihres sofort prüfen und unknackbare Passwörter erzeugen — alles privat in Ihrem Browser.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Sicherheit",
    tags: ["Passwort", "Sicherheit", "Hacking", "Passwortgenerator", "Passwortstärke"],
    readTime: 8,
    featured: false,
    coverEmoji: "🛡️",
    coverGradient: "from-green-500 to-emerald-600",
    locale: "de",
  },
  {
    slug: "remove-image-background-free-de",
    title: "Bildhintergrund kostenlos entfernen — ohne Canva, ohne Photoshop",
    description:
      "Entfernen Sie Hintergründe von Fotos sofort per KI, direkt in Ihrem Browser. Keine Uploads, keine Abonnements, keine Wasserzeichen. Ihre Bilder verlassen niemals Ihr Gerät.",
    date: "2026-02-12",
    author: "BrowseryTools Team",
    category: "Bildwerkzeuge",
    tags: ["Hintergrund entfernen", "Bildbearbeitung", "KI", "kostenlos", "kein Upload", "Datenschutz"],
    readTime: 6,
    featured: false,
    coverEmoji: "🖼️",
    coverGradient: "from-pink-500 to-rose-600",
    locale: "de",
  },
  {
    slug: "boost-productivity-pomodoro-todo-de",
    title: "10 Wege, Ihre Produktivität mit kostenlosen Browser-Tools zu steigern",
    description:
      "Vom Pomodoro-Timer über Aufgabenlisten bis hin zur Weltuhr und zum Ausgaben-Tracker — entdecken Sie die Produktivitäts-Tools, die vollständig in Ihrem Browser laufen, ganz ohne Datensammlung.",
    date: "2026-02-10",
    author: "BrowseryTools Team",
    category: "Produktivität",
    tags: ["Produktivität", "Pomodoro", "Aufgabenliste", "Fokus", "Zeitmanagement"],
    readTime: 7,
    featured: false,
    coverEmoji: "🎯",
    coverGradient: "from-blue-500 to-cyan-600",
    locale: "de",
  },
  {
    slug: "free-image-tools-guide-de",
    title: "Der komplette Leitfaden zu kostenlosen Bildwerkzeugen — komprimieren, konvertieren, skalieren ohne Upload",
    description:
      "Bildkomprimierung, Formatkonvertierung, Skalierung, Farbkorrektur und Hintergrundentfernung — alles lokal in Ihrem Browser verarbeitet, ohne Uploads und ohne Kosten.",
    date: "2026-02-08",
    author: "BrowseryTools Team",
    category: "Bildwerkzeuge",
    tags: ["Bildkomprimierung", "Bildkonverter", "Skalieren", "kostenlos", "kein Upload"],
    readTime: 8,
    featured: false,
    coverEmoji: "🎨",
    coverGradient: "from-violet-500 to-fuchsia-600",
    locale: "de",
  },
  {
    slug: "qr-code-generator-guide-de",
    title: "QR-Codes kostenlos erstellen — für Links, Text, WLAN & Visitenkarten",
    description:
      "Erstellen Sie unbegrenzt QR-Codes für jeden Inhalt — URLs, einfachen Text, WLAN-Zugangsdaten, vCards — mit voller Anpassbarkeit. 100 % kostenlos, ohne Anmeldung, funktioniert offline.",
    date: "2026-02-05",
    author: "BrowseryTools Team",
    category: "Hilfswerkzeuge",
    tags: ["QR-Code", "QR-Generator", "kostenloser QR-Code", "offline", "Visitenkarte"],
    readTime: 5,
    featured: false,
    coverEmoji: "📱",
    coverGradient: "from-teal-500 to-green-600",
    locale: "de",
  },
  {
    slug: "text-tools-for-writers-developers-de",
    title: "Die besten kostenlosen Text-Tools für Autoren, Entwickler und Content-Ersteller",
    description:
      "Textumwandler für Groß- und Kleinschreibung, Lorem-ipsum-Generator, Zeichenzähler, Text-Vergleichstool, Markdown-Editor und mehr. Alles, was Autoren oder Entwickler brauchen — kostenlos und privat.",
    date: "2026-02-03",
    author: "BrowseryTools Team",
    category: "Textwerkzeuge",
    tags: ["Text-Tools", "Schreiben", "Markdown", "Textumwandler", "Lorem ipsum"],
    readTime: 6,
    featured: false,
    coverEmoji: "✍️",
    coverGradient: "from-slate-500 to-gray-600",
    locale: "de",
  },
  {
    slug: "base64-encoding-guide-de",
    title: "Was ist Base64-Kodierung? Ein vollständiger Leitfaden mit Beispielen",
    description:
      "Erfahren Sie, was Base64-Kodierung ist, warum es sie gibt, wo sie eingesetzt wird und wie Sie Base64-Zeichenketten sofort in Ihrem Browser kodieren und dekodieren — ohne Software zu installieren.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Entwicklerwerkzeuge",
    tags: ["Base64", "Kodierung", "Entwickler", "Binärdaten", "Datenformate"],
    readTime: 7,
    featured: false,
    coverEmoji: "🔡",
    coverGradient: "from-cyan-500 to-blue-600",
    locale: "de",
  },
  {
    slug: "jwt-decoder-guide-de",
    title: "JWT-Tokens in Ihrem Browser dekodieren und verifizieren",
    description:
      "JWT-Tokens sind in der modernen Authentifizierung allgegenwärtig. Erfahren Sie, was sie enthalten, wie Sie sie dekodieren, Ablaufprobleme erkennen und Auth-Probleme beheben — alles privat in Ihrem Browser.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Entwicklerwerkzeuge",
    tags: ["JWT", "Authentifizierung", "Token", "OAuth", "Sicherheit", "Entwickler"],
    readTime: 8,
    featured: false,
    coverEmoji: "🔑",
    coverGradient: "from-yellow-500 to-amber-600",
    locale: "de",
  },
  {
    slug: "css-gradient-generator-guide-de",
    title: "CSS-Verlaufsgenerator: Schöne Farbverläufe erstellen, ohne Code zu schreiben",
    description:
      "Erstellen Sie lineare, radiale und konische CSS-Farbverläufe visuell mit Live-Vorschau. Kopieren Sie produktionsreifes CSS mit einem Klick — ganz ohne Designsoftware.",
    date: "2026-02-20",
    author: "BrowseryTools Team",
    category: "Designwerkzeuge",
    tags: ["CSS", "Farbverlauf", "Design", "Frontend", "UI", "Farben"],
    readTime: 5,
    featured: false,
    coverEmoji: "🌈",
    coverGradient: "from-purple-500 to-pink-600",
    locale: "de",
  },
  {
    slug: "hash-generator-guide-de",
    title: "MD5, SHA-256, SHA-512: Kostenloser Hash-Generator und wann Sie welchen verwenden",
    description:
      "Verstehen Sie den Unterschied zwischen MD5, SHA-1, SHA-256 und SHA-512. Erzeugen Sie Datei- und Text-Hashes sofort in Ihrem Browser. Erfahren Sie, wann welcher Algorithmus geeignet ist.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Sicherheit",
    tags: ["Hash", "MD5", "SHA-256", "SHA-512", "Prüfsumme", "Kryptografie"],
    readTime: 7,
    featured: false,
    coverEmoji: "#️⃣",
    coverGradient: "from-gray-500 to-slate-700",
    locale: "de",
  },
  {
    slug: "screen-recorder-guide-de",
    title: "Ihren Bildschirm aufnehmen, ohne Software zu installieren",
    description:
      "Ihr Browser kann mithilfe der Screen Capture API Ihren Bildschirm, ein Fenster oder einen Tab aufnehmen. Erfahren Sie, wie Sie Videos für Anleitungen, Fehlerberichte und Demos aufzeichnen — ganz ohne Erweiterungen.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Hilfswerkzeuge",
    tags: ["Bildschirmaufnahme", "Screen Capture", "Anleitung", "Video", "Browser-API"],
    readTime: 5,
    featured: false,
    coverEmoji: "🎬",
    coverGradient: "from-red-500 to-rose-600",
    locale: "de",
  },
  {
    slug: "fake-data-generator-guide-de",
    title: "Realistische Testdaten (JSON & CSV) kostenlos erzeugen",
    description:
      "Füllen Sie Datenbanken, erstellen Sie UI-Prototypen und schreiben Sie Tests mit realistischen Fake-Namen, -E-Mails, -Adressen, -Telefonnummern und mehr — exportiert als JSON oder CSV, alles in Ihrem Browser.",
    date: "2026-02-16",
    author: "BrowseryTools Team",
    category: "Entwicklerwerkzeuge",
    tags: ["Fake-Daten", "Testdaten", "Mock-Daten", "JSON", "CSV", "Entwicklerwerkzeuge"],
    readTime: 6,
    featured: false,
    coverEmoji: "🤖",
    coverGradient: "from-green-500 to-teal-600",
    locale: "de",
  },
  {
    slug: "cron-expression-guide-de",
    title: "Cron-Ausdrücke erklärt: Wie man Cron-Zeitpläne liest und schreibt",
    description:
      "Die Cron-Syntax ist kryptisch, bis Sie die fünf Felder verstehen. Lernen Sie, Cron-Ausdrücke zu lesen und zu schreiben, häufige Fehler zu vermeiden und jeden Zeitplan sofort in Ihrem Browser zu analysieren.",
    date: "2026-02-14",
    author: "BrowseryTools Team",
    category: "Entwicklerwerkzeuge",
    tags: ["Cron", "Cron-Ausdruck", "Scheduler", "DevOps", "Automatisierung", "Linux"],
    readTime: 7,
    featured: false,
    coverEmoji: "⏰",
    coverGradient: "from-orange-500 to-red-600",
    locale: "de",
  },
  {
    slug: "bmi-calculator-guide-de",
    title: "BMI-Rechner: Was er ist, wie man ihn berechnet und was er wirklich bedeutet",
    description:
      "Berechnen Sie Ihren BMI sofort in metrischen oder imperialen Einheiten. Verstehen Sie, was die Zahl bedeutet, welche Grenzen sie hat und wie ein gesundes Gewicht für Ihre Körpergröße aussieht.",
    date: "2026-05-21",
    author: "BrowseryTools Team",
    category: "Gesundheit & Fitness",
    tags: ["BMI", "Body-Mass-Index", "Gesundheit", "Gewicht", "Rechner"],
    readTime: 6,
    featured: false,
    coverEmoji: "⚖️",
    coverGradient: "from-teal-500 to-cyan-600",
    locale: "de",
  },
];
