export interface BlogPost {
  slug: string;
  title: string;
  description: string;
  date: string;
  author: string;
  category: string;
  tags: string[];
  readTime: number; // minutes
  featured?: boolean;
  coverEmoji: string;
  coverGradient: string;
}

export const blogPosts: BlogPost[] = [
  {
    slug: "why-browser-tools-keep-your-data-private",
    title: "Why Browser-Based Tools Are the Safest Way to Handle Your Data",
    description: "Learn how browser-based tools like BrowseryTools process everything locally on your device — your files, passwords, and sensitive data never leave your computer.",
    date: "2026-02-20",
    author: "BrowseryTools Team",
    category: "Privacy & Security",
    tags: ["privacy", "security", "browser", "local processing", "no upload"],
    readTime: 7,
    featured: true,
    coverEmoji: "🔒",
    coverGradient: "from-indigo-500 to-purple-600",
  },
  {
    slug: "best-free-developer-tools-browser",
    title: "The Ultimate Guide to Free Developer Tools in Your Browser",
    description: "JSON formatter, Base64 encoder, JWT decoder, regex tester, UUID generator and more — all free, all in your browser. No installs, no ads, no sign-up.",
    date: "2026-02-18",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["developer", "JSON", "Base64", "JWT", "regex", "UUID", "free tools"],
    readTime: 9,
    featured: true,
    coverEmoji: "⚡",
    coverGradient: "from-amber-500 to-orange-600",
  },
  {
    slug: "password-security-guide",
    title: "Password Security: Why Most Passwords Are Weak and How to Create Strong Ones",
    description: "Most people use weak passwords without realizing it. Learn what makes a strong password, how to check yours instantly, and generate uncrackable ones — all privately in your browser.",
    date: "2026-02-15",
    author: "BrowseryTools Team",
    category: "Security",
    tags: ["password", "security", "hacking", "password generator", "password strength"],
    readTime: 8,
    featured: false,
    coverEmoji: "🛡️",
    coverGradient: "from-green-500 to-emerald-600",
  },
  {
    slug: "remove-image-background-free",
    title: "How to Remove Image Backgrounds for Free — No Canva, No Photoshop",
    description: "Remove backgrounds from photos instantly using AI, right in your browser. No uploads, no subscriptions, no watermarks. Your images never leave your device.",
    date: "2026-02-12",
    author: "BrowseryTools Team",
    category: "Image Tools",
    tags: ["background removal", "image editing", "AI", "free", "no upload", "privacy"],
    readTime: 6,
    featured: false,
    coverEmoji: "🖼️",
    coverGradient: "from-pink-500 to-rose-600",
  },
  {
    slug: "boost-productivity-pomodoro-todo",
    title: "10 Ways to Boost Your Productivity with Free Browser Tools",
    description: "From the Pomodoro timer to todo lists, world clock to expense tracker — discover the productivity tools that work entirely in your browser with zero data collection.",
    date: "2026-02-10",
    author: "BrowseryTools Team",
    category: "Productivity",
    tags: ["productivity", "pomodoro", "todo", "focus", "time management"],
    readTime: 7,
    featured: false,
    coverEmoji: "🎯",
    coverGradient: "from-blue-500 to-cyan-600",
  },
  {
    slug: "free-image-tools-guide",
    title: "The Complete Guide to Free Image Tools — Compress, Convert, Resize Without Uploading",
    description: "Image compression, format conversion, resizing, color correction, and background removal — all processed locally in your browser with zero uploads and zero cost.",
    date: "2026-02-08",
    author: "BrowseryTools Team",
    category: "Image Tools",
    tags: ["image compression", "image converter", "resize", "free", "no upload"],
    readTime: 8,
    featured: false,
    coverEmoji: "🎨",
    coverGradient: "from-violet-500 to-fuchsia-600",
  },
  {
    slug: "qr-code-generator-guide",
    title: "How to Generate QR Codes for Free — For Links, Text, WiFi & Business Cards",
    description: "Generate unlimited QR codes for any content — URLs, plain text, WiFi credentials, vCards — with full customization. 100% free, no sign-up, works offline.",
    date: "2026-02-05",
    author: "BrowseryTools Team",
    category: "Utility Tools",
    tags: ["QR code", "QR generator", "free QR code", "offline", "business card"],
    readTime: 5,
    featured: false,
    coverEmoji: "📱",
    coverGradient: "from-teal-500 to-green-600",
  },
  {
    slug: "text-tools-for-writers-developers",
    title: "The Best Free Text Tools for Writers, Developers and Content Creators",
    description: "Text case converter, Lorem ipsum generator, character counter, text diff tool, Markdown editor and more. Everything a writer or developer needs — free and private.",
    date: "2026-02-03",
    author: "BrowseryTools Team",
    category: "Text Tools",
    tags: ["text tools", "writing", "markdown", "text converter", "lorem ipsum"],
    readTime: 6,
    featured: false,
    coverEmoji: "✍️",
    coverGradient: "from-slate-500 to-gray-600",
  },
  {
    slug: "base64-encoding-guide",
    title: "What is Base64 Encoding? A Complete Guide with Examples",
    description: "Learn what Base64 encoding is, why it exists, where it's used, and how to encode and decode Base64 strings instantly in your browser — no tools to install.",
    date: "2026-02-22",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["base64", "encoding", "developer", "binary", "data formats"],
    readTime: 7,
    featured: false,
    coverEmoji: "🔡",
    coverGradient: "from-cyan-500 to-blue-600",
  },
  {
    slug: "jwt-decoder-guide",
    title: "How to Decode and Verify JWT Tokens in Your Browser",
    description: "JWT tokens are everywhere in modern authentication. Learn what they contain, how to decode them, spot expiry issues, and debug auth problems — all privately in your browser.",
    date: "2026-02-21",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["JWT", "authentication", "token", "OAuth", "security", "developer"],
    readTime: 8,
    featured: false,
    coverEmoji: "🔑",
    coverGradient: "from-yellow-500 to-amber-600",
  },
  {
    slug: "css-gradient-generator-guide",
    title: "CSS Gradient Generator: Create Beautiful Gradients Without Writing Code",
    description: "Visually build linear, radial, and conic CSS gradients with a live preview. Copy production-ready CSS with one click — no design software needed.",
    date: "2026-02-20",
    author: "BrowseryTools Team",
    category: "Design Tools",
    tags: ["CSS", "gradient", "design", "frontend", "UI", "colors"],
    readTime: 5,
    featured: false,
    coverEmoji: "🌈",
    coverGradient: "from-purple-500 to-pink-600",
  },
  {
    slug: "hash-generator-guide",
    title: "MD5, SHA-256, SHA-512: Free Hash Generator and When to Use Each",
    description: "Understand the difference between MD5, SHA-1, SHA-256, and SHA-512. Generate file and text hashes instantly in your browser. Learn when each algorithm is appropriate.",
    date: "2026-02-19",
    author: "BrowseryTools Team",
    category: "Security",
    tags: ["hash", "MD5", "SHA-256", "SHA-512", "checksum", "cryptography"],
    readTime: 7,
    featured: false,
    coverEmoji: "#️⃣",
    coverGradient: "from-gray-500 to-slate-700",
  },
  {
    slug: "screen-recorder-guide",
    title: "Record Your Screen Without Installing Any Software",
    description: "Your browser can record your screen, window, or tab using the Screen Capture API. Learn how to capture video for tutorials, bug reports, and demos — no extensions needed.",
    date: "2026-02-17",
    author: "BrowseryTools Team",
    category: "Utility Tools",
    tags: ["screen recorder", "screen capture", "tutorial", "video", "browser API"],
    readTime: 5,
    featured: false,
    coverEmoji: "🎬",
    coverGradient: "from-red-500 to-rose-600",
  },
  {
    slug: "fake-data-generator-guide",
    title: "How to Generate Realistic Fake Test Data (JSON & CSV) for Free",
    description: "Populate databases, prototype UIs, and write tests with realistic fake names, emails, addresses, phone numbers, and more — exported as JSON or CSV, all in your browser.",
    date: "2026-02-16",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["fake data", "test data", "mock data", "JSON", "CSV", "developer tools"],
    readTime: 6,
    featured: false,
    coverEmoji: "🤖",
    coverGradient: "from-green-500 to-teal-600",
  },
  {
    slug: "cron-expression-guide",
    title: "Cron Expressions Explained: How to Read and Write Cron Schedules",
    description: "Cron syntax is cryptic until you understand the five fields. Learn to read and write cron expressions, avoid common mistakes, and parse any schedule instantly in your browser.",
    date: "2026-02-14",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["cron", "cron expression", "scheduler", "DevOps", "automation", "Linux"],
    readTime: 7,
    featured: false,
    coverEmoji: "⏰",
    coverGradient: "from-orange-500 to-red-600",
  },
  {
    slug: "bmi-calculator-guide",
    title: "BMI Calculator: What It Is, How to Calculate It, and What It Really Means",
    description: "Calculate your BMI instantly in metric or imperial units. Understand what the number means, its limitations, and what healthy weight looks like for your height.",
    date: "2026-02-24",
    author: "BrowseryTools Team",
    category: "Health & Fitness",
    tags: ["BMI", "body mass index", "health", "weight", "calculator"],
    readTime: 6,
    featured: false,
    coverEmoji: "⚖️",
    coverGradient: "from-teal-500 to-cyan-600",
  },
  {
    slug: "color-contrast-accessibility-guide",
    title: "Color Contrast and Web Accessibility: A Complete WCAG Guide",
    description: "Learn why color contrast matters for accessibility, how to calculate contrast ratios, what WCAG AA and AAA mean, and how to check any color combination instantly.",
    date: "2026-02-23",
    author: "BrowseryTools Team",
    category: "Design Tools",
    tags: ["accessibility", "WCAG", "color contrast", "a11y", "design", "UX"],
    readTime: 8,
    featured: false,
    coverEmoji: "♿",
    coverGradient: "from-blue-500 to-indigo-600",
  },
  {
    slug: "sql-formatter-guide",
    title: "How to Format SQL Queries for Readability and Debugging",
    description: "Unformatted SQL is a debugging nightmare. Learn SQL formatting conventions, how to read complex queries with JOINs and subqueries, and format any query instantly in your browser.",
    date: "2026-02-22",
    author: "BrowseryTools Team",
    category: "Developer Tools",
    tags: ["SQL", "database", "formatting", "MySQL", "PostgreSQL", "developer"],
    readTime: 7,
    featured: false,
    coverEmoji: "🗄️",
    coverGradient: "from-violet-500 to-purple-600",
  },
  {
    slug: "habit-tracker-guide",
    title: "How to Build Good Habits: The Science of Streaks and Daily Tracking",
    description: "Learn the psychology behind habit formation, why streaks work, and how to use a simple browser-based habit tracker to build lasting routines without an app subscription.",
    date: "2026-02-21",
    author: "BrowseryTools Team",
    category: "Productivity",
    tags: ["habits", "habit tracker", "productivity", "streaks", "self-improvement"],
    readTime: 7,
    featured: false,
    coverEmoji: "✅",
    coverGradient: "from-emerald-500 to-green-600",
  },
];

export function getBlogPost(slug: string): BlogPost | undefined {
  return blogPosts.find((p) => p.slug === slug);
}

export function getFeaturedPosts(): BlogPost[] {
  return blogPosts.filter((p) => p.featured);
}

export function getPostsByCategory(category: string): BlogPost[] {
  return blogPosts.filter((p) => p.category === category);
}

export function getAllCategories(): string[] {
  return [...new Set(blogPosts.map((p) => p.category))];
}
