/**
 * Currency names mapping for display purposes
 * Maps 3-character currency codes to their full names
 */
export const currencyNames: Record<string, string> = {
  // Major currencies
  USD: "US Dollar",
  EUR: "Euro",
  GBP: "British Pound Sterling",
  JPY: "Japanese Yen",
  CAD: "Canadian Dollar",
  AUD: "Australian Dollar",
  CHF: "Swiss Franc",
  CNY: "Chinese Yuan",
  SEK: "Swedish Krona",
  NOK: "Norwegian Krone",
  DKK: "Danish Krone",
  PLN: "Polish Zloty",
  CZK: "Czech Koruna",
  HUF: "Hungarian Forint",
  RON: "Romanian Leu",
  BGN: "Bulgarian Lev",
  HRK: "Croatian Kuna",
  RSD: "Serbian Dinar",
  MKD: "Macedonian Denar",
  ALL: "Albanian Lek",
  BAM: "Bosnia and Herzegovina Convertible Mark",
  MDL: "Moldovan Leu",
  UAH: "Ukrainian Hryvnia",
  BYR: "Belarusian Ruble",
  RUB: "Russian Ruble",
  KZT: "Kazakhstani Tenge",
  UZS: "Uzbekistani Som",
  KGS: "Kyrgyzstani Som",
  TJS: "Tajikistani Somoni",
  TMT: "Turkmenistani Manat",
  GEL: "Georgian Lari",
  AMD: "Armenian Dram",
  AZN: "Azerbaijani Manat",
  TRY: "Turkish Lira",
  ILS: "Israeli New Shekel",
  JOD: "Jordanian Dinar",
  LBP: "Lebanese Pound",
  SYP: "Syrian Pound",
  IQD: "Iraqi Dinar",
  IRR: "Iranian Rial",
  SAR: "Saudi Riyal",
  AED: "UAE Dirham",
  QAR: "Qatari Riyal",
  KWD: "Kuwaiti Dinar",
  BHD: "Bahraini Dinar",
  OMR: "Omani Rial",
  YER: "Yemeni Rial",
  AFN: "Afghan Afghani",
  PKR: "Pakistani Rupee",
  INR: "Indian Rupee",
  NPR: "Nepalese Rupee",
  BTN: "Bhutanese Ngultrum",
  BDT: "Bangladeshi Taka",
  LKR: "Sri Lankan Rupee",
  MVR: "Maldivian Rufiyaa",
  MMK: "Myanmar Kyat",
  THB: "Thai Baht",
  LAK: "Lao Kip",
  KHR: "Cambodian Riel",
  VND: "Vietnamese Dong",
  IDR: "Indonesian Rupiah",
  MYR: "Malaysian Ringgit",
  SGD: "Singapore Dollar",
  BND: "Brunei Dollar",
  PHP: "Philippine Peso",
  KRW: "South Korean Won",
  TWD: "Taiwan New Dollar",
  HKD: "Macanese Pataca",
  MOP: "Macanese Pataca",
  NZD: "New Zealand Dollar",
  FJD: "Fijian Dollar",
  PGK: "Papua New Guinean Kina",
  SBD: "Solomon Islands Dollar",
  VUV: "Vanuatu Vatu",
  WST: "Samoan Tala",
  TOP: "Tongan Pa'anga",
  XPF: "CFP Franc",
  ISK: "Icelandic Krona",
  GGP: "Guernsey Pound",
  JEP: "Jersey Pound",
  IMP: "Isle of Man Pound",
  GIP: "Gibraltar Pound",
  FKP: "Falkland Islands Pound",
  SHP: "Saint Helena Pound",
  BMD: "Bermudian Dollar",
  BSD: "Bahamian Dollar",
  BBD: "Barbadian Dollar",
  XCD: "East Caribbean Dollar",
  KYD: "Cayman Islands Dollar",
  JMD: "Jamaican Dollar",
  TTD: "Trinidad and Tobago Dollar",
  BZD: "Belize Dollar",
  GTQ: "Guatemalan Quetzal",
  HNL: "Honduran Lempira",
  NIO: "Nicaraguan Cordoba",
  CRC: "Costa Rican Colon",
  PAB: "Panamanian Balboa",
  DOP: "Dominican Peso",
  HTG: "Haitian Gourde",
  CUP: "Cuban Peso",
  ARS: "Argentine Peso",
  BOB: "Bolivian Boliviano",
  CLP: "Chilean Peso",
  COP: "Colombian Peso",
  PEN: "Peruvian Sol",
  VEF: "Venezuelan Bolivar",
  GYD: "Guyanese Dollar",
  SRD: "Surinamese Dollar",
  BRL: "Brazilian Real",
  UYU: "Uruguayan Peso",
  PYG: "Paraguayan Guarani",
  MXN: "Mexican Peso",
  ZAR: "South African Rand",
  BWP: "Botswana Pula",
  SZL: "Swazi Lilangeni",
  LSL: "Lesotho Loti",
  NAD: "Namibian Dollar",
  ZMW: "Zambian Kwacha",
  ZWD: "Zimbabwean Dollar",
  AOA: "Angolan Kwanza",
  ZMK: "Zambian Kwacha (pre-2013)",
  MZN: "Mozambican Metical",
  MWK: "Malawian Kwacha",
  TZS: "Tanzanian Shilling",
  UGX: "Ugandan Shilling",
  KES: "Kenyan Shilling",
  ETB: "Ethiopian Birr",
  DJF: "Djiboutian Franc",
  SOS: "Somali Shilling",
  ERN: "Eritrean Nakfa",
  SDG: "Sudanese Pound",
  EGP: "Egyptian Pound",
  LYD: "Libyan Dinar",
  TND: "Tunisian Dinar",
  DZD: "Algerian Dinar",
  MAD: "Moroccan Dirham",
  MRO: "Mauritanian Ouguiya",
  XOF: "West African CFA Franc",
  XAF: "Central African CFA Franc",
  GMD: "Gambian Dalasi",
  GNF: "Guinean Franc",
  SLL: "Sierra Leonean Leone",
  LRD: "Liberian Dollar",
  CDF: "Congolese Franc",
  RWF: "Rwandan Franc",
  BIF: "Burundian Franc",
  KMF: "Comorian Franc",
  SCR: "Seychellois Rupee",
  MUR: "Mauritian Rupee",
  MGA: "Malagasy Ariary",
  AQD: "Antarctic Dollar",
  ANG: "Netherlands Antillean Guilder",
  AWG: "Aruban Florin",
  BZD: "Belize Dollar",
  BOB: "Bolivian Boliviano",
  CLP: "Chilean Peso",
  COP: "Colombian Peso",
  CRC: "Costa Rican Colon",
  CUP: "Cuban Peso",
  DOP: "Dominican Peso",
  GTQ: "Guatemalan Quetzal",
  HNL: "Honduran Lempira",
  JMD: "Jamaican Dollar",
  MXN: "Mexican Peso",
  NIO: "Nicaraguan Cordoba",
  PAB: "Panamanian Balboa",
  PYG: "Paraguayan Guarani",
  PEN: "Peruvian Sol",
  SRD: "Surinamese Dollar",
  TTD: "Trinidad and Tobago Dollar",
  UYU: "Uruguayan Peso",
  VEF: "Venezuelan Bolivar",
  KPW: "North Korean Won",
  STD: "Sao Tome and Principe Dobra",
  GHS: "Ghanaian Cedi",
  NGN: "Nigerian Naira",
  CVE: "Cape Verdean Escudo",
  STN: "Sao Tome and Principe Dobra (new)",
  MRO: "Mauritanian Ouguiya",
  MRU: "Mauritanian Ouguiya (new)",
  VES: "Venezuelan Bolivar (new)",
  BYN: "Belarusian Ruble (new)",
  TMT: "Turkmenistani Manat",
  TJS: "Tajikistani Somoni",
  UZS: "Uzbekistani Som",
  KGS: "Kyrgyzstani Som",
  KZT: "Kazakhstani Tenge",
  RUB: "Russian Ruble",
  UAH: "Ukrainian Hryvnia",
  BYR: "Belarusian Ruble",
  MDL: "Moldovan Leu",
  RON: "Romanian Leu",
  BGN: "Bulgarian Lev",
  HRK: "Croatian Kuna",
  RSD: "Serbian Dinar",
  MKD: "Macedonian Denar",
  ALL: "Albanian Lek",
  BAM: "Bosnia and Herzegovina Convertible Mark",
  GEL: "Georgian Lari",
  AMD: "Armenian Dram",
  AZN: "Azerbaijani Manat",
  TRY: "Turkish Lira",
  ILS: "Israeli New Shekel",
  JOD: "Jordanian Dinar",
  LBP: "Lebanese Pound",
  SYP: "Syrian Pound",
  IQD: "Iraqi Dinar",
  IRR: "Iranian Rial",
  SAR: "Saudi Riyal",
  AED: "UAE Dirham",
  QAR: "Qatari Riyal",
  KWD: "Kuwaiti Dinar",
  BHD: "Bahraini Dinar",
  OMR: "Omani Rial",
  YER: "Yemeni Rial",
  AFN: "Afghan Afghani",
  PKR: "Pakistani Rupee",
  INR: "Indian Rupee",
  NPR: "Nepalese Rupee",
  BTN: "Bhutanese Ngultrum",
  BDT: "Bangladeshi Taka",
  LKR: "Sri Lankan Rupee",
  MVR: "Maldivian Rufiyaa",
  MMK: "Myanmar Kyat",
  THB: "Thai Baht",
  LAK: "Lao Kip",
  KHR: "Cambodian Riel",
  VND: "Vietnamese Dong",
  IDR: "Indonesian Rupiah",
  MYR: "Malaysian Ringgit",
  SGD: "Singapore Dollar",
  BND: "Brunei Dollar",
  PHP: "Philippine Peso",
  KRW: "South Korean Won",
  TWD: "Taiwan New Dollar",
  HKD: "Hong Kong Dollar",
  MOP: "Macanese Pataca",
  NZD: "New Zealand Dollar",
  FJD: "Fijian Dollar",
  PGK: "Papua New Guinean Kina",
  SBD: "Solomon Islands Dollar",
  VUV: "Vanuatu Vatu",
  WST: "Samoan Tala",
  TOP: "Tongan Pa'anga",
  XPF: "CFP Franc",
  ISK: "Icelandic Krona",
  GGP: "Guernsey Pound",
  JEP: "Jersey Pound",
  IMP: "Isle of Man Pound",
  GIP: "Gibraltar Pound",
  FKP: "Falkland Islands Pound",
  SHP: "Saint Helena Pound",
  BMD: "Bermudian Dollar",
  BSD: "Bahamian Dollar",
  BBD: "Barbadian Dollar",
  XCD: "East Caribbean Dollar",
  KYD: "Cayman Islands Dollar",
  JMD: "Jamaican Dollar",
  TTD: "Trinidad and Tobago Dollar",
  BZD: "Belize Dollar",
  GTQ: "Guatemalan Quetzal",
  HNL: "Honduran Lempira",
  NIO: "Nicaraguan Cordoba",
  CRC: "Costa Rican Colon",
  PAB: "Panamanian Balboa",
  DOP: "Dominican Peso",
  HTG: "Haitian Gourde",
  CUP: "Cuban Peso",
  ARS: "Argentine Peso",
  BOB: "Bolivian Boliviano",
  CLP: "Chilean Peso",
  COP: "Colombian Peso",
  PEN: "Peruvian Sol",
  VEF: "Venezuelan Bolivar",
  GYD: "Guyanese Dollar",
  SRD: "Surinamese Dollar",
  BRL: "Brazilian Real",
  UYU: "Uruguayan Peso",
  PYG: "Paraguayan Guarani",
  MXN: "Mexican Peso",
  ZAR: "South African Rand",
  BWP: "Botswana Pula",
  SZL: "Swazi Lilangeni",
  LSL: "Lesotho Loti",
  NAD: "Namibian Dollar",
  ZMW: "Zambian Kwacha",
  ZWD: "Zimbabwean Dollar",
  AOA: "Angolan Kwanza",
  MZN: "Mozambican Metical",
  MWK: "Malawian Kwacha",
  TZS: "Tanzanian Shilling",
  UGX: "Ugandan Shilling",
  KES: "Kenyan Shilling",
  ETB: "Ethiopian Birr",
  DJF: "Djiboutian Franc",
  SOS: "Somali Shilling",
  ERN: "Eritrean Nakfa",
  SDG: "Sudanese Pound",
  EGP: "Egyptian Pound",
  LYD: "Libyan Dinar",
  TND: "Tunisian Dinar",
  DZD: "Algerian Dinar",
  MAD: "Moroccan Dirham",
  MRO: "Mauritanian Ouguiya",
  XOF: "West African CFA Franc",
  XAF: "Central African CFA Franc",
  GMD: "Gambian Dalasi",
  GNF: "Guinean Franc",
  SLL: "Sierra Leonean Leone",
  LRD: "Liberian Dollar",
  CDF: "Congolese Franc",
  RWF: "Rwandan Franc",
  BIF: "Burundian Franc",
  KMF: "Comorian Franc",
  SCR: "Seychellois Rupee",
  MUR: "Mauritian Rupee",
  MGA: "Malagasy Ariary",
  AQD: "Antarctic Dollar",
  ANG: "Netherlands Antillean Guilder",
  AWG: "Aruban Florin",
  GHS: "Ghanaian Cedi",
  NGN: "Nigerian Naira",
  CVE: "Cape Verdean Escudo",
  STN: "Sao Tome and Principe Dobra (new)",
  MRU: "Mauritanian Ouguiya (new)",
  VES: "Venezuelan Bolivar (new)",
  BYN: "Belarusian Ruble (new)",
  KPW: "North Korean Won",
  STD: "Sao Tome and Principe Dobra",
};

/**
 * Get currency name by code
 */
export const getCurrencyName = (code: string): string => {
  return currencyNames[code] || code;
};

/**
 * Get all available currencies with their names
 */
export const getAllCurrencies = () => {
  return Object.entries(currencyNames).map(([code, name]) => ({
    code,
    name,
    display: `${code} — ${name}`,
  }));
};
