/**
 * Metadata for the locale-prefixed routes (`/{locale}/…`).
 *
 * Kept out of `src/lib/metadata.ts` on purpose: this module reads the
 * `messages/*.json` bundles, and metadata.ts is imported by all 176 English
 * tool pages — no reason to pull translation loading into each of those
 * server bundles. Only the `[locale]` route segment imports this.
 */
import type { Metadata } from "next";

import { loadMessages } from "./messages";
import { findToolByHref } from "./tools-config";
import {
  SITE_URL,
  getLocaleConfig,
  hreflangLanguages,
  localePath,
  ogAlternateLocales,
  type Locale,
} from "./locales";


interface ToolStrings {
  name?: string;
  description?: string;
}

/** Only the handful of keys this module reads — the bundles carry far more. */
interface MessageBundle {
  Home?: { hero?: string; subtitle?: string };
  Blog?: { blogTitle?: string; privacyDesc?: string };
  ToolsConfig?: { tools?: Record<string, ToolStrings> };
}

/**
 * Read one locale's bundle through the shared lazy loader rather than a
 * hardcoded map. `src/lib/locales.ts` stays the only place a locale is
 * registered — adding a language needs no edit here.
 */
async function bundle(locale: Locale): Promise<MessageBundle> {
  return (await loadMessages(locale)) as MessageBundle;
}

/** Localized tool name/description from the `ToolsConfig` namespace. */
export async function localizedTool(
  slug: string,
  locale: Locale
): Promise<{ name: string; description: string } | null> {
  const tool = findToolByHref(`/tools/${slug}`);
  if (!tool) return null;
  const strings = (await bundle(locale)).ToolsConfig?.tools?.[slug];
  return {
    name: strings?.name || tool.name,
    description: strings?.description || tool.description,
  };
}

/**
 * Shared `alternates` block: a self-referential canonical for this locale plus
 * the full, reciprocal hreflang set. The canonical is deliberately NOT the
 * English URL — canonicalizing translations to English deindexes them.
 */
function alternatesFor(path: string, locale: Locale): Metadata["alternates"] {
  return {
    canonical: `${SITE_URL}${localePath(path, locale)}`,
    languages: hreflangLanguages(path),
  };
}

function openGraphFor(
  path: string,
  locale: Locale,
  title: string,
  description: string,
  images?: { url: string; width: number; height: number; alt: string }[]
): Metadata["openGraph"] {
  return {
    type: "website",
    locale: getLocaleConfig(locale).ogLocale,
    alternateLocale: ogAlternateLocales(locale),
    url: `${SITE_URL}${localePath(path, locale)}`,
    title,
    description,
    siteName: "BrowseryTools — أدواتك",
    images,
  };
}

export async function generateLocalizedToolMetadata(
  slug: string,
  locale: Locale
): Promise<Metadata> {
  const path = `/tools/${slug}`;
  const strings = await localizedTool(slug, locale);

  if (!strings) {
    return { title: "Tool Not Found", robots: { index: false, follow: false } };
  }

  const { name: title, description } = strings;
  // The OG/Twitter images are generated by the file-based routes on the
  // English tool segment; the artwork is language-neutral, so point at them
  // rather than duplicating the generators under `[locale]`.
  const ogImage = `${SITE_URL}${path}/opengraph-image`;

  return {
    title,
    description,
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        "max-video-preview": -1,
        "max-image-preview": "large",
        "max-snippet": -1,
      },
    },
    openGraph: openGraphFor(path, locale, title, description, [
      { url: ogImage, width: 1200, height: 630, alt: title },
    ]),
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [`${SITE_URL}${path}/twitter-image`],
      creator: "@browserytools",
      site: "@browserytools",
    },
    alternates: alternatesFor(path, locale),
    category: "technology",
  };
}

export async function generateLocalizedHomeMetadata(locale: Locale): Promise<Metadata> {
  const home = (await bundle(locale)).Home;
  const title = home?.hero || "Free Browser-Based Productivity Tools";
  const description =
    home?.subtitle || "No servers. Full privacy. Everything runs in your browser.";

  return {
    title,
    description,
    openGraph: openGraphFor("/", locale, title, description, [
      { url: `${SITE_URL}/og-image.png`, width: 1200, height: 630, alt: title },
    ]),
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [`${SITE_URL}/og-image.png`],
    },
    alternates: alternatesFor("/", locale),
    category: "technology",
  };
}

export async function generateLocalizedBlogMetadata(locale: Locale): Promise<Metadata> {
  const blog = (await bundle(locale)).Blog;
  const title = blog?.blogTitle || "BrowseryTools Blog";
  const description =
    blog?.privacyDesc ||
    "Guides and tutorials for free browser-based tools that respect your privacy.";

  return {
    title,
    description,
    openGraph: openGraphFor("/blog", locale, title, description, [
      { url: `${SITE_URL}/og-image.png`, width: 1200, height: 630, alt: title },
    ]),
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [`${SITE_URL}/og-image.png`],
    },
    alternates: alternatesFor("/blog", locale),
  };
}
