/**
 * Metadata for the locale-prefixed routes (`/{locale}/…`).
 *
 * Kept out of `src/lib/metadata.ts` on purpose: this module imports every
 * `messages/*.json` bundle, and metadata.ts is imported by all 176 English
 * tool pages — pulling ~2.3 MB of translations into each of those server
 * bundles for no reason. Only the `[locale]` route segment imports this.
 */
import type { Metadata } from "next";

import { findToolByHref } from "./tools-config";
import {
  SITE_URL,
  getLocaleConfig,
  hreflangLanguages,
  localePath,
  ogAlternateLocales,
  type Locale,
} from "./locales";

import enMessages from "../../messages/en.json";
import arMessages from "../../messages/ar.json";
import esMessages from "../../messages/es.json";
import ptBRMessages from "../../messages/pt-BR.json";
import frMessages from "../../messages/fr.json";
import deMessages from "../../messages/de.json";
import ruMessages from "../../messages/ru.json";
import idMessages from "../../messages/id.json";
import zhCNMessages from "../../messages/zh-CN.json";

interface ToolStrings {
  name?: string;
  description?: string;
}

/** Only the handful of keys this module reads — the bundles carry far more. */
interface MessageBundle {
  Home?: { hero?: string; subtitle?: string };
  Blog?: { blogTitle?: string; privacyDesc?: string };
  ToolsConfig?: { tools?: Record<string, ToolStrings> };
}

const MESSAGES: Record<Locale, MessageBundle> = {
  en: enMessages,
  ar: arMessages,
  es: esMessages,
  "pt-BR": ptBRMessages,
  fr: frMessages,
  de: deMessages,
  ru: ruMessages,
  id: idMessages,
  "zh-CN": zhCNMessages,
};

function bundle(locale: Locale): MessageBundle {
  return MESSAGES[locale] ?? MESSAGES.en;
}

/** Localized tool name/description from the `ToolsConfig` namespace. */
export function localizedTool(
  slug: string,
  locale: Locale
): { name: string; description: string } | null {
  const tool = findToolByHref(`/tools/${slug}`);
  if (!tool) return null;
  const strings = bundle(locale).ToolsConfig?.tools?.[slug];
  return {
    name: strings?.name || tool.name,
    description: strings?.description || tool.description,
  };
}

/**
 * Shared `alternates` block: a self-referential canonical for this locale plus
 * the full, reciprocal hreflang set. The canonical is deliberately NOT the
 * English URL — canonicalizing translations to English deindexes them.
 */
function alternatesFor(path: string, locale: Locale): Metadata["alternates"] {
  return {
    canonical: `${SITE_URL}${localePath(path, locale)}`,
    languages: hreflangLanguages(path),
  };
}

function openGraphFor(
  path: string,
  locale: Locale,
  title: string,
  description: string,
  images?: { url: string; width: number; height: number; alt: string }[]
): Metadata["openGraph"] {
  return {
    type: "website",
    locale: getLocaleConfig(locale).ogLocale,
    alternateLocale: ogAlternateLocales(locale),
    url: `${SITE_URL}${localePath(path, locale)}`,
    title,
    description,
    siteName: "BrowseryTools — أدواتك",
    images,
  };
}

export function generateLocalizedToolMetadata(
  slug: string,
  locale: Locale
): Metadata {
  const path = `/tools/${slug}`;
  const strings = localizedTool(slug, locale);

  if (!strings) {
    return { title: "Tool Not Found", robots: { index: false, follow: false } };
  }

  const { name: title, description } = strings;
  // The OG/Twitter images are generated by the file-based routes on the
  // English tool segment; the artwork is language-neutral, so point at them
  // rather than duplicating the generators under `[locale]`.
  const ogImage = `${SITE_URL}${path}/opengraph-image`;

  return {
    title,
    description,
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        "max-video-preview": -1,
        "max-image-preview": "large",
        "max-snippet": -1,
      },
    },
    openGraph: openGraphFor(path, locale, title, description, [
      { url: ogImage, width: 1200, height: 630, alt: title },
    ]),
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [`${SITE_URL}${path}/twitter-image`],
      creator: "@browserytools",
      site: "@browserytools",
    },
    alternates: alternatesFor(path, locale),
    category: "technology",
  };
}

export function generateLocalizedHomeMetadata(locale: Locale): Metadata {
  const home = bundle(locale).Home;
  const title = home?.hero || "Free Browser-Based Productivity Tools";
  const description =
    home?.subtitle || "No servers. Full privacy. Everything runs in your browser.";

  return {
    title,
    description,
    openGraph: openGraphFor("/", locale, title, description, [
      { url: `${SITE_URL}/og-image.png`, width: 1200, height: 630, alt: title },
    ]),
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [`${SITE_URL}/og-image.png`],
    },
    alternates: alternatesFor("/", locale),
    category: "technology",
  };
}

export function generateLocalizedBlogMetadata(locale: Locale): Metadata {
  const blog = bundle(locale).Blog;
  const title = blog?.blogTitle || "BrowseryTools Blog";
  const description =
    blog?.privacyDesc ||
    "Guides and tutorials for free browser-based tools that respect your privacy.";

  return {
    title,
    description,
    openGraph: openGraphFor("/blog", locale, title, description, [
      { url: `${SITE_URL}/og-image.png`, width: 1200, height: 630, alt: title },
    ]),
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [`${SITE_URL}/og-image.png`],
    },
    alternates: alternatesFor("/blog", locale),
  };
}
