import { Metadata } from "next";
import { findToolByHref } from "./tools-config";

export function generateToolMetadata(href: string): Metadata {
  const tool = findToolByHref(href);

  if (!tool) {
    return {
      title: "Tool Not Found - Browser Tools",
      description: "The requested tool could not be found.",
    };
  }

  const baseUrl = "https://browserytools.com";
  const toolUrl = `${baseUrl}${href}`;

  return {
    title: `${tool.name} - Free Online ${tool.category} Tool`,
    description: tool.description,
    keywords: [
      tool.name.toLowerCase(),
      tool.category.toLowerCase(),
      "free online tool",
      "browser tool",
      "no server",
      "privacy",
      "web tool",
      "online utility",
      ...tool.description
        .toLowerCase()
        .split(" ")
        .filter(
          (word) =>
            word.length > 3 &&
            ![
              "the",
              "and",
              "for",
              "with",
              "from",
              "this",
              "that",
              "your",
              "are",
              "can",
              "use",
              "all",
              "get",
              "has",
              "its",
              "our",
              "out",
              "but",
              "not",
              "you",
              "any",
              "may",
              "new",
              "now",
              "old",
              "see",
              "him",
              "two",
              "how",
              "her",
              "was",
              "one",
              "our",
              "had",
              "by",
              "word",
              "but",
              "what",
              "some",
              "we",
              "it",
              "is",
              "or",
              "had",
              "the",
              "of",
              "to",
              "and",
              "a",
              "in",
              "is",
              "it",
              "you",
              "that",
              "he",
              "was",
              "for",
              "on",
              "are",
              "as",
              "with",
              "his",
              "they",
              "i",
              "at",
              "be",
              "this",
              "have",
              "from",
              "or",
              "one",
              "had",
              "by",
              "word",
              "but",
              "not",
              "what",
              "all",
              "were",
              "we",
              "when",
              "your",
              "can",
              "said",
              "there",
              "each",
              "which",
              "she",
              "do",
              "how",
              "their",
              "if",
              "will",
              "up",
              "other",
              "about",
              "out",
              "many",
              "then",
              "them",
              "these",
              "so",
              "some",
              "her",
              "would",
              "make",
              "like",
              "into",
              "him",
              "time",
              "has",
              "two",
              "more",
              "go",
              "no",
              "way",
              "could",
              "my",
              "than",
              "first",
              "been",
              "call",
              "who",
              "its",
              "now",
              "find",
              "long",
              "down",
              "day",
              "did",
              "get",
              "come",
              "made",
              "may",
              "part",
            ].includes(word)
        ),
    ],
    authors: [{ name: "Browser Tools" }],
    creator: "Browser Tools",
    publisher: "Browser Tools",
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        "max-video-preview": -1,
        "max-image-preview": "large",
        "max-snippet": -1,
      },
    },
    openGraph: {
      type: "website",
      locale: "en_US",
      url: toolUrl,
      title: `${tool.name} - Free Online ${tool.category} Tool`,
      description: tool.description,
      siteName: "Browser Tools",
      images: [
        {
          url: "/og-image.png",
          width: 1200,
          height: 630,
          alt: `${tool.name} - Free Online Tool`,
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title: `${tool.name} - Free Online ${tool.category} Tool`,
      description: tool.description,
      images: ["/og-image.png"],
    },
    alternates: {
      canonical: toolUrl,
    },
    category: "technology",
    other: {
      "application/ld+json": JSON.stringify({
        "@context": "https://schema.org",
        "@type": "SoftwareApplication",
        name: tool.name,
        description: tool.description,
        url: toolUrl,
        applicationCategory: tool.category,
        operatingSystem: "Web Browser",
        browserRequirements: "Requires JavaScript. Requires HTML5.",
        softwareVersion: "1.0",
        datePublished: "2024-01-01",
        dateModified: new Date().toISOString().split("T")[0],
        author: {
          "@type": "Organization",
          name: "Browser Tools",
          url: "https://browserytools.com",
        },
        publisher: {
          "@type": "Organization",
          name: "Browser Tools",
          url: "https://browserytools.com",
          logo: {
            "@type": "ImageObject",
            url: "https://browserytools.com/icon.svg",
          },
        },
        offers: {
          "@type": "Offer",
          price: "0",
          priceCurrency: "USD",
          availability: "https://schema.org/InStock",
        },
      }),
    },
  };
}

export function generatePageMetadata(
  title: string,
  description: string,
  path: string = ""
): Metadata {
  const baseUrl = "https://browserytools.com";
  const pageUrl = `${baseUrl}${path}`;

  return {
    title,
    description,
    keywords: [
      "browser tools",
      "online tools",
      "free tools",
      "productivity",
      "web utilities",
    ],
    authors: [{ name: "Browser Tools" }],
    creator: "Browser Tools",
    publisher: "Browser Tools",
    robots: {
      index: true,
      follow: true,
      googleBot: {
        index: true,
        follow: true,
        "max-video-preview": -1,
        "max-image-preview": "large",
        "max-snippet": -1,
      },
    },
    openGraph: {
      type: "website",
      locale: "en_US",
      url: pageUrl,
      title,
      description,
      siteName: "Browser Tools",
      images: [
        {
          url: "/og-image.png",
          width: 1200,
          height: 630,
          alt: title,
        },
      ],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: ["/og-image.png"],
    },
    alternates: {
      canonical: pageUrl,
    },
    category: "technology",
  };
}
